Repository planetarium/NineChronicles, pull requests merged in 2021-12, with the labels that each got.

#1016 Season1 arena text change
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab
Labels: bug

#1028 [Design] Seson1 schedule Change 12 > 21
  nekoyume/Assets/Resources/UI/Textures/PVP/Bg_Season1.png
Labels: bug

#1034 Fix bug in displaying recipe unlock VFX.
  nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeCell.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
Labels: bug

#1039 Bugfix spine
  nekoyume/Assets/AddressableAssets/Character/NPC/300001/ReferenceAssets/Disappear_03.asset
  nekoyume/Assets/AddressableAssets/Character/NPC/300001/ReferenceAssets/Disappear_03.asset.meta
  nekoyume/Assets/AddressableAssets/Character/NPC/300004/300004.controller
  nekoyume/Assets/AddressableAssets/Character/NPC/300004/300004.json
  nekoyume/Assets/AddressableAssets/Character/NPC/300005/ReferenceAssets/Talking.asset
  nekoyume/Assets/AddressableAssets/Character/NPC/300005/ReferenceAssets/Talking.asset.meta
  nekoyume/Assets/Resources/Character/NPC/205007.prefab
  nekoyume/Assets/Resources/Character/NPC/300000.prefab
  nekoyume/Assets/Resources/Character/NPC/300002.prefab
  nekoyume/Assets/Resources/Character/NPC/300005.prefab
  nekoyume/Assets/_Scripts/Game/Character/MecanimStateToAnimationHandle.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/PrologueDialogPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
Labels: bug

#1036 Fix message of error code 27
  nekoyume/Assets/Resources/UI/Prefabs/UI_IconAndButtonSystem.prefab
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionTimeoutException.cs
  nekoyume/Assets/_Scripts/BlockChain/Agent.cs
  nekoyume/Assets/_Scripts/BlockChain/ErrorCode.cs
  nekoyume/Assets/_Scripts/BlockChain/IAgent.cs
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/IconAndButtonSystem.cs
Labels: bug

#1045 Change 202005 spine resource
  nekoyume/Assets/AddressableAssets/Character/Monster/202005/202005.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Monster/202005/202005.json
  nekoyume/Assets/AddressableAssets/Character/Monster/202005/202005.png
Labels: bug

#1055 Bugfix/UI text area fix
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_HelpTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MimisbrunnrPreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_TwoButtonSystem.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_UpgradeEquipment.prefab
Labels: bug

#1058 Separate qa build
  .gitignore
  nekoyume/Assets/Editor/Builder.cs
  nekoyume/Assets/Resources/UI/Prefabs/UI_TestbedEditor.prefab
  nekoyume/Assets/StreamingAssets/TestbedCreateAvatar.json
  nekoyume/Assets/StreamingAssets/TestbedCreateAvatar.json.meta
  nekoyume/Assets/StreamingAssets/TestbedSell.json
  nekoyume/Assets/StreamingAssets/TestbedSell.json.meta
  nekoyume/Assets/_Scripts/BlockChain/Agent.cs
  nekoyume/Assets/_Scripts/UI/Widget/Development/TestbedEditor.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: improve

#1059 Add testbed wiki images
  docs/wiki/Guides/Testbed_Tool/Testbed_Tool_1.png
  docs/wiki/Guides/Testbed_Tool/Testbed_Tool_2.png
  docs/wiki/Guides/Testbed_Tool/Testbed_Tool_3.png
  docs/wiki/Guides/Testbed_Tool/Testbed_Tool_4.png
  docs/wiki/Guides/Testbed_Tool/Testbed_Tool_5.png
Labels: improve

#1073 Move calling position of DestoryBackground()
  nekoyume/Assets/_Scripts/UI/Widget/Battle.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
Labels: bug

#1074 Optimize getState() related to shop and mail
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Extension/LocalizationExtension.cs
  nekoyume/Assets/_Scripts/Helper/Util.cs
  nekoyume/Assets/_Scripts/UI/Model/ShopItems.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/ShopItemView.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopBuyItems.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopSellItems.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
Labels: improve

#1070 Fix the bug that overlaps the npc.
  nekoyume/Assets/AddressableAssets/Character/Monster/204013/204013.json
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
Labels: bug

#1065 Add Checkpoints to Tutorial Scenarios
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.json
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/Base/TutorialScenario.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tutorial.cs
Labels: bug, improve

#1075 Add setting condition of button by action position
  nekoyume/Assets/_Scripts/UI/Widget/QuestPreparation.cs
Labels: bug

#1085 Revert "Optimize getState() related to shop and mail"
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Extension/LocalizationExtension.cs
  nekoyume/Assets/_Scripts/Helper/Util.cs
  nekoyume/Assets/_Scripts/UI/Model/ShopItems.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/ShopItemView.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopBuyItems.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopSellItems.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
Labels: bug

#1084 Try catch get states in `BlockRenderHandler`
  nekoyume/Assets/_Scripts/BlockChain/BlockRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/State/States.cs
Labels: bug

#1089 Bugfix/freeze select character
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/Agent.cs
  nekoyume/Assets/_Scripts/BlockChain/BlockRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ErrorCode.cs
  nekoyume/Assets/_Scripts/BlockChain/IAgent.cs
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/QuitSystem.cs
Labels: bug

#1091 Fix SetCombinationSlotStatesAsync() to be called whenever an avatar is selected
  nekoyume/Assets/_Scripts/State/States.cs
Labels: bug
