Repository planetarium/NineChronicles, pull requests merged in 2021-04, with the labels that each got.

#86 Bug fix/dimmed combination button
  nekoyume/Assets/_Scripts/UI/Combination.cs
  nekoyume/Assets/_Scripts/UI/Module/CombinationPanel.cs
  nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
  nekoyume/Assets/_Scripts/UI/Module/EnhancementPanel.cs
Labels: bug

#94 Bugfix/bugfix renewal shop
  nekoyume/Assets/Resources/Atlas/Atlas_Shop.spriteatlas
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/dialog.csv
  nekoyume/Assets/StreamingAssets/Localization/notification.csv
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Shop_bg_03.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Shop_bg_03.png.meta
  nekoyume/Assets/UIResources/Content/Shop/Prefab/TabButton.prefab
  nekoyume/Assets/UIResources/Content/Shop/Prefab/TabButton_Main.prefab
  nekoyume/Assets/UIResources/Content/Shop/Prefab/TabButton_Sub.prefab
  nekoyume/Assets/UIResources/Content/Shop/Prefab/TabGroup.prefab
  nekoyume/Assets/_Scenes/uiTest.unity
  nekoyume/Assets/_Scenes/uiTest.unity.meta
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Model/ShopItems.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopBuy.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopBuyBoard.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopBuyItems.cs
Labels: bug

#107 Fix tutorial dialog prefab
  nekoyume/Assets/Resources/L10nSettings/FontAssetData ChineseSimplified SDF.asset
  nekoyume/Assets/Resources/L10nSettings/FontAssetData English SDF.asset
  nekoyume/Assets/Resources/L10nSettings/FontAssetData Japanese SDF.asset
  nekoyume/Assets/Resources/L10nSettings/FontAssetData Korean SDF.asset
  nekoyume/Assets/Resources/L10nSettings/FontAssetData Polish SDF.asset
  nekoyume/Assets/Resources/L10nSettings/FontAssetData PortugueseBrazil SDF.asset
  nekoyume/Assets/Resources/L10nSettings/FontAssetData Thai SDF.asset
  nekoyume/Assets/Resources/Tutorial/Prefab/Item_DialogBox.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/_Scripts/L10n/FontMaterialType.cs
Labels: bug

#109 Bugfix/bugfix renewal shop rc4
  nekoyume/Assets/AddressableAssets/UI/Module/Shop.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: bug

#112 bugfix renewal shop
  nekoyume/Assets/Resources/Atlas/Atlas_Common.spriteatlas
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopBuyBoard.cs
Labels: bug

#114 Delete market item dimming and modify button brightening when mouse over disabled Buy button
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/_Scripts/UI/Shop/ShopBuyBoard.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopBuyItems.cs
Labels: bug

#116 Bugfix/delete buy action
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopBuy.cs
Labels: bug

#118 Fix BuyMultiple action
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
  nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopBuy.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopBuyBoard.cs
Labels: bug

#123 Fix pack
  nekoyume/Assets/AddressableAssets/Character/Monster/201001/ReferenceAssets/attack.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201001/ReferenceAssets/casting.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201001/ReferenceAssets/die.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201001/ReferenceAssets/hit.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201001/ReferenceAssets/idle.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201001/ReferenceAssets/run.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201002/ReferenceAssets/attack.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201002/ReferenceAssets/casting.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201002/ReferenceAssets/die.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201002/ReferenceAssets/hit.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201002/ReferenceAssets/idle.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201002/ReferenceAssets/run.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201003/ReferenceAssets/attack.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201003/ReferenceAssets/casting.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201003/ReferenceAssets/die.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201003/ReferenceAssets/hit.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201003/ReferenceAssets/idle.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201003/ReferenceAssets/run.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201004/ReferenceAssets/attack.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201004/ReferenceAssets/casting.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201004/ReferenceAssets/die.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201004/ReferenceAssets/hit.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201004/ReferenceAssets/idle.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201004/ReferenceAssets/run.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201005/ReferenceAssets/attack.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201005/ReferenceAssets/casting.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201005/ReferenceAssets/die.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201005/ReferenceAssets/hit.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201005/ReferenceAssets/idle.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/201005/ReferenceAssets/run.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/202001/ReferenceAssets/attack.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/202001/ReferenceAssets/casting.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/202001/ReferenceAssets/die.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/202001/ReferenceAssets/hit.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/202001/ReferenceAssets/idle.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/202001/ReferenceAssets/run.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/202002/ReferenceAssets/attack.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/202002/ReferenceAssets/casting.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/202002/ReferenceAssets/die.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/202002/ReferenceAssets/hit.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/202002/ReferenceAssets/idle.asset.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/202002/ReferenceAssets/run.asset.meta
  nekoyume/Assets/Planetarium/Nekoyume/Editor/LibPlanetEditor.cs.meta
Labels: bug, ci

#125 Prefab reflected after toggle modularization.
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/UIResources/Content/Shop/Prefab/TabButton.prefab
  nekoyume/Assets/UIResources/Content/Shop/Prefab/TabButton_Main.prefab
  nekoyume/Assets/UIResources/Content/Shop/Prefab/TabButton_Sub.prefab
  nekoyume/Assets/UIResources/Content/Shop/Prefab/TabGroup.prefab
  nekoyume/Assets/_Scripts/UI/Module/ToggleDropdown/NCToggle.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopBuyItems.cs
Labels: improve

#127 Link missing variable
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
Labels: bug

#130 Add mixpanel event
  nekoyume/Assets/_Scripts/UI/Shop/ShopBuy.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopBuyBoard.cs
Labels: improve

#137 Add timeScale Controller to cheat
  nekoyume/Assets/_Scripts/UI/Cheat.cs
Labels: improve

#133 Fix mail bug on successful sell
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
  nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
  nekoyume/Assets/_Scripts/UI/LoginDetail.cs
Labels: bug

#139 Fix IndexOutOfRangeException in VersionInfo
  nekoyume/Assets/_Scripts/UI/VersionInfo.cs
Labels: bug

#136 Add repeat toggle button in preparation
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/RepeatButton.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/RepeatButton.prefab.meta
  nekoyume/Assets/Resources/UI/Animations/UIBattleResultController@Show.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattleResult.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MimisbrunnrPreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPreparation.prefab
  nekoyume/Assets/Resources/UI/Textures/repeat_03.png
  nekoyume/Assets/Resources/UI/Textures/repeat_03.png.meta
  nekoyume/Assets/Resources/UI/Textures/repeat_04.png
  nekoyume/Assets/Resources/UI/Textures/repeat_04.png.meta
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/UI/Battle.cs
  nekoyume/Assets/_Scripts/UI/BattleResult.cs
  nekoyume/Assets/_Scripts/UI/MimisbrunnrPreparation.cs
  nekoyume/Assets/_Scripts/UI/QuestPreparation.cs
Labels: improve

#146 Fix 201000 monster prefab
  nekoyume/Assets/Resources/Character/Monster/201000.prefab
Labels: bug

#147 Repeat toggle not pressed when the game starts
  nekoyume/Assets/_Scripts/UI/MimisbrunnrPreparation.cs
  nekoyume/Assets/_Scripts/UI/QuestPreparation.cs
Labels: bug

#148 Fix ShopProducts
  nekoyume/Assets/_Scripts/State/ShopProducts.cs
Labels: bug

#150 Fix tutorial emoji type 2 animation
  nekoyume/Assets/Resources/Tutorial/Animation/Emoji/Tutorial_Emoji_Type_02.anim
Labels: bug

#152 Change shop state exception handling
  nekoyume/Assets/_Scripts/State/ShopProducts.cs
Labels: bug

#153 Clear products when update product
  nekoyume/Assets/_Scripts/State/ShopProducts.cs
Labels: bug

#157 Remove LocalLayerModifier in Read method
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Mail.cs
Labels: bug

#164 Fix bug where last sell item were not visible on sell inventory
  nekoyume/Assets/_Scripts/State/ShopProducts.cs
Labels: bug
