Repository planetarium/NineChronicles, pull requests merged in 2022-09, with the labels that each got.

#1860 Enrich Mixpanel properties with `agentAddress` and `avatarAddress`
  nekoyume/Assets/PackageExtensions/Mixpanel/MixpanelValueFactory.cs
  nekoyume/Assets/_Scripts/Analyzer.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ErrorCode.cs
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
  nekoyume/Assets/_Scripts/Game/Character/Player.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Game/Prologue.cs
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
  nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BuffBonusPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
  nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs
Labels: Small

#1882 Chore/chmod+x
  tools/pack/pack.py
Labels: ci, Extra Small

#1884 Fix `BattleResultPopup` rewards bug
  nekoyume/Assets/_Scripts/Extensions/ActionEvalToViewModelExtensions.cs
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
Labels: bug, Extra Small

#1885 Cherry pick the pull request #1883
  nekoyume/Assets/Resources/UI/Prefabs/CombinationSlot.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotsPopup.prefab
Labels: Extra Large

#1883 Bugfix/add combination slots fix
  nekoyume/Assets/Resources/UI/Prefabs/CombinationSlot.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotsPopup.prefab
Labels: Extra Large

#1871 [Design] Championship Resources add
  nekoyume/Assets/Resources/UI/Icons/700308.png
  nekoyume/Assets/Resources/UI/Icons/700308.png.meta
  nekoyume/Assets/Resources/UI/Icons/Item/700108.png
  nekoyume/Assets/Resources/UI/Icons/Item/700208.png
  nekoyume/Assets/Resources/UI/Icons/Item/700308.png
Labels: Small

#1888 Fix upm
  nekoyume/Packages/manifest.json
  nekoyume/Packages/packages-lock.json
  nekoyume/ProjectSettings/PackageManagerSettings.asset
Labels: Small

#1887 [Design] Font Fix
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotsPopup.prefab
Labels: bug, Extra Small

#1895 Update ItemCountableAndPricePopup
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemCountableAndPricePopup.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ItemCountableAndPricePopup.cs
Labels: Extra Large

#1897 Bugfix and Polishing the World Boss
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBoss.prefab
  nekoyume/Assets/Resources/UI/Shaders/UIBlur_ShaderGraph(Unit).mat
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Rank.prefab
  nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossRank.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/OneLineSystem.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldBossDetail.cs
Labels: Extra Small

#1861 Unify working of guide quest with Shortcut
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
  nekoyume/Assets/_Scripts/UI/Module/Button/AcquisitionPlaceButton.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
Labels: Large

#1894 [Chore] Update updater's download url
  tools/Updater/Updater/Program.cs
Labels: Extra Small

#1901 [Design]Rune_Resources / Prefab_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/Position_Tooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBoss.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/Icon_Rune.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/Icon_Rune_Fenrir_1.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/Icon_Rune_Fenrir_2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/Icon_Rune_Fenrir_3.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/Icon_Rune_Random.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/Icon_Rune_Saehrimnir_1.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/Icon_Rune_Saehrimnir_2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/Icon_Rune_Saehrimnir_3.png
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/RuneStoneItem.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossBattleRewardItem.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossGradeRewardItem.prefab
Labels: Extra Small

#1899 Fix Shop sell material level limit filter
  nekoyume/Assets/_Scripts/Helper/Util.cs
Labels: Extra Small

#1900 Use Addressables asset in NoticePopup
  nekoyume/Assets/AddressableAssets/NoticeInfo.meta
  nekoyume/Assets/AddressableAssets/NoticeInfo/NoticeData_v100300.asset
  nekoyume/Assets/AddressableAssets/NoticeInfo/NoticeData_v100300.asset.meta
  nekoyume/Assets/AddressableAssetsData/AddressableAssetSettings.asset
  nekoyume/Assets/AddressableAssetsData/AssetGroups/RemoteAssets.asset
  nekoyume/Assets/_Scripts/Game/ScriptableObject/NoticeInfoScriptableObject.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/NoticeInfoScriptableObject.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs
Labels: Small

#1904 Introduce World Boss Season Rewards.
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/WorldBossBtn.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/Model/WorldBossModel.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs
  nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossQuery.cs
  nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossReward.cs
  nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossStates.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/WorldBossRewardPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldBossDetail.cs
Labels: Extra Large

#1906 Fix NRE on new agent
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Labels: Extra Small

#1907 Fix world boss ranking view
  nekoyume/Assets/_Scripts/UI/Model/WorldBossRankItem.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/WorldBossRankItemView.cs
Labels: bug, Extra Small

#1909 Add loading indicator to NoticePopup
  nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
Labels: Medium

#1910 Rc v100291 to main
  nekoyume/Assets/AddressableAssets/NoticeInfo.meta
  nekoyume/Assets/AddressableAssets/NoticeInfo/NoticeData_v100300.asset
  nekoyume/Assets/AddressableAssets/NoticeInfo/NoticeData_v100300.asset.meta
  nekoyume/Assets/AddressableAssetsData/AddressableAssetSettings.asset
  nekoyume/Assets/AddressableAssetsData/AssetGroups/RemoteAssets.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemCountableAndPricePopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
  nekoyume/Assets/_Scripts/Game/ScriptableObject/NoticeInfoScriptableObject.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/NoticeInfoScriptableObject.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ItemCountableAndPricePopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs
Labels: Extra Large

#1913 [Design] material delete
  nekoyume/Assets/AddressableAssets/UI/Module/Blur.prefab
Labels: Extra Small

#1914 Update crystal balance when rewarded
  nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs
Labels: Extra Small

#1917 Rerun action camera fsm on end of raid battle.
  nekoyume/Assets/_Scripts/Game/ActionCamera.cs
  nekoyume/Assets/_Scripts/Game/RaidCamera.cs
  nekoyume/Assets/_Scripts/Game/RaidStage.cs
Labels: Medium

#1921 [Design]Rune_Prefab / Resources_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/Position_Tooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBoss.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossDetail.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossRewardPopup.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Icon_Rune2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/Icon_Rune.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/Icon_Rune_Fenrir_1.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/Icon_Rune_Fenrir_2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/Icon_Rune_Fenrir_3.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/Icon_Rune_Random.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/Icon_Rune_Saehrimnir_1.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/Icon_Rune_Saehrimnir_2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/Icon_Rune_Saehrimnir_3.png
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/RuneStoneItem.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossBattleRewardItem.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossGradeRewardItem.prefab
Labels: Small

#1919 [Design]Staking Resources_Edit
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/Staking_00.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/Staking_01.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/Staking_02.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/Staking_03.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/Staking_04.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/Staking_05.png
Labels: No Changes

#1920 chore: Remove update launcher submodule CI
  .github/workflows/release.yaml
Labels: Extra Small

#1923 Change raid button string key
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
Labels: Extra Small

#1924 Introduce `Tools/Address Tool`
  nekoyume/Assets/Planetarium/Nekoyume/Editor/AddressToolWindow.cs
  nekoyume/Assets/Planetarium/Nekoyume/Editor/AddressToolWindow.cs.meta
Labels: Extra Small

#1926 [Design]WorldBoss_Ingame_Icon_Resources_Edit / UI_WorldBossDetail_Pre…
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossDetail.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Icon_Rune2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/Icon_IngameWB_Fenrir.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/Icon_IngameWB_Saehrimnir.png
Labels: Extra Small

#1929 Update Event banner and Notice popup asset
  nekoyume/Assets/AddressableAssets/NoticeInfo/NoticeData_v100300.asset
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_21.png
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_21.png.meta
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_22.png
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_22.png.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_1.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_2.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_3.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_4.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_5.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_6.prefab
  nekoyume/Assets/UIResources/Content/Notice/Information_07.png
  nekoyume/Assets/UIResources/Content/Notice/Information_07.png.meta
Labels: Large

#1931 [Design] icon Add
  nekoyume/Assets/Resources/UI/Icons/Buff/icon_buff_minus_bleed.png
  nekoyume/Assets/Resources/UI/Icons/Buff/icon_buff_minus_bleed.png.meta
Labels: Small

#1930 Use `DateTime.TryParseExact` and new datetime format
  nekoyume/Assets/AddressableAssets/NoticeInfo/NoticeData_v100300.asset
  nekoyume/Assets/_Scripts/Helper/Util.cs
Labels: Extra Small

#1934 [Design]S_Grade_Prefab / Resources_Edit
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/WB_Grade_Bg.png
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/S_Grade_0.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/S_Grade_1.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/S_Grade_2.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/S_Grade_3.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/S_Grade_4.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/S_Grade_5.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Reward.prefab
Labels: Extra Small

#1936 Cherry pick
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Reward.prefab
Labels: No Changes

#1937 [Design]RaidBtn_Prefabs_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
Labels: Extra Large

#1938 Add world boss rank effect
  nekoyume/Assets/Resources/ScriptableObject/UI_WorldBossData.asset
  nekoyume/Assets/_Scripts/Game/ScriptableObject/WorldBossScriptableObject.cs
  nekoyume/Assets/_Scripts/Helper/WorldBossFrontHelper.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/WorldBossRankItemView.cs
Labels: Extra Small

#1940 [Design]WorldBossRankCell_Prefabs_Edit
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossRankCell.prefab
Labels: Extra Small

#1941 [Design]Tabs_Infomation_Prefabs_Edit
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/WB_Name_Bg.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldBoss/WB_Name_Bg.png.meta
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Infomation.prefab
Labels: Extra Small

#1942 Add missing code
  nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/PreloadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
Labels: Extra Small

#1939 Hammerpoint initialize when on changed avatar, Refactor HammerPointStates
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/State/RxProps.Craft.cs
  nekoyume/Assets/_Scripts/State/RxProps.Craft.cs.meta
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/State/Subjects/HammerPointStatesSubject.cs
  nekoyume/Assets/_Scripts/State/Subjects/HammerPointStatesSubject.cs.meta
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
  nekoyume/Assets/_Scripts/UI/Model/RecipeModel.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
Labels: Medium

#1966 [Design]HelpScreenshot Resources_Edit
  nekoyume/Assets/Resources/HelpPopupData/Sprites/result_23_WorldBoss.png
  nekoyume/Assets/Resources/HelpPopupData/Sprites/result_24_WorldBoss_Battle.png
Labels: No Changes

#1969 [Design]WB_Localizing_Edit
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Reward.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossGradeRewardItem.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossRankCell.prefab
Labels: Medium

#1968 [Design]UI_Menu / RaidBtn_Prefabs_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Sprites/Background/MainMenu/worldboss_01.png
  nekoyume/Assets/Sprites/Background/MainMenu/worldboss_02.png
  nekoyume/Assets/Sprites/Background/MainMenu/worldboss_03_Body.png
Labels: Extra Small

#1970 UI/wb ready bg
  nekoyume/Assets/Resources/UI/Prefabs/UI_RaidPreparation.prefab
  nekoyume/Assets/Sprites/Background/Dungeon/Bg_dungeon_WorldBoss_01.png
  nekoyume/Assets/Sprites/Background/Dungeon/Bg_dungeon_WorldBoss_01.png.meta
Labels: Extra Large

#1973 Modify world boss reward to be managed by each avatar
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs
  nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossGradeReward.cs
  nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossQuery.cs
  nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossStates.cs
  nekoyume/Assets/_Scripts/UI/RequestManager.cs
  nekoyume/Assets/_Scripts/UI/RequestManager.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Screen/WorldBossRewardScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/QuitSystem.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldBossDetail.cs
Labels: bug, Large

#1974 avoid NRE
  nekoyume/Assets/_Scripts/UI/Widget/Popup/WorldBossResultPopup.cs
Labels: Extra Small

#1975 Add world boss bgm
  nekoyume/Assets/Resources/Audio/Music/Prefabs/bgm_worldboss_battle_01.prefab
  nekoyume/Assets/Resources/Audio/Music/Prefabs/bgm_worldboss_battle_01.prefab.meta
  nekoyume/Assets/Resources/Audio/Music/Prefabs/bgm_worldboss_battle_result.prefab
  nekoyume/Assets/Resources/Audio/Music/Prefabs/bgm_worldboss_battle_result.prefab.meta
  nekoyume/Assets/Resources/Audio/Music/Prefabs/bgm_worldboss_title.prefab
  nekoyume/Assets/Resources/Audio/Music/Prefabs/bgm_worldboss_title.prefab.meta
  nekoyume/Assets/Resources/Audio/Music/clips/bgm_worldboss_battle_result.ogg
  nekoyume/Assets/Resources/Audio/Music/clips/bgm_worldboss_battle_result.ogg.meta
  nekoyume/Assets/Resources/Audio/Music/clips/bgm_worldboss_title.ogg
  nekoyume/Assets/Resources/Audio/Music/clips/bgm_worldboss_title.ogg.meta
  nekoyume/Assets/_Scripts/Game/Controller/AudioController.cs
  nekoyume/Assets/_Scripts/Game/RaidStage.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/WorldBossResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs
Labels: Extra Large

#1977 Fix none object in ArenaBoard
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
Labels: Extra Small

#1983 Disable the avatar info icon in the battle preparation
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
Labels: bug, Extra Small

#1982 Fill current wave on raid progress bar.
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossBattle.prefab
  nekoyume/Assets/_Scripts/UI/Module/RaidProgressBar.cs
Labels: Extra Small

#1986 Add error code
  nekoyume/Assets/_Scripts/BlockChain/ErrorCode.cs
Labels: Extra Small

#1979 Update Localization Date
  nekoyume/Assets/StreamingAssets/Localization/skill_description.csv
  nekoyume/Assets/StreamingAssets/Localization/worldboss_info.csv
Labels: Large

#1987 Implement bleed vfx
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfoSessionProgressFill.mat
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_Skill_Claw.playable
  nekoyume/Assets/Resources/VFX/Prefabs/actionBuff_Bleed.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/actionBuff_Bleed.prefab.meta
  nekoyume/Assets/_Scenes/Game.unity
  nekoyume/Assets/_Scripts/Game/Character/RaidCharacter.cs
  nekoyume/Assets/_Scripts/Game/VFX/Skill/BleedVFX.cs
  nekoyume/Assets/_Scripts/Game/VFX/Skill/BleedVFX.cs.meta
  nekoyume/Assets/_Scripts/Game/VFX/Skill/BuffController.cs
Labels: Medium

#1988 [Bugfix] Play mouse click VFX based on current camera position
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Extra Small

#1989 Improve `AddressTool`
  nekoyume/Assets/Planetarium/Nekoyume/Editor/AddressToolWindow.cs
Labels: Small

#1992 Fix equip cp effect
  nekoyume/Assets/_Scripts/UI/Module/AvatarCP.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
Labels: Extra Small

#1995 Revert preparation widgets
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
Labels: bug, Extra Small

#1991 Fixed to the world boss unlock function to work properly
  nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs
Labels: bug, Extra Small

#1980 Add auto scroll for last unlocked equipment recipe
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RectScroll.cs
  nekoyume/ProjectSettings/EditorSettings.asset
Labels: Extra Small

#1996 Modify notice pop-up and banner management system
  nekoyume/Assets/AddressableAssets/Character/Monster/900001/900001_Material_TintBlack.mat.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/900001/900001_Material_URP.mat.meta
  nekoyume/Assets/AddressableAssets/NoticeInfo.meta
  nekoyume/Assets/AddressableAssets/NoticeInfo/NoticeData_v100300.asset
  nekoyume/Assets/AddressableAssets/NoticeInfo/NoticeData_v100300.asset.meta
  nekoyume/Assets/AddressableAssetsData/AssetGroups/RemoteAssets.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_1.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_1.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_10.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_10.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_2.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_3.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_3.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_4.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_4.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_5.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_6.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_6.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_7.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_7.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_8.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_8.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_9.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_9.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/EventBannerItem.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/EventBannerItem.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Event_Banner_Item.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Event_Banner_Item.prefab.meta
  nekoyume/Assets/_Scripts/Game/ScriptableObject/NoticeInfoScriptableObject.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/NoticeInfoScriptableObject.cs.meta
  nekoyume/Assets/_Scripts/UI/Model/EventBannerData.cs
  nekoyume/Assets/_Scripts/UI/Model/EventBannerData.cs.meta
  nekoyume/Assets/_Scripts/UI/Model/EventBanners.cs
  nekoyume/Assets/_Scripts/UI/Model/EventBanners.cs.meta
  nekoyume/Assets/_Scripts/UI/Model/Notice.cs
  nekoyume/Assets/_Scripts/UI/Model/Notice.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/EventBannerItem.cs
  nekoyume/Assets/_Scripts/UI/RequestManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs
Labels: improve, Extra Large

#1993 Modify the prefab to be changed only when boss id is changed
  nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs
Labels: Extra Small

#1990 Show practice text on raid practice mode
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossResultPopup.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Popup/WorldBossResultPopup.cs
Labels: Extra Small

#1997 Add exception handling to raid button
  nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs
Labels: bug, Extra Small

#1998 Modify raid related buttons
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
  nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs
Labels: bug, Extra Small

#2000 Fix bug in lifecycle of bleed vfx
  nekoyume/Assets/_Scripts/Game/Character/RaidCharacter.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs
Labels: Extra Small

#2002 Modify reward count text options
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossRewardScreen.prefab
Labels: Extra Small

#2001 Fix bugs in raid
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossResultPopup.prefab
  nekoyume/Assets/_Scripts/Game/Character/Character.cs
  nekoyume/Assets/_Scripts/Game/Character/RaidCharacter.cs
  nekoyume/Assets/_Scripts/UI/Widget/RuneStoneItem.cs
Labels: Small

#2003 Improve SuperCraft
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs
Labels: Extra Small

#2004 Fix minor craft ui
  nekoyume/Assets/Resources/UI/Prefabs/EquipDesc.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
Labels: Extra Small

#2005 Fix animation cancel glitch in raid
  nekoyume/Assets/_Scripts/Animation/RaidTimelineContainer.cs
  nekoyume/Assets/_Scripts/Game/Character/Character.cs
  nekoyume/Assets/_Scripts/Game/Character/RaidCharacter.cs
  nekoyume/Assets/_Scripts/Game/RaidStage.cs
Labels: Extra Small

#2006 Bugfix workshop
  nekoyume/Assets/_Scripts/ActionExtensions/CombinationConsumableExtensions.cs
  nekoyume/Assets/_Scripts/ActionExtensions/CombinationEquipmentExtensions.cs
  nekoyume/Assets/_Scripts/ActionExtensions/ItemEnhancementExtensions.cs
  nekoyume/Assets/_Scripts/ActionExtensions/RapidCombinationExtensions.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotsPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
Labels: bug, Large

#2012 Add PatchTableSheet tool
  nekoyume/Assets/Editor/TablePatch.cs
  nekoyume/Assets/Editor/TablePatch.cs.meta
  nekoyume/Assets/Resources/ScriptableObject/TableSheetsForPatch.asset
  nekoyume/Assets/Resources/ScriptableObject/TableSheetsForPatch.asset.meta
  nekoyume/Assets/_Scripts/Game/ScriptableObject/TableSheetsForPatchScriptableObject.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/TableSheetsForPatchScriptableObject.cs.meta
Labels: Medium

#2009 Use `ninechronicles-launcher` protocol when move to staking
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
  nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Extra Small

#2015 Fix bug about unneccessary enabling random skill button
  nekoyume/Assets/_Scripts/UI/Module/Button/BonusBuffButton.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
Labels: Extra Small

#2018 Fix get rewards logic of `GetHackAndSlashReward()`
  nekoyume/Assets/_Scripts/Extensions/ActionEvalToViewModelExtensions.cs
Labels: Extra Small

#2019 Fix acquisition place button bug and improve priority
  nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
Labels: Extra Small

#2023 Fix mail item view background
  nekoyume/Assets/_Scripts/UI/Module/Item/ItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/StageRewardItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/VanillaItemView.cs
  nekoyume/Assets/_Scripts/UI/Scroller/GuidedQuestCell.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/StageInformation.cs
Labels: Small

#2022 Fix craft button disable check
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
Labels: Extra Small

#2024 Apply new design of Super craft
  nekoyume/Assets/Resources/UI/Prefabs/UI_SuperCraftPopup.prefab
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs
Labels: Small

#2025 Hide banner in world boss main
  nekoyume/Assets/_Scripts/UI/Widget/Popup/WorldBossResultPopup.cs
Labels: bug, Extra Small

#2029 Clean up grinding slots when delete item
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
Labels: Extra Small

#2032 Delete duplicated percent character
  nekoyume/Assets/_Scripts/UI/Model/SkillView.cs
Labels: bug, Extra Small
