Repository planetarium/NineChronicles, pull requests merged in 2022-12, with the labels that each got.

#2152 Bugfix
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_RuneListview.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Item/RuneListItem.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Rune.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/RuneEnhancementResultScreen.cs
Labels: Large

#2153 Fixed inventory-equipped display to work properly after sweep action
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
Labels: bug, Extra Small

#2154 graphics optimization
  nekoyume/Assets/Resources/SpriteAtlases/Background/MainMenu.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Item.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Item.spriteatlas.meta
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Lobby_com.spriteatlas
  nekoyume/ProjectSettings/EditorSettings.asset
Labels: Extra Large

#2155 UI/add event stagebg
  nekoyume/Assets/Resources/UI/Textures/00_WorldMap/battle_UI_bg_EventWinter_01.png
  nekoyume/Assets/Resources/UI/Textures/00_WorldMap/battle_UI_bg_EventWinter_01.png.meta
Labels: Small

#2156 detour NRE
  nekoyume/Assets/_Scripts/UI/Module/Lobby/ArenaMenu.cs
Labels: Extra Small

#2157 Change rune enhancement success vfx
  nekoyume/Assets/_Scripts/UI/Widget/Screen/RuneEnhancementResultScreen.cs
Labels: Extra Small

#2147 Test using 8cores on build job
  .github/workflows/build.yml
Labels: Extra Small

#2136 Feature/sentry
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/SentryOptionsConfiguration.cs
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BuffBonusPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs
Labels: Medium

#2167 Fix rune ticker in ui
  nekoyume/Assets/Resources/ScriptableObject/UI_RuneData.asset
Labels: Extra Small

#2170 Split `get state bulk` and Bugfix
  nekoyume/Assets/_Scripts/State/GrandFinaleStates.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: bug, Extra Small

#2168 Uibug/rune text thai fix
  nekoyume/Assets/Resources/HelpPopupData/Sprites/result_14_character.png
  nekoyume/Assets/Resources/HelpPopupData/Sprites/result_25_Rune.png
  nekoyume/Assets/Resources/UI/Prefabs/UI_Rune.prefab
Labels: Large

#2171 Bugfix
  nekoyume/Assets/Resources/HelpPopupData/Sprites/result_03_world_map.png
  nekoyume/Assets/Resources/HelpPopupData/Sprites/result_04_battle_preparation.png
  nekoyume/Assets/Resources/HelpPopupData/Sprites/result_08_craft_workshop.png
  nekoyume/Assets/Resources/HelpPopupData/Sprites/result_15_settings.png
  nekoyume/Assets/Resources/HelpPopupData/Sprites/result_16_craft_equipments.png
  nekoyume/Assets/Resources/HelpPopupData/Sprites/result_17_upgrade_equipment.png
  nekoyume/Assets/Resources/HelpPopupData/Sprites/result_19_mimisbrunnr_stage.png
  nekoyume/Assets/Resources/HelpPopupData/Sprites/result_20_prepare_mimisbrunnr_stage.png
  nekoyume/Assets/Resources/HelpPopupData/Sprites/result_world_01_yggdrasil.png
  nekoyume/Assets/Resources/UI/Prefabs/UI_FriendInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Rune.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab
  nekoyume/Assets/StreamingAssets/Localization/skill_description.csv
  nekoyume/Assets/_Scripts/UI/Model/RuneOptionView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MaterialNavigationPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/RuneEnhancementResultScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/RuneTooltip.cs
Labels: bug, Large

#2172 Change logic of `GetTargetEventDungeonQuest()`
  nekoyume/Assets/_Scripts/UI/Module/GuidedQuest.cs
Labels: Extra Small

#2176 Bugfix/portrait
  nekoyume/Assets/AddressableAssets/UI/Module/CharacterView/FramedCharacterView.prefab
  nekoyume/Assets/_Scripts/Helper/Util.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardPlayerCell.cs
  nekoyume/Assets/_Scripts/UI/Module/Character/DetailedCharacterView.cs
  nekoyume/Assets/_Scripts/UI/Module/Character/FramedCharacterView.cs
  nekoyume/Assets/_Scripts/UI/Module/Character/VanillaCharacterView.cs
  nekoyume/Assets/_Scripts/UI/Module/RaidPlayerStatus.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RankCellPanel.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
  nekoyume/Assets/_Scripts/UI/Widget/Status.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldBossBattle.cs
Labels: bug, Large

#2175 Add notification at event stage
  nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs
Labels: Extra Small

#2179 Bugfix 100340 rc4
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/NotificationCell.prefab
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Model/RuneOptionView.cs
  nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs
  nekoyume/Assets/_Scripts/UI/Module/DailyBonus.cs
  nekoyume/Assets/_Scripts/UI/Scroller/NotificationCell.cs
Labels: bug, Extra Large

#2187 Uibug/tooltip area
  nekoyume/Assets/Resources/Tutorial/Image/Common/Common_bg_3x10.png
  nekoyume/Assets/Resources/Tutorial/Image/Common/Common_bg_3x10.png.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RuneTooltip.prefab
Labels: Extra Large

#2177 Update Event Item L10n Change
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
Labels: Extra Small

#2190 Fix lifecycle of Bleed VFX
  nekoyume/Assets/_Scripts/Game/Character/ArenaCharacter.cs
  nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs
  nekoyume/Assets/_Scripts/Game/Character/RaidCharacter.cs
  nekoyume/Assets/_Scripts/Game/VFX/Skill/BuffVFX.cs
  nekoyume/Assets/_Scripts/Game/VFX/VFX.cs
Labels: Extra Small

#2191 Update Event Dungeon Name Change
  nekoyume/Assets/StreamingAssets/Localization/event_dungeon_name.csv
Labels: Extra Small

#2194 Delete duplicate key
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#2195 Fix error for Language Type Changing
  nekoyume/Assets/_Scripts/UI/Module/BattleReward.cs
  nekoyume/Assets/_Scripts/UI/Scroller/GuidedQuestCell.cs
Labels: Extra Small

#2197 Change Sweep Slider Initial Value
  nekoyume/Assets/_Scripts/UI/Module/Slider/SweepSlider.cs
  nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
Labels: bug, Extra Small

#2189 Add crystal per gold sorting to Shop UI
  nekoyume/Assets/_Scripts/EnumType/ShopSortFilter.cs
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
  nekoyume/Assets/_Scripts/UI/Shop/SellView.cs
Labels: Extra Small

#2199 Fix DateTime prefix in `Util.IsInTime`
  nekoyume/Assets/_Scripts/Helper/Util.cs
Labels: Extra Small

#2205 bugfix: SetActive event view on first Show
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventReleaseNotePopup.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.cs
Labels: Small

#2207 polishing rune
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Item.spriteatlas
  nekoyume/Assets/Resources/UI/Animations/UIRuneEnhancementResult@Close.anim
  nekoyume/Assets/Resources/UI/Animations/UIRuneEnhancementResult@Fail.anim
  nekoyume/Assets/Resources/UI/Animations/UIRuneEnhancementResult@Loop.anim
  nekoyume/Assets/Resources/UI/Animations/UIRuneEnhancementResult@Loop_Fail.anim
  nekoyume/Assets/Resources/UI/Animations/UIRuneEnhancementResult@Show.anim
  nekoyume/Assets/Resources/UI/Animations/UIRuneEnhancementResult@Success.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Rune.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RuneEnhancementResultScreen.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Rune/Rune_Frame_01_Press.png
  nekoyume/Assets/_Scripts/UI/Model/RuneOptionView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
Labels: Extra Large

#2206 WIP
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Item.spriteatlas
  nekoyume/Assets/Resources/UI/Animations/UIRuneEnhancementResult@Close.anim
  nekoyume/Assets/Resources/UI/Animations/UIRuneEnhancementResult@Fail.anim
  nekoyume/Assets/Resources/UI/Animations/UIRuneEnhancementResult@Loop.anim
  nekoyume/Assets/Resources/UI/Animations/UIRuneEnhancementResult@Loop_Fail.anim
  nekoyume/Assets/Resources/UI/Animations/UIRuneEnhancementResult@Show.anim
  nekoyume/Assets/Resources/UI/Animations/UIRuneEnhancementResult@Success.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Rune.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RuneEnhancementResultScreen.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Rune/Rune_Frame_01_Press.png
  nekoyume/Assets/_Scripts/UI/Model/RuneOptionView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
Labels: Extra Large

#2208 [bugfix] image fix
  nekoyume/Assets/Resources/UI/Animations/UIWorldMap_StageController@Show.anim
  nekoyume/Assets/Resources/UI/Textures/00_WorldMap/battle_UI_bg_01_01.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Tooltip/UI_box_04.png
  nekoyume/Assets/UIResources/Content/Effect/BG/worldboss_03_Distortion.png
  nekoyume/Assets/UIResources/Content/Effect/BG/worldboss_03_Distortion.png.meta
Labels: Small

#2210 [bugfix] Atlas option fix
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldClear.spriteatlas
Labels: Extra Small

#2212 fix inventory
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs
  nekoyume/Assets/_Scripts/UI/Module/DailyBonus.cs
  nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
Labels: bug, Medium

#2213 Caching item&rune slot state
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/State/States.cs
Labels: improve, Small

#2215 Update 10030001 Event Name L10n Change
  nekoyume/Assets/StreamingAssets/Localization/event_dungeon_name.csv
Labels: Extra Small

#2216 Increased the height of skill object in rune enhancement result screen
  nekoyume/Assets/Resources/UI/Prefabs/UI_RuneEnhancementResultScreen.prefab
Labels: bug, Small

#2218 Fix friend popup / Modify the lifecycle of lobby character title
  nekoyume/Assets/_Scripts/Game/Character/LobbyCharacter.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/FriendInfoPopup.cs
Labels: bug, Extra Small

#2219 Bugfix
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
  nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentSlot.cs
Labels: bug, Extra Large

#2220 [bugfix] size 1.06 > 1
  nekoyume/Assets/Resources/Prefab/Background/Chapter_04_01.prefab
Labels: Extra Small

#2217 Update Item Name & description Change
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
Labels: Extra Small

#2214 [Design] add
  nekoyume/Assets/Resources/Font/SDF/PortugueseBrazil SDF.asset
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Tutorial.spriteatlas
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaTicketPurchasePopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_TicketPurchasePopup.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ArenaTicketPurchasePopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/TicketPurchasePopup.cs
Labels: Extra Large

#2221 Fix playing event main bgm
  nekoyume/Assets/_Scripts/Game/Controller/AudioController.cs
Labels: Extra Small

#2222 [bugfix] image change
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/GuidedQuestCell.prefab
  nekoyume/Assets/Resources/SpriteAtlases/Background/MainMenu.spriteatlas
  nekoyume/Assets/Resources/UI/Animations/Sweep_Result.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_SweepPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SweepResultPopup.prefab
  nekoyume/Assets/Sprites/Background/MainMenu/worldboss_04_Light.png
  nekoyume/Assets/Sprites/Background/MainMenu/worldboss_04_Light.png.meta
  nekoyume/Assets/UIResources/Backup/worldboss_03_Light.png
  nekoyume/Assets/UIResources/Backup/worldboss_03_Light.png.meta
  nekoyume/Assets/UIResources/Backup/worldboss_03_Support_Back.png
  nekoyume/Assets/UIResources/Backup/worldboss_03_Support_Back.png.meta
Labels: Large

#2223 Fix initial setting bugs in the arena
  nekoyume/Assets/_Scripts/State/GrandFinaleStates.cs
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
Labels: bug, Extra Small

#2225 Uibug/add image change4
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBackground.prefab
  nekoyume/Assets/Resources/UI/Animations/UI_ArenaBoard@Loop.anim
  nekoyume/Assets/Resources/UI/Animations/UI_ArenaBoard@Show.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBoard.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RuneEnhancementResultScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SweepResultPopup.prefab
Labels: Medium

#2228 tidying up the code
  nekoyume/Assets/_Scripts/Helper/RuneFrontHelper.cs
  nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs
  nekoyume/Assets/_Scripts/Helper/Util.cs
  nekoyume/Assets/_Scripts/Helper/WorldBossFrontHelper.cs
  nekoyume/Assets/_Scripts/UI/RequestManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
  nekoyume/Assets/_Scripts/UI/Widget/RuneStoneItem.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/RuneEnhancementResultScreen.cs
Labels: Small

#2229 Improve/celebrates popup
  nekoyume/Assets/Resources/UI/Prefabs/UI_CelebratesPopup.prefab
  nekoyume/Assets/Resources/UI/Textures/00_MenuIllustrates.meta
  nekoyume/Assets/Resources/UI/Textures/00_MenuIllustrates/UI_bg_combination.png
  nekoyume/Assets/Resources/UI/Textures/00_MenuIllustrates/UI_bg_combination.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_MenuIllustrates/UI_bg_mimisbrunnr.png
  nekoyume/Assets/Resources/UI/Textures/00_MenuIllustrates/UI_bg_mimisbrunnr.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_MenuIllustrates/UI_bg_ranking.png
  nekoyume/Assets/Resources/UI/Textures/00_MenuIllustrates/UI_bg_ranking.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_MenuIllustrates/UI_bg_shop.png
  nekoyume/Assets/Resources/UI/Textures/00_MenuIllustrates/UI_bg_shop.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_MenuIllustrates/UI_bg_worldboss.png
  nekoyume/Assets/Resources/UI/Textures/00_MenuIllustrates/UI_bg_worldboss.png.meta
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CelebratesPopup.cs
Labels: Extra Large

#2230 [Bugfix] Persistenting vfx follow target position
  nekoyume/Assets/_Scripts/Game/Character/ArenaCharacter.cs
  nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs
  nekoyume/Assets/_Scripts/Game/Character/RaidCharacter.cs
  nekoyume/Assets/_Scripts/Game/VFX/Skill/BuffController.cs
Labels: Extra Small

#2224 Fix buff view data
  nekoyume/Assets/Resources/ScriptableObject/UI_BonusBuffViewData.asset
Labels: Extra Small

#2233 Bugfix and Polishing
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SweepPopup.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
Labels: bug, Extra Small

#2231 Add error code
  nekoyume/Assets/_Scripts/BlockChain/ErrorCode.cs
Labels: Extra Small

#2238 Resolve the cause of duplicate titles
  nekoyume/Assets/_Scripts/Game/Character/CharacterAppearance.cs
  nekoyume/Assets/_Scripts/Game/Character/Player.cs
  nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
Labels: bug, Extra Small

#2239 Polishing
  nekoyume/Assets/_Scripts/UI/Model/RuneOptionView.cs
Labels: Extra Small

#2235 Change worldInformation reference of shortcut to current avatar
  nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
Labels: Extra Small

#2236 Bug fix about `DateTime` format
  nekoyume/Assets/Resources/ScriptableObject/EventData.asset
  nekoyume/Assets/_Scripts/Game/Event/EventManager.cs
  nekoyume/Assets/_Scripts/Game/Notice/NoticeManager.cs
  nekoyume/Assets/_Scripts/Helper/Util.cs
Labels: Extra Small

#2240 Fix gold to be updated after purchasing event dungeon tickets
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Labels: Extra Small

#2234 [bugfix] Worldmapbg / Questbg
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/GuidedQuestCell.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab
Labels: Extra Large

#2241 Add auto scroll for last unlocked consumable recipe
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
Labels: Extra Small

#2245 Uibug/mainmenu fix
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Sprites/Background/MainMenu/bg_character_main_03.png
  nekoyume/Assets/Sprites/Background/MainMenu/bg_character_main_03.png.meta
Labels: Medium

#2246 Merge rc-v100350-2 into main
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Sprites/Background/MainMenu/bg_character_main_03.png
  nekoyume/Assets/Sprites/Background/MainMenu/bg_character_main_03.png.meta
Labels: Medium

#2244 Caching the state of all slots on the agent
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Game/Character/Player.cs
  nekoyume/Assets/_Scripts/Game/Entrance/NestEntering.cs
  nekoyume/Assets/_Scripts/Game/Factory/PlayerFactory.cs
  nekoyume/Assets/_Scripts/State/GrandFinaleStates.cs
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinEarlyRegisterButton.cs
  nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs
  nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/FriendInfoPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs
Labels: Large

#2232 Remove function about old monster collection
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/Agent.cs
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/State/Subjects/StakingLevelSubject.cs
  nekoyume/Assets/_Scripts/State/Subjects/StakingLevelSubject.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
Labels: Small

#2248 Item slot status is also cached when caching avatar status.
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs
Labels: bug, Medium

#2247 Remove inventory from player
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Game/Character/Player.cs
  nekoyume/Assets/_Scripts/Game/Prologue.cs
  nekoyume/Assets/_Scripts/Helper/Util.cs
  nekoyume/Assets/_Scripts/UI/Module/Character/VanillaCharacterView.cs
  nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs
Labels: Medium
