Repository planetarium/NineChronicles, pull requests merged in 2022-08, with the labels that each got.

#1749 UI/add event dungeon 1
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/QuestBtn.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Icon_EventPeriod.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Icon_EventPeriod.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Popup/UI_bg_frame_EventPeriod.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Popup/UI_bg_frame_EventPeriod.png.meta
Labels: Extra Large

#1750 [Bugfix] Actionpoint Text fix
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
Labels: Extra Small

#1751 [Design] Prefab add
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_BlockPeriod.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_BlockPeriod.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
Labels: Extra Large

#1752 Improve WorldmapButton animation and Refactor code
  nekoyume/Assets/AddressableAssets/UI/Module/Button/WorldmapButton@Unlockable.anim
  nekoyume/Assets/AddressableAssets/UI/Module/Button/WorldmapButton@Unlockable.anim.meta
  nekoyume/Assets/AddressableAssets/UI/Module/Button/WorldmapButton@Unlocked.anim
  nekoyume/Assets/AddressableAssets/UI/Module/Button/WorldmapButton@Unlocked.anim.meta
  nekoyume/Assets/AddressableAssets/UI/Module/Button/WorldmapButtonController.controller
  nekoyume/Assets/AddressableAssets/UI/Module/WorldMap/WorldButton.prefab
  nekoyume/Assets/_Scripts/UI/Module/Button/WorldButton.cs
Labels: Extra Large

#1756 [Bugfix] CraftTab Material Change
  nekoyume/Assets/Resources/UI/Materials/Distortion_Additive_Stencil.shader
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/UIResources/Content/Effect/Material/Distortion_SubTab.mat
  nekoyume/Assets/UIResources/Content/Effect/Material/Distortion_SubTab.mat.meta
  nekoyume/Assets/UIResources/Content/Effect/Material/Distortion_SubTab_Craft.mat
  nekoyume/Assets/UIResources/Content/Effect/Material/Distortion_SubTab_Craft.mat.meta
Labels: Medium

#1757 [Design] World6 intro image add
  nekoyume/Assets/Resources/ScriptableObject/EventData.asset
  nekoyume/Assets/Resources/UI/Textures/00_Intro/title_loading_World6.png
  nekoyume/Assets/Resources/UI/Textures/00_Intro/title_loading_World6.png.meta
Labels: Medium

#1760 [Design] Banner dummy add
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_18.png
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_18.png.meta
  nekoyume/Assets/UIResources/Content/Notice/Information_05.png
  nekoyume/Assets/UIResources/Content/Notice/Information_05.png.meta
Labels: Large

#1762 [Design] Event Tab icon add
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Combination/icon_Combination_Event.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Combination/icon_Combination_Event.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/icon_Event_01_black.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/icon_Event_01_black.png.meta
Labels: Large

#1763 Remove revomon event data.
  nekoyume/Assets/Resources/ScriptableObject/EventData.asset
Labels: Extra Small

#1766 Fix `ConditionalButton_Type2` prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type2.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/icon_ticket_event_dungeon.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/icon_ticket_event_dungeon.png.meta
Labels: Medium

#1767 [Design] Stage icon Change
  nekoyume/Assets/Resources/UI/Textures/00_WorldMap/battle_UI_icon_06.png
Labels: No Changes

#1765 Introduce addressables
  .gitignore
  nekoyume/Assets/AddressableAssetsData.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_1.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_1.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_10.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_10.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_2.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_2.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_3.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_3.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_4.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_4.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_5.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_5.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_6.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_6.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_7.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_7.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_8.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_8.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_9.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_9.prefab.meta
  nekoyume/Assets/_Scripts/Helper/AddressablesHelper.cs
  nekoyume/Assets/_Scripts/Helper/AddressablesHelper.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/EventBannerItem.cs
  nekoyume/Assets/_Scripts/UI/Module/PageView.cs
  nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs
  nekoyume/ProjectSettings/EditorBuildSettings.asset
Labels: Extra Large

#1764 Add test module for Grind animation
  nekoyume/Assets/AddressableAssets/UI/Module/Grinding/GrindModule.prefab
  nekoyume/Assets/Resources/UI/Animations/ItemMoveAnimation_CryStal.controller
  nekoyume/Assets/Resources/UI/Animations/Item_MoveAnimation@show_Crystal.anim
  nekoyume/Assets/Resources/UI/Prefabs/item_CrystalGetAnimation.prefab
  nekoyume/Assets/UIResources/Content/Effect/Common/fx_crystal_glow.png
  nekoyume/Assets/UIResources/Content/Effect/Common/fx_crystal_glow.png.meta
  nekoyume/Assets/_Scripts/Game/Factory/ItemMoveAnimationFactory.cs
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
Labels: Extra Large

#1770 Fix compile error
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
Labels: No Changes

#1772 Fix arena avatar state sync bug
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
Labels: Small

#1774 [Design] MultiResult add
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattleResultPopup.prefab
Labels: No Changes

#1776 Add acquisition place about event dungeon
  nekoyume/Assets/_Scripts/Extensions/EventDungeonExtensions.cs
  nekoyume/Assets/_Scripts/Extensions/StageSheetExtensions.cs
  nekoyume/Assets/_Scripts/UI/Module/Button/AcquisitionPlaceButton.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs
Labels: Medium

#1777 Fix bugs about mimis brunnr with booster
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
Labels: Extra Large

#1778 Add stage button in battle result popup on event dungeon
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs
Labels: Small

#1780 Fix several assets
  nekoyume/Assets/Resources/ScriptableObject/CostIconData.asset
  nekoyume/Assets/Resources/ScriptableObject/UI_Palette.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_TicketPurchasePopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_TicketPurchasePopup.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab
  nekoyume/Assets/_Scripts/EnumType/ColorType.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/TicketPurchasePopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/TicketPurchasePopup.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs
Labels: Extra Large

#1781 [Design] TMP BlockEmoji add
  nekoyume/Assets/Resources/Font/SDF/Count SDF.asset
  nekoyume/Assets/Resources/SpriteAssets/UI_icon_Element.asset
  nekoyume/Assets/Resources/SpriteAssets/UI_icon_Goods.asset
  nekoyume/Assets/Resources/SpriteAssets/UI_icon_lock_01.asset
  nekoyume/Assets/Resources/SpriteAssets/UI_item_Grade_enhancement.asset
  nekoyume/Assets/Resources/SpriteAssets/UI_main_icon_quest_02.asset
  nekoyume/Assets/TextMesh Pro/Resources/Style Sheets/Default Style Sheet.asset
  nekoyume/Assets/TextMesh Pro/Sprites/icon_Goods.png
  nekoyume/Assets/TextMesh Pro/Sprites/icon_Goods.png.meta
Labels: Large

#1782 [Design] Font rebundling
  nekoyume/Assets/Resources/SpriteAssets/UI_icon_Goods.asset
  nekoyume/Assets/TextMesh Pro/Resources/Style Sheets/Default Style Sheet.asset
  nekoyume/Assets/TextMesh Pro/Sprites/icon_Goods.png.meta
Labels: Extra Small

#1783 UI/worldmap text
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab
Labels: Extra Small

#1785 Fix git ignore and add addressable assets data files
  .gitignore
  nekoyume/Assets/AddressableAssetsData/AddressableAssetSettings.asset
  nekoyume/Assets/AddressableAssetsData/AddressableAssetSettings.asset.meta
  nekoyume/Assets/AddressableAssetsData/AssetGroupTemplates.meta
  nekoyume/Assets/AddressableAssetsData/AssetGroupTemplates/Packed Assets.asset
  nekoyume/Assets/AddressableAssetsData/AssetGroupTemplates/Packed Assets.asset.meta
  nekoyume/Assets/AddressableAssetsData/AssetGroups.meta
  nekoyume/Assets/AddressableAssetsData/AssetGroups/Built In Data.asset
  nekoyume/Assets/AddressableAssetsData/AssetGroups/Built In Data.asset.meta
  nekoyume/Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
  nekoyume/Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset.meta
  nekoyume/Assets/AddressableAssetsData/AssetGroups/RemoteAssets.asset
  nekoyume/Assets/AddressableAssetsData/AssetGroups/RemoteAssets.asset.meta
  nekoyume/Assets/AddressableAssetsData/AssetGroups/Schemas.meta
  nekoyume/Assets/AddressableAssetsData/AssetGroups/Schemas/Built In Data_PlayerDataGroupSchema.asset
  nekoyume/Assets/AddressableAssetsData/AssetGroups/Schemas/Built In Data_PlayerDataGroupSchema.asset.meta
  nekoyume/Assets/AddressableAssetsData/AssetGroups/Schemas/Default Local Group_BundledAssetGroupSchema.asset
  nekoyume/Assets/AddressableAssetsData/AssetGroups/Schemas/Default Local Group_BundledAssetGroupSchema.asset.meta
  nekoyume/Assets/AddressableAssetsData/AssetGroups/Schemas/Default Local Group_ContentUpdateGroupSchema.asset
  nekoyume/Assets/AddressableAssetsData/AssetGroups/Schemas/Default Local Group_ContentUpdateGroupSchema.asset.meta
  nekoyume/Assets/AddressableAssetsData/AssetGroups/Schemas/RemoteAssets_BundledAssetGroupSchema.asset
  nekoyume/Assets/AddressableAssetsData/AssetGroups/Schemas/RemoteAssets_BundledAssetGroupSchema.asset.meta
  nekoyume/Assets/AddressableAssetsData/AssetGroups/Schemas/RemoteAssets_ContentUpdateGroupSchema.asset
  nekoyume/Assets/AddressableAssetsData/AssetGroups/Schemas/RemoteAssets_ContentUpdateGroupSchema.asset.meta
  nekoyume/Assets/AddressableAssetsData/DataBuilders.meta
  nekoyume/Assets/AddressableAssetsData/DataBuilders/BuildScriptFastMode.asset
  nekoyume/Assets/AddressableAssetsData/DataBuilders/BuildScriptFastMode.asset.meta
  nekoyume/Assets/AddressableAssetsData/DataBuilders/BuildScriptPackedMode.asset
  nekoyume/Assets/AddressableAssetsData/DataBuilders/BuildScriptPackedMode.asset.meta
  nekoyume/Assets/AddressableAssetsData/DataBuilders/BuildScriptPackedPlayMode.asset
  nekoyume/Assets/AddressableAssetsData/DataBuilders/BuildScriptPackedPlayMode.asset.meta
  nekoyume/Assets/AddressableAssetsData/DataBuilders/BuildScriptVirtualMode.asset
  nekoyume/Assets/AddressableAssetsData/DataBuilders/BuildScriptVirtualMode.asset.meta
  nekoyume/Assets/AddressableAssetsData/DefaultObject.asset
  nekoyume/Assets/AddressableAssetsData/DefaultObject.asset.meta
  nekoyume/Assets/AddressableAssetsData/ProfileDataSourceSettings.asset
  nekoyume/Assets/AddressableAssetsData/ProfileDataSourceSettings.asset.meta
  nekoyume/Assets/AddressableAssetsData/Windows.meta
  nekoyume/Assets/AddressableAssetsData/Windows/addressables_content_state.bin
  nekoyume/Assets/AddressableAssetsData/Windows/addressables_content_state.bin.meta
  nekoyume/Assets/AddressableAssetsData/link.xml
  nekoyume/Assets/AddressableAssetsData/link.xml.meta
Labels: Extra Large

#1786 [Design] add
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_18.png
Labels: No Changes

#1787 Add d:cc banner and notice
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Shop.spriteatlas
  nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_19.png
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_19.png.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_1.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_2.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_3.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_5.prefab
  nekoyume/Assets/UIResources/Content/Notice/Information_06.png
  nekoyume/Assets/UIResources/Content/Notice/Information_06.png.meta
Labels: Large

#1788 Fix `UI_Craft` to add the main stat text will be multiple
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
Labels: Extra Large

#1791 Re-open #1758
  nekoyume/Assets/Resources/Prefab/Background/Chapter_06_01.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_06_01.prefab.meta
  nekoyume/Assets/Resources/Prefab/Background/Chapter_06_02.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_06_02.prefab.meta
  nekoyume/Assets/Resources/Prefab/Background/Chapter_06_03.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_06_03.prefab.meta
  nekoyume/Assets/Sprites/Background/Chapter_06.meta
  nekoyume/Assets/Sprites/Background/Chapter_06/bg_chapter06_01_01.png
  nekoyume/Assets/Sprites/Background/Chapter_06/bg_chapter06_01_01.png.meta
  nekoyume/Assets/Sprites/Background/Chapter_06/bg_chapter06_01_02.png
  nekoyume/Assets/Sprites/Background/Chapter_06/bg_chapter06_01_02.png.meta
  nekoyume/Assets/Sprites/Background/Chapter_06/bg_chapter06_02_01.png
  nekoyume/Assets/Sprites/Background/Chapter_06/bg_chapter06_02_01.png.meta
  nekoyume/Assets/Sprites/Background/Chapter_06/bg_chapter06_02_02.png
  nekoyume/Assets/Sprites/Background/Chapter_06/bg_chapter06_02_02.png.meta
  nekoyume/Assets/Sprites/Background/Chapter_06/bg_chapter06_02_03.png
  nekoyume/Assets/Sprites/Background/Chapter_06/bg_chapter06_02_03.png.meta
  nekoyume/Assets/Sprites/Background/Chapter_06/bg_chapter06_03_01.png
  nekoyume/Assets/Sprites/Background/Chapter_06/bg_chapter06_03_01.png.meta
  nekoyume/Assets/Sprites/Background/Chapter_06/bg_chapter06_03_02.png
  nekoyume/Assets/Sprites/Background/Chapter_06/bg_chapter06_03_02.png.meta
  nekoyume/Assets/Sprites/Background/Chapter_06/bg_chapter06_03_03.png
  nekoyume/Assets/Sprites/Background/Chapter_06/bg_chapter06_03_03.png.meta
Labels: Extra Large

#1790 Fix l10n
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/event_dungeon_name.csv
  nekoyume/Assets/StreamingAssets/Localization/event_dungeon_name.csv.meta
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
Labels: Extra Small

#1799 Cherry pick world6 resource from `2022q3-World6`
  nekoyume/Assets/Resources/UI/Icons/Character/207000.png
  nekoyume/Assets/Resources/UI/Icons/Character/207000.png.meta
  nekoyume/Assets/Resources/UI/Icons/Character/207001.png
  nekoyume/Assets/Resources/UI/Icons/Character/207001.png.meta
  nekoyume/Assets/Resources/UI/Icons/Character/207002.png
  nekoyume/Assets/Resources/UI/Icons/Character/207002.png.meta
  nekoyume/Assets/Resources/UI/Icons/Character/207003.png
  nekoyume/Assets/Resources/UI/Icons/Character/207003.png.meta
  nekoyume/Assets/Resources/UI/Icons/Character/207004.png
  nekoyume/Assets/Resources/UI/Icons/Character/207004.png.meta
  nekoyume/Assets/Resources/UI/Icons/Character/207005.png
  nekoyume/Assets/Resources/UI/Icons/Character/207005.png.meta
  nekoyume/Assets/Resources/UI/Icons/Character/207006.png
  nekoyume/Assets/Resources/UI/Icons/Character/207006.png.meta
  nekoyume/Assets/Resources/UI/Icons/Character/207007.png
  nekoyume/Assets/Resources/UI/Icons/Character/207007.png.meta
Labels: Extra Large

#1802 Reflect to libplanet 0.40.0
  nekoyume/Assets/Packages/Libplanet.Net.dll
  nekoyume/Assets/Packages/Libplanet.Net.xml
  nekoyume/Assets/Packages/Libplanet.RocksDBStore.dll
  nekoyume/Assets/Packages/Libplanet.Stun.dll
  nekoyume/Assets/Packages/Libplanet.dll
  nekoyume/Assets/Packages/Libplanet.xml
  nekoyume/Assets/_Scripts/BlockChain/BlockManager.cs
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
Labels: Extra Large

#1800 2022q3 world6 resources
  nekoyume/Assets/Resources/Recipe/ConsumableRecipeGroup.json
  nekoyume/Assets/Resources/UI/Icons/Item/302019.png
  nekoyume/Assets/Resources/UI/Icons/Item/302019.png.meta
  nekoyume/Assets/Resources/UI/Icons/Item/302020.png
  nekoyume/Assets/Resources/UI/Icons/Item/302020.png.meta
  nekoyume/Assets/Resources/UI/Icons/Item/302021.png
  nekoyume/Assets/Resources/UI/Icons/Item/302021.png.meta
  nekoyume/Assets/Resources/UI/Icons/Item/302022.png
  nekoyume/Assets/Resources/UI/Icons/Item/302022.png.meta
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_20.png
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_20.png.meta
Labels: Extra Large

#1804 [bugfix] Material Noise size down
  nekoyume/Assets/UIResources/Content/Effect/Material/Distortion_SubTab_Craft.mat
Labels: Extra Small

#1807 Improve `EventData`
  nekoyume/Assets/Resources/ScriptableObject/EventData.asset
  nekoyume/Assets/_Scripts/EnumType/EventType.cs
  nekoyume/Assets/_Scripts/Game/Event/EventManager.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/EventScriptableObject.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
Labels: Medium

#1806 Add `SuperCraftPopup` and new `SubRecipeView` design
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_SkillOption.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/RecipeView/EquipDesc.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/RecipeView/EquipDesc.prefab.meta
  nekoyume/Assets/Resources/AddressableAssetsContainer.asset
  nekoyume/Assets/Resources/Font/Materials/ChineseSimplified SDF Material - DiceCount.mat
  nekoyume/Assets/Resources/Font/Materials/English SDF Material - DiceCount.mat
  nekoyume/Assets/Resources/Font/Materials/Japanese SDF Material - DiceCount.mat
  nekoyume/Assets/Resources/Font/Materials/Korean SDF Material - DiceCount.mat
  nekoyume/Assets/Resources/Font/Materials/Polish SDF Material - DiceCount.mat
  nekoyume/Assets/Resources/Font/Materials/PortugueseBrazil SDF Material - DiceCount.mat
  nekoyume/Assets/Resources/Font/Materials/Russia SDF Material - DiceCount.mat
  nekoyume/Assets/Resources/UI/Icons/Buff/icon_buff_SuperCraft.png
  nekoyume/Assets/Resources/UI/Icons/Buff/icon_buff_SuperCraft.png.meta
  nekoyume/Assets/Resources/UI/Prefabs/EquipDesc.prefab
  nekoyume/Assets/Resources/UI/Prefabs/EquipDesc.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SuperCraftPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SuperCraftPopup.prefab.meta
  nekoyume/Assets/Resources/UI/Textures/UI_stage_icon_Hammer_01.png
  nekoyume/Assets/Resources/UI/Textures/UI_stage_icon_Hammer_01.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Popup/UI_bg_frame_17.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Popup/UI_bg_frame_17.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_StageBuff/StageBuff_SuperCraft_bg.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_StageBuff/StageBuff_SuperCraft_bg.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_StageBuff/StageBuff_SuperCraft_icon.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_StageBuff/StageBuff_SuperCraft_icon.png.meta
  nekoyume/Assets/UIResources/Content/Shop/Prefab/ItemBuffActive@Show.anim
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Game/TableSheets.cs
  nekoyume/Assets/_Scripts/State/RxProps.Craft.cs
  nekoyume/Assets/_Scripts/State/RxProps.Craft.cs.meta
  nekoyume/Assets/_Scripts/State/RxProps.cs
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs.meta
Labels: Extra Large

#1810 Set default tab to repeat in SweepPopup
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs
Labels: Extra Small

#1812 Remove condition about showing SuperCraftPopup
  nekoyume/Assets/Resources/UI/Prefabs/UI_SuperCraftPopup.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs
Labels: Extra Small

#1813 [Design] Emoji add(Arena, EventDungeon, Worldboss)
  nekoyume/Assets/Resources/SpriteAssets/UI_icon_Goods.asset
  nekoyume/Assets/TextMesh Pro/Resources/Style Sheets/Default Style Sheet.asset
  nekoyume/Assets/TextMesh Pro/Sprites/icon_Goods.png
  nekoyume/Assets/TextMesh Pro/Sprites/icon_Goods.png.meta
Labels: Large

#1815 Fix recipe scroll disappear bug on craft
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
Labels: Extra Small

#1816 Change world6 value
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab
Labels: Extra Small

#1817 Set mainstat view in SubRecipeView
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
Labels: Extra Small

#1818 Implement to report all of sheet addresses to unity console log
  nekoyume/Assets/Planetarium/Nekoyume/Editor/ReportAnything.cs
Labels: Extra Small

#1819 Avoid `InvalidCastException` about HammerPointState
  nekoyume/Assets/_Scripts/State/RxProps.Craft.cs
Labels: Extra Small

#1821 Fix `UI_Craft` prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
Labels: Large

#1822 Fix `UI_Craft` prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
Labels: No Changes

#1823 Fix Bugs from not-set `StageType`
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Labels: Extra Small

#1824 Fix exp bug on render handler of `EventDungeonBattle` action
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Labels: Extra Small

#1825 Fix cost text when buying event dungeon tickets
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
Labels: bug, Extra Small

#1826 Fix shortcut for material items related with event dungeon rewards
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs
Labels: bug, Extra Small

#1820 Add world button unlock condition
  nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs
Labels: Extra Small

#1828 Fix stat view list of `ItemTooltipDetail`
  nekoyume/Assets/_Scripts/UI/Module/ItemTooltipDetail.cs
Labels: bug, Extra Small

#1830 Bug fix/consider all of consumable stats on shop
  nekoyume/Assets/_Scripts/EnumType/ItemSubTypeFilter.cs
  nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
  nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotsPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
Labels: bug, Extra Large

#1831 Fix bug about can not enter new world
  nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs
Labels: Extra Small

#1829 [bugfix] Tutorial Craft Area fix
  nekoyume/Assets/AddressableAssets/UI/Module/TutorialDummys.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
Labels: bug, Extra Large

#1832 Fix state of `HeaderMenuStatic` on `WorldMap`
  nekoyume/Assets/_Scripts/UI/Widget/Base/Widget.cs
  nekoyume/Assets/_Scripts/UI/Widget/StageInformation.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs
Labels: bug, Small

#1834 Set block index of super craft to 20
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs
Labels: Extra Small

#1835 Disable super craft in mimis brunnr recipe
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
Labels: Extra Large

#1836 Fix stats does not updated bug related to consumable
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
Labels: bug, Extra Small

#1839 Update event banner prefabs
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_1.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_2.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_3.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_4.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_5.prefab
Labels: Extra Small

#1846 Fix event crafts gauge
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Labels: bug, Extra Small

#1847 Optimize UI minor
  nekoyume/Assets/_Scripts/UI/Widget/Development/Cheat.cs
Labels: Extra Small

#1849 Update url of event banner
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_2.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_3.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Addressables/Event_Banner_Item_4.prefab
Labels: Extra Small

#1850 Fix remaining time of event dungeon
  nekoyume/Assets/_Scripts/State/RxProps.Event.cs
Labels: bug, Extra Small

#1851 FIx Monster Collection Ingame UI
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_BenefitsListView.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
  nekoyume/Assets/_Scripts/UI/Module/Item/StakingBenefitsListView.cs
Labels: Extra Small

#1859 Refactor code about acquisition place and shortcut
  nekoyume/Assets/_Scripts/Extensions/StageSheetExtensions.cs
  nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
  nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/Button/AcquisitionPlaceButton.cs
  nekoyume/Assets/_Scripts/UI/Module/StakingBonus.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs
Labels: Extra Large

#1863 Fix shop requirement filter
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
Labels: Extra Small

#1864 Change path
  nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs
Labels: bug, Extra Small

#1870 Chore/upload without acl
  .github/workflows/build.yml
Labels: ci

#1866 UI/add design fix
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/GuideQuestCell@Loop.anim
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/GuidedQuestCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/GuidedQuest.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView.prefab
  nekoyume/Assets/Resources/UI/Animations/EventBanner@Show.anim
  nekoyume/Assets/Resources/UI/Prefabs/CombinationSlot.prefab
  nekoyume/Assets/Resources/UI/Prefabs/EquipDesc.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotsPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Common_Prrogressbar_GaugeBg_Glow.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Common_Prrogressbar_GaugeBg_Glow.png.meta
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
Labels: bug, Extra Large

#1876 Change invoking timing of SetBenefitsListViews()
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Extra Small

#1858 Add `Planetarium-Dev` Discord server invitation button
  README.md
Labels: Extra Small

#1877 Add ActionPoint changing rate by Staking
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_BenefitsListView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_StakingBenefits.prefab
  nekoyume/Assets/Resources/AddressableAssetsContainer.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
  nekoyume/Assets/_Scripts/Game/TableSheets.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/StakingBenefitsListView.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs
Labels: Large

#1880 Change costAp with Staking bonus
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs
Labels: Extra Small
