Repository planetarium/NineChronicles, pull requests merged in 2022-06, with the labels that each got.

#1502 Change value of StakingBonus level to States.StakingLevel
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
Labels: Extra Small

#1504 Fix arena battle graphics
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
Labels: Extra Small

#1505 Add Stake action rendering and avoid InvalidCastException
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Model/RecipeModel.cs
Labels: Small

#1507 Apply crystal fluctuation sheet
  nekoyume/Assets/Resources/AddressableAssetsContainer.asset
  nekoyume/Assets/_Scripts/Game/TableSheets.cs
Labels: Extra Small

#1514 new medal data added
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
Labels: Medium

#1515 Avoid ArgumentNullException with Bencodex.Null
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Model/RecipeModel.cs
Labels: Extra Small

#1517 Change CharacterBase.CoTimeout logic
  nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs
Labels: Small

#1494 Show notification on unreplaceable materials.
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/ActionExtensions/BattleArenaExtensions.cs
  nekoyume/Assets/_Scripts/ActionExtensions/JoinArenaExtensions.cs
  nekoyume/Assets/_Scripts/Analyzer.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/Agent.cs
  nekoyume/Assets/_Scripts/BlockChain/ErrorCode.cs
  nekoyume/Assets/_Scripts/Extension/ArenaInformationExtensions.cs
  nekoyume/Assets/_Scripts/Extension/ArenaSheetExtensions.cs
  nekoyume/Assets/_Scripts/Game/Event.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/Game/TableSheets.cs
  nekoyume/Assets/_Scripts/State/ReactiveAvatarState.cs
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
  nekoyume/Assets/_Scripts/State/RxProps.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
  nekoyume/Assets/_Scripts/UI/Model/RecipeModel.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardBillboard.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardPlayerCell.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardPlayerScroll.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardSO.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Emblems/ChampionshipArenaEmblem.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Emblems/OffseasonArenaEmblem.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Emblems/SeasonArenaEmblem.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinEarlyRegisterButton.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSeasonBarScroll.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSeasonCell.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSeasonCellChampionship.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSeasonInfo.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSeasonScroll.cs
  nekoyume/Assets/_Scripts/UI/Module/ArenaTickets.cs
  nekoyume/Assets/_Scripts/UI/Module/Crystal.cs
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/ArenaMenu.cs
  nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeCell.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
  nekoyume/Assets/_Scripts/UI/Widget/Hud/SpeechBubbleWithItem.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/RankingBattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ReplaceMaterialPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/ArenaBattleLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/CombinationLoadingScreen.cs
Labels: Extra Large

#1525 Upgrade unity packages
  nekoyume/Assets/Assets.index
  nekoyume/Assets/Assets.index.meta
  nekoyume/Packages/manifest.json
  nekoyume/Packages/packages-lock.json
Labels: Extra Small

#1527 Bug fix on rendering unlocked recipes.
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Labels: Extra Small

#1529 Fix formula for arena season number with unit tests
  nekoyume/Assets/Tests/EditMode/Extensions.meta
  nekoyume/Assets/Tests/EditMode/Extensions/ArenaSheetExtensionsTest.cs
  nekoyume/Assets/Tests/EditMode/Extensions/ArenaSheetExtensionsTest.cs.meta
  nekoyume/Assets/Tests/EditMode/State/AsyncUpdatableRxPropTest.cs
  nekoyume/Assets/_Scripts/Extension/ArenaSheetExtensions.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
  nekoyume/Packages/manifest.json
  nekoyume/Packages/packages-lock.json
Labels: Medium

#1526 [bugfix] Tutorial Guide Area fix
  nekoyume/Assets/AddressableAssets/UI/Module/TutorialDummys.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/TutorialDummys.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
Labels: Extra Large

#1528 Display indicator on start of crystal related actions.
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Module/Crystal.cs
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
  nekoyume/Assets/_Scripts/UI/Payment/PaymentPopup.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ReplaceMaterialPopup.cs
Labels: Medium

#1530 [Design] StakingBonus Object on
  nekoyume/Assets/AddressableAssets/UI/Module/Inventory.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/StakingBonus.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Grind.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Decomposition_StakingBuff_Bg.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Decomposition_StakingBuff_Bg.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Icon_Detail.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Icon_Detail.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Staking_Buff_01.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Staking_Buff_01.png.meta
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
Labels: Extra Large

#1540 Clean up some of login logics
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs
  nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
Labels: Large

#1541 Improve arena UIs
  .gitignore
  nekoyume/Assets/Resources/UI/Animations/UIRankingBoardController.overrideController
  nekoyume/Assets/Resources/UI/Animations/UIRankingBoardController.overrideController.meta
  nekoyume/Assets/Resources/UI/Animations/UIRankingBoardController@Show.anim
  nekoyume/Assets/Resources/UI/Animations/UIRankingBoardController@Show.anim.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab.meta
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
Labels: Extra Large

#1542 Add action rendering about renewed Stake(Monster Collection)
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/Agent.cs
  nekoyume/Assets/_Scripts/State/States.cs
Labels: Medium

#1546 Fix sync table from chain in initializing
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: bug, Extra Small

#1547 Fix several bugs related to arena
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
Labels: bug, Extra Small

#1543 Fix `CoTimeout()` logic in CharacterBase
  nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs
Labels: Extra Small

#1520 Add new event value to Analyzer
  .github/bin/inject-mixpanel-client-data.sh
  .github/workflows/build.yml
  nekoyume/Assets/PackageExtensions/Mixpanel/MixpanelValueFactory.cs
Labels: Extra Small

#1555 Cherry picking #1520 to the `2022q2` branch
  .github/bin/inject-mixpanel-client-data.sh
  .github/workflows/build.yml
  nekoyume/Assets/PackageExtensions/Mixpanel/MixpanelValueFactory.cs
Labels: Extra Small

#1562 Correct `TARGET_BRANCH` swith-case expression
  .github/workflows/build.yml
Labels: bug, ci, Extra Small

#1563 Apply libplanet bump
  nekoyume/Assets/_Scripts/BlockChain/Agent.cs
Labels: bug, Extra Small

#1564 Correct `LoadIceServer`
  nekoyume/Assets/_Scripts/BlockChain/Agent.cs
Labels: bug

#1561 Staking ingame
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/StakingItemView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/StakingItemView.prefab.meta
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/StakingBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/StakingBtn.prefab.meta
  nekoyume/Assets/Resources/AddressableAssetsContainer.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopupNone.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopupNone.prefab.meta
  nekoyume/Assets/Resources/UI/Textures/Staking_00.png
  nekoyume/Assets/Resources/UI/Textures/Staking_00.png.meta
  nekoyume/Assets/Resources/UI/Textures/Staking_01.png
  nekoyume/Assets/Resources/UI/Textures/Staking_01.png.meta
  nekoyume/Assets/Resources/UI/Textures/Staking_02.png
  nekoyume/Assets/Resources/UI/Textures/Staking_02.png.meta
  nekoyume/Assets/Resources/UI/Textures/Staking_03.png
  nekoyume/Assets/Resources/UI/Textures/Staking_03.png.meta
  nekoyume/Assets/Resources/UI/Textures/Staking_04.png
  nekoyume/Assets/Resources/UI/Textures/Staking_04.png.meta
  nekoyume/Assets/Resources/UI/Textures/Staking_05.png
  nekoyume/Assets/Resources/UI/Textures/Staking_05.png.meta
  nekoyume/Assets/Resources/UI/Textures/Staking_Mob_01.png
  nekoyume/Assets/Resources/UI/Textures/Staking_Mob_01.png.meta
  nekoyume/Assets/Resources/UI/Textures/Staking_Mob_02.png
  nekoyume/Assets/Resources/UI/Textures/Staking_Mob_02.png.meta
  nekoyume/Assets/Resources/UI/Textures/Staking_Mob_03.png
  nekoyume/Assets/Resources/UI/Textures/Staking_Mob_03.png.meta
  nekoyume/Assets/Resources/UI/Textures/Staking_Mob_04.png
  nekoyume/Assets/Resources/UI/Textures/Staking_Mob_04.png.meta
  nekoyume/Assets/Resources/UI/Textures/Staking_Mob_05.png
  nekoyume/Assets/Resources/UI/Textures/Staking_Mob_05.png.meta
  nekoyume/Assets/Resources/UI/Textures/UI_Tooltip_01.png
  nekoyume/Assets/Resources/UI/Textures/UI_Tooltip_01.png.meta
  nekoyume/Assets/Resources/UI/Textures/UI_Tooltip_02.png
  nekoyume/Assets/Resources/UI/Textures/UI_Tooltip_02.png.meta
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_Staking_Icon_Arena.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_Staking_Icon_Arena.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_Staking_Icon_Decomposition.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_Staking_Icon_Decomposition.png.meta
  nekoyume/Assets/_Scripts/Game/TableSheets.cs
  nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/StakingItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/StakingItemView.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/Lobby/MainMenu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopupNone.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopupNone.cs.meta
Labels: Extra Large

#1568 Improve lobby and other UIs
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_EnhanceEquipment.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_EnhanceEquipment.prefab.meta
  nekoyume/Assets/_Scripts/UI/Module/ArenaTickets.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/ArenaMenu.cs
Labels: Extra Large

#1575 Fix CI
  .github/workflows/build.yml
Labels: bug, ci, Extra Small

#1581 [hotfix] Fix arena render bug
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Labels: bug, Extra Small, previewnet

#1582 Fix arena render bug
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Labels: bug, Extra Small

#1583 [Design]UI_StakingPopupNone_Prefab_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopupNone.prefab
Labels: Extra Small

#1585 Improve arena UI
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Emblems/SeasonArenaEmblem.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinBottomButtons.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonBarScroll.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfo.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfoSessionProgressFill.mat
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonScroll.prefab
  nekoyume/Assets/Resources/UI/Animations/ConditionalButton_Type7.controller
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/_Scripts/Extension/ArenaSheetExtensions.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinMissionButton.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinMissionButton.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSeasonInfo.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
Labels: Extra Large

#1586 Add missing value in `Analyzer`
  nekoyume/Assets/PackageExtensions/Mixpanel/MixpanelValueFactory.cs
Labels: bug, Extra Small

#1579 [Design] Button off
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopSell.prefab
Labels: Extra Small

#1578 Bugfix/main menu button fix
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
  nekoyume/Assets/Resources/UI/Animations/UIMenuController@Show.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
Labels: Large

#1589 Fix debug analyzer option
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Extra Small

#1592 [Bugfix] AfterRevomonContainer Animation add
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/EquipmentSlot.prefab
  nekoyume/Assets/Resources/UI/Animations/UILobbyController@BoxCatLoop.anim
  nekoyume/Assets/Resources/UI/Animations/UILobbyController@Combination_XmasLoop.anim
  nekoyume/Assets/Resources/UI/Animations/UILobbyController@MimirLoop.anim
  nekoyume/Assets/Resources/UI/Animations/UILobbyController@Quest_XmasLoop.anim
  nekoyume/Assets/Resources/UI/Animations/UILobbyController@RankingLoop.anim
  nekoyume/Assets/Resources/UI/Animations/UILobbyController@Shop_XmasLoop.anim
  nekoyume/Assets/Resources/UI/Animations/UILobbyController@bg_XmasLoop.anim
  nekoyume/Assets/Resources/UI/Animations/UIMenuController@Close.anim
  nekoyume/Assets/Resources/UI/Animations/UIMenuController@Show.anim
  nekoyume/Assets/Resources/UI/Animations/UI_ArenaJoin@Show.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
Labels: Extra Large

#1598 Add mixpanel trackers of crystal related actions.
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BuffBonusPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs
Labels: Extra Small

#1599 [Design] Disable not implemented crystal reward object
  nekoyume/Assets/Resources/UI/Prefabs/UI_Grind.prefab
Labels: Small

#1539 Skip prologue with certain registry value.
  nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
Labels: Extra Small

#1600 Disable not implemented object (second try)
  nekoyume/Assets/AddressableAssets/UI/Module/Grinding/GrindModule.prefab
Labels: Extra Large

#1601 Crystal and arena reboot L10N fixed
  nekoyume/Assets/StreamingAssets/Localization/buff_description.csv
  nekoyume/Assets/StreamingAssets/Localization/buff_name.csv
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/error.csv
  nekoyume/Assets/StreamingAssets/Localization/help_popup.csv
  nekoyume/Assets/StreamingAssets/Localization/notification.csv
  nekoyume/Assets/StreamingAssets/Localization/skill_name.csv
Labels: Extra Large

#1603 Add missing L10N key in StakingPopupNone
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopupNone.prefab
Labels: Extra Small

#1608 Reflect on ItemEnhancement9 & 10
  nekoyume/Assets/_Scripts/Extension/LocalizationExtension.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/EnhancementResultPopup.cs
Labels: Extra Small

#1609 Fix NRE in checking registry value
  nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
Labels: Extra Small

#1610 Fix `BalanceDoesNotExistException`
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
Labels: bug, Extra Small

#1611 Back to lobby when `BattleArena` action failed
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Labels: bug, Extra Small

#1614 Fix rewards of championship on `ArenaJoin` UI
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
Labels: Extra Small

#1615 Fix not initialize the staking level in `States` when run on rpc mode
  nekoyume/Assets/_Scripts/BlockChain/Agent.cs
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
Labels: bug, Extra Small

#1616 Add exception handling about find level by staked amount
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/Agent.cs
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
Labels: Small

#1617 Fix arena data cache bug
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
  nekoyume/Assets/_Scripts/State/RxProps.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardBillboard.cs
Labels: bug, Extra Small

#1620 [bugfix] PlusText, ButtonText fix
  nekoyume/Assets/Resources/UI/Prefabs/UI_SweepPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SweepScreenPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SweepScreenPopup.prefab.meta
Labels: Extra Small

#1623 Fix arena medal resource getter
  nekoyume/Assets/_Scripts/Extension/ArenaSheetExtensions.cs
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
Labels: bug, Extra Small

#1625 bump: libplanet
  nekoyume/Assets/Packages/Libplanet.Net.dll
  nekoyume/Assets/Packages/Libplanet.dll
  nekoyume/Assets/_Scripts/BlockChain/Agent.cs
Labels: Extra Small

#1624 [Design] ArenaBoard text add
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerScroll.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBoard.prefab
Labels: Large

#1626 Fix bug in loading stake icon image.
  nekoyume/Assets/Resources/ScriptableObject/UI_StakeIconData.asset
  nekoyume/Assets/Resources/ScriptableObject/UI_StakeIconData.asset.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
  nekoyume/Assets/_Scripts/Game/ScriptableObject/StakeIconDataScriptableObject.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/StakeIconDataScriptableObject.cs.meta
  nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Medium

#1629 Introduce UpdateAvatarStateV2
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
  nekoyume/Assets/_Scripts/Extension/AvatarStateExtensions.cs
Labels: Extra Small

#1631 Fix animation bug in inventory grinding.
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
  nekoyume/Assets/_Scripts/Animation.meta
  nekoyume/Assets/_Scripts/Animation/AnimationFinisher.cs
  nekoyume/Assets/_Scripts/Animation/AnimationFinisher.cs.meta
Labels: Medium

#1632 Update the `GameObject` activation on the `UI_ArenaBoard`
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBoard.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardPlayerScroll.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
Labels: Small

#1633 Bug fix/arena board player scroll
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerScroll.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/ArenaRankCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/ArenaRankCell.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBoard.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_FriendInfoPopup.prefab
  nekoyume/Assets/_Scripts/Extension/ItemExtensions.cs
  nekoyume/Assets/_Scripts/Extension/ItemExtensions.cs.meta
  nekoyume/Assets/_Scripts/Extension/ItemSheetExtension.cs
  nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardPlayerCell.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardPlayerScroll.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardSO.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinMissionButton.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSO.cs
  nekoyume/Assets/_Scripts/UI/Module/Character/FramedCharacterView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/BaseItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentInventoryItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/InventoryItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/ShopCartItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/ShopItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/StakingItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/SweepItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/TooltipItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/VanillaItemView.cs
  nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankCell.cs
  nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankCell.cs.meta
  nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankScroll.cs
  nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankScroll.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/FriendInfoPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/RankingBattleResultPopup.cs
Labels: bug, Extra Large

#1634 Fix arena medal bugs
  nekoyume/Assets/Tests/EditMode/Extensions/ArenaSheetExtensionsTest.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Extension/ArenaSheetExtensions.cs
  nekoyume/Assets/_Scripts/Extension/ItemSheetExtension.cs
  nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/BaseItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/VanillaItemView.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
Labels: bug, Medium

#1638 100230 l10n 2ndfixed
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
Labels: Extra Small

#1639 Fix bug in displaying buff button.
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/RankCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CharacterView/DetailedCharacterView.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
  nekoyume/Assets/_Scripts/UI/Module/Button/BonusBuffButton.cs
  nekoyume/Assets/_Scripts/UI/Module/Character/DetailedCharacterView.cs
Labels: Small

#1641 Add Linux CI Build
  .github/workflows/build.yml
Labels: Extra Small

#1642 Fix arena battle reward bug
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Extension/ItemExtensions.cs
Labels: bug, Extra Small

#1645 Cover arena ticket does not enough case in `ArenaBattlePreparation` UI
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalCostButton.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
Labels: bug, Extra Small

#1646 Bugfix/button type animation fix
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfoSessionProgressFill.mat
  nekoyume/Assets/Resources/UI/Animations/ConditionalButton_Type1.controller
  nekoyume/Assets/Resources/UI/Animations/ConditionalButton_Type2.controller
  nekoyume/Assets/Resources/UI/Animations/ConditionalButton_Type4.controller
  nekoyume/Assets/Resources/UI/Animations/ConditionalButton_Type5.controller
  nekoyume/Assets/Resources/UI/Animations/ConditionalButton_Type6.controller
  nekoyume/Assets/Resources/UI/Animations/ConditionalButton_Type7.controller
Labels: Extra Large

#1650 Fix ncg and crystal text
  nekoyume/Assets/_Scripts/UI/Module/Crystal.cs
  nekoyume/Assets/_Scripts/UI/Module/Gold.cs
Labels: bug, Extra Small

#1651 Fix ncg and crystal text
  nekoyume/Assets/_Scripts/UI/Module/Crystal.cs
  nekoyume/Assets/_Scripts/UI/Module/Gold.cs
Labels: bug, Extra Small

#1649 Fix unit tests and minor changes
  nekoyume/Assets/Tests/EditMode/Extensions/ArenaSheetExtensionsTest.cs
  nekoyume/Assets/_Scripts/Extension/ArenaSheetExtensions.cs
  nekoyume/Assets/_Scripts/Extension/AvatarStateExtensions.cs
  nekoyume/Assets/_Scripts/Extension/ItemSheetExtension.cs
  nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/BaseItemView.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
  nekoyume/Packages/manifest.json
  nekoyume/Packages/packages-lock.json
Labels: Extra Small

#1652 Show bonus buff button on state is null
  nekoyume/Assets/_Scripts/UI/Module/Button/BonusBuffButton.cs
Labels: Extra Small

#1654 Bug fix/async loading for arena
  nekoyume/Assets/Tests/EditMode/State/AsyncUpdatableRxPropTest.cs
  nekoyume/Assets/_Scripts/State/AsyncUpdatableRxProp.cs
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/ArenaMenu.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs
Labels: bug, Small

#1655 Enable world unlock effect by first unlock condition
  nekoyume/Assets/_Scripts/UI/Module/Button/WorldButton.cs
Labels: Extra Small

#1656 [Hotfix] Change banner order
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
Labels: Extra Small

#1657 Merge `rc-v100231` into `main`
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
  nekoyume/Assets/Tests/EditMode/State/AsyncUpdatableRxPropTest.cs
  nekoyume/Assets/_Scripts/State/AsyncUpdatableRxProp.cs
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
  nekoyume/Assets/_Scripts/UI/Module/Button/WorldButton.cs
  nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
  nekoyume/Assets/_Scripts/UI/Module/Crystal.cs
  nekoyume/Assets/_Scripts/UI/Module/Gold.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/ArenaMenu.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs
Labels: Medium

#1658 Fix NRE on `ArenaBoard`
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
Labels: bug, Extra Small

#1660 Empty `CrystalRandomSkillState` when switching to new avatar.
  nekoyume/Assets/_Scripts/State/States.cs
Labels: Extra Small

#1661 Merge `rc-v100231` into `main`
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
Labels: Extra Small

#1665 Fix compile error
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
Labels: bug, Extra Small

#1667 Fix WorldMap button UI bugs
  nekoyume/Assets/_Scripts/UI/Module/Button/WorldButton.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs
Labels: Extra Small

#1621 [Design] ArenaBattle Bg add
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattlePreparation.prefab
  nekoyume/Assets/Sprites/Background/Combination/bg_combination_Main_04.png
  nekoyume/Assets/Sprites/Background/Dungeon/Bg_dungeon_Arena_01.png
  nekoyume/Assets/Sprites/Background/Dungeon/Bg_dungeon_Arena_01.png.meta
  nekoyume/Assets/Sprites/Background/Dungeon/Bg_dungeon_Arena_02.png
  nekoyume/Assets/Sprites/Background/Dungeon/Bg_dungeon_Arena_02.png.meta
Labels: Medium

#1670 Improve arena stuffs
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinBottomButtons.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/RankCell.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinMissionButton.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
Labels: Large

#1671 Fix the crystal update timings
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/BlockRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Module/Crystal.cs
Labels: bug, Extra Small

#1669 Introcude `ToCurrencyNotation` extension method
  nekoyume/Assets/_Scripts/Extension/BigIntegerExtensions.cs
  nekoyume/Assets/_Scripts/Extension/BigIntegerExtensions.cs.meta
  nekoyume/Assets/_Scripts/Extension/FungibleAssetValueExtensions.cs
  nekoyume/Assets/_Scripts/Extension/FungibleAssetValueExtensions.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/Crystal.cs
Labels: Extra Small

#1672 Add new notice - Claim Daily reward X2
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
  nekoyume/Assets/UIResources/Content/Notice/Information_04.png
  nekoyume/Assets/UIResources/Content/Notice/Information_04.png.meta
  nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs
Labels: Medium
