Repository planetarium/NineChronicles, pull requests merged in 2022-10, with the labels that each got.

#2033 Add request condition
  nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs
  nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossStates.cs
  nekoyume/Assets/_Scripts/UI/RequestManager.cs
Labels: Extra Small

#2030 Add price-per-unit marker on shop item price text
  nekoyume/Assets/_Scripts/UI/Module/Item/ShopItemView.cs
Labels: Extra Small

#2039 Add equipped notification to Foods
  nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs
Labels: Extra Small

#2040 [Design] RuneTab add
  nekoyume/Assets/AddressableAssets/UI/Module/Inventory.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/WorldMap/WorldButton.prefab
  nekoyume/Assets/Resources/UI/Icons/Mail/icon_mail_arena.png
  nekoyume/Assets/Resources/UI/Icons/Mail/icon_mail_staking.png
  nekoyume/Assets/Resources/UI/Icons/Mail/icon_mail_staking.png.meta
  nekoyume/Assets/Resources/UI/Icons/Mail/icon_mail_worldBoss.png
  nekoyume/Assets/Resources/UI/Icons/Mail/icon_mail_worldBoss.png.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab
Labels: Extra Large

#2044 Fix skill animation and damage text sync in Arena
  nekoyume/Assets/_Scripts/Game/Character/ArenaCharacter.cs
Labels: Extra Small

#2043 Fix `InvalidCastException`
  nekoyume/Assets/_Scripts/BlockChain/Agent.cs
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
Labels: Extra Small

#2046 add agent address to mixpanel tracking
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
  nekoyume/Assets/_Scripts/Game/Character/Player.cs
  nekoyume/Assets/_Scripts/Game/Prologue.cs
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BuffBonusPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs
Labels: Extra Small

#2042 Update UI of super craft and etc.
  nekoyume/Assets/Resources/UI/Animations/UI_ArenaBoard@Show.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBoard.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattleResultPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemCountableAndPricePopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SuperCraftPopup.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Popup/UI_Popup_bg_32.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Popup/UI_Popup_bg_32.png.meta
Labels: Large

#2053 [Design] Arena Title add
  nekoyume/Assets/Resources/Font/Materials/ChineseSimplified SDF Material - QuestRewardText6.mat
  nekoyume/Assets/Resources/Font/Materials/ChineseSimplified SDF Material - QuestRewardText6.mat.meta
  nekoyume/Assets/Resources/Font/Materials/English SDF Material - QuestRewardText6.mat
  nekoyume/Assets/Resources/Font/Materials/English SDF Material - QuestRewardText6.mat.meta
  nekoyume/Assets/Resources/Font/Materials/Japanese SDF Material - QuestRewardText6.mat
  nekoyume/Assets/Resources/Font/Materials/Japanese SDF Material - QuestRewardText6.mat.meta
  nekoyume/Assets/Resources/Font/Materials/Korean SDF Material - QuestRewardText6.mat
  nekoyume/Assets/Resources/Font/Materials/Korean SDF Material - QuestRewardText6.mat.meta
  nekoyume/Assets/Resources/Font/Materials/Polish SDF Material - QuestRewardText6.mat
  nekoyume/Assets/Resources/Font/Materials/Polish SDF Material - QuestRewardText6.mat.meta
  nekoyume/Assets/Resources/Font/Materials/PortugueseBrazil SDF Material - QuestRewardText6.mat
  nekoyume/Assets/Resources/Font/Materials/PortugueseBrazil SDF Material - QuestRewardText6.mat.meta
  nekoyume/Assets/Resources/Font/Materials/Russia SDF Material - QuestRewardText6.mat
  nekoyume/Assets/Resources/Font/Materials/Russia SDF Material - QuestRewardText6.mat.meta
  nekoyume/Assets/Resources/Font/Materials/Thai SDF Material - QuestRewardText6.mat
  nekoyume/Assets/Resources/Font/Materials/Thai SDF Material - QuestRewardText6.mat.meta
  nekoyume/Assets/Resources/L10nSettings/FontAssetData ChineseSimplified SDF.asset
  nekoyume/Assets/Resources/L10nSettings/FontAssetData English SDF.asset
  nekoyume/Assets/Resources/L10nSettings/FontAssetData Japanese SDF.asset
  nekoyume/Assets/Resources/L10nSettings/FontAssetData Korean SDF.asset
  nekoyume/Assets/Resources/L10nSettings/FontAssetData Polish SDF.asset
  nekoyume/Assets/Resources/L10nSettings/FontAssetData PortugueseBrazil SDF.asset
  nekoyume/Assets/Resources/L10nSettings/FontAssetData Thai SDF.asset
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_ChStyle/Icon_ChTextStyle_06.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_ChStyle/Icon_ChTextStyle_06.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_ChStyle/Icon_ChTextStyle_06_Outglow.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_ChStyle/Icon_ChTextStyle_06_Outglow.png.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/item_TextStyle_06.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/item_TextStyle_06.prefab.meta
  nekoyume/Assets/UIResources/Content/Effect/TextStyle/Item_TextStyle_06.controller
  nekoyume/Assets/UIResources/Content/Effect/TextStyle/Item_TextStyle_06.controller.meta
  nekoyume/Assets/UIResources/Content/Effect/TextStyle/Item_TextStyle_06_Loop.anim
  nekoyume/Assets/UIResources/Content/Effect/TextStyle/Item_TextStyle_06_Loop.anim.meta
  nekoyume/Assets/_Scripts/L10n/FontMaterialType.cs
Labels: Extra Large

#2054 [bugfix] Text Area fix
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab
Labels: Small

#2052 [bugfix] Enhancement Effect fix
  nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
  nekoyume/Assets/UIResources/Content/Effect/Grade/Distortion_Result_Success.mat
Labels: Extra Small

#2058 Fix CurrencyNotation expression
  nekoyume/Assets/_Scripts/Extensions/BigIntegerExtensions.cs
Labels: Extra Small

#2060 [Design] ArenaTitle Icon add
  nekoyume/Assets/Resources/UI/Icons/Item/49900007.png
  nekoyume/Assets/Resources/UI/Icons/Item/49900007.png.meta
Labels: Medium

#2048 Introduce `LocalMailHelper`
  nekoyume/Assets/_Scripts/Helper/LocalMailHelper.cs
  nekoyume/Assets/_Scripts/Helper/LocalMailHelper.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
Labels: Extra Small

#2062 [bugfix] TextArea 115 > 160
  nekoyume/Assets/UIResources/Content/Common/Prefab/item_TextStyle_06.prefab
Labels: Extra Small

#2064 Cherry-pick #2062 to rc-v100310
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
  nekoyume/Assets/UIResources/Content/Common/Prefab/item_TextStyle_06.prefab
Labels: Small

#2073 Edit arena season schedule
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonBarScroll.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfoSessionProgressFill.mat
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/Tests/EditMode/Extensions/ArenaSheetExtensionsTest.cs
  nekoyume/Assets/_Scripts/Extensions/ArenaSheetExtensions.cs
  nekoyume/Assets/_Scripts/Extensions/ItemSheetExtensions.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSeasonBarScroll.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSeasonInfo.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/BaseItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/VanillaItemView.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
Labels: Extra Large

#2074 Fix ArenaJoinSeasonBarScroll prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonBarScroll.prefab
Labels: Extra Small

#2075 Remove avatar address logging in prologue
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
  nekoyume/Assets/_Scripts/Game/Prologue.cs
Labels: Extra Small

#2070 introduce sentry tracing
  .github/bin/inject-client-data.sh
  .github/bin/inject-mixpanel-client-data.sh
  .github/workflows/build.yml
  nekoyume/Assets/PackageExtensions/Mixpanel/MixpanelValueFactory.cs
  nekoyume/Assets/Plugins/Sentry.meta
  nekoyume/Assets/Plugins/Sentry/SentryCliOptions.asset
  nekoyume/Assets/Plugins/Sentry/SentryCliOptions.asset.meta
  nekoyume/Assets/Resources/Sentry.meta
  nekoyume/Assets/Resources/Sentry/SentryOptions.asset
  nekoyume/Assets/Resources/Sentry/SentryOptions.asset.meta
  nekoyume/Assets/_Scripts/Analyzer.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
  nekoyume/Assets/_Scripts/Game/Character/Player.cs
  nekoyume/Assets/_Scripts/Game/Prologue.cs
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BuffBonusPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/TitleOneButtonSystem.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/HelpTooltip.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs
  nekoyume/Packages/manifest.json
  nekoyume/Packages/packages-lock.json
Labels: Large

#2077 Update `auto_assign.yml`, add new maintainer
  .github/auto_assign.yml
Labels: Extra Small

#2063 Cache Raid:Season reward, Add notifying as Mail
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs
  nekoyume/Assets/_Scripts/Helper/LocalMailHelper.cs
  nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs
  nekoyume/Assets/_Scripts/L10n/L10nManager.cs
  nekoyume/Assets/_Scripts/UI/Model/RaidRewardMail.cs
  nekoyume/Assets/_Scripts/UI/Model/RaidRewardMail.cs.meta
  nekoyume/Assets/_Scripts/UI/Model/WorldBossModel.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs
  nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossGradeReward.cs
  nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossQuery.cs
  nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossStates.cs
  nekoyume/Assets/_Scripts/UI/RequestManager.cs
  nekoyume/Assets/_Scripts/UI/Scroller/MailCell.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/QuitSystem.cs
Labels: Extra Large

#2078 Edit arena participants order
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
Labels: Extra Small

#2079 Fix notice popup
  nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs
Labels: bug, Extra Small
