Repository planetarium/NineChronicles, pull requests merged in 2022-03, with the labels that each got.

#1207 Introduce Caching state & balance
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
  nekoyume/Assets/_Scripts/Game/Event.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/PreloadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
Labels: Small

#1223 Check Libplanet versions using the proper assembly metadata
  .github/bin/check-libplanet-version.sh
  .github/workflows/build-misc.yml
  nekoyume/Assets/Packages/Libplanet.RocksDBStore.dll
  nekoyume/Assets/Packages/Libplanet.Stun.dll
Labels: bug, ci, Small

#1227 Introduce `DataExporter`
  nekoyume/Assets/Planetarium/Nekoyume/Editor/DataExporter.cs
  nekoyume/Assets/Planetarium/Nekoyume/Editor/DataExporter.cs.meta
  nekoyume/Assets/Planetarium/Nekoyume/Editor/Nekoyume-editor.asmdef
Labels: Small

#1229 Fix CI
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionUnrenderHandler.cs
Labels: Extra Small

#1228 Introduce `StoreDownloader` editor menu
  nekoyume/Assets/Planetarium/Nekoyume/Editor/DataExporter.cs
  nekoyume/Assets/Planetarium/Nekoyume/Editor/StoreDownloader.cs
  nekoyume/Assets/Planetarium/Nekoyume/Editor/StoreDownloader.cs.meta
  nekoyume/Assets/Planetarium/Nekoyume/Editor/ZipUnzip.cs
  nekoyume/Assets/Planetarium/Nekoyume/Editor/ZipUnzip.cs.meta
Labels: Small

#1231 Show preview spine object in costume tooltip.
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView_tooltip.prefab
  nekoyume/Assets/RenderTexture/CostumeTooltipSpineCamera.renderTexture
  nekoyume/Assets/RenderTexture/CostumeTooltipSpineCamera.renderTexture.meta
  nekoyume/Assets/Resources/Character/FullCostumeCutscene/40100001.prefab
  nekoyume/Assets/Resources/Character/FullCostumeCutscene/40100005.prefab
  nekoyume/Assets/Resources/Character/FullCostumeCutscene/40100006.prefab
  nekoyume/Assets/Resources/ScriptableObject/SpineTooltipData.asset
  nekoyume/Assets/Resources/ScriptableObject/SpineTooltipData.asset.meta
  nekoyume/Assets/_Scenes/Game.unity
  nekoyume/Assets/_Scripts/Game/ScriptableObject/SpineTooltipData.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/SpineTooltipData.cs.meta
  nekoyume/Assets/_Scripts/Game/ScriptableObject/SpineTooltipDataScriptableObject.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/SpineTooltipDataScriptableObject.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/Item/BaseItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/TooltipItemView.cs
Labels: Extra Large

#1244 link material popup to item view
  nekoyume/Assets/_Scripts/UI/Scroller/QuestCell.cs
Labels: improve, Extra Small

#1235 Optimize shop buy items loading
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/UIResources/Content/Shop/Ani/MainButton.controller
  nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopView.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
Labels: improve, Extra Large

#1233 [Design] Season image Change
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/ArenaRankCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CharacterView/DetailedCharacterView.prefab
  nekoyume/Assets/Resources/UI/Icons/Item/700003.png
  nekoyume/Assets/Resources/UI/Icons/Item/700003.png.meta
  nekoyume/Assets/Resources/UI/Icons/Item/700004.png
  nekoyume/Assets/Resources/UI/Icons/Item/700004.png.meta
  nekoyume/Assets/Resources/UI/Icons/Item/700005.png
  nekoyume/Assets/Resources/UI/Icons/Item/700005.png.meta
  nekoyume/Assets/Resources/UI/Icons/Item/700006.png
  nekoyume/Assets/Resources/UI/Icons/Item/700006.png.meta
  nekoyume/Assets/Resources/UI/Icons/Item/700007.png
  nekoyume/Assets/Resources/UI/Icons/Item/700007.png.meta
  nekoyume/Assets/Resources/UI/Icons/Item/700008.png
  nekoyume/Assets/Resources/UI/Icons/Item/700008.png.meta
  nekoyume/Assets/Resources/UI/Icons/Item/700009.png
  nekoyume/Assets/Resources/UI/Icons/Item/700009.png.meta
  nekoyume/Assets/Resources/UI/Icons/Item/700010.png
  nekoyume/Assets/Resources/UI/Icons/Item/700010.png.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab
Labels: Extra Large

#1248 Improve/notice popup logic
  nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs
Labels: Extra Small

#1247 Improve acquisition place UI
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs
Labels: Medium

#1251 [Cherry pick] add notification popup
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab.meta
  nekoyume/Assets/Resources/UI/Textures/Notice.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_Popup_icon_10.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_Popup_icon_10.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Popup/UI_bg_frame_16.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Popup/UI_bg_frame_16.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Popup/UI_bg_frame_16_deco.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Popup/UI_bg_frame_16_deco.png.meta
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_06.png
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_06.png.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Item_Banner_06.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Item_Banner_06.prefab.meta
  nekoyume/Assets/UIResources/Content/Notice.meta
  nekoyume/Assets/UIResources/Content/Notice/Information_01.png
  nekoyume/Assets/UIResources/Content/Notice/Information_01.png.meta
  nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs
  nekoyume/Assets/_Scripts/Game/Event/EventManager.cs
  nekoyume/Assets/_Scripts/Helper/Util.cs
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
  nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs.meta
Labels: Extra Large

#1252 fix banner url
  nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs
Labels: Extra Small

#1254 Polishing for v100140
  nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
Labels: Extra Small

#1253 Apply ui skeleton animation on costume tooltip
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView.prefab
  nekoyume/Assets/AddressableAssetsData.meta
  nekoyume/Assets/RenderTexture/CostumeTooltipSpineCamera.renderTexture
  nekoyume/Assets/Resources/Character/FullCostumeTooltip.meta
  nekoyume/Assets/Resources/Character/FullCostumeTooltip/40100001.prefab
  nekoyume/Assets/Resources/Character/FullCostumeTooltip/40100001.prefab.meta
  nekoyume/Assets/Resources/Character/FullCostumeTooltip/40100002.prefab
  nekoyume/Assets/Resources/Character/FullCostumeTooltip/40100002.prefab.meta
  nekoyume/Assets/Resources/Character/FullCostumeTooltip/40100003.prefab
  nekoyume/Assets/Resources/Character/FullCostumeTooltip/40100003.prefab.meta
  nekoyume/Assets/Resources/Character/FullCostumeTooltip/40100005.prefab
  nekoyume/Assets/Resources/Character/FullCostumeTooltip/40100005.prefab.meta
  nekoyume/Assets/Resources/Character/FullCostumeTooltip/40100006.prefab
  nekoyume/Assets/Resources/Character/FullCostumeTooltip/40100006.prefab.meta
  nekoyume/Assets/Resources/ScriptableObject/SpineTooltipData.asset
  nekoyume/Assets/_Scenes/Game.unity
  nekoyume/Assets/_Scripts/Game/ScriptableObject/SpineTooltipDataScriptableObject.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/TooltipItemView.cs
Labels: Extra Large

#1255 Check tutorial is complete safely
  nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs
Labels: Extra Small

#1258 Fix GetStageByOrder in acquisition place
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs
Labels: Extra Small

#1259 Add disposable to touchHandler
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
  nekoyume/Assets/_Scripts/Helper/Util.cs
  nekoyume/Assets/_Scripts/UI/Module/BattleReward.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/CountableItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/ItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/RequiredItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/StageRewardItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/VanillaItemView.cs
  nekoyume/Assets/_Scripts/UI/Scroller/GuidedQuestCell.cs
  nekoyume/Assets/_Scripts/UI/Scroller/QuestCell.cs
  nekoyume/Assets/_Scripts/UI/Widget/StageInformation.cs
Labels: Medium

#1260 Fix notice info
  nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs
Labels: Extra Small

#1264 Remove returning, add not cleared stage next cleared stage
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs
Labels: Extra Small

#1263 Remove settings folder at uninstall
  tools/installer/installer.iss
Labels: Extra Small

#1265 Add Editor Menu to Generate font asset automatically
  nekoyume/Assets/Resources/L10nSettings/FontAssetGenerationSettings.asset
  nekoyume/Assets/Resources/L10nSettings/FontAssetGenerationSettings.asset.meta
  nekoyume/Assets/_Scripts/L10n/Editor/FontAssetGenerator.cs
  nekoyume/Assets/_Scripts/L10n/Editor/FontAssetGenerator.cs.meta
  nekoyume/Assets/_Scripts/L10n/Editor/L10nManagerEditor.cs
  nekoyume/Assets/_Scripts/L10n/Editor/Nekoyume.L10n.Editor.asmdef
  nekoyume/Assets/_Scripts/L10n/FontAssetGenerationSettings.cs
  nekoyume/Assets/_Scripts/L10n/FontAssetGenerationSettings.cs.meta
Labels: Extra Large

#1250 Extend event data
  nekoyume/Assets/Resources/ScriptableObject/EventData.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Event_Banner_Item.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Event_Banner_Item.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Event_Banner_Page_Off.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Event_Banner_Page_Off.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Event_Banner_Page_On.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Event_Banner_Page_On.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Item_Banner_01.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Item_Banner_01.prefab.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Item_Banner_02.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Item_Banner_03.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Item_Banner_04.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Item_Banner_05.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Item_Banner_05.prefab.meta
  nekoyume/Assets/_Scripts/Game/Event/EventManager.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/EventScriptableObject.cs
  nekoyume/Assets/_Scripts/UI/Module/EventBannerItem.cs
  nekoyume/Assets/_Scripts/UI/Module/EventBannerItem.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/PageView.cs
  nekoyume/Assets/_Scripts/UI/RankingInfo.cs
  nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs
  nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs
Labels: improve, Extra Large

#1272 Change url of submodules ssh to https
  .gitmodules
Labels: Extra Small

#1274 Override CanHandleInputEvent to false in HeaderMenuStatic
  nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
Labels: Extra Small

#1276 Cherry pick #1274 to rc-v100141
  nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
Labels: Extra Small

#1277 fix `DateTime` parsing bug
  nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs
Labels: bug, Extra Small

#1278 change playerfrabs key format for `NoticePopup`
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Shop.spriteatlas
  nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs
Labels: bug, Extra Small

#1279 Merge rc-v100141 to main
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Shop.spriteatlas
  nekoyume/Assets/_Scripts/UI/Widget/Popup/NoticePopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
Labels: Extra Small

#1225 Fix invalid equipment in Arena
  nekoyume/Assets/_Scripts/Game/Character/Player.cs
Labels: Extra Small

#1286 fix NRE when create avatar
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
Labels: bug

#1292 Release automation
  .github/workflows/release.yaml
Labels: Extra Small

#1289 [Design] font fix
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab
Labels: Extra Small

#1271 Make target in Tooltip to optional and if target is null, panel move to center
  nekoyume/Assets/_Scripts/UI/Module/BattleReward.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/RequiredItemView.cs
  nekoyume/Assets/_Scripts/UI/Scroller/GuidedQuestCell.cs
  nekoyume/Assets/_Scripts/UI/Scroller/QuestCell.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/FriendInfoPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
  nekoyume/Assets/_Scripts/UI/Widget/StageInformation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltip.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs
Labels: Medium

#1296 `Analyzer` contains rpc server host data
  nekoyume/Assets/PackageExtensions/Mixpanel/MixpanelValueFactory.cs
  nekoyume/Assets/_Scripts/Analyzer.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Extra Small
