Repository planetarium/NineChronicles, pull requests merged in 2022-05, with the labels that each got.

#1414 Change `ConfirmCallback` invoking sequence in `IconAndButtonSystem`
  nekoyume/Assets/_Scripts/UI/Widget/System/IconAndButtonSystem.cs
Labels: Extra Small

#1424 Improve `ConditionalCostButton` to handle various currencies.
  nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type2.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type6.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Grind.prefab
  nekoyume/Assets/_Scripts/UI/Combination/RecipeUnlockInfo.cs
  nekoyume/Assets/_Scripts/UI/Combination/RecipeUnlockInfo.cs.meta
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
  nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalCostButton.cs
Labels: Extra Large

#1423 Add AP charge in Grinding
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Grind.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalCostButton.cs
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
  nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
Labels: Medium

#1427 Introduce CompileHelper
  nekoyume/Assets/Planetarium/Nekoyume/Editor/CompileHelper.cs
  nekoyume/Assets/Planetarium/Nekoyume/Editor/CompileHelper.cs.meta
Labels: Extra Small

#1428 Update missing changes from #1427
  nekoyume/Assets/Planetarium/Nekoyume/Editor/CompileHelper.cs
Labels: Extra Small

#1430 Show recipe unlock button regardless of current balance.
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Model/RecipeModel.cs
  nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeCell.cs
  nekoyume/Assets/_Scripts/UI/Payment/PaymentPopup.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
Labels: Small

#1432 Introduce `ShowOnAttribute`.
  nekoyume/Assets/_Scripts/Editor.meta
  nekoyume/Assets/_Scripts/Editor/ShowOnAttribute.cs
  nekoyume/Assets/_Scripts/Editor/ShowOnAttribute.cs.meta
  nekoyume/Assets/_Scripts/Editor/ShowOnAttributeDrawer.cs
  nekoyume/Assets/_Scripts/Editor/ShowOnAttributeDrawer.cs.meta
  nekoyume/Assets/_Scripts/Game/Util/PositionConstraints/Editor/PositionConstraintToScreenEditor.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/ItemView.cs
Labels: Medium

#1434 Refactor UI_Menu prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby.meta
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/BoxCatBtnContainers.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/BoxCatBtnContainers.prefab.meta
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CombinationBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CombinationBtn.prefab.meta
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/Mail.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/Mail.prefab.meta
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/MimisbrunnrBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/MimisbrunnrBtn.prefab.meta
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/QuestBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/QuestBtn.prefab.meta
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab.meta
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/ShopBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/ShopBtn.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
Labels: Extra Large

#1442 Improve handling local modifier in crystal.
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/Agent.cs
  nekoyume/Assets/_Scripts/BlockChain/BlockRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
  nekoyume/Assets/_Scripts/State/LocalLayer.cs
  nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs
  nekoyume/Assets/_Scripts/State/Modifiers/AgentCrystalModifier.cs
  nekoyume/Assets/_Scripts/State/Modifiers/IValueModifier.cs
  nekoyume/Assets/_Scripts/State/Modifiers/IValueModifier.cs.meta
  nekoyume/Assets/_Scripts/State/ReactiveCrystalState.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/State/Subjects/AgentStateSubject.cs
  nekoyume/Assets/_Scripts/UI/Model/RecipeModel.cs
  nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalCostButton.cs
  nekoyume/Assets/_Scripts/UI/Module/Crystal.cs
  nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeCell.cs
  nekoyume/Assets/_Scripts/UI/Payment/PaymentPopup.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
Labels: Medium

#1451 Introduce `RxProps`
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/State/AsyncUpdatableRxProp.cs
  nekoyume/Assets/_Scripts/State/AsyncUpdatableRxProp.cs.meta
  nekoyume/Assets/_Scripts/State/IAsyncUpdatableReadOnlyRxProp.cs
  nekoyume/Assets/_Scripts/State/IAsyncUpdatableReadOnlyRxProp.cs.meta
  nekoyume/Assets/_Scripts/State/RxProps.cs
  nekoyume/Assets/_Scripts/State/RxProps.cs.meta
Labels: Medium

#1454 Improve `ArenaJoin` UI
  .gitignore
  nekoyume/.gitignore
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/ArenaJoinBottomButtons.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/ArenaJoinSO.asset
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/ArenaJoinSeasonInfo.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/ArenaTicketProgressBar.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/ArenaTicketProgressBar.prefab.meta
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/_Scripts/L10n/L10nManager.cs
  nekoyume/Assets/_Scripts/State/AsyncUpdatableRxProp.cs
  nekoyume/Assets/_Scripts/State/RxProps.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/ArenaJoinBottomButtons.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/ArenaJoinBottomButtons.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/Arena/ArenaJoinSO.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/ArenaJoinSeasonInfo.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/ArenaJoinSeasonScroll.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/ArenaTicketProgressBar.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/ArenaTicketProgressBar.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/Lobby/ArenaMenu.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
  nekoyume/UserSettings/QuickSearch.settings
Labels: Extra Large

#1456 Introduce ArenaTickets module using in HeaderMenuStatic
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/ActionPoint.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/ArenaTickets.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/ArenaTickets.prefab.meta
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/DailyBonus.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/DailyBonusController.controller
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/DailyBonusController@Full.anim
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/DailyBonusController@GetReward.anim
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/DailyBonusController@Loop.anim
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/Gold.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/Hourglass.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
  nekoyume/Assets/_Scripts/State/AsyncUpdatableRxProp.cs
  nekoyume/Assets/_Scripts/State/RxProps.cs
  nekoyume/Assets/_Scripts/UI/Module/ActionPoint.cs
  nekoyume/Assets/_Scripts/UI/Module/ArenaTickets.cs
  nekoyume/Assets/_Scripts/UI/Module/ArenaTickets.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/DailyBonus.cs
  nekoyume/Assets/_Scripts/UI/Module/Gold.cs
  nekoyume/Assets/_Scripts/UI/Module/Hourglass.cs
  nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
Labels: Extra Large

#1458 arena-season3-coustume l10n added
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
Labels: Medium

#1468 Change daily reward banner image
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_11.png
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_11.png.meta
Labels: Medium

#1470 Implement `Read(GrindingMail)` in previewnet
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
Labels: Extra Small

#1466 shop &sweep improvement l10n added
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#1457 Support challenge stage sweep
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
Labels: Extra Small

#1474 [Design] Scroll Animation add
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonBarScroll.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonCellChampionship@Scroll.anim
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonCellSeason@Scroll.anim
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfo.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfoSessionProgressFill.mat
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonScroll.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/Resources/UI/Textures/PVP/Bg_Arena_Championship_add.png
  nekoyume/Assets/Resources/UI/Textures/PVP/Bg_Arena_Championship_add.png.meta
  nekoyume/Assets/Resources/UI/Textures/PVP/Bg_Arena_Season_add.png
  nekoyume/Assets/Resources/UI/Textures/PVP/Bg_Arena_Season_add.png.meta
Labels: Extra Large

#1476 Change icon name 40100008 & 9
  nekoyume/Assets/Resources/UI/Icons/Item/40100008.png
  nekoyume/Assets/Resources/UI/Icons/Item/40100009.png
Labels: No Changes

#1480 Bugfix/crystal icon reconnect
  nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type2.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type6.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type6_Test.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type6_Test.prefab.meta
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/ActionPoint.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/ArenaTickets.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/Crystal.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/DailyBonus.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/Gold.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/Hourglass.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_RecipeSlot.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/WorldMap/WorldButton.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationLoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_EnhancementResultPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Grind.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PaymentPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ReplaceMaterialPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/item_CrystalGetAnimation.prefab
  nekoyume/Assets/TextMesh Pro/Sprites/icon_Goods.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Popup/UI_main_icon_crystal_big.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Popup/UI_main_icon_crystal_big.png.meta
Labels: bug, Extra Large

#1484 Publish Unity Player on also 2022q2 branch
  .github/workflows/build.yml
Labels: Extra Small

#1481 Add ItemMoveAnimation pull to AnimationLayer
  nekoyume/Assets/_Scenes/Game.unity
Labels: Small

#1488 UI/apply chain data to arena join
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSO.asset
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfo.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/Agent.cs
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
  nekoyume/Assets/_Scripts/Extension/ArenaSheetExtensions.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Helper/ArenaHelperOld.cs
  nekoyume/Assets/_Scripts/Helper/ArenaHelperOld.cs.meta
  nekoyume/Assets/_Scripts/State/RxProps.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSO.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSeasonCell.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSeasonCellChampionship.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSeasonInfo.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
  nekoyume/nekoyume.sln.DotSettings
Labels: Extra Large

#1493 Drop action version about Crystal
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Extension/LocalizationExtension.cs
Labels: Extra Small

#1487 Disable raycast target in avatarinfo-reward text
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
Labels: Extra Large

#1490 Improve the `Analyzer`
  nekoyume/Assets/_Scripts/Analyzer.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Small

#1491 Improve the `Analyzer` to `2022q2` branch
  nekoyume/Assets/_Scripts/Analyzer.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Small

#1495 UI/apply chain data to arena join
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinBottomButtons.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSO.asset
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfoSessionProgressFill.mat
  nekoyume/Assets/Resources/AddressableAssetsContainer.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/_Scripts/ActionExtensions/BattleArenaExtensions.cs
  nekoyume/Assets/_Scripts/ActionExtensions/BattleArenaExtensions.cs.meta
  nekoyume/Assets/_Scripts/ActionExtensions/JoinArenaExtensions.cs
  nekoyume/Assets/_Scripts/ActionExtensions/JoinArenaExtensions.cs.meta
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/Agent.cs
  nekoyume/Assets/_Scripts/BlockChain/ErrorCode.cs
  nekoyume/Assets/_Scripts/Extension/ArenaInformationExtensions.cs
  nekoyume/Assets/_Scripts/Extension/ArenaInformationExtensions.cs.meta
  nekoyume/Assets/_Scripts/Extension/ArenaSheetExtensions.cs
  nekoyume/Assets/_Scripts/State/RxProps.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Emblems/ChampionshipArenaEmblem.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Emblems/OffseasonArenaEmblem.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Emblems/SeasonArenaEmblem.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinEarlyRegisterButton.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinEarlyRegisterButton.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSeasonCell.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSeasonCellChampionship.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSeasonInfo.cs
  nekoyume/Assets/_Scripts/UI/Module/ArenaTickets.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/ArenaMenu.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
Labels: Extra Large
