Repository planetarium/NineChronicles, pull requests merged in 2022-11, with the labels that each got.

#2083 Set default toggle to premium recipe in Super craft popup
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs
Labels: Extra Small

#2080 [bugfix] ViewDetail Button Area fix
  nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
Labels: Medium

#2085 Fix compile error
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSO.cs
Labels: Extra Small

#2081 get sentry sample rate from command options
  nekoyume/Assets/Resources/Sentry/SentryOptions.asset
  nekoyume/Assets/Resources/Sentry/SentryOptionsConfiguration.asset
  nekoyume/Assets/Resources/Sentry/SentryOptionsConfiguration.asset.meta
  nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs
  nekoyume/Assets/_Scripts/SentryOptionsConfiguration.cs
  nekoyume/Assets/_Scripts/SentryOptionsConfiguration.cs.meta
Labels: Small

#2091 Change dotnet version of ci
  .github/workflows/build.yml
Labels: Extra Small

#2093 Added rune ticker string key
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#2094 Fix arena ticket purchasepopup
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ArenaTicketPurchasePopup.cs
Labels: Extra Small

#2095 Add SetWorldInformation in ShortcutActionForStage()
  nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
Labels: Extra Small

#2097 Fix ArenaTicketPurchasePopup
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ArenaTicketPurchasePopup.cs
Labels: Extra Small

#2109 Feature/larger runners
  .github/workflows/build.yml
Labels: ci, Extra Small

#2051 Bugfix and Cleanup code
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Effect_InventorySlot_Lockcover.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Effect_InventorySlot_Lockcover.prefab.meta
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/EquipmentSlot.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/icon_notice_06_black.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/icon_notice_06_black.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/icon_notice_07_black.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/icon_notice_07_black.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Inventory/UI_icon_item_bg_14.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Inventory/UI_icon_item_bg_15.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Inventory/UI_icon_item_bg_15.png.meta
  nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs
Labels: Extra Large

#2113 [bugfix] Alllow Rotation option / Read/write option Check
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldBossResult.spriteatlas
Labels: Extra Small

#2112 [Design] MissionMedal Change
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Emblems/CheckArenaEmblem.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinBottomButtons.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemOptionView/CombinationResultSkillOptionView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemOptionView/EnhancementResultSkillOptionView.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/Resources/UI/Textures/00_Arena/Arena_bg_15.png
  nekoyume/Assets/Resources/UI/Textures/00_Arena/Icon_OfficialChampionshipMedal.png
  nekoyume/Assets/Resources/UI/Textures/00_Arena/Icon_OfficialChampionshipMedal.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Arena/Icon_OfficialSeasonMedal.png
  nekoyume/Assets/Resources/UI/Textures/00_Arena/Icon_OfficialSeasonMedal.png.meta
Labels: Medium

#2114 Upgrade some unity packages
  nekoyume/Assets/NuGet.config.meta
  nekoyume/Packages/manifest.json
  nekoyume/Packages/packages-lock.json
Labels: Extra Small

#2115 [Design] Arena GrandFinale Prefab add
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardBillboard.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
  nekoyume/Assets/Resources/UI/Animations/UI_ArenaJoin@Show.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBoard.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/Resources/UI/Textures/00_Arena/Arena_bg_25.png
  nekoyume/Assets/Resources/UI/Textures/00_Arena/Arena_bg_25.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Arena/Arena_bg_27.png
  nekoyume/Assets/Resources/UI/Textures/00_Arena/Arena_bg_27.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Arena/Arena_bg_28.png
  nekoyume/Assets/Resources/UI/Textures/00_Arena/Arena_bg_28.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_PVP/Bg_Arena_Championship.png
  nekoyume/Assets/Resources/UI/Textures/00_PVP/Bg_Arena_Grade.png
  nekoyume/Assets/Resources/UI/Textures/00_PVP/Bg_Arena_Grade.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_PVP/Bg_Arena_Season.png
  nekoyume/Assets/Resources/UI/Textures/00_PVP/icon_Arena_lose.png
  nekoyume/Assets/Resources/UI/Textures/00_PVP/icon_Arena_lose.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_PVP/icon_Arena_win.png
  nekoyume/Assets/Resources/UI/Textures/00_PVP/icon_Arena_win.png.meta
Labels: Extra Large

#2098 Add ErrorCode CoolDownBlockException
  nekoyume/Assets/_Scripts/BlockChain/ErrorCode.cs
Labels: Extra Small

#2120 Arens Reward Name
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
Labels: Extra Small

#2100 [Design] Rune CurrentBenefits add
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_BenefitsListView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_StakingBenefits.prefab
  nekoyume/Assets/Resources/SpriteAssets/UI_icon_Element.asset
  nekoyume/Assets/Resources/SpriteAssets/UI_icon_Goods.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
  nekoyume/Assets/TextMesh Pro/Resources/Style Sheets/Default Style Sheet.asset
  nekoyume/Assets/TextMesh Pro/Sprites/icon_Element.png
  nekoyume/Assets/TextMesh Pro/Sprites/icon_Element.png.meta
Labels: Extra Large

#2124 Add null checking to GrandFinaleScheduleSheet
  nekoyume/Assets/_Scripts/UI/Module/GrandFinaleJoin.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/ArenaMenu.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
Labels: Extra Small

#2126 Add rune reward to StakingPopup
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_BenefitsListView.prefab
  nekoyume/Assets/Resources/UI/Icons/Item/20001.png
  nekoyume/Assets/Resources/UI/Icons/Item/20001.png.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
  nekoyume/Assets/_Scripts/UI/Module/Item/StakingBenefitsListView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/StakingInterestBenefitsView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Medium

#2129 Update rune ticker
  nekoyume/Assets/Resources/ScriptableObject/UI_WorldBossData.asset
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#2130 Add check offseason for mission button
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinMissionButton.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
Labels: Extra Small

#2134 Add check not level requirement item in recipe view
  nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeView.cs
Labels: Extra Small

#2133 Change critical animation of 40100010(Full costume)
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100010/40100010.json
  nekoyume/Assets/Resources/Character/FullCostume/40100010.prefab
Labels: Extra Small

#2135 Add check row in staking popup
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Extra Small

#2137 Filter not arena avatar state in GrandFinaleStates
  nekoyume/Assets/_Scripts/State/GrandFinaleStates.cs
Labels: Extra Small

#2138 Fix required item view for event material craft
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/_Scripts/Extensions/ArenaSheetExtensions.cs
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
Labels: Extra Small

#2140 Fix bug about not set recipe id at event metarial
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
Labels: Medium

#2141 Fix inputfield in ArenaMedalCountcell
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_ArenaMedalCountcell.prefab
Labels: Extra Small

#2146 [bugfix] Craft Material Text fix
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
Labels: No Changes

#2148 [Design] Increase Text color fix
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemOptionView/EnhancementResultMainStatView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemOptionView/EnhancementResultSkillOptionView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemOptionView/EnhancementResultStatOptionView.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationResultPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_EnhancementResultPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_LevelUpCelebratePopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SweepPopup.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_main_icon_Item.png
Labels: Extra Large
