Repository planetarium/NineChronicles, pull requests merged in 2022-01, with the labels that each got.

#1105 Separately group locked and unlocked objects
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/_Scripts/UI/Module/MainMenu.cs
Labels: bug, improve

#1106 Set block raycast option to false in notification cell
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/NotificationCell.prefab
Labels: improve

#1109 Fix an issue about backspace input during searching in Shop
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
Labels: bug

#1110 Fix an issue about color of quest button changing
  nekoyume/Assets/_Scripts/UI/Widget/QuestPreparation.cs
Labels: improve

#1103 Fix to button to be disabled when item was expires
  nekoyume/Assets/_Scripts/UI/BlockTimer.cs
  nekoyume/Assets/_Scripts/UI/Model/ShopBuyItems.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemInformationTooltip.cs
Labels: bug

#1094 optimize shop using bulk
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
  nekoyume/Assets/_Scripts/UI/Model/Item.cs
  nekoyume/Assets/_Scripts/UI/Model/ShopItem.cs
  nekoyume/Assets/_Scripts/UI/Model/ShopItems.cs
  nekoyume/Assets/_Scripts/UI/Model/ShopSellItems.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/ShopItemView.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
Labels: improve

#1115 Change npc animator
  nekoyume/Assets/Resources/Character/NPC/300000.prefab
  nekoyume/Assets/Resources/Character/NPC/300001.prefab
  nekoyume/Assets/Resources/Character/NPC/300002.prefab
  nekoyume/Assets/Resources/Character/NPC/300003.prefab
  nekoyume/Assets/Resources/Character/NPC/300004.prefab
  nekoyume/Assets/Resources/Character/NPC/300005.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Popup/PrologueDialogPopup.cs
Labels: bug

#1117 Solved the warning log and add UIOnClickSound component
  nekoyume/Assets/AddressableAssets/UI/Module/Button/BackButton.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type1.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type2.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type3.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type4.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type5.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Button/TextButton.prefab
  nekoyume/Assets/Resources/UI/Animations/ConditionalButton_Type3.controller
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_HelpTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemCountableAndPricePopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RedeemCode.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopSell.prefab
  nekoyume/Assets/_Scripts/Game/Controller/UIOnClickSound.cs
  nekoyume/Assets/_Scripts/Game/Controller/UIOnClickSound.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalButton.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/VanillaItemView.cs
  nekoyume/Assets/_Scripts/UI/Scroller/NotificationCell.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopSellItems.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
  nekoyume/Assets/_Scripts/UI/Tween/BaseTweener.cs
  nekoyume/Assets/_Scripts/UI/Tween/DOTweenBase.cs
  nekoyume/Assets/_Scripts/UI/Widget/Base/XTweenPopupWidget.cs
  nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
Labels: bug, improve

#1123 Season1 Arena close
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab
Labels: bug

#1119 Fix to be modified only when it matches the current avatar state
  nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs
Labels: bug

#1132 Fix bug about submit button disabling
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemInformationTooltip.cs
Labels: bug

#1135 Fix buff and skill localization
  nekoyume/Assets/StreamingAssets/Localization/buff_description.csv
  nekoyume/Assets/StreamingAssets/Localization/buff_name.csv
  nekoyume/Assets/StreamingAssets/Localization/skill_name.csv
Labels: bug

#1122 [Design] Bugfix / Design Change
  nekoyume/Assets/AddressableAssets/UI/Module/Button/BackButton.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_Notification.prefab
  nekoyume/Assets/Resources/Tutorial/Prefab/Item_DialogBox.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Battle.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BoosterPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ChatPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_IconAndButtonSystem.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginDetail.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_StageInformation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_TitleOneButtonSystem.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_TwoButtonSystem.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_Btn_bg_03.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_Btn_bg_04.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_icon_new.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_icon_new.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_icon_open.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_main_icon_quest_02.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/button_Orange_03.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/button_brown_01.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/button_brown_01.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/button_yellow_02.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Tooltip/Common_Tooltipbg.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Tooltip/Common_Tooltipbg.png.meta
  nekoyume/Assets/UIResources/Content/Shop/Prefab/TabButton_Sub.prefab
  nekoyume/Assets/_Scripts/UI/Tween/MaskedRectTransformXRoller.cs
Labels: bug, Extra Large

#1128 Put spine on canvas
  nekoyume/Assets/Editor/SpineSettings.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_CelebratesPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationLoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PrologueDialogPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopSell.prefab
  nekoyume/Assets/_Scenes/Game.unity
  nekoyume/Assets/_Scripts/UI/Module/Button/UIOnClickSound.cs
  nekoyume/Assets/_Scripts/UI/Module/Button/UIOnClickSound.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/Spine.meta
  nekoyume/Assets/_Scripts/UI/Module/Spine/UISpineAnimation.cs
  nekoyume/Assets/_Scripts/UI/Module/Spine/UISpineAnimation.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/CombinationMain.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CelebratesPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/PrologueDialogPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/CombinationLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
Labels: improve

#1138 Add changing tooltip in loading screen
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoadingScreen.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Screen/LoadingScreen.cs
Labels: good first issue, Small

#1131 Add loading screen in freezing in skipping intro and selecting character
  nekoyume/Assets/Resources/UI/Prefabs/UI_DimmedLoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_DimmedLoadingScreen.prefab.meta
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/BlockSyncLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/DataLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/DimmedLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/DimmedLoadingScreen.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
Labels: Extra Small

#1130 Add Notification to block equip in game
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemInformationTooltip.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/Model/ItemInformationTooltip.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemInformationTooltip.cs
Labels: good first issue, Extra Large

#1141 Improve `MaskedRectTransformXRoller`
  nekoyume/Assets/UIResources/Content/Shop/Prefab/TabButton_Sub.prefab
  nekoyume/Assets/_Scripts/UI/Tween/MaskedRectTransformXRoller.cs
Labels: Extra Small

#1143 Fix not closed loading screen in synopsis of new user
  nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
Labels: Extra Small

#1142 Fix warning log
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationLoadingScreen.prefab
  nekoyume/Assets/_Scripts/UI/Module/Button/WorldButton.cs
  nekoyume/Assets/_Scripts/UI/Module/GuidedQuest.cs
  nekoyume/Assets/_Scripts/UI/Widget/Animation/ItemMoveAnimation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Hud/HpBar.cs
  nekoyume/Assets/_Scripts/UI/Widget/Hud/SpeechBubble.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CodeRewardPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/FriendInfoPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/RankingBattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
  nekoyume/Assets/_Scripts/UI/Widget/UpgradeEquipment.cs
Labels: Medium

#1145 Add new mimisbrunnr bg
  nekoyume/Assets/Resources/UI/Textures/WorldMap/battle_UI_bg_mimisbrunnr_01.png
  nekoyume/Assets/Resources/UI/Textures/WorldMap/battle_UI_bg_mimisbrunnr_01.png.meta
  nekoyume/Assets/Resources/UI/Textures/WorldMap/battle_UI_bg_mimisbrunnr_02.png
  nekoyume/Assets/Resources/UI/Textures/WorldMap/battle_UI_bg_mimisbrunnr_02.png.meta
  nekoyume/Assets/Resources/UI/Textures/WorldMap/battle_UI_bg_mimisbrunnr_03.png
  nekoyume/Assets/Resources/UI/Textures/WorldMap/battle_UI_bg_mimisbrunnr_03.png.meta
  nekoyume/Assets/Resources/UI/Textures/WorldMap/battle_UI_bg_mimisbrunnr_04.png
  nekoyume/Assets/Resources/UI/Textures/WorldMap/battle_UI_bg_mimisbrunnr_04.png.meta
  nekoyume/Assets/_Scripts/UI/Module/WorldMap/WorldMapWorld.cs
Labels: Large

#1149 Fix how to find player
  nekoyume/Assets/_Scripts/Game/Entrance/NestEntering.cs
  nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/Game/Trigger/MonsterSpawner.cs
  nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankCell.cs
  nekoyume/Assets/_Scripts/UI/Scroller/ExpRankCell.cs
  nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/LevelUpCelebratePopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/AvatarTooltip.cs
Labels: bug, Small

#1147 Fix how to get buy error list
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Labels: bug, Extra Small

#1154 Remove animator in shop menu notification mark
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
Labels: Small

#1148 Add UI camera
  nekoyume/Assets/_Scenes/Game.unity
Labels: improve, Small

#1146 Introduce `ResourceTestScene`
  nekoyume/Assets/Planetarium/Nekoyume/Editor/SpineEditor.cs
  nekoyume/Assets/_Scenes/ResourceTestScene.unity
  nekoyume/Assets/_Scenes/ResourceTestScene.unity.meta
  nekoyume/Assets/_Scripts/Game/Character/CharacterAnimator.cs
  nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs
  nekoyume/Assets/_Scripts/Game/Character/Enemy.cs
  nekoyume/Assets/_Scripts/Game/Character/NPC.cs
  nekoyume/Assets/_Scripts/Game/Character/NPCAnimator.cs
  nekoyume/Assets/_Scripts/Game/Character/Player.cs
  nekoyume/Assets/_Scripts/Game/TestScene.meta
  nekoyume/Assets/_Scripts/Game/TestScene/SpineCharacterViewer.cs
  nekoyume/Assets/_Scripts/Game/TestScene/SpineCharacterViewer.cs.meta
Labels: Large

#1159 Bump Lib9c & upgrade Libplanet to 0.27.0
  nekoyume/Assets/Packages/Libplanet.Net.dll
  nekoyume/Assets/Packages/Libplanet.Net.dll.meta
  nekoyume/Assets/Packages/Libplanet.Net.xml
  nekoyume/Assets/Packages/Libplanet.Net.xml.meta
  nekoyume/Assets/Packages/Libplanet.RocksDBStore.dll
  nekoyume/Assets/Packages/Libplanet.Stun.dll
  nekoyume/Assets/Packages/Libplanet.dll
  nekoyume/Assets/Packages/Libplanet.xml
Labels: Extra Small

#1161 Add event banner
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
  nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs
Labels: Large

#1155 Edit Shop Action Notification to Mark Item Count
  nekoyume/Assets/StreamingAssets/Localization/notification.csv
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopBuyBoard.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
Labels: Medium

#1151 ci(gh-actions): fail step when failed to upload artifact
  .github/workflows/build.yml
Labels: bug, ci, Extra Small, suggestion

#1168 add event banner
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_04.png
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_04.png.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Item_Banner_04.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Item_Banner_04.prefab.meta
  nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs
Labels: Extra Large

#1166 Reduce get `WeeklyArenaState`
  nekoyume/Assets/_Scripts/BlockChain/BlockRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/RankingBattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs
Labels: Extra Large

#1169 Increase HAS boosting max count from 12 to 24
  nekoyume/Assets/_Scripts/UI/Widget/MimisbrunnrPreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BoosterPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/QuestPreparation.cs
Labels: Extra Large

#1162 Update Text UI on Change LanguageType
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattleResultPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BuyItemInformationPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_GrayLoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Login.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginDetail.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MailPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MimisbrunnrPreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBattleResultPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RedeemCode.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopSell.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_StageInformation.prefab
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/L10n/L10nTextMeshProUGUI.cs
  nekoyume/Assets/_Scripts/L10n/LanguageTypeInspectorDisplayDrawer.cs
  nekoyume/Assets/_Scripts/L10n/LanguageTypeInspectorDisplayDrawer.cs.meta
  nekoyume/Assets/_Scripts/L10n/LanguageTypeReactiveProperty.cs
  nekoyume/Assets/_Scripts/L10n/LanguageTypeReactiveProperty.cs.meta
  nekoyume/Assets/_Scripts/UI/LoginPlayerSlot.cs
  nekoyume/Assets/_Scripts/UI/Module/BattleReward.cs
  nekoyume/Assets/_Scripts/UI/Scroller/GuidedQuestCell.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopSellItems.cs
  nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
  nekoyume/Assets/_Scripts/UI/Widget/MimisbrunnrPreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BuyItemInformationPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ItemCountPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ItemCountableAndPricePopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/RankingBattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SettingPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/QuestPreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs
  nekoyume/Assets/_Scripts/UI/Widget/RedeemCode.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/DataLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/GrayLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/LoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
  nekoyume/Assets/_Scripts/UI/Widget/StageInformation.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
Labels: Large
