Repository planetarium/NineChronicles, pull requests merged in 2022-04, with the labels that each got.

#1294 Fix not showing lock object in tooltip
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView_tooltip.prefab
  nekoyume/Assets/Resources/Font/Materials/ChineseSimplified SDF Material - Descinfor.mat
  nekoyume/Assets/Resources/Font/Materials/ChineseSimplified SDF Material - Descinfor.mat.meta
  nekoyume/Assets/Resources/Font/Materials/English SDF Material - Descinfor.mat
  nekoyume/Assets/Resources/Font/Materials/English SDF Material - Descinfor.mat.meta
  nekoyume/Assets/Resources/Font/Materials/Japanese SDF Material - Descinfor.mat
  nekoyume/Assets/Resources/Font/Materials/Japanese SDF Material - Descinfor.mat.meta
  nekoyume/Assets/Resources/Font/Materials/Korean SDF Material - Descinfor.mat
  nekoyume/Assets/Resources/Font/Materials/Korean SDF Material - Descinfor.mat.meta
  nekoyume/Assets/Resources/Font/Materials/Polish SDF Material - Descinfor.mat
  nekoyume/Assets/Resources/Font/Materials/Polish SDF Material - Descinfor.mat.meta
  nekoyume/Assets/Resources/Font/Materials/PortugueseBrazil SDF Material - Descinfor.mat
  nekoyume/Assets/Resources/Font/Materials/PortugueseBrazil SDF Material - Descinfor.mat.meta
  nekoyume/Assets/Resources/Font/Materials/Russia SDF Material - Descinfor.mat
  nekoyume/Assets/Resources/Font/Materials/Russia SDF Material - Descinfor.mat.meta
  nekoyume/Assets/Resources/Font/Materials/Thai SDF Material - Descinfor.mat
  nekoyume/Assets/Resources/Font/Materials/Thai SDF Material - Descinfor.mat.meta
  nekoyume/Assets/Resources/L10nSettings/FontAssetData ChineseSimplified SDF.asset
  nekoyume/Assets/Resources/L10nSettings/FontAssetData English SDF.asset
  nekoyume/Assets/Resources/L10nSettings/FontAssetData Japanese SDF.asset
  nekoyume/Assets/Resources/L10nSettings/FontAssetData Korean SDF.asset
  nekoyume/Assets/Resources/L10nSettings/FontAssetData Polish SDF.asset
  nekoyume/Assets/Resources/L10nSettings/FontAssetData PortugueseBrazil SDF.asset
  nekoyume/Assets/Resources/L10nSettings/FontAssetData Thai SDF.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_CostumeTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MaterialTooltip.prefab
  nekoyume/Assets/Resources/UI/Textures/Tooltip.meta
  nekoyume/Assets/Resources/UI/Textures/Tooltip/Navigation_bg_01.png
  nekoyume/Assets/Resources/UI/Textures/Tooltip/Navigation_bg_01.png.meta
  nekoyume/Assets/StreamingAssets/Localization/help_popup.csv
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Tooltip/Common_Tooltipbg4.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Tooltip/Common_Tooltipbg4.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Tooltip/Common_Tooltipbg5.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Tooltip/Common_Tooltipbg5.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Tooltip/Common_Tooltipbg6.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Tooltip/Common_Tooltipbg6.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Tooltip/Common_Tooltipbg7.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Tooltip/Common_Tooltipbg7.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Tooltip/Common_Tooltipbg8.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Tooltip/Common_Tooltipbg8.png.meta
  nekoyume/Assets/_Scripts/L10n/FontMaterialType.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/TooltipItemView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltip.cs
Labels: Extra Large

#1308 Fix the problem of ignoring the enemy.
  nekoyume/Assets/_Scripts/Game/Character/Player.cs
Labels: bug, Extra Small

#1301 Share Code Convention
  hooks/pre-commit
Labels: Extra Small

#1312 Fix sequence of tooltip moving logic
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltip.cs
Labels: Extra Small

#1313 merge rc-v100160 into development
  nekoyume/Assets/_Scripts/Game/Character/Player.cs
Labels: Extra Small

#1315 Set default preset for arena
  nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs
Labels: Extra Small

#1317 Fix material tooltip for previewnet
  nekoyume/Assets/Resources/UI/Prefabs/UI_MaterialTooltip.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs
Labels: Small

#1284 Fix bug in reconnecting rpc connection.
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/DimmedLoadingScreen.cs
Labels: Extra Small

#1320 Fix not to update the purchase page per block
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopView.cs
Labels: bug, Extra Small

#1319 Fix XXX NCG NCG text
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
Labels: Extra Small

#1318 Revert "Set default preset for arena"
  nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs
Labels: Extra Small

#1307 [Design] Count Font Change
  nekoyume/Assets/Resources/Font/SDF/Count SDF.asset
Labels: No Changes

#1321 [Design] RankingBoard info Text Delete
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab
Labels: Small

#1323 fix broken prefab: `UI_RankingBoard > UI_RankingInfo`
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab
Labels: bug, Extra Small

#1325 Add handling about mimisbrunnr recipe in SubRecipeView
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
Labels: Extra Small

#1326 handle NotEnoughAvatarLevelException as 29 error
  nekoyume/Assets/StreamingAssets/Localization/error.csv
  nekoyume/Assets/_Scripts/BlockChain/ErrorCode.cs
Labels: bug, Extra Small

#1327 Bug fix/duplicate player
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBattleLoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBattleLoadingScreen.prefab.meta
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/Game/Entrance/NestEntering.cs
  nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/ArenaBattleLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/RankingBattleLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/RankingBattleLoadingScreen.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
Labels: bug, Extra Large

#1329 Trigger Submodule Updater on every push to rc-v* branches
  .github/workflows/release.yaml
Labels: ci, Extra Small

#1330 fix acquisition button ui bug
  nekoyume/Assets/_Scripts/UI/Module/Button/AcquisitionPlaceButton.cs
Labels: bug, Extra Small

#1331 Reset cancellationTokenSource on purchase page display
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
Labels: bug, Extra Small

#1333 fix mimisbrunnr battle preparation stage text bug
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs
Labels: bug, Small

#1334 Remove filtering inventory on caching skeleton objects.
  nekoyume/Assets/_Scripts/UI/Module/Item/TooltipItemView.cs
Labels: Extra Small

#1332 Block battle action in client
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
  nekoyume/Assets/_Scripts/Helper/Util.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentSlot.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentSlots.cs
  nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankCell.cs
  nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankScroll.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs
Labels: Extra Large

#1335 Bug fix/acquisition button
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs
Labels: bug, Extra Small

#1336 Fix data loading screen
  nekoyume/Assets/Resources/UI/Prefabs/UI_DataLoadingScreen.prefab
Labels: bug, Extra Small

#1343 show ui first when entering the shop sell
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
Labels: bug, Extra Small

#1339 Fix data loading screen
  nekoyume/Assets/Resources/UI/Prefabs/UI_DataLoadingScreen.prefab
Labels: Extra Small

#1349 Fix RankingBoard infinity loading
  nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs
Labels: Extra Small

#1347 Edit UI button action
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ItemCountableAndPricePopup.cs
Labels: Extra Small

#1351 Fix ranking board
  nekoyume/Assets/_Scripts/UI/RankingInfo.cs
  nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs
Labels: bug, Extra Small

#1350 Add null check when costume tail is changed.
  nekoyume/Assets/_Scripts/Game/Character/PlayerSpineController.cs
Labels: Extra Small

#1324 Block rendering about timed out battle action
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Labels: Extra Small

#1243 Introduce `ReportAnything`
  nekoyume/Assets/Planetarium/Nekoyume/Editor/ReportAnything.cs
  nekoyume/Assets/Planetarium/Nekoyume/Editor/ReportAnything.cs.meta
Labels: Extra Small

#1353 Fix UpdateContent of ArenaRankCell
  nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankCell.cs
Labels: Extra Small

#1354 UI/add common UI 6
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
Labels: Extra Large

#1348 Fix shop page refresh logic
  nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopView.cs
Labels: bug, Extra Small

#1356 add inventory sort condition
  nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
Labels: bug, Extra Small

#1359 add event banner
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_08.png
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_08.png.meta
  nekoyume/Assets/UIResources/Content/Notice/Information_02.png
  nekoyume/Assets/UIResources/Content/Notice/Information_02.png.meta
Labels: Large

#1360 Fix different alert message
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
  nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalCostButton.cs
Labels: Extra Small

#1364 Add crystal balance UI on header menu.
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/Crystal.prefab
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/State/ReactiveAvatarState.cs
  nekoyume/Assets/_Scripts/UI/Module/Crystal.cs
  nekoyume/Assets/_Scripts/UI/Module/Crystal.cs.meta
Labels: Large

#1366 change url linked to popup
  nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
Labels: bug, Extra Small

#1355 Prevent avatar overlapping on displaying `FriendInfoPopup`.
  nekoyume/Assets/_Scripts/Game/Character/Player.cs
  nekoyume/Assets/_Scripts/UI/Scroller/ArenaRankCell.cs
Labels: Extra Small

#1367 Introduce `PaymentManager`
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/State/ReactiveAvatarState.cs
  nekoyume/Assets/_Scripts/UI/Payment.meta
  nekoyume/Assets/_Scripts/UI/Payment/PaymentManager.cs
  nekoyume/Assets/_Scripts/UI/Payment/PaymentManager.cs.meta
Labels: Small

#1369 merge main into development
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_08.png
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_08.png.meta
  nekoyume/Assets/UIResources/Content/Notice/Information_02.png
  nekoyume/Assets/UIResources/Content/Notice/Information_02.png.meta
Labels: Large

#1361 organize materials
  nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
Labels: bug, Extra Small

#1368 [bufgix] Combinationslot button text Area fix
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotPopup.prefab
Labels: Medium

#1372 change event banner mask
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
Labels: bug, Extra Small

#1371 [bugfix] Text Area fix
  nekoyume/Assets/Resources/UI/Prefabs/UI_ConsumableTooltip.prefab
Labels: Large

#1370 change shop sort filter order
  nekoyume/Assets/_Scripts/EnumType/ShopSortFilter.cs
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
  nekoyume/Assets/_Scripts/UI/Shop/SellView.cs
Labels: improve, Extra Small

#1376 add arena season 3 event
  nekoyume/Assets/Resources/ScriptableObject/EventData.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_NoticePopup.prefab
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_09.png
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_09.png.meta
  nekoyume/Assets/UIResources/Content/Notice/Information_03.png
  nekoyume/Assets/UIResources/Content/Notice/Information_03.png.meta
  nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs
Labels: Large

#1374 Implement crystal recipe unlock
  nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type6.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type6.prefab.meta
  nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type6_Test.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type6_Test.prefab.meta
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_RecipeSlot.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView_2.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView_2.prefab.meta
  nekoyume/Assets/Resources/UI/Animations/ItemRecipeController.controller
  nekoyume/Assets/Resources/UI/Animations/ItemRecipeController@Clicked.anim
  nekoyume/Assets/Resources/UI/Animations/ItemRecipeController@Loading.anim
  nekoyume/Assets/Resources/UI/Animations/ItemRecipeController@Loading.anim.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PaymentPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PaymentPopup.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_Use_CrystalPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Use_CrystalPopup.prefab.meta
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/button_sub_bg.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/button_sub_bg.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/icon_Craft_recipe.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/icon_Craft_recipe.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Popup/UI_Popup_bg_11.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Popup/UI_Popup_bg_11.png.meta
  nekoyume/Assets/_Scripts/ActionExtensions/UnlockEquipmentRecipeExtensions.cs
  nekoyume/Assets/_Scripts/ActionExtensions/UnlockEquipmentRecipeExtensions.cs.meta
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/Agent.cs
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
  nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs
  nekoyume/Assets/_Scripts/State/Modifiers/AvatarCrystalModifier.cs
  nekoyume/Assets/_Scripts/State/Modifiers/AvatarCrystalModifier.cs.meta
  nekoyume/Assets/_Scripts/State/ReactiveAvatarState.cs
  nekoyume/Assets/_Scripts/State/ReactiveCrystalState.cs
  nekoyume/Assets/_Scripts/State/ReactiveCrystalState.cs.meta
  nekoyume/Assets/_Scripts/UI/Combination/RecipeUnlockInfo.cs
  nekoyume/Assets/_Scripts/UI/Combination/RecipeUnlockInfo.cs.meta
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Model/RecipeModel.cs
  nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalCostButton.cs
  nekoyume/Assets/_Scripts/UI/Module/Crystal.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/RequiredItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeCell.cs
  nekoyume/Assets/_Scripts/UI/Module/Recipe/RequiredItemRecipeView.cs
  nekoyume/Assets/_Scripts/UI/Payment/PaymentPopup.cs
  nekoyume/Assets/_Scripts/UI/Payment/PaymentPopup.cs.meta
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
Labels: Extra Large

#1379 Chunk address list
  nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs
Labels: Extra Small

#1388 Make crystal modifier based on avatar to agent.
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs
  nekoyume/Assets/_Scripts/State/Modifiers/AgentCrystalModifier.cs
  nekoyume/Assets/_Scripts/State/Modifiers/AgentCrystalModifier.cs.meta
Labels: Extra Small

#1389 Show combination loading screen on grinding.
  nekoyume/Assets/Resources/UI/Prefabs/UI_Grind.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SpeechBubbleWithItem.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
  nekoyume/Assets/_Scripts/UI/Widget/Hud/SpeechBubbleWithItem.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/CombinationLoadingScreen.cs
Labels: Extra Large

#1390 [bugfix] Season Text Change
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab
Labels: Extra Small

#1391 Release rc-v100181 to main
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab
Labels: Extra Small

#1392 Release rc-v100181 to development
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankingBoard.prefab
Labels: Extra Small

#1396 [Design] Goods Emoji add
  nekoyume/Assets/Resources/SpriteAssets/UI_icon_Goods.asset
  nekoyume/Assets/Resources/SpriteAssets/UI_icon_Goods.asset.meta
  nekoyume/Assets/TextMesh Pro/Resources/Sprite Assets/EmojiOne.asset
  nekoyume/Assets/TextMesh Pro/Resources/Style Sheets/Default Style Sheet.asset
  nekoyume/Assets/TextMesh Pro/Sprites/icon_Goods.png
  nekoyume/Assets/TextMesh Pro/Sprites/icon_Goods.png.meta
Labels: Extra Large

#1399 update sweep result anim
  nekoyume/Assets/Resources/UI/Animations/Sweep_Result.anim
Labels: Small

#1402 Bug fix/action point guage
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/State/ReactiveAvatarState.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs
Labels: bug, Small

#1403 fix to refresh ap stone count every time
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldClear_03.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldClear_04.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldClear_05.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs
Labels: bug, Extra Small

#1398 Fix buy tooltip button label
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltipBuy.cs
Labels: Extra Small

#1404 Fixed so that usable ap stones are displayed properly in sweep popup
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs
Labels: bug, Extra Small
