Repository planetarium/NineChronicles, pull requests merged in 2022-02, with the labels that each got.

#1174 Fix compile errors
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/L10n/Editor/LanguageTypeInspectorDisplayDrawer.cs
  nekoyume/Assets/_Scripts/L10n/Editor/LanguageTypeInspectorDisplayDrawer.cs.meta
  nekoyume/Assets/_Scripts/L10n/Editor/Nekoyume.L10n.Editor.asmdef
  nekoyume/Assets/_Scripts/L10n/LanguageTypeInspectorDisplayDrawer.cs.meta
Labels: bug, Extra Small

#1158 Refactor get states
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/AvatarTooltip.cs
Labels: Extra Small

#1157 Fix macOS build
  .github/workflows/build-misc.yml
  nekoyume/Assets/Editor/Builder.cs
  nekoyume/Assets/Editor/SpineSettings.asset
  nekoyume/Assets/Packages/runtimes/linux-x64/native/librocksdb.so.meta
  nekoyume/Assets/Packages/runtimes/linux-x64/native/libsecp256k1.so.meta
  nekoyume/Assets/Packages/runtimes/osx-arm64/native/libgflags.2.2.dylib.meta
  nekoyume/Assets/Packages/runtimes/osx-arm64/native/liblz4.1.dylib.meta
  nekoyume/Assets/Packages/runtimes/osx-arm64/native/librocksdb.dylib.meta
  nekoyume/Assets/Packages/runtimes/osx-arm64/native/libsnappy.1.dylib.meta
  nekoyume/Assets/Packages/runtimes/osx-arm64/native/libzstd.1.dylib.meta
  nekoyume/Assets/Packages/runtimes/osx-x64/native/libgflags.2.2.dylib.meta
  nekoyume/Assets/Packages/runtimes/osx-x64/native/liblz4.1.dylib.meta
  nekoyume/Assets/Packages/runtimes/osx-x64/native/librocksdb.dylib.meta
  nekoyume/Assets/Packages/runtimes/osx-x64/native/libsecp256k1.dylib.meta
  nekoyume/Assets/Packages/runtimes/osx-x64/native/libsnappy.1.dylib.meta
  nekoyume/Assets/Packages/runtimes/osx-x64/native/libzstd.1.dylib.meta
  nekoyume/Assets/Packages/runtimes/win-x64/native/rocksdb.dll.meta
  nekoyume/Assets/Packages/runtimes/win-x64/native/secp256k1.dll.meta
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Shop.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Worldmap.spriteatlas
Labels: bug, Extra Large

#1164 Add changing tooltip in DataLoadingScreen
  nekoyume/Assets/Resources/UI/Prefabs/UI_DataLoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PreLoadingScreen.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Screen/DataLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/LoadingScreen.cs
Labels: Extra Large

#1171 [Bot] Merge rc-v100101 to main
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_04.png
  nekoyume/Assets/UIResources/Content/Banner/Banner_Event_04.png.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/Item_Banner_04.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/Item_Banner_04.prefab.meta
  nekoyume/Assets/_Scripts/BlockChain/BlockRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs
  nekoyume/Assets/_Scripts/UI/Widget/MimisbrunnrPreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BoosterPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/RankingBattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/QuestPreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/RankingBoard.cs
Labels: Extra Large

#1175 Fix UI Sorting Layer settings
  nekoyume/Assets/_Scenes/Game.unity
  nekoyume/ProjectSettings/TagManager.asset
Labels: bug, Extra Small

#1178 Add properties to `RecipeViewData`.
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_RecipeSlot.prefab
  nekoyume/Assets/Resources/ScriptableObject/UI_RecipeViewData.asset
  nekoyume/Assets/Resources/UI/Animations/ItemRecipeController.controller
  nekoyume/Assets/Resources/UI/Animations/ItemRecipeController@Clicked.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/UIResources/Font/NATZSB__ SDF Material - RecipeGrade_00.mat
  nekoyume/Assets/UIResources/Font/NATZSB__ SDF Material - RecipeGrade_00.mat.meta
  nekoyume/Assets/UIResources/Font/NATZSB__ SDF Material - RecipeGrade_01.mat
  nekoyume/Assets/UIResources/Font/NATZSB__ SDF Material - RecipeGrade_01.mat.meta
  nekoyume/Assets/UIResources/Font/NATZSB__ SDF Material - RecipeGrade_02.mat
  nekoyume/Assets/UIResources/Font/NATZSB__ SDF Material - RecipeGrade_02.mat.meta
  nekoyume/Assets/UIResources/Font/NATZSB__ SDF Material - RecipeGrade_03.mat
  nekoyume/Assets/UIResources/Font/NATZSB__ SDF Material - RecipeGrade_03.mat.meta
  nekoyume/Assets/_Scripts/Game/ScriptableObject/RecipeViewData.cs
  nekoyume/Assets/_Scripts/L10n/FontMaterialType.cs
  nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeCell.cs
  nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeView.cs
Labels: Extra Large

#1179 Apply level limit data on crafting.
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_UpgradeEquipment.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scenes/Game.unity
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
  nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeView.cs
  nekoyume/Assets/_Scripts/UI/Widget/UpgradeEquipment.cs
Labels: Extra Large

#1181 Track `Unity/ActionRender` event with `ActionType` and `Elapsed` value
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Extension/GameActionExtensions.cs
  nekoyume/Assets/_Scripts/Extension/GameActionExtensions.cs.meta
Labels: Extra Small

#1182 Add `ItemRequirementSheet` on `AddressableAssetsContainer`
  nekoyume/Assets/Resources/AddressableAssetsContainer.asset
Labels: Extra Small

#1183 Update ranking board query.
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/Model/Rank.cs
  nekoyume/Assets/_Scripts/UI/Model/RankingModel.cs
  nekoyume/Assets/_Scripts/UI/Module/Character/DetailedCharacterView.cs
  nekoyume/Assets/_Scripts/UI/Module/Character/FramedCharacterView.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RankCell.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RankCellPanel.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/GrayLoadingScreen.cs
Labels: Extra Large

#1184 Show popup on crafting of unusable item.
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
Labels: Extra Small

#1198 Reduce GetState called in BlockRenderer
  nekoyume/Assets/_Scripts/BlockChain/BlockRenderHandler.cs
Labels: Extra Small

#1202 Remove stage requirement label in recipe when requirement stage is 999
  nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeCell.cs
Labels: Extra Small

#1206 [bugfix] RedeemCodeButton Text fix
  nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab
Labels: bug, Small

#1205 Fix minor bugs about UI
  nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs
  nekoyume/Assets/_Scripts/UI/Widget/MimisbrunnrPreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/DimmedLoadingScreen.cs
Labels: Extra Small

#1209 Decompress action evaluation
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
Labels: Extra Small
