Repository planetarium/NineChronicles, pull requests merged in 2022-07, with the labels that each got.

#1674 Fixed the skill name to be displayed correctly
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotPopup.cs
Labels: bug, Extra Small

#1675 Change how to get Spine animation time
  nekoyume/Assets/_Scripts/Game/Character/ArenaCharacter.cs
  nekoyume/Assets/_Scripts/Game/Character/CharacterAnimator.cs
Labels: bug, Extra Small

#1676 Change InputField line type
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
Labels: bug, Extra Small

#1677 Check updated fungible assets when update crystal
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
Labels: bug, Extra Small

#1679 Change URL of claim x2 banner
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
Labels: Extra Small

#1680 Enable ap fill area
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/ActionPoint.prefab
Labels: Extra Small

#1681 Revert "Enable ap fill area"
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/ActionPoint.prefab
Labels: Extra Small

#1683 Enable ap slider
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/ActionPoint.prefab
Labels: Extra Small

#1686 Bugfix: Update `BonusBuffButton`'s icon on every skill selection via ui.
  nekoyume/Assets/_Scripts/UI/Module/Button/BonusBuffButton.cs
Labels: Extra Small

#1685 Bug fix/update inventory on arena battle preparation
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
  nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
Labels: bug, Extra Small

#1695 Enable AP slider (cherry-pick of #1683)
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/ActionPoint.prefab
Labels: Extra Small, hotfix

#1694 Restore removed sprite
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Common_Prrogressbar_thumbBg.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Common_Prrogressbar_thumbBg.png.meta
Labels: Medium

#1692 Optimize handling the render of `BattleArena`
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Game/Arena.cs
  nekoyume/Assets/_Scripts/State/AsyncUpdatableRxProp.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
Labels: Extra Small, hotfix

#1693 Optimize handling the render of `BattleArena`
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Game/Arena.cs
  nekoyume/Assets/_Scripts/State/AsyncUpdatableRxProp.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
Labels: Extra Small

#1696 Add NFT page link on menu
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/BoxCatBtnContainers.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_00.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_00.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_01.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_01.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_02.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_02.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_03.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_03.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_04.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_04.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_05.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_05.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_06.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_06.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_07.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_07.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_08.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_08.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_09.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_09.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_10.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_10.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_11.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_11.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_12.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_12.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_13.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_13.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_14.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_14.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_15.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_15.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_16.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_16.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_17.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_17.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_18.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_18.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_19.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_19.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_20.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_20.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_21.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_21.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_22.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_22.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_23.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_23.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_24.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_24.png.meta
  nekoyume/Assets/_Scripts/EnumType/EventType.cs
  nekoyume/Assets/_Scripts/UI/Module/ExternalWebsiteButton.cs
  nekoyume/Assets/_Scripts/UI/Module/ExternalWebsiteButton.cs.meta
Labels: Extra Large

#1697 Bugfix: Update BonusBuffButton's icon on every skill selection via ui.
  nekoyume/Assets/_Scripts/UI/Module/Button/BonusBuffButton.cs
Labels: Extra Small

#1698 Merge `rc-v100241` into `main`
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/ActionPoint.prefab
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Game/Arena.cs
  nekoyume/Assets/_Scripts/State/AsyncUpdatableRxProp.cs
  nekoyume/Assets/_Scripts/UI/Module/Button/BonusBuffButton.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
Labels: Extra Small

#1701 New workflow to request Unity license activation files
  .github/workflows/activate-unity.yaml
Labels: ci, Extra Small

#1702 Fix missing `inputs` on `workflow_dispatch`
  .github/workflows/activate-unity.yaml
Labels: bug, ci, Extra Small

#1703 Fix arena medal item bug
  nekoyume/Assets/_Scripts/Extension/ArenaSheetExtensions.cs
  nekoyume/Assets/_Scripts/Extension/ItemSheetExtension.cs
Labels: bug, Extra Small

#1688 Add system reward to staking reward UI
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/Module/Item/StakingItemView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Medium

#1706 Update NFT page url.
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
Labels: Large

#1707 Move serveral exposed sprite resource path to `SpriteHelper`.
  nekoyume/Assets/Resources/UI/Icons/ElementalType.meta
  nekoyume/Assets/Resources/UI/Icons/ElementalType/icon_element_normal.png
  nekoyume/Assets/Resources/UI/Icons/ElementalType/icon_element_normal.png.meta
  nekoyume/Assets/Resources/UI/Icons/ElementalType/icon_elemental_fire.png
  nekoyume/Assets/Resources/UI/Icons/ElementalType/icon_elemental_fire.png.meta
  nekoyume/Assets/Resources/UI/Icons/ElementalType/icon_elemental_land.png
  nekoyume/Assets/Resources/UI/Icons/ElementalType/icon_elemental_land.png.meta
  nekoyume/Assets/Resources/UI/Icons/ElementalType/icon_elemental_water.png
  nekoyume/Assets/Resources/UI/Icons/ElementalType/icon_elemental_water.png.meta
  nekoyume/Assets/Resources/UI/Icons/ElementalType/icon_elemental_wind.png
  nekoyume/Assets/Resources/UI/Icons/ElementalType/icon_elemental_wind.png.meta
  nekoyume/Assets/_Scripts/Extension/ElementalTypeUIExtension.cs
  nekoyume/Assets/_Scripts/Game/Background.cs
  nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs
  nekoyume/Assets/_Scripts/UI/Module/WorldMap/WorldMapPage.cs
  nekoyume/Assets/_Scripts/UI/QuestInfo.cs
  nekoyume/Assets/_Scripts/UI/QuestInfo.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Popup/DialogPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
Labels: Small

#1708 Fix `ArenaMenu`
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
  nekoyume/Assets/_Scripts/UI/Module/Lobby/ArenaMenu.cs
  nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
Labels: bug, Extra Small

#1709 l10n common.csv updated.
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#1705 Disable block raycast in ItemTooltip, effect texture
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
Labels: Extra Large

#1710 [Bugfix] Enhancement Animation fix
  nekoyume/Assets/Resources/UI/Animations/UIEnhancementResult@Loop.anim
  nekoyume/Assets/Resources/UI/Animations/UIEnhancementResult@Loop_Fail.anim
  nekoyume/Assets/Resources/UI/Animations/UIEnhancementResult@Success.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_EnhancementResultPopup.prefab
Labels: bug, Extra Large

#1711 Fix broken CI by OpenUPM & DOTween
  nekoyume/Packages/manifest.json
  nekoyume/Packages/packages-lock.json
Labels: Extra Small

#1712 Fix broken CI by OpenUPM & DOTween (same with #1711, To branch`rc-v100250`)
  nekoyume/Packages/manifest.json
  nekoyume/Packages/packages-lock.json
Labels: Extra Small

#1713 Fix arena ticket synchronizing bug
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/PreloadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
Labels: bug, Extra Small

#1714 Fix header ui not updated bug
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs
Labels: Extra Small

#1715 Disable raycast target in ItemTooltip
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
Labels: Extra Small
