Repository planetarium/NineChronicles, pull requests merged in 2023-06, with the labels that each got.

#2697 change android version to 31 and fix bug
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#2696 Edit `BuyView.GetSortedModels` to check mimir level
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
Labels: Extra Small

#2699 improve something about l10n
  nekoyume/Assets/StreamingAssets/Localization/DirectoryForAndroid.txt
Labels: Extra Small

#2702 Revert "improve something about l10n"
  nekoyume/Assets/StreamingAssets/Localization/DirectoryForAndroid.txt
Labels: Extra Small

#2709 block using ap potioin at HAS
  nekoyume/Assets/Resources/UI/Prefabs/UI_SweepPopup.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs
Labels: Extra Small

#2711 Expand `GetStateAsync()` and `GetAvatarStates()` of `IAgent`
  nekoyume/Assets/Planetarium/Nekoyume/Editor/NineChroniclesAPIClientToolWindow.cs
  nekoyume/Assets/Planetarium/Nekoyume/Editor/NineChroniclesAPIClientToolWindow.cs.meta
  nekoyume/Assets/_Scripts/Blockchain/Agent.cs
  nekoyume/Assets/_Scripts/Blockchain/BlockHashCache.cs
  nekoyume/Assets/_Scripts/Blockchain/BlockHashCache.cs.meta
  nekoyume/Assets/_Scripts/Blockchain/IAgent.cs
  nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
  nekoyume/Assets/_Scripts/GraphQL/NineChroniclesAPIClientExtensions.cs
  nekoyume/Assets/_Scripts/GraphQL/NineChroniclesAPIClientExtensions.cs.meta
Labels: Medium

#2712 Merge hotfix/repeat-ap into development
  nekoyume/Assets/Resources/UI/Prefabs/UI_SweepPopup.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs
Labels: Extra Small

#2714 Create arena digest from `OutputStates` on render `BattleArena`
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
Labels: Small

#2713 Update Costume L10n Add
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
Labels: Small

#2720 Fix HairToggle init in LoginDetail
  nekoyume/Assets/_Scripts/UI/Login/LoginDetailCostume.cs
Labels: Extra Small

#2726 fix extract internal trigger
  .github/workflows/build.yml
Labels: Extra Small

#2707 UI/shop mobile 1
  nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type8.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type8.prefab.meta
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Shop.spriteatlas
  nekoyume/Assets/Resources/UI/Prefabs/UI_Shop_Mobile_1.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Shop_Mobile_1.prefab.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_APPOTION_EN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_APPOTION_EN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_APPOTION_PT.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_APPOTION_PT.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_APPOTION_ZH-CN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_APPOTION_ZH-CN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_DAILYGROWTHPACKAGE_EN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_DAILYGROWTHPACKAGE_EN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_DAILYGROWTHPACKAGE_PT.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_DAILYGROWTHPACKAGE_PT.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_DAILYGROWTHPACKAGE_ZH-CN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_DAILYGROWTHPACKAGE_ZH-CN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_HOURGLASS_EN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_HOURGLASS_EN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_HOURGLASS_PT.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_HOURGLASS_PT.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_HOURGLASS_ZH-CN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_HOURGLASS_ZH-CN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_WEEKLYGROWTHPACKAGE_EN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_WEEKLYGROWTHPACKAGE_EN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_WEEKLYGROWTHPACKAGE_PT.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_WEEKLYGROWTHPACKAGE_PT.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_WEEKLYGROWTHPACKAGE_ZH-CN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_WEEKLYGROWTHPACKAGE_ZH-CN.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Shop_Goods_Bg.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Shop_Goods_Bg.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Shop_Goods_List_Bg.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Shop_Goods_List_Bg.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Shop_Goods_Mark_Best.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Shop_Goods_Mark_Best.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Shop_Goods_Mark_Hot.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Shop_Goods_Mark_Hot.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Shop_Goods_Mark_New.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Shop_Goods_Mark_New.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Shop_ListBox_Pattern.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Shop_ListBox_Pattern.png.meta
  nekoyume/Assets/UIResources/Content/Shop/Prefab/GoodsBox.prefab
  nekoyume/Assets/UIResources/Content/Shop/Prefab/GoodsBox.prefab.meta
  nekoyume/Assets/UIResources/Content/Shop/Prefab/TabButton_Main.prefab
Labels: Extra Large

#2728 Bugfix/for release 4
  nekoyume/Assets/Resources/UI/Prefabs/UI_RuneEnhancementResultScreen.prefab
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
Labels: Medium

#2730 assemble EnemyAvatarState for BattleArena rendering
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
Labels: Extra Small

#2738 Handle the render of `UnloadFromMyGarages` action
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Blockchain/BlockRenderHandler.cs
  nekoyume/Assets/_Scripts/Blockchain/IAgent.cs
  nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Helper/PetFrontHelper.cs
  nekoyume/Assets/_Scripts/State/RxProps.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/State/Subjects/AgentStateSubject.cs
  nekoyume/Assets/_Scripts/UI/Model/RuneItem.cs
  nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
  nekoyume/Assets/_Scripts/UI/Module/Pet/PetInfoView.cs
  nekoyume/Assets/_Scripts/UI/Module/WorldBoss/WorldBossRuneStoneInventory.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/PetEnhancementPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
  nekoyume/Assets/_Scripts/UI/Widget/RuneStoneItem.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
Labels: Extra Large

#2727 Introduce `IAPServiceManager`
  nekoyume/Assets/NineChronicles.meta
  nekoyume/Assets/NineChronicles/ExternalServices.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Editor.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Editor/IAPServiceToolWindow.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Editor/IAPServiceToolWindow.cs.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Common.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Common/JsonExceptionFactory.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Common/JsonExceptionFactory.cs.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceCache.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceCache.cs.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceClient.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceClient.cs.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceEndpoints.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceEndpoints.cs.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServicePoller.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServicePoller.cs.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/Currency.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/Currency.cs.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/HTTPValidationError.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/HTTPValidationError.cs.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/ProductSchema.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/ProductSchema.cs.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/ProductType.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/ProductType.cs.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/PurchaseProcessResultSchema.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/PurchaseProcessResultSchema.cs.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/ReceiptSchema.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/ReceiptSchema.cs.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/ReceiptStatus.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/ReceiptStatus.cs.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/Store.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/Store.cs.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/ValidationError.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/ValidationError.cs.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Responses.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Responses/IResponse.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Responses/IResponse.cs.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Responses/ProductResponse200.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Responses/ProductResponse200.cs.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Responses/PurchaseResponse200.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Responses/PurchaseResponse200.cs.meta
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Responses/Response422.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Responses/Response422.cs.meta
  nekoyume/Assets/Planetarium/Nekoyume/Editor/NineChroniclesAPIClientToolWindow.cs
  nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs
  nekoyume/Packages/manifest.json
  nekoyume/Packages/packages-lock.json
  nekoyume/nekoyume.sln.DotSettings
Labels: Extra Large

#2739 Feature/iap price schema
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceClient.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceEndpoints.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/ProductSchema.cs
  nekoyume/Assets/_Scripts/BlockChain.meta
Labels: enhancement, Extra Small
