Repository planetarium/NineChronicles, pull requests merged in 2023-04, with the labels that each got.

#2538 add yield return to CoInitDccAvatar()
  nekoyume/Assets/_Scripts/Game/Dcc.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/RequestManager.cs
Labels: Extra Small

#2553 enable Mixpanel tracking
  nekoyume/Assets/_Scripts/Analyzer.cs
Labels: Extra Small

#2556 Fix Recipe Scroll row
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
Labels: Extra Small

#2558 Update dcc UI
  nekoyume/Assets/Resources/UI/Animations/UI_PetSummonResultScreen.controller
  nekoyume/Assets/Resources/UI/Animations/UI_PetSummonResultScreen.controller.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccMain.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetSummonResultScreen.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Game/Dcc.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/Module/Mileage.cs
  nekoyume/Assets/_Scripts/UI/Widget/DccMain.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/PetSummonResultScreen.cs
Labels: Extra Small

#2559 Add LocalLayerModifier, AP loading in ShopSell actions
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Labels: Medium

#2561 change stack trace option to script only from full
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#2562 Add ConfirmConnectPopup, Apply to dcc connect
  nekoyume/Assets/Resources/UI/Prefabs/UI_ConfirmConnectPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ConfirmConnectPopup.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_OpenSeaPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_OpenSeaPopup.prefab.meta
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Widget/DccCollection.cs
  nekoyume/Assets/_Scripts/UI/Widget/DccMain.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ConfirmConnectPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ConfirmConnectPopup.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Popup/DccSettingPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ProfileSelectPopup.cs
Labels: Extra Large

#2566 feat: Improve UX of manipulate inventory state in State Viewer
  nekoyume/Assets/Packages/Microsoft.Extensions.Caching.Abstractions.dll.meta
  nekoyume/Assets/Packages/Microsoft.Extensions.Caching.Abstractions.xml.meta
  nekoyume/Assets/Packages/Microsoft.Extensions.Caching.Memory.dll.meta
  nekoyume/Assets/Packages/Microsoft.Extensions.Caching.Memory.xml.meta
  nekoyume/Assets/Packages/Microsoft.Extensions.Options.dll.meta
  nekoyume/Assets/Packages/Microsoft.Extensions.Options.xml.meta
  nekoyume/Assets/Packages/Microsoft.Extensions.Primitives.dll.meta
  nekoyume/Assets/Packages/Microsoft.Extensions.Primitives.xml.meta
  nekoyume/Assets/Plugins/BalanceTool/Editor/BalanceToolWindow.cs
  nekoyume/Assets/Plugins/BalanceTool/Runtime/HackAndSlashCalculator.cs
  nekoyume/Assets/Plugins/StateViewer/Editor/StateTreeView.cs
  nekoyume/Assets/Plugins/StateViewer/Editor/StateViewerWindow.cs
  nekoyume/Assets/Plugins/StateViewer/Runtime/BlacksmithMaster.cs
  nekoyume/Assets/Plugins/StateViewer/Runtime/BlacksmithMaster.cs.meta
  nekoyume/Assets/Plugins/StateViewer/Runtime/ContentKind.cs
  nekoyume/Assets/Plugins/StateViewer/Runtime/ContentKind.cs.meta
  nekoyume/Assets/Plugins/StateViewer/Runtime/StateTreeViewItemModel.cs
Labels: Extra Large

#2573 Feature/embedded headless pbft
  nekoyume/Assets/Planetarium/Nekoyume/Editor/HeadlessTool.cs
  nekoyume/Assets/Planetarium/Nekoyume/Editor/LibplanetEditor.cs
  nekoyume/Assets/Planetarium/Nekoyume/Editor/appsettings.example.json
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Helper/HeadlessHelper.cs
Labels: enhancement

#2571 Modify to update the fav when the action fails
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
Labels: bug

#2589 Use local `Agent` in unity editor
  nekoyume/Assets/Planetarium/Nekoyume/Editor/HeadlessTool.cs
  nekoyume/Assets/Planetarium/Nekoyume/Editor/LibplanetEditor.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: improve

#2597 Fix rpc/agent condition check logic
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Helper/HeadlessHelper.cs
Labels: bug

#2610 Fix agent and RPC conditoin checking logic
  nekoyume/Assets/Planetarium/Nekoyume/Editor/HeadlessTool.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Helper/HeadlessHelper.cs
Labels: bug
