Repository planetarium/NineChronicles, pull requests merged in 2023-01, with the labels that each got.

#2250 Fix gold to be updated when purchasing tickets
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Labels: Extra Small

#2249 Fix cost text in TicketPurchasePopup
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ArenaTicketPurchasePopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/TicketPurchasePopup.cs
Labels: Extra Small

#2255 Minimize Sentry SampleRate only for errors
  nekoyume/Assets/_Scripts/SentryOptionsConfiguration.cs
Labels: Extra Small

#2254 Fix combo text not reset
  nekoyume/Assets/_Scripts/UI/ComboText.cs
Labels: Extra Small

#2253 Responds to lobby character multi-resolution
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/BoxCatBtnContainers.prefab
  nekoyume/Assets/Resources/UI/Animations/UILobbyController@BackbgLoop.anim
  nekoyume/Assets/Resources/UI/Animations/UIMenuController@Show.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Sprites/Background/MainMenu/Object/Main_rock_01.png
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
Labels: Extra Large

#2258 UI fix
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardBillboard.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BossStatus.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationResultPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_EnemyPlayerStatus.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_EnhancementResultPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Status.prefab
Labels: Extra Large

#2257 Update arena battle button for interval index
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattlePreparation.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Extensions/ArenaInformationExtensions.cs
  nekoyume/Assets/_Scripts/Extensions/InventoryExtensions.cs
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
  nekoyume/Assets/_Scripts/State/RxProps.Common.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
Labels: Medium

#2256 Skip synopsis
  nekoyume/Assets/_Scripts/UI/Widget/Screen/PreloadingScreen.cs
Labels: improve, Extra Small

#2263 Bump `lib9c`
  nekoyume/Assets/Packages/Bencodex.Json.dll
  nekoyume/Assets/Packages/Bencodex.xml
  nekoyume/Assets/Packages/Bencodex.xml.meta
  nekoyume/Assets/Packages/BouncyCastle.Cryptography.xml
  nekoyume/Assets/Packages/BouncyCastle.Cryptography.xml.meta
  nekoyume/Assets/Packages/Caching.dll
  nekoyume/Assets/Packages/Caching.xml
  nekoyume/Assets/Packages/Caching.xml.meta
  nekoyume/Assets/Packages/Destructurama.Attributed.dll
  nekoyume/Assets/Packages/ImmutableTrie.dll
  nekoyume/Assets/Packages/Libplanet.Net.dll
  nekoyume/Assets/Packages/Libplanet.Net.xml
  nekoyume/Assets/Packages/Libplanet.RocksDBStore.deps.json
  nekoyume/Assets/Packages/Libplanet.RocksDBStore.deps.json.meta
  nekoyume/Assets/Packages/Libplanet.RocksDBStore.dll
  nekoyume/Assets/Packages/Libplanet.Stun.deps.json
  nekoyume/Assets/Packages/Libplanet.Stun.deps.json.meta
  nekoyume/Assets/Packages/Libplanet.Stun.dll
  nekoyume/Assets/Packages/Libplanet.dll
  nekoyume/Assets/Packages/Libplanet.xml
  nekoyume/Assets/Packages/ListSortHelper.dll
  nekoyume/Assets/Packages/LiteDB.dll
  nekoyume/Assets/Packages/LruCacheNet.dll
  nekoyume/Assets/Packages/Microsoft.Bcl.HashCode.dll
  nekoyume/Assets/Packages/Norgerman.Cryptography.Scrypt.dll
  nekoyume/Assets/Packages/Serilog.dll
  nekoyume/Assets/Packages/System.Collections.NonGeneric.dll
  nekoyume/Assets/Packages/System.Memory.xml
  nekoyume/Assets/Packages/System.Memory.xml.meta
  nekoyume/Assets/Packages/System.Numerics.Vectors.dll
  nekoyume/Assets/Packages/System.Reflection.TypeExtensions.dll
  nekoyume/Assets/Packages/System.Threading.Channels.xml
  nekoyume/Assets/Packages/System.Threading.Channels.xml.meta
  nekoyume/Assets/Packages/System.Threading.dll
  nekoyume/Assets/Packages/Validation.dll
  nekoyume/Assets/Packages/Zio.dll
  nekoyume/Assets/Packages/Zio.xml
  nekoyume/Assets/Packages/Zio.xml.meta
  nekoyume/Assets/_Scripts/BlockChain/Agent.cs
  nekoyume/Packages/manifest.json
  nekoyume/Packages/packages-lock.json
Labels: Extra Large

#2270 Merge `rc-v100351` into `development`
  .github/workflows/build-misc.yml
Labels: Extra Small

#2259 UI/shop cartview
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
  nekoyume/Assets/_Scripts/UI/Shop/CartView.cs
Labels: Small

#2269 Add condition to `EventReleaseNotePopup.Show()` about tutorial
  nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.cs
Labels: Extra Small

#2274 Change Grinding UI to one click working
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
Labels: Extra Small

#2272 Block duplicate clicks
  nekoyume/Assets/_Scripts/UI/Widget/Base/Widget.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/CombinationLoadingScreen.cs
Labels: Extra Small

#2275 Add l10n keys
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#2276 Check item slot status
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/State/States.cs
Labels: bug, Extra Small

#2277 Display buff vfx based on scriptable object data.
  nekoyume/Assets/Resources/ScriptableObject/BuffVFXData.asset
  nekoyume/Assets/Resources/ScriptableObject/BuffVFXData.asset.meta
  nekoyume/Assets/Resources/ScriptableObject/UI_WorldBossData.asset
  nekoyume/Assets/Resources/VFX/Prefabs/SkillRune_casting.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/SkillRune_casting.prefab.meta
  nekoyume/Assets/_Scripts/Extensions/BuffSheetExtension.cs
  nekoyume/Assets/_Scripts/Game/Character/ArenaCharacter.cs
  nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs
  nekoyume/Assets/_Scripts/Game/Character/RaidCharacter.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/BuffVFXScriptableObject.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/BuffVFXScriptableObject.cs.meta
  nekoyume/Assets/_Scripts/Game/VFX/Skill/BuffController.cs
  nekoyume/Assets/_Scripts/Helper/BuffHelper.cs
  nekoyume/Assets/_Scripts/Helper/BuffHelper.cs.meta
Labels: Large

#2278 consumable -> food and l10n bugfixed
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/enum_type.csv
  nekoyume/Assets/StreamingAssets/Localization/quest.csv
  nekoyume/Assets/StreamingAssets/Localization/speech_bubble.csv
Labels: Medium

#2285 Add forceClose() in widget
  nekoyume/Assets/_Scripts/UI/Widget/Base/Widget.cs
  nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs
Labels: bug, Extra Small

#2287 Apply libplanet changes
  nekoyume/Assets/_Scripts/BlockChain/Agent.cs
Labels: Extra Small

#2289 Grand finale 2022 l10n
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/worldboss_info.csv
Labels: Small

#2292 Change Close ()to ForceClose()
  nekoyume/Assets/_Scripts/UI/Widget/Base/Widget.cs
  nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs
Labels: bug, Extra Small

#2293 Logging APV
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Extra Small

#2296 Bugfix
  nekoyume/Assets/Resources/UI/Prefabs/UI_MailPopup.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
Labels: bug, Medium

#2297 [CI] Remove sign step
  .github/workflows/build.yml
  tools/pack/pack.py
Labels: Medium

#2300 fix: Restore download step
  .github/workflows/build.yml
  tools/pack/pack.py
Labels: Extra Small

#2290 Handle exception and fix minor
  nekoyume/Assets/_Scripts/UI/Module/GrandFinaleJoin.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/ArenaMenu.cs
Labels: Extra Small

#2303 Fix raid timeline activation track, change intro screen
  nekoyume/Assets/Resources/ScriptableObject/EventData.asset
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_Skill_Fury.playable
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
Labels: Extra Small

#2305 Bugfix
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
  nekoyume/Assets/_Scripts/UI/Shop/CartView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
Labels: bug, Extra Small

#2308 Fixed rune enhancement animation
  nekoyume/Assets/Resources/UI/Animations/UIRuneEnhancementResult@Loop.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_EnhancementResultPopup.prefab
Labels: bug, Extra Large

#2309 Bugfix/fix repeat button text
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattlePreparation.prefab
Labels: Extra Large

#2312 Update L10n Change
  nekoyume/Assets/StreamingAssets/Localization/character_name.csv
  nekoyume/Assets/StreamingAssets/Localization/notification.csv
Labels: Extra Small

#2310 [bugfix] Text /uibug fix
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RuneTooltip.prefab
  nekoyume/Assets/Resources/UI/Textures/icon_executable.png
  nekoyume/Assets/Resources/UI/Textures/icon_executable.png.meta
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Large

#2316 Bugfix
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs
Labels: bug, Extra Small

#2315 [bugfix] CP Text Style fix
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/RankCell.prefab
  nekoyume/Assets/Resources/UI/Animations/UIMenuController@Show.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
Labels: Extra Large

#2321 Uibug/rank listview text fix
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/RankCell.prefab
Labels: Small

#2322 [Bugfix] Prevent applying stage buff on switched character
  nekoyume/Assets/_Scripts/UI/Module/Button/BonusBuffButton.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BuffBonusResultPopup.cs
Labels: Extra Small

#2323 Update rune stat display
  nekoyume/Assets/_Scripts/Helper/RuneFrontHelper.cs
Labels: bug, Extra Small

#2324 [Design] add
  nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
Labels: Small
