Repository planetarium/NineChronicles, pull requests merged in 2023-07, with the labels that each got.

#2740 Edit login flow
  nekoyume/Assets/PackageExtensions/Mixpanel/MixpanelValueFactory.cs
  nekoyume/Assets/PackageExtensions/Mixpanel/MixpanelValueFactory.cs.meta
  nekoyume/Assets/Plugins/Android/AndroidManifest.xml
  nekoyume/Assets/Resources/UI/Animations/TextTouch.anim
  nekoyume/Assets/Resources/UI/Animations/TextTouch.anim.meta
  nekoyume/Assets/Resources/UI/Animations/TextTouch.controller
  nekoyume/Assets/Resources/UI/Animations/TextTouch.controller.meta
  nekoyume/Assets/Resources/UI/Animations/UIIntroScreenMobileController.controller
  nekoyume/Assets/Resources/UI/Animations/UIIntroScreenMobileController.controller.meta
  nekoyume/Assets/Resources/UI/Animations/UIIntroScreenMobileController@Show.anim
  nekoyume/Assets/Resources/UI/Animations/UIIntroScreenMobileController@Show.anim.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MobileTitle.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MobileTitle.prefab.meta
  nekoyume/Assets/Resources/Video/intro.mp4.meta
  nekoyume/Assets/Resources/Video/intro_video.renderTexture
  nekoyume/Assets/Resources/Video/intro_video.renderTexture.meta
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Analyzer.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Blockchain/Agent.cs
  nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Login/DeepLinkHandler.cs
  nekoyume/Assets/_Scripts/UI/Login/DeepLinkHandler.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/GrayLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
  nekoyume/Packages/manifest.json
  nekoyume/Packages/packages-lock.json
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Large

#2743 Add new param to portal open url
  nekoyume/Assets/_Scripts/UI/Login/DeepLinkHandler.cs
Labels: Extra Small

#2747 Fix platform exception
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Extra Small

#2748 Add command line option - RpcServerHosts
  nekoyume/Assets/Resources/ScriptableObject/LiveAssetEndpoint.asset
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/LiveAssetEndpointScriptableObject.cs
  nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs
Labels: Extra Small

#2756 Android level patch
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#2759 Fix check clo rpc client
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Extra Small

#2758 develop something for mobile
  .github/workflows/build.yml
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#2760 Fix Android aspect ratio diynamic to static
  nekoyume/Assets/_Scripts/Game/ActionCamera.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/CapturedImage.cs
Labels: Extra Small

#2762 feat: apply changes of IAP `ProductSchema`
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/ProductSchema.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
Labels: Extra Small

#2764 add android manifest ADID permission
  nekoyume/Assets/Plugins/Android/AndroidManifest.xml
Labels: Extra Small

#2766 UI/sweep setting upgrade edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SweepResultPopup.prefab
Labels: Extra Small

#2767 fix change background blur texture copy size
  nekoyume/Assets/_Scripts/UI/CapturedImage.cs
Labels: Extra Small

#2765 feat: track more events related to `Shop` UI
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
Labels: Extra Small

#2768 Fix Bugs
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccCollection.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Game/RaidStage.cs
  nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopView.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
Labels: Extra Small

#2769 improve l10n for mobile
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Large

#2773 Bugfix/iap shop bug
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceClient.cs
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#2774 fix: toggle value change at mobile shop
  nekoyume/Assets/Editor/Builder.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Small

#2777 Bugfix/iap caching bug
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#2780 fix: disable cache of `IAPServiceManager`
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Editor/IAPServiceToolWindow.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
Labels: Extra Small

#2778 Bugfix/background split check
  nekoyume/Assets/_Scripts/Game/ActionCamera.cs
  nekoyume/Assets/_Scripts/Game/RaidCamera.cs
Labels: Extra Small

#2741 Design]UI_DialogPopup_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_DialogPopup.prefab
Labels: Extra Small

#2770 fix ui synopsis size fix
  nekoyume/Assets/Resources/UI/Prefabs/UI_Synopsis.prefab
Labels: Small

#2757 edit local data rc
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/elemental_type.csv
Labels: Extra Small

#2781 fix pakage name
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#2763 add CommendLineOption Setting tool Add
  nekoyume/Assets/Planetarium/Nekoyume/Editor/CloSettingToolWindow.cs
  nekoyume/Assets/Planetarium/Nekoyume/Editor/CloSettingToolWindow.cs.meta
Labels: Medium

#2782 add application version in android platform
  nekoyume/Assets/_Scripts/UI/Widget/System/VersionSystem.cs
Labels: Extra Small

#2788 fix: disable raw image of grinding loading screen
  nekoyume/Assets/Resources/UI/Prefabs/UI_GrindingLoadingScreen.prefab
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#2791 feat: add disable animation to button of mobile shop
  nekoyume/Assets/Resources/UI/Animations/ConditionalButton_For-MobileShop.controller
  nekoyume/Assets/Resources/UI/Animations/ConditionalButton_For-MobileShop.controller.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
  nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopView.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
Labels: Extra Large

#2792 Fix ui texts, inputfield focusing
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/InputBoxPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
Labels: Small

#2801 Add missing l10n component to tmp
  nekoyume/Assets/AddressableAssets/UI/Module/ItemOptionView/CombinationResultSkillOptionView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemOptionView/CombinationResultStatOptionView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemOptionView/CombinationSlotPopupCombinationSkillOptionView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemOptionView/CombinationSlotPopupCombinationStatOptionView.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationResultPopup.prefab
Labels: Medium

#2800 fix application version view exception handling
  nekoyume/Assets/Resources/UI/Prefabs/UI_VersionSystem.prefab
  nekoyume/Assets/_Scripts/UI/Widget/System/VersionSystem.cs
Labels: Extra Small

#2813 Obsolete dcc ui for mobile
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Status.cs
Labels: Extra Small

#2812 fix iap purchase btn loading animation add
  nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
  nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopView.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
Labels: Extra Small

#2805 [Design]UI_IntroScreen_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Extra Large

#2808 chore: log more info of `Stage`
  nekoyume/Assets/_Scripts/Game/Stage.cs
Labels: Small

#2817 [Design]block-hash_test_overlap_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotsPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MailPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PrologueDialogPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPopup.prefab
Labels: Small

#2821 add local network clo setting
  nekoyume/Assets/StreamingAssets/clo-local-network-test.json
  nekoyume/Assets/StreamingAssets/clo-local-network-test.json.meta
Labels: Extra Small

#2822 [Design]UI_StageLoadingEffect_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_StageLoadingEffect.prefab
Labels: Extra Small

#2819 [Design] text-cut-off_Prefabs_Edit
  nekoyume/Assets/Resources/Font/Materials/English SDF Material - QuestRewardText3.mat
  nekoyume/Assets/Resources/Tutorial/Animation/Item_DialogBoxComma.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Synopsis.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/prologue_00.png
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/prologue_01.png
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/prologue_02.png
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/prologue_03.png
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/prologue_04.png
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/prologue_05.png
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/prologue_06.png
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/prologue_07.png
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/prologue_08.png
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/prologue_09.png
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/prologue_10.png
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/prologue_Bg.png
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/prologue_Bg.png.meta
Labels: Extra Large

#2815 feat: remove if branching at already has keystore
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#2811 fixed worldboss effect scale fix
  nekoyume/Assets/Resources/Worldboss/Prefab/Item_WorldBossWave_01.prefab
Labels: Extra Small

#2810 fix worldboss skipbtn flip issue
  nekoyume/Assets/_Scripts/Animation/RaidTimelineContainer.cs
Labels: Extra Small

#2824 Merge development into m-development
  nekoyume/Assets/Resources/Worldboss/Prefab/Item_WorldBossWave_01.prefab
  nekoyume/Assets/_Scripts/Animation/RaidTimelineContainer.cs
  nekoyume/Assets/_Scripts/Game/Stage.cs
Labels: Small

#2820 feat: implement `TrackState` feature on `StateViewer`
  .gitignore
  nekoyume/Assets/Plugins/StateViewer/Editor/Features/StateAndBalanceFeature.cs
  nekoyume/Assets/Plugins/StateViewer/Editor/Features/TrackStateFeature.cs
  nekoyume/Assets/Plugins/StateViewer/Editor/Features/TrackStateFeature.cs.meta
  nekoyume/Assets/Plugins/StateViewer/Editor/StateViewerWindow.cs
  nekoyume/Assets/Plugins/StateViewer/Runtime/StateProxy.cs
  nekoyume/Assets/_Scripts/Blockchain/Agent.cs
  nekoyume/Assets/_Scripts/Blockchain/IAgent.cs
  nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
Labels: Extra Large

#2827 UI/increase touch points
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/GuidedQuestCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/GuidedQuest.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/RecipeView/RequiredItemRecipeView.prefab
  nekoyume/Assets/Resources/UI/Prefabs/EquipDesc.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MaterialTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
  nekoyume/Assets/UIResources/Content/Shop/Prefab/TabButton_Sub.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Infomation.prefab
Labels: Extra Large

#2823 Add ingame debug console
  nekoyume/Assets/Plugins/IngameDebugConsole.meta
  nekoyume/Assets/Plugins/IngameDebugConsole/IngameDebugConsole.prefab
  nekoyume/Assets/Plugins/IngameDebugConsole/IngameDebugConsole.prefab.meta
  nekoyume/Assets/_Scenes/Game.unity
  nekoyume/Assets/_Scripts/Debug.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
  nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs
  nekoyume/Assets/_Scripts/Nekoyume.asmdef
  nekoyume/Packages/manifest.json
  nekoyume/Packages/packages-lock.json
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Small

#2814 feat: introduce `IconPopup`
  nekoyume/Assets/AddressableAssets/UI/Module/FungibleAssetValueView.meta
  nekoyume/Assets/AddressableAssets/UI/Module/FungibleAssetValueView/FungibleAssetValueView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/FungibleAssetValueView/FungibleAssetValueView.prefab.meta
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/CRYSTAL.png
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/CRYSTAL.png.meta
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/NCG.png
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/NCG.png.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_IconPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_IconPopup.prefab.meta
  nekoyume/Assets/_Scripts/Extensions/FungibleAssetValueExtensions.cs
  nekoyume/Assets/_Scripts/Extensions/ItemExtensions.cs
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Module/FungibleAssetValue.meta
  nekoyume/Assets/_Scripts/UI/Module/FungibleAssetValue/FungibleAssetValueView.cs
  nekoyume/Assets/_Scripts/UI/Module/FungibleAssetValue/FungibleAssetValueView.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Popup/IconPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/IconPopup.cs.meta
  nekoyume/nekoyume.sln.DotSettings
Labels: Extra Large

#2816 Edit LoginSystem ui, add alert popup
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_TitleOneButtonSystem.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
Labels: Medium

#2825 Add TimeOut to pledge
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Small

#2826 Obsolete dcc ui for mobile
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/PetSelectionPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotsPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Status.cs
Labels: Extra Small

#2832 Feature/block time
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/DailyBonus.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
  nekoyume/Assets/Resources/UI/Prefabs/CombinationSlot.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotPopup.prefab
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Extensions/BlockIndexExtensions.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Helper/Util.cs
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
  nekoyume/Assets/_Scripts/State/RxProps.Common.cs
  nekoyume/Assets/_Scripts/State/RxProps.Event.cs
  nekoyume/Assets/_Scripts/UI/BlockTimer.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinSeasonInfo.cs
  nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
  nekoyume/Assets/_Scripts/UI/Module/DailyBonus.cs
  nekoyume/Assets/_Scripts/UI/Module/GrandFinaleJoin.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/ArenaMenu.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ArenaTicketPurchasePopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/WorldBossTickets.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs
Labels: Extra Large

#2783 feat: improve `UnloadFromMyGaragesRecipientMail` UI
  .gitignore
  nekoyume/Assets/StreamingAssets/Localization/mail.csv
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Extensions/MailExtensions.cs
  nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Medium

#2828 feature: add keystore importing with data matrix
  nekoyume/Assets/Packages/zxing.unity.dll
  nekoyume/Assets/Packages/zxing.unity.dll.meta
  nekoyume/Assets/Packages/zxing.unity.xml
  nekoyume/Assets/Packages/zxing.unity.xml.meta
  nekoyume/Assets/Plugins/Android/AndroidManifest.xml
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/Login/DataMatrixReaderView.cs
  nekoyume/Assets/_Scripts/UI/Login/DataMatrixReaderView.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Extra Large

#2834 UI/loading text position edit
  nekoyume/Assets/Resources/UI/Animations/UIPopupController@Close.anim
  nekoyume/Assets/Resources/UI/Animations/UIPopupController@Show.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_DimmedLoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_GrayLoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossResultPopup.prefab
Labels: Medium

#2836 chore: update app icon
  nekoyume/Assets/Resources/UI/Textures/icon_executable.png
Labels: No Changes
