Repository planetarium/NineChronicles, pull requests merged in 2023-11, with the labels that each got.

#3283 fix screen clearing
  nekoyume/Assets/_Scenes/Game.unity
  nekoyume/Assets/_Scripts/Game/ActionCamera.cs
  nekoyume/Assets/_Scripts/Game/RaidCamera.cs
  nekoyume/Assets/_Scripts/Game/Util/IngameDebugConsoleCommands.cs
Labels: Small

#3293 feat: google sign-in button disable at google sign-in feature...
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Extra Small

#3292 redesign DimmedLoadingScreen
  nekoyume/Assets/Resources/UI/Prefabs/UI_DimmedLoadingScreen.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Blockchain/Agent.cs
  nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/DimmedLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/IconAndButtonSystem.cs
Labels: Extra Large

#3294 🔧 fix: Freezing when `BattleArena` action rendering
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
Labels: bug, Extra Small

#3297 fix(prefab): invoke `IntroScreen.ShowMobile()` in `DMXReader.BackButton`
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
Labels: Extra Small

#3298 fix(prefab): invoke `IntroScreen.ShowMobile()` in `DMXReader.BackButton`
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
Labels: Extra Small

#3291 Run download shop image task in background
  nekoyume/Assets/_Scripts/Helper/Util.cs
  nekoyume/Assets/_Scripts/L10n/L10nManager.cs
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
Labels: Medium

#3303 UI/loui add
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/40100019.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/40100019.atlas.txt.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/40100019.json
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/40100019.json.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/40100019.png
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/40100019.png.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/40100019_Atlas.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/40100019_Atlas.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/40100019_Material-Additive.mat
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/40100019_Material-Additive.mat.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/40100019_Material-Multiply.mat
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/40100019_Material-Multiply.mat.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/40100019_Material.mat
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/40100019_Material.mat.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/40100019_SkeletonData.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/40100019_SkeletonData.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Attack.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Attack.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Attack_02.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Attack_02.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Attack_03.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Attack_03.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Casting.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Casting.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/CriticalAttack.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/CriticalAttack.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Die.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Die.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Hit.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Hit.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Idle.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Idle.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Run.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Run.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Touch.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Touch.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/TurnOver_01.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/TurnOver_01.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/TurnOver_02.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/TurnOver_02.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Win.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100019/ReferenceAssets/Win.asset.meta
  nekoyume/Assets/Resources/UI/Icons/Item/40100019.png
  nekoyume/Assets/Resources/UI/Icons/Item/40100019.png.meta
Labels: Extra Large

#3306 Change audio resources
  nekoyume/Assets/Resources/Audio/Music/Prefabs/bgm_workshop.prefab
  nekoyume/Assets/Resources/Audio/Music/Prefabs/bgm_workshop.prefab.meta
  nekoyume/Assets/Resources/Audio/Music/clips/bgm_main.ogg
  nekoyume/Assets/Resources/Audio/Music/clips/bgm_prologue.ogg
  nekoyume/Assets/Resources/Audio/Music/clips/bgm_selectcharacter.ogg
  nekoyume/Assets/Resources/Audio/Music/clips/bgm_shop.ogg
  nekoyume/Assets/Resources/Audio/Music/clips/bgm_workshop.ogg
  nekoyume/Assets/Resources/Audio/Music/clips/bgm_workshop.ogg.meta
  nekoyume/Assets/Resources/Audio/Sfx/clips/sfx_celebration0.wav
  nekoyume/Assets/Resources/Audio/Sfx/clips/sfx_levelup.wav
  nekoyume/Assets/Resources/Audio/Sfx/clips/sfx_success.wav
  nekoyume/Assets/_Scripts/Game/Controller/AudioController.cs
Labels: Extra Small

#3309 Fix synopsis length
  nekoyume/Assets/Resources/UI/Prefabs/UI_Synopsis.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
Labels: Extra Small

#3304 Track cancel event
  nekoyume/Assets/_Scripts/Game/OAuth/GoogleSigninBehaviour.cs
Labels: Extra Small

#3307 Rename GameConfig client variables
  nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs
  nekoyume/Assets/_Scripts/Game/LiveAsset/GameConfig.cs
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
  nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
  nekoyume/Assets/_Scripts/UI/Module/Currency/ActionPoint.cs
  nekoyume/Assets/_Scripts/UI/Module/GuidedQuest.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/MainMenu.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeCellView.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
Labels: Small

#3308 Delete Mimisburnnr tab in rank popup prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
  nekoyume/Assets/_Scripts/UI/Model/Rank.cs
  nekoyume/Assets/_Scripts/UI/Model/RankCategory.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/RankPopup.cs
Labels: Extra Large

#3305 Add Asset Detail to Header Menu
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/ActionPoint.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/Crystal.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/Gold.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/Hourglass.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/MaterialAsset.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/RuneStone.prefab
  nekoyume/Assets/Resources/ScriptableObject/CostIconData.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_MaterialNavigationPopup.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/_Scripts/UI/Module/Currency/ActionPoint.cs
  nekoyume/Assets/_Scripts/UI/Module/Currency/Crystal.cs
  nekoyume/Assets/_Scripts/UI/Module/Currency/Gold.cs
  nekoyume/Assets/_Scripts/UI/Module/Currency/Hourglass.cs
  nekoyume/Assets/_Scripts/UI/Module/Currency/MaterialAsset.cs
  nekoyume/Assets/_Scripts/UI/Module/Currency/RuneStone.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MaterialNavigationPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
  nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
Labels: Extra Large

#3313 bugfix letter box size
  nekoyume/Assets/_Scenes/Game.unity
  nekoyume/Assets/_Scripts/Game/ActionCamera.cs
  nekoyume/Assets/_Scripts/Game/RaidCamera.cs
  nekoyume/Assets/_Scripts/Game/Util/IngameDebugConsoleCommands.cs
Labels: Large

#3314 Introduce many tutorial
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBoss.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossDetail.prefab
  nekoyume/Assets/StreamingAssets/Localization/dialog.csv
  nekoyume/Assets/_Scripts/Game/LiveAsset/GameConfig.cs
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
  nekoyume/Assets/_Scripts/UI/Model/RecipeModel.cs
  nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/GuideArrow.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialActionType.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialTargetType.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/StageLoadingEffect.cs
  nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldBossDetail.cs
Labels: Extra Large

#3315 Add bgm to widgets
  nekoyume/Assets/Resources/Audio/Music/Prefabs/bgm_battle_loading.prefab
  nekoyume/Assets/Resources/Audio/Music/Prefabs/bgm_battle_loading.prefab.meta
  nekoyume/Assets/Resources/Audio/Music/clips/bgm_battle_loading.ogg
  nekoyume/Assets/Resources/Audio/Music/clips/bgm_battle_loading.ogg.meta
  nekoyume/Assets/_Scripts/Game/Controller/AudioController.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
  nekoyume/Assets/_Scripts/UI/Widget/StageLoadingEffect.cs
Labels: Medium

#3316 Update L10n Title Item
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
Labels: Extra Small

#3318 change ap charge tutorial to stage 24
  nekoyume/Assets/_Scripts/Game/LiveAsset/GameConfig.cs
  nekoyume/Assets/_Scripts/UI/Module/Currency/ActionPoint.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
Labels: Extra Small

#3327 delete dialog
  nekoyume/Assets/StreamingAssets/Localization/dialog.csv
Labels: Small

#3328 fix: change ap charge tutorial to stage 23
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MaterialNavigationPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Rune.prefab
  nekoyume/Assets/_Scripts/Game/LiveAsset/GameConfig.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
Labels: Extra Small

#3330 Fix/71.0.0
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MaterialNavigationPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Rune.prefab
  nekoyume/Assets/StreamingAssets/Localization/dialog.csv
  nekoyume/Assets/_Scripts/Game/LiveAsset/GameConfig.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
Labels: Small

#3329 Convert korean language in PC
  nekoyume/Assets/_Scripts/L10n/L10nManager.cs
Labels: Extra Small

#3311 Feature/ios
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Game/RaidCamera.cs
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
  nekoyume/Assets/_Scripts/UI/Widget/Status.cs
Labels: Extra Small

#3325 Add try-catch to gql request
  nekoyume/Assets/_Scripts/GraphQL/NineChroniclesAPIClient.cs
Labels: Extra Small

#3339 fix: move OpenApiGenerator to Assets/Editor
  nekoyume/Assets/Editor/OpenAPIGenerator.cs
  nekoyume/Assets/Editor/OpenAPIGenerator.cs.meta
Labels: No Changes

#3338 Introduce KR/JP notice
  nekoyume/Assets/Resources/ScriptableObject/LiveAssetEndpoint.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventReleaseNotePopup.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/NoteListview.prefab
  nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/LiveAssetEndpointScriptableObject.cs
Labels: Medium

#3301 feat: planet selector
  nekoyume/Assets/Resources/UI/Animations/UIIntroScreenMobileController.controller
  nekoyume/Assets/Resources/UI/Animations/UIIntroScreenMobileController@ShowButtons.anim
  nekoyume/Assets/Resources/UI/Animations/UIIntroScreenMobileController@ShowButtons.anim.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/WorldMapWorld.prefab
  nekoyume/Assets/StreamingAssets/Localization/DirectoryForAndroid.txt
  nekoyume/Assets/StreamingAssets/Localization/button.csv
  nekoyume/Assets/StreamingAssets/Localization/button.csv.meta
  nekoyume/Assets/StreamingAssets/Localization/loading.csv
  nekoyume/Assets/StreamingAssets/Localization/loading.csv.meta
  nekoyume/Assets/StreamingAssets/Localization/sentence.csv
  nekoyume/Assets/StreamingAssets/Localization/sentence.csv.meta
  nekoyume/Assets/StreamingAssets/Localization/word.csv
  nekoyume/Assets/StreamingAssets/Localization/word.csv.meta
  nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Game/OAuth/GoogleSigninBehaviour.cs
  nekoyume/Assets/_Scripts/L10n/L10nManager.cs
  nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs
  nekoyume/Assets/_Scripts/State/RxProps.cs
  nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
  nekoyume/Assets/_Scripts/UI/Widget/Base/Widget.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
Labels: Extra Large

#3342 UI/UI edit 231107
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/ActionPoint.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/ArenaTickets.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/Crystal.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/EventDungeonTickets.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/Gold.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/Hourglass.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/MaterialAsset.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/Mileage.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/RuneStone.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/WorldBossTickets.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ReceiveArea.prefab
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
  nekoyume/Assets/Resources/UI/Prefabs/UI_Alert.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ChatPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventReleaseNotePopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_TitleOneButtonSystem.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossDetail.prefab
  nekoyume/Assets/Resources/UI/Textures/00_Loading/loading_worldboss.png
  nekoyume/Assets/Resources/UI/Textures/00_Loading/loading_worldboss.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_RewardImg.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_RewardImg/RewardImg_1.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_RewardImg/RewardImg_1.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_RewardImg/RewardImg_2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_RewardImg/RewardImg_2.png.meta
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Infomation.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Rank.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Rune.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossBattleRewardItem.prefab
Labels: Extra Large

#3349 Fix to call SetPushNotification on main thread
  nekoyume/Assets/_Scripts/UI/Model/PatrolReward.cs
Labels: Extra Small

#3350 cherry-pick Add try-catch to gql request #3325
  nekoyume/Assets/_Scripts/GraphQL/NineChroniclesAPIClient.cs
Labels: Extra Small

#3351 chore: update version to 80.0.1
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#3352 🔧 fix: less ping check
  nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
Labels: Extra Small

#3354 Merge/80.0.1 to develop
  nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
  nekoyume/Assets/_Scripts/UI/Model/PatrolReward.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#3323 UI/seasonpass style add
  nekoyume/Assets/Resources/UI/Icons/Item/49900011.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_ChStyle/Icon_ChTextStyle_07.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_ChStyle/Icon_ChTextStyle_07.png.meta
  nekoyume/Assets/UIResources/Content/Common/Prefab/item_TextStyle_07.prefab
  nekoyume/Assets/UIResources/Content/Common/Prefab/item_TextStyle_07.prefab.meta
  nekoyume/Assets/UIResources/Content/Effect/TextStyle/Item_TextStyle_07_Loop.anim
  nekoyume/Assets/UIResources/Content/Effect/TextStyle/Item_TextStyle_07_Loop.anim.meta
  nekoyume/Assets/UIResources/Content/Effect/TextStyle/item_TextStyle_07.controller
  nekoyume/Assets/UIResources/Content/Effect/TextStyle/item_TextStyle_07.controller.meta
Labels: Extra Large

#3348 fix helppopup prefap and json
  nekoyume/Assets/Resources/HelpPopupData/HelpPopupData.json
  nekoyume/Assets/Resources/UI/Prefabs/UI_HelpTooltip.prefab
Labels: Extra Large

#3355 SeasonPassServiceManager has to initialized
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Extra Small

#3356 chore: update bundle code
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#3357 find all assembly and check field
  nekoyume/Assets/Editor/OpenAPIGenerator.cs
Labels: Extra Small

#3360 feat: improve DimmedLoadingScreen
  nekoyume/Assets/Resources/UI/Prefabs/UI_DimmedLoadingScreen.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/loading.csv
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/DimmedLoadingScreen.cs
Labels: Small

#3346 feat: remove disabling headermenu when battle end
  nekoyume/Assets/_Scripts/UI/Widget/Battle.cs
  nekoyume/Assets/_Scripts/UI/Widget/StageLoadingEffect.cs
Labels: Extra Small

#3364 chore: change guide rect position about accel button
  nekoyume/Assets/Resources/UI/Prefabs/UI_Battle.prefab
Labels: Extra Small

#3366 Feature/notch adjuster
  nekoyume/Assets/AddressableAssets/UI/Module/Button/BackButton.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventBanner.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Grind.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Rune.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopSell.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_StageInformation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Status.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_VersionSystem.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBoss.prefab
  nekoyume/Assets/Resources/UI/Prefabs/WorldMapWorld.prefab
  nekoyume/Assets/_Scripts/Game/ActionCamera.cs
  nekoyume/Assets/_Scripts/Game/RaidCamera.cs
  nekoyume/Assets/_Scripts/UI/Module/Common/NotchAdjuster.cs
  nekoyume/Assets/_Scripts/UI/Module/Common/NotchAdjuster.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Large

#3361 Modified to enable testing on Unity Editor Android platform
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Helper/Url.cs
  nekoyume/Assets/_Scripts/PushNotifier.cs
Labels: Extra Small

#3367 fix: enable/disable tutorial skip button when play/close timing
  nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Tutorial.cs
Labels: Extra Small

#3363 feat: tutorial bg disabling if target is null
  nekoyume/Assets/_Scripts/UI/Tutorial/GuideBackground.cs
Labels: Extra Small

#3374 notch ui apply
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Battle.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RaidPreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPass.prefab
Labels: Large

#3347 Japanese Translation Polishing
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/help_popup.csv
  nekoyume/Assets/StreamingAssets/Localization/tutorial.csv
Labels: bug, Extra Small

#3376 Localization korean
  nekoyume/Assets/AddressableAssets/UI/Module/PFP/PetInventory.prefab
  nekoyume/Assets/Resources/UI/Prefabs/CombinationSlot.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventReleaseNotePopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetSelectionPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RaidPreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopSell.prefab
  nekoyume/Assets/StreamingAssets/Localization/buff_name.csv
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/elemental_type.csv
  nekoyume/Assets/StreamingAssets/Localization/enum_type.csv
  nekoyume/Assets/StreamingAssets/Localization/error.csv
  nekoyume/Assets/StreamingAssets/Localization/event_dungeon_name.csv
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
  nekoyume/Assets/StreamingAssets/Localization/loading.csv
  nekoyume/Assets/StreamingAssets/Localization/mail.csv
  nekoyume/Assets/StreamingAssets/Localization/notification.csv
  nekoyume/Assets/StreamingAssets/Localization/quest.csv
  nekoyume/Assets/StreamingAssets/Localization/skill_description.csv
  nekoyume/Assets/StreamingAssets/Localization/skill_name.csv
  nekoyume/Assets/StreamingAssets/Localization/speech_bubble.csv
  nekoyume/Assets/StreamingAssets/Localization/worldboss_info.csv
Labels: Extra Large

#3377 store `PlanetContext.SelectedPlanetInfo.ID` to `Game.CurrentPlanetId`
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Extra Small

#3373 seasson pass planet api apply
  nekoyume/Assets/_Scripts/GeneratedApi/SeasonPassServiceClient.cs
  nekoyume/Assets/_Scripts/SeasonPassService/SeasonPassServiceManager.cs
Labels: Extra Small

#3379 feat: init `Game.CurrentPlanetId` on standalone
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Helper/CommandLineOptions.cs
  nekoyume/Assets/_Scripts/Helper/CommandLineOptions.cs.meta
  nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs
  nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs
  nekoyume/Assets/_Scripts/Planet/Planets.cs
Labels: Extra Large

#3385 revert csv edit to develop play
  nekoyume/Assets/StreamingAssets/Localization/help_popup.csv
Labels: No Changes

#3380 NRE exception handle
  nekoyume/Assets/_Scripts/SeasonPassService/SeasonPassServiceManager.cs
Labels: Extra Small

#3382 change seasonpass menu level text
  nekoyume/Assets/_Scripts/UI/Module/Lobby/SeasonPassMenu.cs
  nekoyume/Assets/_Scripts/UI/Widget/SeasonPass.cs
Labels: Extra Small

#3390 improve aura tutorial
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
  nekoyume/Assets/StreamingAssets/Localization/tutorial.csv
  nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs
  nekoyume/Assets/_Scripts/UI/Module/Button/SimpleCostButton.cs
  nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/GuideArrow.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialActionType.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialTargetType.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/CombinationMain.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/SummonResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Summon.cs
Labels: Large

#3391 Feature/season pass claim items action handle
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
Labels: Extra Small

#3388 seasonpass enter exception handle
  nekoyume/Assets/AddressableAssets/UI/Module/SeasonPassBtn.prefab
  nekoyume/Assets/_Scripts/SeasonPassService/SeasonPassServiceManager.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/SeasonPassMenu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassNewPopup.cs
Labels: Small

#3384 add screen ratio limit 16/9 ~ 21/9
  nekoyume/Assets/_Scripts/Game/ActionCamera.cs
  nekoyume/Assets/_Scripts/Game/RaidCamera.cs
Labels: Extra Small

#3387 arena repeat text fix
  nekoyume/Assets/_Scripts/UI/Widget/Popup/RankingBattleResultPopup.cs
Labels: Extra Small

#3383 [Design]UI_Menu_Prefabs_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/SeasonPassBtn.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
Labels: Large

#3392 [Design]UI_shopListPopup_Prefabs_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/ShopListCell.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopListPopup.prefab
Labels: Extra Small

#3381 [Design]WorldBossResult@Show_anim_Edi
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossResultPopup.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossResult@Show.anim
Labels: Large

#3394 fix[Android]: handle back button event in login context
  nekoyume/Assets/StreamingAssets/Localization/button.csv
  nekoyume/Assets/StreamingAssets/Localization/help_popup.csv
  nekoyume/Assets/StreamingAssets/Localization/sentence.csv
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Game/OAuth/GoogleSigninBehaviour.cs
  nekoyume/Assets/_Scripts/Permissions.meta
  nekoyume/Assets/_Scripts/Permissions/PermissionState.cs
  nekoyume/Assets/_Scripts/Permissions/PermissionState.cs.meta
  nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs
  nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/DimmedLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/OneButtonSystem.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/TwoButtonSystem.cs
Labels: Large

#3395 Update InviteFriendsPopup
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Game/OAuth/GoogleSigninBehaviour.cs
  nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/InviteFriendsPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
Labels: Medium

#3397 edd noti about connect fail season pass
  nekoyume/Assets/StreamingAssets/Localization/notification.csv
Labels: Medium

#3396 Changed to not calculate updated addresses
  nekoyume/Assets/_Scripts/Blockchain/Agent.cs
  nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#3398 fix localization files
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
Labels: Extra Small

#3400 fix: `PlanetId?` as a `string` in `CommandLineOptions`
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Helper/CommandLineOptions.cs
  nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs
  nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs
  nekoyume/Assets/_Scripts/Planet/Planets.cs
Labels: Extra Small

#3401 Add l10n key
  nekoyume/Assets/AddressableAssets/UI/Module/StakingBonus.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_AlertPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBoard.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginDetail.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SuperCraftPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SweepPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SweepResultPopup.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/tutorial.csv
Labels: Extra Large

#3403 fix TryGetPlanetInfoByHeadlessGrpc
  nekoyume/Assets/_Scripts/Planet/Planets.cs
Labels: Extra Small

#3405 Fix various prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/GuidedQuestCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/RuneStoneInventoryCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_RuneListview.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Item/RuneListItem.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Item/RuneStakingListItem.prefab
  nekoyume/Assets/Resources/Audio/Sfx/Prefabs/sfx_notice.prefab
  nekoyume/Assets/Resources/UI/Prefabs/EquipDesc.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Battle.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BossStatus.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_DialogPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MailPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PrologueDialogPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RewardScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_StageInformation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_StageProgressBar.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_StageTitle.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
  nekoyume/Assets/_Scripts/UI/Widget/CodeRewardEffector.cs
Labels: Extra Large

#3407 add preprocessor
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
Labels: Extra Small

#3409 fix start button anchor
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattlePreparation.prefab
Labels: Extra Small

#3406 feat: [Android] open native system settings for permission
  nekoyume/Assets/StreamingAssets/Localization/button.csv
  nekoyume/Assets/StreamingAssets/Localization/sentence.csv
  nekoyume/Assets/_Scripts/Native.meta
  nekoyume/Assets/_Scripts/Native/SystemSettingsOpener.cs
  nekoyume/Assets/_Scripts/Native/SystemSettingsOpener.cs.meta
  nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs
Labels: Medium

#3411 fix: add yield return null without mobile compiling env
  nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs
Labels: Extra Small

#3410 Add platform to check tokens
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Extra Small

#3413 tutorial: remove guide offset
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
Labels: Extra Small

#3412 Fix typo at refresh token
  nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
Labels: Small

#3344 Test/arena graphql
  nekoyume/Assets/Tests/EditMode/AvatarStateTest.cs
  nekoyume/Assets/Tests/EditMode/State/RxPropsTest.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/GraphQL/NineChroniclesAPIClientExtensions.cs
  nekoyume/Assets/_Scripts/GraphQL/TxResultQuery.cs
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
  nekoyume/Assets/_Scripts/UI/Model/ArenaParticipantModel.cs
  nekoyume/Assets/_Scripts/UI/Model/ArenaParticipantModel.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ArenaTicketPopup.cs
Labels: Extra Large

#3415 fix tutorial ui notch and runtime change screen size
  nekoyume/Assets/AddressableAssets/UI/Module/TutorialDummys.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
  nekoyume/Assets/_Scripts/Game/ActionCamera.cs
  nekoyume/Assets/_Scripts/Game/RaidCamera.cs
  nekoyume/Assets/_Scripts/UI/Module/Common/NotchAdjuster.cs
Labels: Extra Small

#3414 feat: quit with kind message when login context cannot go forward
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Game/OAuth/GoogleSigninBehaviour.cs
  nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Extra Small

#3429 disable celebrate opening shop on mobile
  nekoyume/Assets/_Scripts/Game/Stage.cs
Labels: Extra Small

#3428 fix: set timeScale at Menu.Show()
  nekoyume/Assets/_Scripts/Game/Prologue.cs
  nekoyume/Assets/_Scripts/Game/RaidStage.cs
  nekoyume/Assets/_Scripts/Timeline/TimeScale/TimeScaleBehaviour.cs
  nekoyume/Assets/_Scripts/Timeline/TimeScale/TimeScaleTrack.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
Labels: Extra Small

#3435 add planet id into iap PurchaseRequestAsync
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceClient.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
Labels: Extra Small

#3434 Bugfix/seasonpass UI fix
  nekoyume/Assets/Editor/OpenAPIGenerator.cs
  nekoyume/Assets/_Scripts/GeneratedApi/SeasonPassServiceClient.cs
  nekoyume/Assets/_Scripts/SeasonPassService/SeasonPassServiceManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/SeasonPass.cs
Labels: Extra Small

#3433 add notch apply
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
Labels: Extra Small

#3440 [hotfix] fix l10n error
  nekoyume/Assets/StreamingAssets/Localization/tutorial.csv
Labels: Extra Small

#3439 remove cell count fix in RuneListScroll
  nekoyume/Assets/_Scripts/UI/Scroller/RuneListScroll.cs
Labels: Extra Small

#3432 [Referral] Fix referral bugs
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
Labels: Extra Small

#3443 fix wrong text
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/tutorial.csv
Labels: Extra Small

#3444 fix wrong text
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#3446 csv parsing failed skip load
  nekoyume/Assets/_Scripts/L10n/L10nManager.cs
Labels: Extra Small

#3445 move seasonpass tutorial popup
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialActionType.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassNewPopup.cs
Labels: Extra Small

#3452 Fix wrong endpoints for DataProvider GQL
  nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs
Labels: Extra Small

#3447 feat: track elapsed several point in game initializing context
  nekoyume/Assets/_Scripts/Analyzer.cs
  nekoyume/Assets/_Scripts/Extensions/GraphQlHttpClientExtensions.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Planet/PlanetContext.cs
  nekoyume/Assets/_Scripts/Planet/PlanetRegistry.cs
  nekoyume/Assets/_Scripts/Planet/PlanetRegistry.cs.meta
  nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs
  nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Large

#3453 fix seasonpass obj hide when worldboss practicemode
  nekoyume/Assets/_Scripts/UI/Widget/Popup/WorldBossResultPopup.cs
Labels: Extra Small

#3448 Update Rune Stone Icon Add
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/RUNESTONE_STUN.png
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/RUNESTONE_STUN.png.meta
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/RUNESTONE_VAMPIRIC.png
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/RUNESTONE_VAMPIRIC.png.meta
Labels: Medium

#3471 change concurrency group to github.ref_name from github.ref
  .github/workflows/android-build-and-release.yml
  .github/workflows/build.yml
Labels: Extra Small

#3472 fix PrepareClaimItems about update avatar state and handling crystal
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
Labels: Extra Small

#3474 prepare 90.0.7
  .github/workflows/android-build-and-release.yml
  .github/workflows/build.yml
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs
Labels: Extra Small

#3476 fix ClaimItems rendering and patrol reward mail
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Extensions/MailExtensions.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
Labels: Small

#3477 fix UpdateAgentStateAsync invoking with run on thread pool
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
Labels: Extra Small

#3478 UI/customizing edit
  nekoyume/Assets/AddressableAssets/Character/Parts/ear_skin.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Parts/ear_skin.json
  nekoyume/Assets/AddressableAssets/Character/Parts/ear_skin.png
  nekoyume/Assets/Resources/ScriptableObject/UI_CostumeColor.asset
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Login.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_LoginDetail.spriteatlas
  nekoyume/Assets/Resources/UI/Prefabs/ColorSelectView.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginDetail.prefab
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Customizing_List_4.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Customizing_List_4.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Customizing_List_5.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Customizing_List_5.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Customizing_List_6.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Customizing_List_6.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Customizing_List_7.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Customizing_List_7.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/UI_box_gold_01.png
  nekoyume/Assets/UIResources/Content/Shop/Prefab/TabButton_Character.prefab
  nekoyume/Assets/_Scripts/EnumType/ColorSelectType.cs
  nekoyume/Assets/_Scripts/UI/Login/ColorSelectView.cs
  nekoyume/Assets/_Scripts/UI/Login/LoginDetailCostume.cs
  nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
Labels: Extra Large

#3480 fix default language and using system language
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Helper/CommandLineOptions.cs
Labels: Extra Small

#3481 Feature/tutorial edit add for tutorial edit
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
  nekoyume/Assets/StreamingAssets/Localization/tutorial.csv
Labels: Large

#3484 fix wrong text
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/tutorial.csv
Labels: Extra Small

#3485 UI/polishing 231115
  nekoyume/Assets/Resources/UI/Animations/ConditionalButton_Type4.controller
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopListPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SweepResultPopup.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Button_Tab_bg_Normal_06.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Button_Tab_bg_Normal_06.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/icon_ability_01_black.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/icon_ability_01_black.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Discount_Bg_2.png
  nekoyume/Assets/UIResources/Content/Shop/Prefab/TabButton_Main.prefab
  nekoyume/Assets/UIResources/Content/Shop/Prefab/TabButton_Sub.prefab
Labels: Extra Large

#3482 unlock texture DownloadTextureRaw mipmap limit
  nekoyume/Assets/_Scripts/Helper/Util.cs
Labels: Extra Small

#3483 change battle result show button by stage clear
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
Labels: Extra Small

#3479 add fallback font and debug log
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceClient.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
  nekoyume/Assets/TextMesh Pro/Resources/TMP Settings.asset
Labels: Extra Small

#3488 improve tutorial
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_Summon.prefab
  nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs
  nekoyume/Assets/_Scripts/UI/Module/EnhancementInventory.cs
  nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
  nekoyume/Assets/_Scripts/UI/Scroller/EnhancementInventoryCell.cs
  nekoyume/Assets/_Scripts/UI/Scroller/EnhancementInventoryScroll.cs
  nekoyume/Assets/_Scripts/UI/Scroller/InventoryCell.cs
  nekoyume/Assets/_Scripts/UI/Scroller/InventoryScroll.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
Labels: Small

#3490 Fix item tooltip layout
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_Navigation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ConsumableTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CostumeTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_EquipmentTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MaterialTooltip.prefab
Labels: Extra Large

#3489 Fix loginSystem background
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
  nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
Labels: Extra Small

#3491 add conditional accessor to planetContext
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Extra Small

#3495 fix ui label
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#3498 UI/polishing 231115 2
  nekoyume/Assets/AddressableAssets/UI/Module/WorldMap/WorldButton.prefab
  nekoyume/Assets/Resources/Images/npc/NPC_01.png
  nekoyume/Assets/Resources/Images/npc/NPC_02.png
  nekoyume/Assets/Resources/Images/npc/NPC_03.png
  nekoyume/Assets/Resources/Images/npc/NPC_04.png
  nekoyume/Assets/Resources/Images/npc/NPC_05.png
  nekoyume/Assets/Resources/Images/npc/NPC_06.png
  nekoyume/Assets/Resources/Images/npc/NPC_07.png
  nekoyume/Assets/Resources/Images/npc/NPC_08.png
  nekoyume/Assets/Resources/Images/npc/NPC_09.png
  nekoyume/Assets/Resources/Images/npc/NPC_10.png
  nekoyume/Assets/Resources/Images/npc/NPC_11.png
  nekoyume/Assets/Resources/Images/npc/NPC_12.png
  nekoyume/Assets/Resources/Images/npc/NPC_13.png
  nekoyume/Assets/Resources/Images/npc/NPC_14.png
  nekoyume/Assets/Resources/Images/npc/NPC_15.png
  nekoyume/Assets/Resources/Images/npc/NPC_16.png
  nekoyume/Assets/Resources/Images/npc/NPC_17.png
  nekoyume/Assets/Resources/Images/npc/NPC_18.png
  nekoyume/Assets/Resources/Images/npc/NPC_19.png
  nekoyume/Assets/Resources/Images/npc/NPC_20.png
  nekoyume/Assets/Resources/Images/npc/NPC_21.png
  nekoyume/Assets/Resources/Images/npc/NPC_22.png
  nekoyume/Assets/Resources/Images/npc/NPC_23.png
  nekoyume/Assets/Resources/Images/npc/NPC_24.png
  nekoyume/Assets/Resources/Images/npc/NPC_25.png
  nekoyume/Assets/Resources/Images/npc/NPC_26.png
  nekoyume/Assets/Resources/Images/npc/NPC_27.png
  nekoyume/Assets/Resources/Images/npc/NPC_28.png
  nekoyume/Assets/Resources/Images/npc/NPC_29.png
  nekoyume/Assets/Resources/Images/npc/NPC_30.png
  nekoyume/Assets/Resources/Images/npc/NPC_31.png
  nekoyume/Assets/Resources/Images/npc/NPC_32.png
  nekoyume/Assets/Resources/Images/npc/NPC_33.png
  nekoyume/Assets/Resources/Images/npc/NPC_34.png
  nekoyume/Assets/Resources/Images/npc/NPC_35.png
  nekoyume/Assets/Resources/Images/npc/NPC_36.png
  nekoyume/Assets/Resources/Images/npc/NPC_37.png
  nekoyume/Assets/Resources/Images/npc/NPC_38.png
  nekoyume/Assets/Resources/Images/npc/NPC_39.png
  nekoyume/Assets/Resources/Images/npc/NPC_40.png
  nekoyume/Assets/Resources/Images/npc/NPC_41.png
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_BattleResult.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Combination.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Rune.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Shop.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldBoss.spriteatlas
  nekoyume/Assets/Resources/UI/Animations/UIDialogController@Show.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_DialogPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/ui_dialog_arrow.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/ui_dialog_arrow.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/ui_dialog_bg.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/ui_dialog_bg.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/ui_dialog_name_bg.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/ui_dialog_name_bg.png.meta
  nekoyume/Assets/UIResources/Font/Black Drama SDF Material - WorldmapClose.mat
Labels: Extra Large

#3496 Bug worldboss info
  nekoyume/Assets/StreamingAssets/Localization/worldboss_info.csv
Labels: Extra Small

#3500 fix various prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/MailCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/QuestCell.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Alert.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattle.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_InviteFriendsPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MailPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SpeechBubble.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SpeechBubbleWithItem.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Medium

#3501 add sfx to all receive popup
  nekoyume/Assets/_Scripts/UI/Widget/Screen/MailRewardScreen.cs
Labels: Extra Small

#3502 fix UI_AvatarInfoPopup for parsing yaml
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
Labels: Extra Small

#3505 Feature/iap service price change
  nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
  nekoyume/Assets/TextMesh Pro/Resources/TMP Settings.asset
  nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ShopListPopup.cs
Labels: Extra Small

#3506 rollback create widget timing
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#3509 apply planet id to get iap product
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Editor/IAPServiceToolWindow.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceClient.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
  nekoyume/Assets/_Scripts/Extensions/MailExtensions.cs
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
Labels: Extra Small

#3511 fix localization text
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/help_popup.csv
  nekoyume/Assets/StreamingAssets/Localization/notification.csv
  nekoyume/Assets/StreamingAssets/Localization/speech_bubble.csv
  nekoyume/Assets/StreamingAssets/Localization/tutorial.csv
Labels: Medium

#3508 UI/polishing 231116
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/RankCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/ShopListCell.prefab
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
  nekoyume/Assets/Resources/UI/Prefabs/EquipDesc.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattleResultPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopListPopup.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/AuraResourecs/aura_02_blue_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/AuraResourecs/aura_02_green_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/AuraResourecs/aura_02_violet_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/AuraResourecs/aura_02_yellow_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_01_blue_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_02_blue_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_02_violet_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_02_yellow_03.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Rank/Rank_bg_10.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Rank/Rank_bg_10.png.meta
  nekoyume/Assets/UIResources/Content/Shop/Prefab/TabButton_Sub.prefab
  nekoyume/Assets/_Scenes/uiTest_Grade.unity
Labels: Extra Large

#3512 adjust scroller width
  nekoyume/Assets/_Scripts/Helper/Util.cs
  nekoyume/Assets/_Scripts/UI/Scroller/EnhancementInventoryScroll.cs
  nekoyume/Assets/_Scripts/UI/Scroller/EnhancementSelectedMaterialItemScroll.cs
  nekoyume/Assets/_Scripts/UI/Scroller/InventoryScroll.cs
Labels: Extra Small

#3514 edit tutorial dialog positon and text
  nekoyume/Assets/Resources/Tutorial/Data/BattleTutorial.csv
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
Labels: Large

#3520 hide price tag while loading
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ShopListPopup.cs
Labels: Extra Small

#3519 UI/seasonpass edit 231116
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPass.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPassPremiumPopup.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_SeasonPass/Icon_Seasonpass_s_1.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_SeasonPass/Icon_Seasonpass_s_2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_SeasonPass/Icon_Seasonpass_s_3.png
Labels: Extra Large

#3523 fix: camera aspect on iOS
  nekoyume/Assets/_Scripts/Game/ActionCamera.cs
  nekoyume/Assets/_Scripts/Game/RaidCamera.cs
Labels: Extra Small

#3530 Bugfix/many tutorial
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBoss.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossDetail.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
Labels: Large

#3525 remove Testcode
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
Labels: Extra Small

#3529 Update Aura Name Change
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
Labels: Extra Small

#3528 Delete GameConfig from lib9c
  nekoyume/Assets/_Scripts/UI/Model/InventoryItem.cs
  nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentSlot.cs
Labels: Small

#3527 Fix WorldBoss Timeline Spine animation
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_Appear.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_FallDown_Defeat.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_FallDown_Victory.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_RunAway_1.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_RunAway_2.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_RunAway_3.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_RunAway_4.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_Skill.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_Skill_Bite.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_Skill_Claw.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_Skill_Enrage.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_Skill_Wrath.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_FallDown_Defeat.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_FallDown_Victory.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_RunAway_1.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_RunAway_2.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_RunAway_3.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_RunAway_4.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_Skill_Corrosion.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_Skill_Enrage.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_Skill_Fury.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_Skill_Multistrike.playable
Labels: Extra Large

#3535 fix wrong find product for render
  nekoyume/Assets/_Scripts/Extensions/MailExtensions.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
Labels: Small

#3538 fix iap product render issue
  nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs
Labels: Extra Small

#3540 season pass apple purchase fix
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs
Labels: Extra Small

#3542 handle non tradable item locallayer at receive all
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
Labels: Extra Small

#3539 edit battle tutorial & seasonpass image l10n
  nekoyume/Assets/Resources/Tutorial/Data/BattleTutorial.csv
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#3541 Bugfix/iap purchase mailbox setting
  nekoyume/Assets/Resources/UI/Prefabs/UI_MailRewardScreen.prefab
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Extensions/MailExtensions.cs
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/MailRewardScreen.cs
Labels: Small

#3547 fix text
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#3548 change seassonpass new popup flow
  nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassCouragePopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassCouragePopup.cs.meta
Labels: Extra Small

#3536 [PDX-137]fix: edge case of pledge
  nekoyume/Assets/_Scripts/Extensions/GraphQlHttpClientExtensions.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/GraphQL/GraphTypes/AgentAndPledgeGraphType.cs
  nekoyume/Assets/_Scripts/GraphQL/GraphTypes/AgentAndPledgeGraphType.cs.meta
  nekoyume/Assets/_Scripts/GraphQL/GraphTypes/PledgeGraphType.cs
  nekoyume/Assets/_Scripts/GraphQL/GraphTypes/PledgeGraphType.cs.meta
  nekoyume/Assets/_Scripts/Planet/PlanetAccountInfo.cs
  nekoyume/Assets/_Scripts/Planet/PlanetContext.cs
  nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs
  nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Large

#3550 Log table sync
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Game/TableSheets.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#3543 remove delay(*1.15) interval about push noti
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Extra Small

#3537 Fix arena prefab
  nekoyume/Assets/Resources/Audio/Sfx/Prefabs/sfx_arenabattleloading.prefab
  nekoyume/Assets/Resources/Audio/Sfx/Prefabs/sfx_arenabattleloading.prefab.meta
  nekoyume/Assets/Resources/Audio/Sfx/clips/sfx_arenabattleloading.wav
  nekoyume/Assets/Resources/Audio/Sfx/clips/sfx_arenabattleloading.wav.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossResultPopup.prefab
  nekoyume/Assets/_Scripts/Game/Controller/AudioController.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/RankingBattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/ArenaBattleLoadingScreen.cs
Labels: Medium

#3551 Feature/l10n improve
  nekoyume/Assets/AddressableAssets/UI/Module/EnhancementInventory.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopSell.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBoss.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/elemental_type.csv
  nekoyume/Assets/_Scripts/UI/Module/EnhancementInventory.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs
Labels: Large

#3557 fix text
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small
