Repository planetarium/NineChronicles, pull requests merged in 2023-09, with the labels that each got.

#2966 skip setting password
  nekoyume/Assets/Editor/KeyStoreEditor.cs
  nekoyume/Assets/Editor/KeyStoreEditor.cs.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Helper/KeyStoreHelper.cs
  nekoyume/Assets/_Scripts/Helper/KeyStoreHelper.cs.meta
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SettingPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
Labels: Extra Large

#2970 [Fix] L10nManager filename split error
  nekoyume/Assets/_Scripts/L10n/L10nManager.cs
Labels: Extra Small

#2972 Fast track/50.1.0
  nekoyume/Assets/Editor/KeyStoreEditor.cs
  nekoyume/Assets/Editor/KeyStoreEditor.cs.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Helper/KeyStoreHelper.cs
  nekoyume/Assets/_Scripts/Helper/KeyStoreHelper.cs.meta
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SettingPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Large

#2973 Fast track/50.1.0 into development
  nekoyume/Assets/Editor/KeyStoreEditor.cs
  nekoyume/Assets/Editor/KeyStoreEditor.cs.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Helper/KeyStoreHelper.cs
  nekoyume/Assets/_Scripts/Helper/KeyStoreHelper.cs.meta
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SettingPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Large

#2974 Feature/aura battle
  nekoyume/Assets/Resources/Character/Avatar.prefab
  nekoyume/Assets/Resources/ScriptableObject/VFX_Aura.asset
  nekoyume/Assets/Resources/ScriptableObject/VFX_Aura.asset.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_FriendInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RaidPreparation.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_blue_01.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_blue_02.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_blue_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_green_01.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_green_02.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_green_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_violet_01.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_violet_02.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_violet_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_yellow_01.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_yellow_02.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_yellow_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_blue_01.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_blue_02.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_blue_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_green_01.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_green_02.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_green_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_violet_01.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_violet_02.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_violet_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_yellow_01.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_yellow_02.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_yellow_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_event_blue_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_event_green_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_event_violet_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_event_white_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_event_yellow_03.prefab
  nekoyume/Assets/_Scripts/Game/Avatar/AvatarSpineController.cs
  nekoyume/Assets/_Scripts/Game/Character/CharacterAppearance.cs
  nekoyume/Assets/_Scripts/Game/Character/Player.cs
  nekoyume/Assets/_Scripts/Game/Entrance/NestEntering.cs
  nekoyume/Assets/_Scripts/Game/Factory/PlayerFactory.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/AuraScriptableObject.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/AuraScriptableObject.cs.meta
  nekoyume/Assets/_Scripts/Helper/ResourcesHelper.cs
  nekoyume/Assets/_Scripts/UI/Model/InventoryItem.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentSlot.cs
Labels: Extra Large

#2984 add aura in upgrade inventory
  nekoyume/Assets/AddressableAssets/UI/Module/EnhancementInventory.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
Labels: Small

#2991 Add .gitallowed for git secrets
  .gitallowed
Labels: Extra Small

#2994 Feature/aura effect rendering
  nekoyume/Assets/Resources/UI/Materials/SpineCharacterRenderTexture.mat
  nekoyume/Assets/Resources/UI/Materials/SpineCharacterRenderTexture.mat.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_FriendInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RaidPreparation.prefab
  nekoyume/Assets/Resources/UI/Shaders/AdditiveAlphaBlend.shader
  nekoyume/Assets/Resources/UI/Shaders/AdditiveAlphaBlend.shader.meta
Labels: Medium

#2996 increase rpc reconnection attempt count from `20` to `50`
  nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
Labels: Extra Small

#2997 change avatar effect refresh rate (don't refersh when equip same equi…
  nekoyume/Assets/_Scripts/Game/Avatar/AvatarSpineController.cs
  nekoyume/Assets/_Scripts/Game/Character/CharacterAppearance.cs
Labels: Extra Small

#3002 change new skill description
  nekoyume/Assets/_Scripts/UI/Module/Common/SkillPositionTooltip.cs
  nekoyume/Assets/_Scripts/UI/Module/Stat/EnhancementSkillOptionView.cs
Labels: Extra Small

#3008 Improve/intro UI
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Large

#3013 Fix/qr back
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Extra Large

#3014 Fast track/50.3.0
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Extra Large

#3015 bugfix Enhancement effect
  nekoyume/Assets/_Scripts/Game/Avatar/AvatarSpineController.cs
  nekoyume/Assets/_Scripts/Game/Character/CharacterAppearance.cs
Labels: Extra Small

#3018 chore: add lock object to shop menu ui
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/ShopBtn.prefab
Labels: Extra Large

#3020 fix: change mp4 to webm about aura
  nekoyume/Assets/Resources/UI/Prefabs/UI_SummonResultPopup.prefab
  nekoyume/Assets/Resources/Video/Summon_GoldenAura_1.mp4.meta
  nekoyume/Assets/Resources/Video/Summon_GoldenAura_1.webm.meta
  nekoyume/Assets/Resources/Video/Summon_GoldenAura_2.mp4.meta
  nekoyume/Assets/Resources/Video/Summon_GoldenAura_2.webm.meta
  nekoyume/Assets/Resources/Video/Summon_NormalAura_1.mp4.meta
  nekoyume/Assets/Resources/Video/Summon_NormalAura_1.webm.meta
  nekoyume/Assets/Resources/Video/Summon_NormalAura_2.mp4.meta
  nekoyume/Assets/Resources/Video/Summon_NormalAura_2.webm.meta
Labels: Small

#3021 feat: consider StakeStateV2 in client
  nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Blockchain/Agent.cs
  nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
  nekoyume/Assets/_Scripts/Extensions/StakeStateUtilsForClient.cs
  nekoyume/Assets/_Scripts/Extensions/StakeStateUtilsForClient.cs.meta
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Medium

#3023 bugfix aura equipmenet bug when equip costume
  nekoyume/Assets/_Scripts/Game/Character/CharacterAppearance.cs
Labels: Extra Small

#3022 bugfix enhancement matrialscrollview position refresh limit
  nekoyume/Assets/_Scripts/UI/Scroller/GridScroll.cs
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
Labels: Extra Small

#3027 fix conditionalCostButton legacy functional
  nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalCostButton.cs
Labels: Extra Small

#3026 Update UI for summon count bonus
  nekoyume/Assets/Resources/UI/Animations/UI_SummonResult@Hide.anim
  nekoyume/Assets/Resources/UI/Animations/UI_SummonResult@Normal.anim
  nekoyume/Assets/Resources/UI/Animations/UI_SummonResult@ShowButton.anim
  nekoyume/Assets/Resources/UI/Animations/UI_SummonResultPopup.controller
  nekoyume/Assets/Resources/UI/Prefabs/UI_SummonResultPopup.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Screen/SummonResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Summon.cs
Labels: Extra Large

#3028 bugfix endhancement skill description
  nekoyume/Assets/_Scripts/UI/Module/Stat/EnhancementSkillOptionView.cs
Labels: Extra Small

#3032 player place renderoder and position change
  nekoyume/Assets/Resources/Prefab/PlayerPlace.prefab
Labels: Extra Small

#3030 fix StakingPopup and bump lib9c:release/1.1.0
  nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Blockchain/Agent.cs
  nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Medium

#3036 chore: add golddust image
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust01_EN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust01_EN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust01_PT.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust01_PT.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust01_ZH-CN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust01_ZH-CN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust02_EN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust02_EN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust02_PT.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust02_PT.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust02_ZH-CN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust02_ZH-CN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust03_EN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust03_EN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust03_PT.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust03_PT.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust03_ZH-CN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust03_ZH-CN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust04_EN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust04_EN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust04_PT.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust04_PT.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust04_ZH-CN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust04_ZH-CN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust05_EN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust05_EN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust05_PT.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust05_PT.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust05_ZH-CN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust05_ZH-CN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust06_EN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust06_EN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust06_PT.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust06_PT.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust06_ZH-CN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust06_ZH-CN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust07_EN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust07_EN.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust07_PT.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust07_PT.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust07_ZH-CN.png
  nekoyume/Assets/Resources/UI/Textures/00_Shop/PKG_single_golddust07_ZH-CN.png.meta
Labels: Extra Large

#3037 fix recipe skillOption ratio
  nekoyume/Assets/_Scripts/UI/Module/Stat/RecipeOptionView.cs
Labels: Extra Small

#3038 Update GAME START L10n Change
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#3040 Fix submit button font asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
Labels: Extra Large

#3043 fix: scroller to scroll rect at MobileShop
  nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
Labels: Extra Small

#3044 fix font setting
  nekoyume/Assets/AddressableAssets/UI/Module/Skill/SkillView_Enhancement.prefab
Labels: Extra Small

#3048 fix: add conditional access to GameConfigState
  nekoyume/Assets/_Scripts/UI/Module/Currency/ActionPoint.cs
  nekoyume/Assets/_Scripts/UI/Module/Currency/DailyBonus.cs
Labels: Extra Small

#3047 fix: change mobile shop price to iso currency code
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
Labels: Extra Small

#3046 fix: use `BlockChainService.GetBlockHash` instead of GQL
  nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
Labels: Extra Small

#3050 fix: consider staking contract in StakingPopup
  nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
  nekoyume/Assets/_Scripts/Blockchain/Agent.cs
  nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/State/Subjects/StakingLevelSubject.cs
  nekoyume/Assets/_Scripts/State/Subjects/StakingSubject.cs
  nekoyume/Assets/_Scripts/State/Subjects/StakingSubject.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Large

#3053 fix grind Inventory best item notification
  nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
Labels: Extra Small

#3055 fix AndroidBundleVersionCode 52->53
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#3054 Merge prepare/60.0.0 into release/60.0.0
  nekoyume/Assets/AddressableAssets/UI/Module/Skill/SkillView_Enhancement.prefab
  nekoyume/Assets/Resources/HelpPopupData/Sprites/result_28_Summon.png
  nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
  nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Blockchain/Agent.cs
  nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
  nekoyume/Assets/_Scripts/State/LocalLayerModifier.cs
  nekoyume/Assets/_Scripts/State/Modifiers/AvatarInventoryNonFungibleItemRemover.cs
  nekoyume/Assets/_Scripts/State/Modifiers/AvatarInventoryNonFungibleItemRemover.cs.meta
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/State/Subjects/StakingLevelSubject.cs
  nekoyume/Assets/_Scripts/State/Subjects/StakingSubject.cs
  nekoyume/Assets/_Scripts/State/Subjects/StakingSubject.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/Currency/ActionPoint.cs
  nekoyume/Assets/_Scripts/UI/Module/Currency/DailyBonus.cs
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
  nekoyume/Assets/_Scripts/UI/Module/Inventory.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Large

#3057 fix: disable signin button
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Extra Small

#3058 Prepare/60.0.0
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#3059 Bugfix/stake state
  nekoyume/Assets/_Scripts/State/States.cs
Labels: Extra Small

#3060 Prepare/60.0.0
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_green_03.prefab
  nekoyume/Assets/_Scripts/State/States.cs
Labels: Extra Small

#3061 chore: update android bundle version to 55
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#3063 Cherry-pick pull request #3057 into fast-track/50.4.0
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Extra Small

#3064 Cherry-pick pull request #3047 into fast-track/50.4.0
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
Labels: Extra Small

#3066 fix tutorial guide highlighting
  nekoyume/Assets/Editor/TutorialTestingEditor.cs
  nekoyume/Assets/Editor/TutorialTestingEditor.cs.meta
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.json
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
Labels: Large

#3062 fix: uniqueId to uuid
  nekoyume/Assets/_Scripts/Analyzer.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Extra Small

#3070 fix: add FirebaseAnalytics.SetUserId
  nekoyume/Assets/_Scripts/Analyzer.cs
Labels: Extra Small

#3071 fix: set GoogleSigninBehaviour state to Canceled when task fault
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/_Scripts/Game/OAuth/GoogleSigninBehaviour.cs
Labels: Extra Small

#3073 Introduce BattleTutorialController
  nekoyume/Assets/Editor/TutorialTestingEditor.cs
  nekoyume/Assets/Resources/Tutorial/Data/BattleTutorial.csv
  nekoyume/Assets/Resources/Tutorial/Data/BattleTutorial.csv.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
  nekoyume/Assets/StreamingAssets/Localization/tutorial.csv
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/BattleTutorialController.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/BattleTutorialController.cs.meta
  nekoyume/Assets/_Scripts/UI/Tutorial/GuideDialog.cs
  nekoyume/Assets/_Scripts/UI/Widget/Base/Widget.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tutorial.cs
Labels: Medium

#3075 fix: fix animation about battle tutorial controller
  nekoyume/Assets/Resources/UI/Animations/DialogBoxSmall@Show.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
  nekoyume/Assets/_Scripts/Game/Stage.cs
Labels: Extra Small

#3076 chore: update app bundleVersion to 50.4.0
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#3077 fix battle tutorial bug
  nekoyume/Assets/_Scripts/UI/Widget/Tutorial.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#3082 add patrol reward push notification
  nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab
  nekoyume/Assets/_Scripts/PushNotifier.cs
  nekoyume/Assets/_Scripts/Settings.cs
  nekoyume/Assets/_Scripts/UI/Model/PatrolReward.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SettingPopup.cs
Labels: Extra Large

#3084 add MoblieShop L10N Key
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#3086 Update 200090 L10n Add
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
  nekoyume/Assets/StreamingAssets/Localization/skill_description.csv
  nekoyume/Assets/StreamingAssets/Localization/skill_name.csv
Labels: Small

#3088 Feature/open nornal aura
  nekoyume/Assets/Resources/UI/Prefabs/UI_Summon.prefab
  nekoyume/Assets/_Scripts/UI/Module/Lobby/PatrolRewardMenu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/PatrolRewardPopup.cs
Labels: Small

#3089 add costume data
  nekoyume/Assets/Resources/ScriptableObject/Avatar.asset
Labels: Extra Small

#3090 Guest login per platform/version
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Extra Small

#3091 Update ProjectSettings.asset
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#3092 fix grid sort order
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
Labels: Extra Small

#3093 fix costume error
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100015/40100015.json
Labels: No Changes

#3094 Fix patrol reward model
  nekoyume/Assets/_Scripts/UI/Model/PatrolReward.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/PatrolRewardMenu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/PatrolRewardPopup.cs
Labels: Small

#3095 Delete dummy code for test
  nekoyume/Assets/_Scripts/UI/Module/Lobby/PatrolRewardMenu.cs
Labels: Extra Small

#3096 fix mailbox notification rule
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
Labels: Extra Small

#3097 Prepare/70.0.0 to Release/70.0.0
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100015/40100015.json
  nekoyume/Assets/_Scripts/UI/Model/PatrolReward.cs
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/PatrolRewardMenu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/PatrolRewardPopup.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Small

#3099 60.0.1 merge dev
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#3100 add battle animation acceleration feature
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_BattleResult.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Combination.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Item.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Rune.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Shop.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldBoss.spriteatlas
  nekoyume/Assets/Resources/UI/Prefabs/UI_Battle.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Icon_DoubleSpeed.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Icon_DoubleSpeed.png.meta
  nekoyume/Assets/_Scenes/Game.unity
  nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs
  nekoyume/Assets/_Scripts/Game/Character/Enemy.cs
  nekoyume/Assets/_Scripts/Game/Character/Player.cs
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/UI/Widget/Base/Widget.cs
  nekoyume/Assets/_Scripts/UI/Widget/Battle.cs
Labels: Large

#3117 chore: add analyzer tracking about synopsis skip
  nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
Labels: Extra Small

#3114 Redesign contents unlock UI
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/MenuOpen_Obj.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CelebratesPopup.prefab
  nekoyume/Assets/_Scripts/Game/Stage.cs
Labels: Extra Large

#3118 Improve/tutorial etc
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.json
  nekoyume/Assets/StreamingAssets/Localization/tutorial.csv
  nekoyume/Assets/_Scripts/UI/Widget/Battle.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tutorial.cs
Labels: Extra Small

#3122 enable animation accel button at tutorial
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/button_Round_Normal.png
  nekoyume/Assets/_Scripts/UI/Widget/Battle.cs
Labels: Extra Small

#3116 fix: change all receive button condition
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
Labels: Extra Small

#3115 fix mobile shop item tooltip and itemvisible
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopListPopup.prefab
  nekoyume/Assets/_Scripts/UI/Module/IAP/IAPRewardView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ShopListPopup.cs
Labels: Large

#3120 Edit Levelup vfx, animation time
  nekoyume/Assets/Resources/UI/Animations/UILevelUpCelebratePopup@Show.anim
  nekoyume/Assets/_Scripts/Game/VFX/LevelUpVFX.cs
Labels: Small

#3125 add loadingScreen when download detail productBgImages
  nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
  nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ShopListPopup.cs
Labels: Large

#3126 chore: update app bundle version to 60.1.0
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small
