Repository planetarium/NineChronicles, pull requests merged in 2023-10, with the labels that each got.

#3131 fix: remove disabling unity logger
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Extra Small

#3136 remove disabling unity logger
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Extra Small

#3140 Hotfix/60.2.0
  nekoyume/Assets/_Scripts/UI/Tutorial/GuideArrow.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tutorial.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#3141 Hotfix/60.2.0 into prepare/70.0.0
  nekoyume/Assets/_Scripts/UI/Tutorial/GuideArrow.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tutorial.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#3139 Fix battle result popup
  nekoyume/Assets/AddressableAssets/UI/Module/Reward/BattleReward.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattleResultPopup.prefab
  nekoyume/Assets/_Scripts/UI/Module/BattleReward.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
Labels: Large

#3142 `prepare/70.0.0` to `release/70.0.0` (rc5)
  nekoyume/Assets/AddressableAssets/UI/Module/Reward/BattleReward.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattleResultPopup.prefab
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Module/BattleReward.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/GuideArrow.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tutorial.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Large

#3145 fix ShopListCell.prefab mask issue
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/ShopListCell.prefab
Labels: Extra Small

#3153 fix: several side effects on non-rpc play with `libplanet 3.4.0`
  nekoyume/Assets/_Scripts/Blockchain/StateGetter.cs
Labels: bug

#3072 feat: render `ClaimItems`, `TransferAssets`
  nekoyume/Assets/Plugins/StateViewer/Editor/Features/StateAndBalanceFeature.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionTimeoutException.cs
  nekoyume/Assets/_Scripts/Blockchain/ErrorCode.cs
  nekoyume/Assets/_Scripts/State/LocalLayer.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
Labels: Large

#3137 Update LoadingScreen
  nekoyume/Assets/AddressableAssets/UI/Module/LoadingModule.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/LoadingModule.prefab.meta
  nekoyume/Assets/Resources/SpriteAtlases/Background/Loading.spriteatlas
  nekoyume/Assets/Resources/UI/Animations/LoadingImageContainerController@Idle.anim
  nekoyume/Assets/Resources/UI/Animations/LoadingImageContainerController@Start.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_DataLoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_DataLoadingScreen.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_GrayLoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoadingScreen.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_StageLoadingEffect.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_UnlockWorldLoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMapLoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMapLoadingScreen.prefab.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Common_Gradiant_bg_02.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Common_Gradiant_bg_02.png.meta
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Module/LoadingModule.cs
  nekoyume/Assets/_Scripts/UI/Module/LoadingModule.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaJoin.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/DataLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/DataLoadingScreen.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/LoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/PreloadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/UnlockWorldLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/UnlockWorldLoadingScreen.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Screen/WorldMapLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/WorldMapLoadingScreen.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
  nekoyume/Assets/_Scripts/UI/Widget/StageLoadingEffect.cs
  nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs
Labels: Extra Large

#3242 result improve into 70.3.0
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfo.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfoSessionProgressFill.mat
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/SimpleCountableItemView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/VanillaItemView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Reward/BattleReward.prefab
  nekoyume/Assets/Resources/UI/Animations/CP_Up@Loop.anim
  nekoyume/Assets/Resources/UI/Animations/CP_Up@Loop.anim.meta
  nekoyume/Assets/Resources/UI/Animations/List_1.controller
  nekoyume/Assets/Resources/UI/Animations/List_1.controller.meta
  nekoyume/Assets/Resources/UI/Animations/UIBattleResultController@Show.anim
  nekoyume/Assets/Resources/UI/Animations/VictoryImageContainerController.controller
  nekoyume/Assets/Resources/UI/Animations/VictoryImageContainerController@BoosterIdle.anim
  nekoyume/Assets/Resources/UI/Animations/VictoryImageContainerController@BoosterImpact.anim
  nekoyume/Assets/Resources/UI/Animations/VictoryImageContainerController@GoodIdle.anim
  nekoyume/Assets/Resources/UI/Animations/VictoryImageContainerController@GoodImpact.anim
  nekoyume/Assets/Resources/UI/Animations/VictoryImageContainerController@GreatIdle.anim
  nekoyume/Assets/Resources/UI/Animations/VictoryImageContainerController@GreatImpact.anim
  nekoyume/Assets/Resources/UI/Animations/VictoryImageContainerController@PerfectIdle.anim
  nekoyume/Assets/Resources/UI/Animations/VictoryImageContainerController@PerfectImpact.anim
  nekoyume/Assets/Resources/UI/Icons/Navigation/icon_Navigation_009.png
  nekoyume/Assets/Resources/UI/Icons/Navigation/icon_Navigation_009.png.meta
  nekoyume/Assets/Resources/UI/Icons/Navigation/icon_Navigation_010.png
  nekoyume/Assets/Resources/UI/Icons/Navigation/icon_Navigation_010.png.meta
  nekoyume/Assets/Resources/UI/Icons/Navigation/icon_Navigation_011.png
  nekoyume/Assets/Resources/UI/Icons/Navigation/icon_Navigation_011.png.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattleResultPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_StageInformation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBoss.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossResultPopup.prefab
  nekoyume/Assets/Resources/UI/Textures/00_Result/UI_result_bg_2.png
  nekoyume/Assets/Resources/UI/Textures/00_Result/UI_result_bg_2.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Result/UI_result_bg_3.png
  nekoyume/Assets/Resources/UI/Textures/00_Result/UI_result_bg_3.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Result/UI_victory_star_1.png
  nekoyume/Assets/Resources/UI/Textures/00_Result/UI_victory_star_1.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Result/UI_victory_star_2.png
  nekoyume/Assets/Resources/UI/Textures/00_Result/UI_victory_star_2.png.meta
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_main_icon_Courage.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_main_icon_Courage.png.meta
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/RuneStoneItem.prefab
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/UI/Module/BattleReward.cs
  nekoyume/Assets/_Scripts/UI/Module/BattleReward.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
Labels: Extra Large

#3241 Improve tutorial scripting - json to SO
  nekoyume/Assets/Editor/TutorialPresetScriptableObjectEditor.cs
  nekoyume/Assets/Editor/TutorialPresetScriptableObjectEditor.cs.meta
  nekoyume/Assets/Editor/TutorialScenarioScriptableObjectEditor.cs
  nekoyume/Assets/Editor/TutorialScenarioScriptableObjectEditor.cs.meta
  nekoyume/Assets/Resources/Tutorial/Data/TutorialPreset.asset
  nekoyume/Assets/Resources/Tutorial/Data/TutorialPreset.asset.meta
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset.meta
  nekoyume/Assets/_Scripts/Game/ScriptableObject/TutorialPresetScriptableObject.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/TutorialPresetScriptableObject.cs.meta
  nekoyume/Assets/_Scripts/Game/ScriptableObject/TutorialScenarioScriptableObject.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/TutorialScenarioScriptableObject.cs.meta
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
Labels: Extra Large

#3244 fix persistent data path on editor(android)
  nekoyume/Assets/_Scripts/PlatformUtility/Platform.cs
Labels: Extra Small

#3251 Update loading screen resources
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_BattleResult.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Combination.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Item.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Rune.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Shop.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldBoss.spriteatlas
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Textures/00_Loading/loading_adventure.png
  nekoyume/Assets/Resources/UI/Textures/00_Loading/loading_arena.png
  nekoyume/Assets/Resources/UI/Textures/00_Loading/loading_entering.png
  nekoyume/Assets/Resources/UI/Textures/00_Loading/loading_shop.png
  nekoyume/Assets/Resources/UI/Textures/00_Loading/loading_workshop.png
Labels: Medium

#3245 add letterbox clearing ScreenBoader
  nekoyume/Assets/Planetarium/Nekoyume/Editor/ScreenEditorMenus.cs
  nekoyume/Assets/Plugins/IngameDebugConsole/IngameDebugConsole.prefab
  nekoyume/Assets/Resources/UI/Textures/worldmap_bg_cover_480.png
  nekoyume/Assets/Resources/UI/Textures/worldmap_bg_cover_480.png.meta
  nekoyume/Assets/_Scenes/Game.unity
  nekoyume/Assets/_Scripts/Game/ActionCamera.cs
  nekoyume/Assets/_Scripts/Game/RaidCamera.cs
  nekoyume/Assets/_Scripts/Game/Util/IngameDebugConsoleCommands.cs
Labels: Extra Large

#3252 Fix Patrol Reward data NRE
  nekoyume/Assets/_Scripts/UI/Model/PatrolReward.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/PatrolRewardMenu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/PatrolRewardPopup.cs
Labels: Extra Small

#3250 implement upgrade/grind tutorial
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage.meta
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Arena_1.png
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Arena_1.png.meta
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Arena_2.png
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Arena_2.png.meta
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Grind_1.png
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Grind_1.png.meta
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Grind_2.png
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Grind_2.png.meta
  nekoyume/Assets/_Scripts/UI/Module/EnhancementInventory.cs
  nekoyume/Assets/_Scripts/UI/Widget/CombinationMain.cs
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
Labels: Extra Large

#3254 UI/loading position edit
  nekoyume/Assets/AddressableAssets/UI/Module/LoadingModule.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CombinationBtn.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_GrayLoadingScreen.prefab
  nekoyume/Assets/Sprites/Background/MainMenu/Event/3th.meta
  nekoyume/Assets/Sprites/Background/MainMenu/Event/3th/bg_3th_bg_01.png
  nekoyume/Assets/Sprites/Background/MainMenu/Event/3th/bg_3th_bg_01.png.meta
Labels: Large

#3256 Implement Arena, Upgrade, Grinding tutorial
  nekoyume/Assets/PostProcessing/OutlineGrow.mat
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Arena_1.png
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Arena_2.png
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Grind_1.png
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Grind_2.png
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Combination/UI_Combination_mainmenu_bg_01.png
  nekoyume/Assets/_Scripts/UI/Tutorial/Base/GuideDialogData.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/Base/TutorialScenario.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/GuideDialog.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/Type/DialogPositionType.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/Type/DialogPositionType.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tutorial.cs
Labels: Large

#3257 Add new tutorials for 70.3
  nekoyume/Assets/PostProcessing/OutlineGrow.mat
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.json
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage.meta
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Arena_1.png
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Arena_1.png.meta
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Arena_2.png
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Arena_2.png.meta
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Grind_1.png
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Grind_1.png.meta
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Grind_2.png
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Grind_2.png.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotsPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SuperCraftPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBoss.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossDetail.prefab
  nekoyume/Assets/StreamingAssets/Localization/tutorial.csv
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Combination/UI_Combination_mainmenu_bg_01.png
  nekoyume/Assets/_Scripts/Game/ScriptableObject/TutorialScenarioScriptableObject.cs
  nekoyume/Assets/_Scripts/UI/Module/EnhancementInventory.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/Base/GuideDialogData.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/Base/TutorialScenario.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/GuideDialog.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/Type/DialogPositionType.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/Type/DialogPositionType.cs.meta
  nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialActionType.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialTargetType.cs
  nekoyume/Assets/_Scripts/UI/Widget/CombinationMain.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tutorial.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldBoss.cs
Labels: Extra Large

#3258 feat: add locking ui of workshop
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/LockObjects.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/LockObjects.prefab.meta
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/PatrolBtn.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
  nekoyume/Assets/_Scripts/UI/Widget/CombinationMain.cs
Labels: Extra Large

#3263 feat: add UIOnClockSound to receive all button
  nekoyume/Assets/AddressableAssets/UI/Module/ReceiveArea.prefab
Labels: Extra Small

#3253 feat: `Planets` with `PlanetId`
  nekoyume/Assets/StreamingAssets/Localization/error.csv
  nekoyume/Assets/Tests/EditMode/Planet.meta
  nekoyume/Assets/Tests/EditMode/Planet/PlanetIdTest.cs
  nekoyume/Assets/Tests/EditMode/Planet/PlanetIdTest.cs.meta
  nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs
  nekoyume/Assets/_Scripts/Planet.meta
  nekoyume/Assets/_Scripts/Planet/PlanetId.Define.cs
  nekoyume/Assets/_Scripts/Planet/PlanetId.Define.cs.meta
  nekoyume/Assets/_Scripts/Planet/PlanetId.cs
  nekoyume/Assets/_Scripts/Planet/PlanetId.cs.meta
  nekoyume/Assets/_Scripts/Planet/PlanetIdJsonConverter.cs
  nekoyume/Assets/_Scripts/Planet/PlanetIdJsonConverter.cs.meta
  nekoyume/Assets/_Scripts/Planet/PlanetInfo.cs
  nekoyume/Assets/_Scripts/Planet/PlanetInfo.cs.meta
  nekoyume/Assets/_Scripts/Planet/Planets.cs
  nekoyume/Assets/_Scripts/Planet/Planets.cs.meta
Labels: Large

#3259 feat: initialize `PlanetContext` in `Game`
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Planet/PlanetContext.cs
  nekoyume/Assets/_Scripts/Planet/PlanetContext.cs.meta
  nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs
  nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs.meta
Labels: Medium

#3260 feat: select planet in `IntroScreen` UI
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Extra Large

#3262 Feature/tutorial 23 stage
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/ActionPoint.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/DailyBonusController.controller
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MaterialNavigationPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Rune.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SuperCraftPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBoss.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossDetail.prefab
  nekoyume/Assets/_Scripts/UI/Module/Currency/ActionPoint.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/Type/TutorialActionType.cs
  nekoyume/Assets/_Scripts/UI/Widget/CombinationMain.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MaterialNavigationPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
  nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
Labels: Large

#3269 add locking to ActionPoint and Rune menu
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
  nekoyume/Assets/_Scripts/UI/Module/Currency/ActionPoint.cs
Labels: Extra Small

#3267 fix clear screen boader in android platform
  nekoyume/Assets/_Scenes/Game.unity
  nekoyume/Assets/_Scripts/Game/Util/IngameDebugConsoleCommands.cs
Labels: Extra Small

#3266 Fix intro screen to image
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
  nekoyume/Assets/Resources/UI/Animations/Logo.controller
  nekoyume/Assets/Resources/UI/Animations/Logo.controller.meta
  nekoyume/Assets/Resources/UI/Animations/Logo@Loop.anim
  nekoyume/Assets/Resources/UI/Animations/Logo@Loop.anim.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MaterialNavigationPopup.prefab
  nekoyume/Assets/Resources/UI/Textures/00_Intro/title_loading.png
  nekoyume/Assets/Resources/UI/Textures/00_Intro/title_loading.png.meta
  nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs
  nekoyume/Assets/_Scripts/UI/Module/Currency/ActionPoint.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MaterialNavigationPopup.cs
Labels: Extra Large

#3268 refactor: `IAgent` initialization
  nekoyume/Assets/_Scripts/Blockchain/Agent.cs
  nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs
  nekoyume/Assets/_Scripts/Planet/Planets.cs
Labels: Small

#3273 feat: pledge with planets and more
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
  nekoyume/Assets/_Scripts/Game/OAuth/GoogleSigninBehaviour.cs
  nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs
  nekoyume/Assets/_Scripts/Planet/PlanetSelector.cs
  nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
  nekoyume/Packages/manifest.json
  nekoyume/Packages/packages-lock.json
Labels: Large

#3276 UI/screen ratio react
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_RuneListview.prefab
  nekoyume/Assets/Resources/UI/Animations/RightArrowButtonController@Normal.anim
  nekoyume/Assets/Resources/UI/Animations/UIWorldMap_StageController@Show.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBoard.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Grind.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Rune.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_StageInformation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/WorldMapWorld.prefab
Labels: Extra Large

#3275 UI/mail quest workshop popup edit
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/QuestCell.prefab
  nekoyume/Assets/Resources/UI/Animations/UIPopupController@Close.anim
  nekoyume/Assets/Resources/UI/Animations/UIPopupController@Show.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotsPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MailPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBoss.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossDetail.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Rank.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotsPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/QuestPopup.cs
Labels: Extra Large

#3277 Fix analyzer in tutorial
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
Labels: Extra Small

#3279 update `UI_IntroScreen` prefab
  nekoyume/Assets/Resources/UI/Animations/NewMark.controller
  nekoyume/Assets/Resources/UI/Animations/NewMark.controller.meta
  nekoyume/Assets/Resources/UI/Animations/NewMark2@Loop.anim
  nekoyume/Assets/Resources/UI/Animations/NewMark2@Loop.anim.meta
  nekoyume/Assets/Resources/UI/Animations/UIIntroScreenMobileController.controller
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Arrow.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Arrow.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Common_Gradiant_bg_01.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Common_Gradiant_bg_01.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Dot.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Dot.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Icon_Planet.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Icon_Planet.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/NewMark.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/NewMark.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/UI_PFP_Bg_1.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/UI_PFP_Bg_1.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/UI_bg_frame_03.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/UI_bg_frame_03.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/button_yellow_02.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/button_yellow_02.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/ui_line_06.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/ui_line_06.png.meta
Labels: Extra Large

#3280 cherry-picking #3279
  nekoyume/Assets/Resources/UI/Animations/NewMark.controller
  nekoyume/Assets/Resources/UI/Animations/NewMark.controller.meta
  nekoyume/Assets/Resources/UI/Animations/NewMark2@Loop.anim
  nekoyume/Assets/Resources/UI/Animations/NewMark2@Loop.anim.meta
  nekoyume/Assets/Resources/UI/Animations/UIIntroScreenMobileController.controller
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Arrow.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Arrow.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Common_Gradiant_bg_01.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Common_Gradiant_bg_01.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Dot.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Dot.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Icon_Planet.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Icon_Planet.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/NewMark.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/NewMark.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/UI_PFP_Bg_1.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/UI_PFP_Bg_1.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/UI_bg_frame_03.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/UI_bg_frame_03.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/button_yellow_02.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/button_yellow_02.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/ui_line_06.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/ui_line_06.png.meta
Labels: Extra Large

#3284 update: `UI_IntroScreen` prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
Labels: No Changes

#3285 cherry picking #3284
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
Labels: No Changes

#3282 Improve guide arrow position&rect size setting logic
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_Battle.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/_Scripts/UI/Tutorial/GuideArrow.cs
Labels: Large

#3286 Add new Structure to tutorial SO
  nekoyume/Assets/Editor/TutorialScenarioScriptableObjectEditor.cs
  nekoyume/Assets/Resources/Tutorial/Data/TutorialScenario.asset
  nekoyume/Assets/_Scripts/Game/ScriptableObject/TutorialScenarioScriptableObject.cs
Labels: Extra Large
