Repository planetarium/NineChronicles, pull requests merged in 2023-08, with the labels that each got.

#2701 Fix block time match
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfo.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/ArenaTickets.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/DailyBonus.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/EventDungeonTickets.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/WorldBossTickets.prefab
  nekoyume/Assets/Resources/UI/Prefabs/CombinationSlot.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotPopup.prefab
Labels: Extra Large

#2837 Add mixpanel track pledge success
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Extra Small

#2839 feat: change store option to Google from GoogleTest
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Extra Small

#2838 remove bg at dmx reader
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs
  nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Medium

#2840 Revert "feat: improve `UnloadFromMyGaragesRecipientMail` UI"
  .gitignore
  nekoyume/Assets/StreamingAssets/Localization/mail.csv
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Extensions/MailExtensions.cs
  nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Medium

#2841 chore: disable rayCastTarget of text at StakingPopup
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
Labels: Extra Small

#2844 revert #2840 and fix async
  .gitignore
  nekoyume/Assets/StreamingAssets/Localization/mail.csv
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs
  nekoyume/Assets/_Scripts/Extensions/MailExtensions.cs
  nekoyume/Assets/_Scripts/Helper/SpriteHelper.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Medium

#2842 release internal-20
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
  nekoyume/Assets/Resources/UI/Textures/icon_executable.png
  nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs
  nekoyume/Assets/_Scripts/Extensions/MailExtensions.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs
  nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Medium

#2845 Edit has result ui - ap not enough, failed
  nekoyume/Assets/Resources/UI/Animations/UIBattleResultController@Show.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattleResultPopup.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/StageInformation.cs
Labels: Extra Large

#2846 Fix block time ui space
  nekoyume/Assets/Resources/UI/Prefabs/CombinationSlot.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotsPopup.prefab
  nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotPopup.cs
Labels: Large

#2848 chore: reduce font size and change vertical alignment at LoginSystem
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
Labels: Extra Small

#2849 Fix broken l10n text
  nekoyume/Assets/Resources/Font/SDF/Portuguese SDF.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/_Scripts/L10n/Editor/L10nManagerEditor.cs
Labels: Medium

#2850 fix arena push notification content not matched
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Extra Small

#2851 Prepare/release 20
  nekoyume/Assets/Resources/Font/SDF/Portuguese SDF.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/L10n/Editor/L10nManagerEditor.cs
Labels: Medium

#2857 feat(GitHub Actions): introduce Build via Workflow Dispatch
  .editorconfig
  .github/workflows/build-via-workflow-dispatch.yaml
Labels: Small

#2859 fix(github-actions): Build via Workflow Dispatch
  .github/workflows/build-via-workflow-dispatch.yaml
Labels: Extra Small

#2858 Add Skip button to intro video
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Large

#2862 feat(github-actions): set `clo.json` file at `Build via Workflow Dispatch`
  .github/workflows/build-via-workflow-dispatch.yaml
Labels: Extra Small

#2863 improve ux for 30
  nekoyume/Assets/Resources/UI/Prefabs/UI_CelebratesPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_DialogPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Tutorial.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Popup/DialogPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
  nekoyume/ProjectSettings/TimeManager.asset
Labels: Medium

#2853 Feature/console command add
  nekoyume/Assets/Plugins/IngameDebugConsole/IngameDebugConsole.prefab
  nekoyume/Assets/_Scripts/Game/ActionCamera.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Game/RaidCamera.cs
  nekoyume/Assets/_Scripts/Game/Util/IngameDebugConsoleCommands.cs
  nekoyume/Assets/_Scripts/Game/Util/IngameDebugConsoleCommands.cs.meta
  nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs
Labels: Medium

#2861 Feature/add qr sharing
  nekoyume/Assets/Plugins/NativeShare.meta
  nekoyume/Assets/Plugins/NativeShare/Android.meta
  nekoyume/Assets/Plugins/NativeShare/Android/NSCallbackHelper.cs
  nekoyume/Assets/Plugins/NativeShare/Android/NSCallbackHelper.cs.meta
  nekoyume/Assets/Plugins/NativeShare/Android/NSShareResultCallbackAndroid.cs
  nekoyume/Assets/Plugins/NativeShare/Android/NSShareResultCallbackAndroid.cs.meta
  nekoyume/Assets/Plugins/NativeShare/Android/NativeShare.aar
  nekoyume/Assets/Plugins/NativeShare/Android/NativeShare.aar.meta
  nekoyume/Assets/Plugins/NativeShare/Editor.meta
  nekoyume/Assets/Plugins/NativeShare/Editor/NSPostProcessBuild.cs
  nekoyume/Assets/Plugins/NativeShare/Editor/NSPostProcessBuild.cs.meta
  nekoyume/Assets/Plugins/NativeShare/Editor/NativeShare.Editor.asmdef
  nekoyume/Assets/Plugins/NativeShare/Editor/NativeShare.Editor.asmdef.meta
  nekoyume/Assets/Plugins/NativeShare/NativeShare.Runtime.asmdef
  nekoyume/Assets/Plugins/NativeShare/NativeShare.Runtime.asmdef.meta
  nekoyume/Assets/Plugins/NativeShare/NativeShare.cs
  nekoyume/Assets/Plugins/NativeShare/NativeShare.cs.meta
  nekoyume/Assets/Plugins/NativeShare/README.txt
  nekoyume/Assets/Plugins/NativeShare/README.txt.meta
  nekoyume/Assets/Plugins/NativeShare/iOS.meta
  nekoyume/Assets/Plugins/NativeShare/iOS/NSShareResultCallbackiOS.cs
  nekoyume/Assets/Plugins/NativeShare/iOS/NSShareResultCallbackiOS.cs.meta
  nekoyume/Assets/Plugins/NativeShare/iOS/NativeShare.mm
  nekoyume/Assets/Plugins/NativeShare/iOS/NativeShare.mm.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Helper/Util.cs
  nekoyume/Assets/_Scripts/Nekoyume.asmdef
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SettingPopup.cs
Labels: Extra Large

#2867 add auto login for mobile
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Helper/Util.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
Labels: Small

#2865 feat: remove using HelpTooltip.Helpme with showOnceForEachAgentAddress
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
  nekoyume/Assets/_Scripts/UI/Widget/BattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/CombinationMain.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
  nekoyume/Assets/_Scripts/UI/Widget/Login.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ChatPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotsPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/QuestPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SettingPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
  nekoyume/Assets/_Scripts/UI/Widget/StageInformation.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs
Labels: Extra Small

#2868 improve menu ui
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CombinationBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/ShopBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/StakingBtn.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/_Scripts/Game/Prologue.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/MainMenu.cs
  nekoyume/Assets/_Scripts/UI/Tween/HoverScaleTweener.cs
  nekoyume/Assets/_Scripts/UI/Widget/Base/Widget.cs
Labels: Small

#2869 feat: revert removed hackandslash tutorial code
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
Labels: Extra Small

#2864 Fix broken text ui
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinBottomButtons.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfo.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
Labels: Large

#2872 change loading timing
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
Labels: Extra Small

#2875 Port 30.0.0 release to development
  nekoyume/Assets/Resources/UI/Textures/icon_executable.png
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#2874 fix(Analyzer): replace "/" to "_" of event name and key for Firebase Analystics
  nekoyume/Assets/_Scripts/Analyzer.cs
Labels: Extra Small

#2876 UI/menu not open
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/BoxCatBtnContainers.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CombinationBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/QuestBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/ShopBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/StakingBtn.prefab
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_BattleResult.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Combination.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Rune.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Shop.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldBoss.spriteatlas
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Icon_Lock.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Icon_Lock.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_Gradiant_bg_04.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_Gradiant_bg_04.png.meta
  nekoyume/Assets/_Scripts/UI/Module/Lobby/MainMenu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
Labels: Extra Large

#2883 feat: use DecimalRate instead of Rate in StakingPopup
  nekoyume/Assets/Packages/Libplanet.Action.dll
  nekoyume/Assets/Packages/Libplanet.Common.dll
  nekoyume/Assets/Packages/Libplanet.Crypto.dll
  nekoyume/Assets/Packages/Libplanet.RocksDBStore.dll
  nekoyume/Assets/Packages/Libplanet.Store.dll
  nekoyume/Assets/Packages/Libplanet.Types.dll
  nekoyume/Assets/Packages/Libplanet.dll
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Extra Small

#2881 Backport #2874
  nekoyume/Assets/_Scripts/Analyzer.cs
Labels: Extra Small

#2885 chore: bump `Libplanet` assemblies to 3.1.2
  nekoyume/Assets/Packages/Libplanet.Action.dll
  nekoyume/Assets/Packages/Libplanet.Common.dll
  nekoyume/Assets/Packages/Libplanet.Crypto.dll
  nekoyume/Assets/Packages/Libplanet.RocksDBStore.dll
  nekoyume/Assets/Packages/Libplanet.Store.dll
  nekoyume/Assets/Packages/Libplanet.Types.dll
  nekoyume/Assets/Packages/Libplanet.dll
Labels: No Changes

#2884 chore(github-actions): add more trigers to build workflow
  .github/workflows/build-misc.yml
  .github/workflows/build.yml
Labels: Extra Small

#2888 [Design]UI_ArenaJoin_Prefabs_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinBottomButtons.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfo.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
Labels: Large

#2886 change push notification limit for craft, upgrade
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
Labels: Extra Small

#2880 feat: add receive all feature and button to QuestPopup
  nekoyume/Assets/AddressableAssets/UI/Module/ReceiveArea.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ReceiveArea.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_MailPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPopup.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Popup/QuestPopup.cs
Labels: Extra Large

#2870 [Design]UI_Synopsis_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_Synopsis.prefab
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/Common_gradiant_64_Shop.png
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/Common_gradiant_64_Shop.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/button_skip.png
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/button_skip.png.meta
  nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
Labels: Extra Large

#2891 feat: add toggle sfx to MobileShop
  nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
  nekoyume/Assets/UIResources/Content/Shop/Prefab/IAP_ProductTab.prefab
Labels: Extra Small

#2892 Disable repeat button on failed
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
Labels: Extra Small

#2893 fix apply changed staking rewards to monster collection render
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_BenefitsListView.prefab
  nekoyume/Assets/_Scripts/UI/Module/Item/StakingBenefitsListView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/StakingInterestBenefitsView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Extra Small

#2895 release 30.1.0
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinBottomButtons.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfo.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/BoxCatBtnContainers.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CombinationBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/QuestBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/ShopBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/StakingBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ReceiveArea.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ReceiveArea.prefab.meta
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_BattleResult.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Combination.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Rune.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Shop.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldBoss.spriteatlas
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MailPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Synopsis.prefab
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/Common_gradiant_64_Shop.png
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/Common_gradiant_64_Shop.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/button_skip.png
  nekoyume/Assets/Resources/UI/Textures/00_Synopsis/button_skip.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Icon_Lock.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Icon_Lock.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_Gradiant_bg_04.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_Gradiant_bg_04.png.meta
  nekoyume/Assets/UIResources/Content/Shop/Prefab/IAP_ProductTab.prefab
  nekoyume/Assets/_Scripts/Analyzer.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/MainMenu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/QuestPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Large

#2896 chore: change product name to "NineChronicles"
  nekoyume/ProjectSettings/ProjectSettings.asset
  tools/pack/pack.py
Labels: Extra Small

#2796 UI/title full screen
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/Resources/UI/Textures/00_Intro/title_loading.png
  nekoyume/Assets/Resources/UI/Textures/00_Intro/title_loading.png.meta
Labels: Extra Small

#2899 [CI] Upload apk in android build
  .github/bin/install-bundletool.sh
  .github/workflows/build.yml
Labels: Extra Small

#2900 [CI] Separate android CI and merge manual execute action
  .github/workflows/android-build-and-release.yml
  .github/workflows/build-via-workflow-dispatch.yaml
  .github/workflows/build.yml
Labels: Large

#2902 Add Check Keystore in IntroScreen, Portal Deeplink
  nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
Labels: Extra Small

#2906 Fix Intro background
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Extra Small

#2904 fix: failure of MarketServiceClient networking
  nekoyume/Assets/_Scripts/Game/MarketServiceClient.cs
Labels: bug, Extra Small

#2905 bugfix stakingpopup render issue
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Extra Small

#2907 add screen ratio editor commands
  nekoyume/Assets/Planetarium/Nekoyume/Editor/Nekoyume-editor.asmdef
  nekoyume/Assets/Planetarium/Nekoyume/Editor/ScreenEditorMenus.cs
  nekoyume/Assets/Planetarium/Nekoyume/Editor/ScreenEditorMenus.cs.meta
  nekoyume/Assets/_Scripts/Game/ActionCamera.cs
  nekoyume/Assets/_Scripts/Game/RaidCamera.cs
Labels: Small

#2908 Prepare/release 40.0.0
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/_Scripts/Game/MarketServiceClient.cs
  nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
Labels: Small

#2909 add android icon
  nekoyume/Assets/Resources/UI/Textures/icon_executable_mobile.png
  nekoyume/Assets/Resources/UI/Textures/icon_executable_mobile.png.meta
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Large

#2912 change actionpoint push noti lable
  nekoyume/Assets/StreamingAssets/Localization/notification.csv
Labels: Extra Small

#2913 Fix loading indicator duplication
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Medium

#2914 Edit OneButtonSystem bg
  nekoyume/Assets/Resources/UI/Prefabs/UI_OneButtonSystem.prefab
Labels: Medium

#2915 Add api re-request code
  nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
Labels: Extra Small

#2916 Prepare/40.0.0
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_OneButtonSystem.prefab
  nekoyume/Assets/StreamingAssets/Localization/notification.csv
  nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Large

#2889 feat(IAgent): implement async methods for get balance
  nekoyume/Assets/Plugins/StateViewer/Editor/Features/StateAndBalanceFeature.cs
  nekoyume/Assets/Plugins/StateViewer/Editor/Features/TrackStateFeature.cs
  nekoyume/Assets/Plugins/StateViewer/Runtime/StateProxy.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
  nekoyume/Assets/_Scripts/Blockchain/Agent.cs
  nekoyume/Assets/_Scripts/Blockchain/IAgent.cs
  nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
  nekoyume/Assets/_Scripts/Extensions/AvatarStateExtensions.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/State/GrandFinaleStates.cs
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
  nekoyume/Assets/_Scripts/State/States.cs
Labels: Large

#2917 add googleplay release git action workflow
  .github/workflows/android-googleplay-release.yml
Labels: Small

#2887 [CI] Android deploy to google play console internal
  .github/workflows/android-build-and-release.yml
  .gitignore
  Gemfile
  Gemfile.lock
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/README.md
Labels: Large

#2919 [CI] Handle semver versioning in internal deploy
  .github/workflows/build.yml
Labels: Extra Small

#2924 cherry-pick: c63cd6c
  .github/workflows/build.yml
Labels: Extra Small

#2866 [Design]UI_GrayLoadingScreen_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_GrayLoadingScreen.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/LoadingGauge_Light.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/LoadingGauge_Light.png.meta
Labels: Extra Large

#2929 fix compile errors
  nekoyume/Assets/Tests/EditMode/StateModifierTest.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
Labels: Small

#2935 [CI] Change aws credentials
  .github/workflows/android-build-and-release.yml
  .github/workflows/build.yml
Labels: Extra Small

#2923 add googleplaystore deploy
  .github/workflows/android-googleplay-release.yml
Labels: Small

#2937 reflecting af4bf(commit ref) changes
  .github/workflows/android-googleplay-release.yml
Labels: Small

#2934 Update Craft ui
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Effect_Lockcover.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_RecipeListview.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_RecipeSlot.prefab
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_BattleResult.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Combination.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Rune.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Shop.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldBoss.spriteatlas
  nekoyume/Assets/Resources/UI/Animations/ItemRecipeController.controller
  nekoyume/Assets/Resources/UI/Animations/ItemRecipeController@Clicked.anim
  nekoyume/Assets/Resources/UI/Animations/ItemRecipeController@Show.anim
  nekoyume/Assets/Resources/UI/Prefabs/EquipDesc.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CelebratesPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Combination/Icon_Item_Lock.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Combination/Icon_Item_Lock.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Combination/Item_Level_Dim.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Combination/Item_Level_Dim.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Combination/Item_Recipebg_01.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Combination/Item_Recipebg_02.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Combination/Item_Recipebg_03.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Combination/Item_Recipebg_04.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Combination/Item_Recipebg_05.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Combination/UI_Combination_Elementbg.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_icon_open_2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_icon_open_2.png.meta
  nekoyume/Assets/_Scripts/Helper/RecipeHelper.cs
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
  nekoyume/Assets/_Scripts/UI/Model/RecipeModel.cs
  nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeCell.cs
  nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeView.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeRow.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
Labels: Extra Large

#2938 remove checkout step
  .github/workflows/android-googleplay-release.yml
Labels: Extra Small

#2940 add android versioncode to workflows/android-build-and-release.yml
  .github/workflows/android-build-and-release.yml
Labels: Extra Small

#2945 add manual build option for android-build-and-release.yml
  .github/workflows/android-build-and-release.yml
Labels: Extra Small

#2943 Update BNB Costeme Add
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
Labels: Extra Small

#2942 Edit intro screen to improve ui
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Extra Small

#2941 improve password checking at password setting
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
  nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
Labels: Extra Large

#2954 Update ProjectSettings.asset
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#2951 Fix craft recipe filtering
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
Labels: Extra Small

#2953 Fix portal error popup
  nekoyume/Assets/Resources/UI/Prefabs/UI_TitleOneButtonSystem.prefab
  nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#2960 Fix tutorial CombineEquipmentCategory position
  nekoyume/Assets/AddressableAssets/UI/Module/TutorialDummys.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_TitleOneButtonSystem.prefab
  nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#2962 Bugfix/upgrage slide gage reset
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
Labels: Extra Small

#2963 Fix recipe scroll
  nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeCell.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
Labels: Extra Small

#2964 Prepare/50.0.0
  nekoyume/Assets/AddressableAssets/UI/Module/TutorialDummys.prefab
  nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeCell.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Medium
