Repository planetarium/NineChronicles, pull requests merged in 2023-03, with the labels that each got.

#2412 Uibug/UI 380 fix
  nekoyume/Assets/AddressableAssets/UI/Module/Inventory.prefab
  nekoyume/Assets/Packages/Libplanet.Net.dll
  nekoyume/Assets/Packages/Libplanet.RocksDBStore.dll
  nekoyume/Assets/Packages/Libplanet.Stun.dll
  nekoyume/Assets/Packages/Libplanet.dll
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BuyFungibleAssetInformationPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopSell.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/icon_FungibleAsset_01_black.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/icon_FungibleAsset_01_black.png.meta
Labels: Extra Large

#2411 Improve dcc UI
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/Mileage.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/Mileage.prefab.meta
  nekoyume/Assets/Resources/HelpPopupData/HelpPopupData.json
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccMain.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetEnhancementPopup.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/url.json
  nekoyume/Assets/_Scripts/Helper/Url.cs
  nekoyume/Assets/_Scripts/UI/Module/Mileage.cs
  nekoyume/Assets/_Scripts/UI/Module/Mileage.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/DccMain.cs
  nekoyume/Assets/_Scripts/UI/Widget/Static/HeaderMenuStatic.cs
Labels: Extra Large

#2415 Bugfix pet
  nekoyume/Assets/AddressableAssets/Character/PetAnimator.controller
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/RankCell.prefab
  nekoyume/Assets/Resources/Character/Pet/Pet.prefab
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Labels: Small

#2421 UI/menu dcc edit
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/BoxCatBtnContainers.prefab
  nekoyume/Assets/Resources/SpriteAtlases/Background/MainMenu.spriteatlas
  nekoyume/Assets/Sprites/Background/MainMenu/Object/Main_dcc_01.png
  nekoyume/Assets/Sprites/Background/MainMenu/Object/Main_dcc_01.png.meta
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_00.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_01.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_02.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_03.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_04.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_05.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_06.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_07.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_08.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_09.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_10.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_11.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_12.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_13.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_14.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_15.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_16.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_17.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_18.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_19.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_20.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_21.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_22.png
  nekoyume/Assets/UIResources/Atlas_image/SpriteAnimation/UI_Lobby_nft_npc/main_pfp-Idle_23.png
Labels: Extra Large

#2422 Add dcc eth chain header
  nekoyume/Assets/StreamingAssets/url.json
  nekoyume/Assets/_Scripts/Game/Dcc.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Helper/Url.cs
  nekoyume/Assets/_Scripts/UI/Module/Mileage.cs
  nekoyume/Assets/_Scripts/UI/RequestManager.cs
Labels: Small

#2429 feat: Improve `State Viewer`
  nekoyume/Assets/Plugins/StateViewer/Editor/StateTreeView.cs
  nekoyume/Assets/Plugins/StateViewer/Editor/StateTreeViewItem.cs
  nekoyume/Assets/Plugins/StateViewer/Editor/StateViewer.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Labels: Small

#2431 feat: Model Viewer
  nekoyume/Assets/Plugins/ModelViewer.meta
  nekoyume/Assets/Plugins/ModelViewer/Editor.meta
  nekoyume/Assets/Plugins/ModelViewer/Editor/ModelViewerWindow.cs
  nekoyume/Assets/Plugins/ModelViewer/Editor/ModelViewerWindow.cs.meta
  nekoyume/Assets/Plugins/ModelViewer/Runtime.meta
Labels: Medium

#2424 Fix pet for friend character
  nekoyume/Assets/_Scripts/Game/Character/CharacterAppearance.cs
  nekoyume/Assets/_Scripts/Game/Character/FriendCharacter.cs
Labels: Extra Small

#2423 Fix craft recipe scroll
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeRow.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
Labels: Extra Small

#2438 Bugfix
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_Appear.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_FallDown_Defeat.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_FallDown_Victory.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_RunAway_1.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_RunAway_2.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_RunAway_3.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_RunAway_4.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_Skill.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_Skill_Bite.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_Skill_Claw.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_Skill_Enrage.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssFenrir/900001_Skill_Wrath.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_Appear.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_FallDown_Defeat.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_FallDown_Victory.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_RunAway_1.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_RunAway_2.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_RunAway_3.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_RunAway_4.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_Skill_Corrosion.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_Skill_Enrage.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_Skill_Fury.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_Skill_Multistrike.playable
  nekoyume/Assets/Resources/Timeline/WorldBoss/Animations/AbyssSaehrimnir/900002_Skill_Wrath.playable
  nekoyume/Assets/_Scripts/Animation/RaidTimelineContainer.cs
  nekoyume/Assets/_Scripts/Extensions/SpineAnimationHelper.cs
  nekoyume/Assets/_Scripts/Game/Avatar/AvatarSpineController.cs
  nekoyume/Assets/_Scripts/Game/Character/CharacterAppearance.cs
Labels: bug, Extra Large

#2434 Fix arena battle profile
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattle.prefab
Labels: Extra Large

#2450 [Design]RankLevel_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/ExpRankCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CharacterView/DetailedCharacterView.prefab
  nekoyume/Assets/Resources/UI/Icons/Item/Character_Level_Bg.png
  nekoyume/Assets/Resources/UI/Icons/Item/Character_Level_Bg.png.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/Character_Level_Bg.png
Labels: Small

#2447 Uibug/UI prefab fix2
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinSeasonInfo.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/QuestCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CombinationItemInformation.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Grinding/GrindModule.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Inventory.prefab
  nekoyume/Assets/Resources/Font/Materials/Japanese SDF Material - Mining.mat
  nekoyume/Assets/Resources/UI/Animations/UIRuneEnhancementResult@Fail.anim
  nekoyume/Assets/Resources/UI/Animations/UIRuneEnhancementResult@Success.anim
  nekoyume/Assets/Resources/UI/Prefabs/EquipDesc.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BuyItemInformationPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Grind.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MaterialNavigationPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PaymentPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RaidPreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RuneEnhancementResultScreen.prefab
  nekoyume/Assets/_Scripts/Helper/PetFrontHelper.cs
Labels: Extra Large

#2451 Add cost button to sell ui
  nekoyume/Assets/AddressableAssets/UI/Module/Button/ConditionalButton_Type6.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemCountAndPricePopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemCountableAndPricePopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopSell.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_TwoButtonSystem.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ItemCountPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ItemCountableAndPricePopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/TwoButtonSystem.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltipSell.cs
Labels: Extra Large

#2454 Update spine resources
  nekoyume/Assets/AddressableAssets/Character/Parts/aceye_skin.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Parts/aceye_skin.json
  nekoyume/Assets/AddressableAssets/Character/Parts/acface_skin.json
  nekoyume/Assets/AddressableAssets/Character/Parts/achead_skin.json
  nekoyume/Assets/AddressableAssets/Character/Parts/ear_skin.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Parts/ear_skin.json
  nekoyume/Assets/AddressableAssets/Character/Parts/face_skin.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Parts/face_skin.json
  nekoyume/Assets/AddressableAssets/Character/Parts/face_skin.png
  nekoyume/Assets/AddressableAssets/Character/Parts/hairback_skin.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Parts/hairback_skin.json
  nekoyume/Assets/AddressableAssets/Character/Parts/hairback_skin.png
  nekoyume/Assets/AddressableAssets/Character/Parts/hairfront_skin.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Parts/hairfront_skin.json
  nekoyume/Assets/AddressableAssets/Character/Parts/hairfront_skin.png
  nekoyume/Assets/AddressableAssets/Character/Parts/tail_skin.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Parts/tail_skin.json
  nekoyume/Assets/AddressableAssets/Character/Parts/tail_skin.png
Labels: Extra Large

#2439 feat: Improve Model Viewer
  nekoyume/Assets/Plugins/ModelViewer/Editor/ModelViewerWindow.cs
  nekoyume/Assets/Plugins/ModelViewer/Runtime/ModelFactory.cs
  nekoyume/Assets/Plugins/ModelViewer/Runtime/ModelFactory.cs.meta
Labels: Large

#2458 Fix ProfileSelectPopup for dcc connected
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ProfileSelectPopup.cs
Labels: Extra Small

#2461 change address.ToHex() to ToString()
  nekoyume/Assets/_Scripts/UI/Module/ArenaStatus.cs
  nekoyume/Assets/_Scripts/UI/Module/RaidPlayerStatus.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RankCellPanel.cs
  nekoyume/Assets/_Scripts/UI/Widget/Status.cs
Labels: Extra Small

#2460 fix: `Game.CachedBalance` bug.
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: bug, Small

#2465 Fix AvatarAnimator
  nekoyume/Assets/AddressableAssets/Character/AvatarAnimator.controller
Labels: Extra Small

#2463 Fix ProfileSelectPopup button animation
  nekoyume/Assets/Resources/UI/Prefabs/UI_ProfileSelectPopup.prefab
Labels: Extra Small

#2462 Uibug/UI prefab fix4
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/QuestCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/StatArea.prefab
  nekoyume/Assets/Resources/UI/Prefabs/EquipDesc.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotsPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MailPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RaidPreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RuneEnhancementResultScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBoss.prefab
  nekoyume/Assets/_Scripts/UI/Scroller/MailCell.cs
  nekoyume/Assets/_Scripts/UI/Scroller/QuestCell.cs
Labels: Extra Large

#2468 feat: Improve State Viewer
  nekoyume/Assets/Plugins/StateViewer/Editor/StateViewer.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
Labels: Small

#2469 feat: Improve State Viewer
  nekoyume/Assets/Plugins/StateViewer/Editor/StateViewer.cs
Labels: Extra Small

#2475 Fix pet sort order
  nekoyume/Assets/_Scripts/UI/Module/PetInventory.cs
Labels: Extra Small

#2477 bugfix about dcc collection
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/SOULSTONE_1001.png
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/SOULSTONE_1001.png.meta
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/SOULSTONE_1002.png
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/SOULSTONE_1002.png.meta
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/SOULSTONE_1003.png
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/SOULSTONE_1003.png.meta
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/SOULSTONE_1004.png
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/SOULSTONE_1004.png.meta
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/Soulstone_1001.png
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/Soulstone_1001.png.meta
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/Soulstone_1002.png
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/Soulstone_1002.png.meta
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/Soulstone_1003.png
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/Soulstone_1003.png.meta
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/Soulstone_1004.png
  nekoyume/Assets/Resources/UI/Icons/FungibleAssetValue/Soulstone_1004.png.meta
  nekoyume/Assets/Resources/UI/Icons/SoulStone.meta
  nekoyume/Assets/_Scripts/UI/Widget/Popup/PetEnhancementPopup.cs
Labels: Extra Large

#2479 Fix pet animation at worldboss
  nekoyume/Assets/_Scripts/Game/Character/Pet.cs
  nekoyume/Assets/_Scripts/Game/RaidStage.cs
Labels: Extra Small

#2480 Improve description blockperhourglass
  nekoyume/Assets/_Scripts/Helper/PetFrontHelper.cs
  nekoyume/Assets/_Scripts/UI/Module/PetInventory.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/PetEnhancementPopup.cs
Labels: Extra Large

#2474 fix market
  nekoyume/Assets/Resources/UI/Prefabs/UI_FungibleAssetTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/EnumType/ItemSubTypeFilter.cs
  nekoyume/Assets/_Scripts/EnumType/MarketOrderType.cs
  nekoyume/Assets/_Scripts/EnumType/ShopSortFilter.cs
  nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs
  nekoyume/Assets/_Scripts/Game/MarketServiceClient.cs
  nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
  nekoyume/Assets/_Scripts/UI/Model/InventoryItem.cs
  nekoyume/Assets/_Scripts/UI/Model/ShopItem.cs
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
  nekoyume/Assets/_Scripts/UI/Shop/SellView.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/FungibleAssetTooltip.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltip.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltipBuy.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltipSell.cs
Labels: bug, Extra Large

#2481 fix rendering transfer asset and etc.
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
  nekoyume/Assets/_Scripts/UI/Module/Pet/PetInfoView.cs
Labels: Extra Small

#2483 Market Bugfix
  nekoyume/Assets/_Scripts/Game/MarketServiceClient.cs
  nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
  nekoyume/Assets/_Scripts/UI/Shop/IShopView.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopView.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
Labels: bug, Medium

#2486 Fix minor issues
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/MimisbrunnrBtn.prefab
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Item.spriteatlas
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotsPopup.cs
Labels: Extra Small

#2487 Add system message to the DCC activation button.
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
Labels: Extra Small

#2488 Update spine resources
  nekoyume/Assets/AddressableAssets/Character/Parts/aceye_skin.json
  nekoyume/Assets/AddressableAssets/Character/Parts/acface_skin.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Parts/acface_skin.json
  nekoyume/Assets/AddressableAssets/Character/Parts/acface_skin.png
  nekoyume/Assets/AddressableAssets/Character/Parts/achead_skin.json
  nekoyume/Assets/AddressableAssets/Character/Parts/ear_skin.json
  nekoyume/Assets/AddressableAssets/Character/Parts/face_skin.json
  nekoyume/Assets/AddressableAssets/Character/Parts/hairback_skin.json
  nekoyume/Assets/AddressableAssets/Character/Parts/hairfront_skin.json
  nekoyume/Assets/Resources/Character/Avatar.prefab
  nekoyume/Assets/Resources/Character/UI_Avatar.prefab
  nekoyume/Assets/_Scripts/EnumType/AvatarPartsType.cs
Labels: Extra Small

#2493 Fix and improve StateViewer
  nekoyume/Assets/Planetarium/Nekoyume/Editor/AddressToolWindow.cs
  nekoyume/Assets/Plugins/StateViewer/Editor/StateTreeView.cs
  nekoyume/Assets/Plugins/StateViewer/Editor/StateTreeViewItem.cs
  nekoyume/Assets/Plugins/StateViewer/Editor/StateViewerEditor.asmdef
  nekoyume/Assets/Plugins/StateViewer/Editor/StateViewerEditor.asmdef.meta
  nekoyume/Assets/Plugins/StateViewer/Editor/StateViewerWindow.cs
  nekoyume/Assets/Plugins/StateViewer/Editor/StateViewerWindow.cs.meta
  nekoyume/Assets/Plugins/StateViewer/Runtime.meta
  nekoyume/Assets/Plugins/StateViewer/Runtime/StateProxy.cs
  nekoyume/Assets/Plugins/StateViewer/Runtime/StateProxy.cs.meta
  nekoyume/Assets/Plugins/StateViewer/Runtime/StateTreeViewItemModel.cs
  nekoyume/Assets/Plugins/StateViewer/Runtime/StateTreeViewItemModel.cs.meta
  nekoyume/Assets/Plugins/StateViewer/Runtime/StateViewer.asmdef
  nekoyume/Assets/Plugins/StateViewer/Runtime/StateViewer.asmdef.meta
  nekoyume/Assets/Plugins/StateViewer/Tests.meta
  nekoyume/Assets/Plugins/StateViewer/Tests/EditMode.meta
  nekoyume/Assets/Plugins/StateViewer/Tests/EditMode/StateTreeViewItemModelTest.cs
  nekoyume/Assets/Plugins/StateViewer/Tests/EditMode/StateTreeViewItemModelTest.cs.meta
  nekoyume/Assets/Plugins/StateViewer/Tests/EditMode/StateViewerTestsEditMode.asmdef
  nekoyume/Assets/Plugins/StateViewer/Tests/EditMode/StateViewerTestsEditMode.asmdef.meta
  nekoyume/Packages/manifest.json
  nekoyume/Packages/packages-lock.json
  nekoyume/StateViewerEditor.csproj.DotSettings
  nekoyume/StateViewerTestsEditMode.csproj.DotSettings
  nekoyume/nekoyume.sln.DotSettings
Labels: Extra Large

#2489 Add AvatarWeapon for UI avatar.
  nekoyume/Assets/Resources/Character/UI_Avatar.prefab
  nekoyume/Assets/_Scripts/Game/Avatar/AvatarWeapon.cs
  nekoyume/Assets/_Scripts/Game/Avatar/AvatarWeapon.cs.meta
Labels: bug, Extra Large

#2490 Adjust the length of the attack animation
  nekoyume/Assets/_Scripts/Game/Character/ArenaCharacter.cs
  nekoyume/Assets/_Scripts/Game/Character/CharacterAnimator.cs
Labels: bug, Extra Small

#2491 Fix rune display
  nekoyume/Assets/_Scripts/UI/Model/RuneItem.cs
Labels: bug, Extra Small

#2492 Modify the font of the Rune sell popup.
  nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/VanillaItemView.cs
Labels: bug, Extra Small

#2495 Fix conditional cost button submittable
  nekoyume/Assets/Resources/UI/Prefabs/UI_CostTwoButtonPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemCountableAndPricePopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
  nekoyume/Assets/_Scripts/UI/Module/Button/ConditionalCostButton.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CostTwoButtonPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ItemCountableAndPricePopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltipSell.cs
Labels: Medium

#2494 Fix character view for dcc profile issue
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/RankCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CharacterView/DetailedCharacterView.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattleLoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Rank.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossRankCell.prefab
  nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardPlayerCell.cs
  nekoyume/Assets/_Scripts/UI/Module/Character/CharacterProfile.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/WorldBossRankItemView.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/ArenaBattleLoadingScreen.cs
Labels: Extra Large

#2497 Update WorkShop L10n Change
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#2498 Bugfix shop search
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
Labels: bug, Extra Small

#2499 Fix the bug related to store option tags
  nekoyume/Assets/_Scripts/UI/Module/Item/ShopItemView.cs
Labels: bug, Extra Small

#2500 Fix soul stone ticker
  nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
Labels: bug, Extra Small

#2501 Active `button` gameObject
  nekoyume/Assets/Resources/UI/Prefabs/UI_RuneTooltip.prefab
Labels: bug, Extra Small

#2502 fix dcc url and etc.
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccCollection.prefab
  nekoyume/Assets/StreamingAssets/url.json
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/Helper/Url.cs
  nekoyume/Assets/_Scripts/UI/Widget/DccCollection.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ProfileSelectPopup.cs
Labels: Small

#2503 Fix bug in updating world information
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattleResultPopup.prefab
  nekoyume/Assets/_Scripts/Extensions/AvatarStateExtensions.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
Labels: Extra Small

#2508 Delete unused costume tabs
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/_Scripts/EnumType/ItemSubTypeFilter.cs
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopBuy.cs
Labels: bug, Extra Small

#2509 Fix prologue
  nekoyume/Assets/_Scripts/Game/Character/PrologueCharacter.cs
Labels: bug, Extra Small

#2510 handling minus exp at sweep popup
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs
Labels: Extra Large

#2512 Fix ArenaBattleResultPopup text
  nekoyume/Assets/_Scripts/UI/Widget/Popup/RankingBattleResultPopup.cs
Labels: Extra Small

#2513 Add a Soulstone condition to fav sell popup
  nekoyume/Assets/_Scripts/UI/Model/ItemCountPopup.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/VanillaItemView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/FungibleAssetTooltip.cs
Labels: bug, Extra Small

#2514 Apply improved description on pet levelup result popup.
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetLevelUpResultScreen.prefab
  nekoyume/Assets/_Scripts/Helper/PetFrontHelper.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/PetEnhancementPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/PetLevelUpResultScreen.cs
Labels: Extra Small

#2515 Fix pet summon description
  nekoyume/Assets/_Scripts/UI/Widget/Screen/PetSummonResultScreen.cs
Labels: Extra Small

#2516 Add missing code
  nekoyume/Assets/_Scripts/UI/Module/Item/VanillaItemView.cs
Labels: bug, Extra Small

#2521 Upgrade `CsvHelper` to `30.0.1`
  nekoyume/Assets/Packages/CsvHelper.dll
  nekoyume/Assets/Packages/CsvHelper.xml
  nekoyume/Assets/_Scripts/L10n/L10nManager.cs
Labels: Extra Small

#2522 Subscribe blockIndex only on item which has expiration date.
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltipBuy.cs
Labels: Extra Small

#2528 Bugfix/fix shop
  nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs
  nekoyume/Assets/_Scripts/L10n/L10nManager.cs
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
  nekoyume/Assets/_Scripts/UI/Shop/SellView.cs
Labels: bug

#2531 Merge 100380-2 into dev
  nekoyume/Assets/Packages/MarketService.Response.dll
  nekoyume/Assets/Resources/Audio/Music/Prefabs/bgm_dcc.prefab
  nekoyume/Assets/Resources/Audio/Music/Prefabs/bgm_dcc.prefab.meta
  nekoyume/Assets/Resources/Audio/Music/clips/bgm_dcc.ogg
  nekoyume/Assets/Resources/Audio/Music/clips/bgm_dcc.ogg.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotPopup.prefab
  nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs
  nekoyume/Assets/_Scripts/Game/Character/MecanimAnimator.cs
  nekoyume/Assets/_Scripts/Game/Controller/AudioController.cs
  nekoyume/Assets/_Scripts/L10n/L10nManager.cs
  nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
  nekoyume/Assets/_Scripts/UI/Shop/SellView.cs
  nekoyume/Assets/_Scripts/UI/Widget/DccMain.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/ItemTooltipBuy.cs
Labels: Large

#2532 enable blur at sweep popup
  nekoyume/Assets/Resources/UI/Prefabs/UI_SweepPopup.prefab
Labels: Small

#2536 introduce fillWithNullToEmptyCellGroup
  nekoyume/Assets/_Scripts/UI/Scroller/GridScroll.cs
Labels: Extra Small

#2537 fix logic about fillWithNullToEmptyCellGroup
  nekoyume/Assets/_Scripts/UI/Scroller/GridScroll.cs
Labels: Extra Small

#2520 Feature/headless tool
  .gitignore
  nekoyume/Assets/Planetarium/Nekoyume/Editor/HeadlessTool.cs
  nekoyume/Assets/Planetarium/Nekoyume/Editor/HeadlessTool.cs.meta
  nekoyume/Assets/Planetarium/Nekoyume/Editor/appsettings.example.json
  nekoyume/Assets/Planetarium/Nekoyume/Editor/appsettings.example.json.meta
  nekoyume/Assets/StreamingAssets/clo.local.json
  nekoyume/Assets/StreamingAssets/clo.local.json.meta
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Helper/HeadlessHelper.cs
  nekoyume/Assets/_Scripts/Helper/HeadlessHelper.cs.meta
Labels: enhancement, Large

#2545 add: dependency for Libplanet.Net
  nekoyume/Assets/Packages/Microsoft.Extensions.Caching.Memory.dll
  nekoyume/Assets/Packages/Microsoft.Extensions.Caching.Memory.xml
Labels: Large

#2546 add: missing dll
  nekoyume/Assets/Packages/Microsoft.Extensions.Caching.Abstractions.dll
  nekoyume/Assets/Packages/Microsoft.Extensions.Caching.Abstractions.xml
  nekoyume/Assets/Packages/Microsoft.Extensions.Options.dll
  nekoyume/Assets/Packages/Microsoft.Extensions.Options.xml
Labels: Extra Large

#2547 add: missing dependency
  nekoyume/Assets/Packages/Microsoft.Extensions.Primitives.dll
  nekoyume/Assets/Packages/Microsoft.Extensions.Primitives.xml
Labels: Extra Large

#2535 Update UI of Dcc collection
  nekoyume/Assets/Resources/UI/Animations/DccCollection@Close.anim
  nekoyume/Assets/Resources/UI/Animations/DccCollection@Close.anim.meta
  nekoyume/Assets/Resources/UI/Animations/DccCollection@Show.anim
  nekoyume/Assets/Resources/UI/Animations/DccCollection@Show.anim.meta
  nekoyume/Assets/Resources/UI/Animations/DccCollectionController.controller
  nekoyume/Assets/Resources/UI/Animations/DccCollectionController.controller.meta
  nekoyume/Assets/Resources/UI/Animations/DccMain@Close.anim
  nekoyume/Assets/Resources/UI/Animations/DccMain@Close.anim.meta
  nekoyume/Assets/Resources/UI/Animations/DccMain@Show.anim
  nekoyume/Assets/Resources/UI/Animations/DccMain@Show.anim.meta
  nekoyume/Assets/Resources/UI/Animations/DccMainController.controller
  nekoyume/Assets/Resources/UI/Animations/DccMainController.controller.meta
  nekoyume/Assets/Resources/UI/Animations/UI_DccMain.controller
  nekoyume/Assets/Resources/UI/Animations/UI_DccMain.controller.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccCollection.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccMain.prefab
Labels: Extra Large

#2544 Update avatar resources
  nekoyume/Assets/AddressableAssets/Character/Parts/aceye_skin.json
  nekoyume/Assets/AddressableAssets/Character/Parts/face_skin.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Parts/face_skin.json
  nekoyume/Assets/AddressableAssets/Character/Parts/face_skin.png
  nekoyume/Assets/AddressableAssets/Character/Parts/hairback_skin.json
  nekoyume/Assets/AddressableAssets/Character/Parts/hairfront_skin.json
Labels: Medium
