Repository planetarium/NineChronicles, pull requests merged in 2023-05, with the labels that each got.

#2622 Revert "Fix casting exception when tracking actions."
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Labels: Extra Small

#2616 Fix shop search filter to multiple ticker
  nekoyume/Assets/_Scripts/Game/MarketServiceClient.cs
  nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
Labels: Small

#2623 Fix shop bugs
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
Labels: Extra Small

#2624 rc-v200010-2 to main for hotfix
  nekoyume/Assets/Packages/MarketService.Response.dll
  nekoyume/Assets/_Scripts/Game/MarketServiceClient.cs
  nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
Labels: Small

#2634 Remove unused `Libplanet.Stun` DLL file
  nekoyume/Assets/Packages/Libplanet.Stun.dll
  nekoyume/Assets/Packages/Libplanet.Stun.dll.meta
Labels: dependencies

#2636 add androidAppBundle value to true
  .github/workflows/build.yml
  nekoyume/Assets/Editor/Builder.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Small

#2637 Update ConsumableRecipe Add
  nekoyume/Assets/Resources/Recipe/ConsumableRecipeGroup.json
Labels: Extra Small

#2639 Update Item Name Add
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
Labels: Extra Small

#2640 Bugfix SubRecipeView
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
Labels: Extra Small

#2642 World7 l10n
  nekoyume/Assets/StreamingAssets/Localization/character_name.csv
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/world_name.csv
Labels: Extra Small

#2643 Update Food Item Description L10n Add
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
Labels: Extra Small

#2647 remove noisy bug logging
  nekoyume/Assets/_Scripts/BlockChain/Agent.cs
  nekoyume/Assets/_Scripts/Helper/LocalMailHelper.cs
  nekoyume/Assets/_Scripts/Helper/Util.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Extra Small

#2648 Fix SubRecipeView(crystal equipment) bug
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
Labels: Extra Small

#2656 Fix supercraft default tab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SuperCraftPopup.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs
Labels: Extra Small

#2657 Implement skill description in item information tooltip
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RuneTooltip.prefab
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
  nekoyume/Assets/_Scripts/UI/Model/SkillView.cs
  nekoyume/Assets/_Scripts/UI/Module/Common/PositionTooltip.cs
  nekoyume/Assets/_Scripts/UI/Module/Common/SkillPositionTooltip.cs
  nekoyume/Assets/_Scripts/UI/Module/ItemInformation.cs
  nekoyume/Assets/_Scripts/UI/Module/ItemInformation.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/ItemTooltipDetail.cs
  nekoyume/Assets/_Scripts/UI/Module/Skill/SkillView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
Labels: Extra Large

#2663 UI/title change
  nekoyume/Assets/Resources/UI/Textures/00_Intro/title_loading.png
  nekoyume/Assets/Resources/UI/Textures/00_Intro/title_loading.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Intro/title_loading_DCC.png
Labels: No Changes

#2664 Fix workshop ResultPopup options
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationResultPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_EnhancementResultPopup.prefab
Labels: Extra Large

#2666 Get state from Agent on arena render
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Labels: Small

#2635 Support iOS build
  nekoyume/Assets/Editor/Builder.cs
  nekoyume/Assets/Plugins/Sentry.meta
  nekoyume/Assets/Plugins/Sentry/SentryCliOptions.asset
  nekoyume/Assets/Plugins/Sentry/SentryCliOptions.asset.meta
  nekoyume/Assets/Plugins/iOS/libgrpc.a.meta
  nekoyume/Assets/Plugins/iOS/rocksdb.framework.meta
  nekoyume/Assets/Plugins/iOS/rocksdb.framework/Info.plist
  nekoyume/Assets/Plugins/iOS/rocksdb.framework/Info.plist.meta
  nekoyume/Assets/Plugins/iOS/rocksdb.framework/_CodeSignature.meta
  nekoyume/Assets/Plugins/iOS/rocksdb.framework/_CodeSignature/CodeResources
  nekoyume/Assets/Plugins/iOS/rocksdb.framework/_CodeSignature/CodeResources.meta
  nekoyume/Assets/Plugins/iOS/rocksdb.framework/librocksdb.meta
  nekoyume/Assets/Plugins/iOS/secp256k1.framework.meta
  nekoyume/Assets/Plugins/iOS/secp256k1.framework/Info.plist
  nekoyume/Assets/Plugins/iOS/secp256k1.framework/Info.plist.meta
  nekoyume/Assets/Plugins/iOS/secp256k1.framework/_CodeSignature.meta
  nekoyume/Assets/Plugins/iOS/secp256k1.framework/_CodeSignature/CodeResources
  nekoyume/Assets/Plugins/iOS/secp256k1.framework/_CodeSignature/CodeResources.meta
  nekoyume/Assets/Plugins/iOS/secp256k1.framework/libsecp256k1
  nekoyume/Assets/Plugins/iOS/secp256k1.framework/libsecp256k1.meta
  nekoyume/Assets/Resources/SpriteAtlases/Background/MainMenu.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_BattleResult.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Combination.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Common.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Rune.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Shop.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldBoss.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldClear.spriteatlas
  nekoyume/Assets/_Scripts/SentryOptionsConfiguration.cs
  nekoyume/Assets/_Scripts/SentryOptionsConfiguration.cs.meta
Labels: Extra Large

#2669 Fix equipment recipe id
  nekoyume/Assets/Resources/Recipe/EquipmentSubRecipeTab.json
  nekoyume/Assets/_Scripts/Helper/Util.cs
Labels: Extra Small

#2673 Fix button condition in SuperCraftPopup
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs
Labels: Extra Small

#2677 Update World7 Item L10n Change
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
Labels: Extra Small

#2682 Update 7 World Dialog Add
  nekoyume/Assets/StreamingAssets/Localization/dialog.csv
Labels: Extra Small

#2679 change initializing value of LocalMailHelper
  nekoyume/Assets/_Scripts/Helper/LocalMailHelper.cs
Labels: Extra Small

#2681 Fix shader for recipe slot's legendary effect
  nekoyume/Assets/Resources/UI/Materials/Distortion_Additive_Maskable.shader
  nekoyume/Assets/Resources/UI/Materials/Distortion_Additive_Maskable.shader.meta
  nekoyume/Assets/UIResources/Content/Effect/Grade/Distortion_RecipeSlotOpen_eff.mat
Labels: Extra Small

#2680 Display stat power ratio on `Shop`.
  nekoyume/Assets/Packages/MarketService.Response.dll
  nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
Labels: Extra Small

#2683 fix Distortion_Addtive_Maskable shader for rect mask 2d
  nekoyume/Assets/Resources/UI/Materials/Distortion_Additive_Maskable.shader
Labels: Extra Small

#2685 Bug fix in supercraft pet.
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs
Labels: Extra Small

#2687 add masking scroll text to skill option
  nekoyume/Assets/AddressableAssets/UI/Module/ItemOptionView/EnhancementResultSkillOptionView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemOptionView/EnhancementResultSkillOptionView@Show.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_EnhancementResultPopup.prefab
  nekoyume/Assets/_Scripts/UI/Module/ItemOption/ItemOptionView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/EnhancementResultPopup.cs
Labels: Large

#2688 Hide zero skill power on enhancement.
  nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
Labels: Extra Small

#2689 Fix MaskedRectTransformXRoller for uninitialized value
  nekoyume/Assets/_Scripts/UI/Tween/MaskedRectTransformXRoller.cs
Labels: Extra Small

#2692 Introduce new deployment workflow
  .github/workflows/build.yml
Labels: Small
