Repository planetarium/NineChronicles, pull requests merged in 2023-12, with the labels that each got.

#3729 [Design]ActionPoint_Prefabs_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/Currency/ActionPoint.prefab
Labels: Extra Small

#3730 Release/90.2.8 to main
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#3732 back merge Release/90.2.8 to Prepare/90.3.x
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#3726 apply CenteredGridLayout
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopListPopup.prefab
  nekoyume/Assets/_Scripts/UI/Module/CenteredGridLayout.cs
  nekoyume/Assets/_Scripts/UI/Module/CenteredGridLayout.cs.meta
Labels: Extra Small

#3722 Feature/upgrade event popupl10n
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventPopup.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/Module/EventNotice/AutoBannerItem.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/EventPopup.cs
Labels: Extra Small

#3735 add fav item in garage when receiveAllButton
  nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
Labels: Small

#3728 [Design]RankingBtn_Prefabs_Edit + Add L10n Image
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
  nekoyume/Assets/Resources/SpriteAtlases/Background/MainMenu.spriteatlas
  nekoyume/Assets/Resources/UI/Animations/Promotion.controller
  nekoyume/Assets/Resources/UI/Animations/Promotion.controller.meta
  nekoyume/Assets/Resources/UI/Animations/Promotion@Loop.anim
  nekoyume/Assets/Resources/UI/Animations/Promotion@Loop.anim.meta
  nekoyume/Assets/Sprites/Background/MainMenu/Event/Promotion.meta
  nekoyume/Assets/Sprites/Background/MainMenu/Event/Promotion/bg_promotion_bg_01_EN.png
  nekoyume/Assets/Sprites/Background/MainMenu/Event/Promotion/bg_promotion_bg_01_EN.png.meta
  nekoyume/Assets/Sprites/Background/MainMenu/Event/Promotion/bg_promotion_bg_01_JP.png
  nekoyume/Assets/Sprites/Background/MainMenu/Event/Promotion/bg_promotion_bg_01_JP.png.meta
  nekoyume/Assets/Sprites/Background/MainMenu/Event/Promotion/bg_promotion_bg_01_KR.png
  nekoyume/Assets/Sprites/Background/MainMenu/Event/Promotion/bg_promotion_bg_01_KR.png.meta
  nekoyume/Assets/_Scripts/L10n/L10nImage.cs
  nekoyume/Assets/_Scripts/L10n/L10nImage.cs.meta
Labels: Extra Large

#3736 Fix/summon UI
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/SummonDetailCell.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SummonResultPopup.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Screen/SummonResultPopup.cs
Labels: Extra Small

#3737 add notch adjust to tab position
  nekoyume/Assets/Resources/UI/Prefabs/UI_Summon.prefab
Labels: Extra Small

#3739 [Design]UI_Menu_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RaidPreparation.prefab
Labels: Medium

#3738 accout > account
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: No Changes

#3749 [Design]UI_LoadingScreen_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoadingScreen.prefab
Labels: Extra Small

#3756 Feature/account delete
  nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SettingPopup.cs
Labels: Large

#3750 edit arena l10n
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#3748 [Design]UI_IntroScreen_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Guide_QRcode_1.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Guide_QRcode_1.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Guide_QRcode_2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Login/Guide_QRcode_2.png.meta
Labels: Extra Large

#3760 fix Vampiric rendering at Arena and Raid
  nekoyume/Assets/_Scripts/Game/Arena.cs
  nekoyume/Assets/_Scripts/Game/RaidStage.cs
Labels: Extra Small

#3757 UI/menu christmas
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/BoxCatBtnContainers.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CombinationBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/QuestBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/ShopBtn.prefab
  nekoyume/Assets/Resources/ScriptableObject/EventData.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Sprites/Background/MainMenu/Event/X-mas/bg_xmas_box_01.png
Labels: Medium

#3763 fix debug log and loading hide flow
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
Labels: Extra Small

#3761 [Summon] add rune summon ui
  nekoyume/Assets/AddressableAssets/UI/Module/Button/SummonCostButton.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/SummonItemView.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Summon.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SummonResultPopup.prefab
  nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs
  nekoyume/Assets/_Scripts/UI/Module/Button/SimpleCostButton.cs
  nekoyume/Assets/_Scripts/UI/Module/Button/SummonCostButton.cs
  nekoyume/Assets/_Scripts/UI/Module/Button/SummonCostButton.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/Common/SkillPositionTooltip.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/ItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/SummonItemView.cs
  nekoyume/Assets/_Scripts/UI/Scroller/SummonDetailCell.cs
  nekoyume/Assets/_Scripts/UI/Scroller/SummonSkillsCell.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SummonDetailPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SummonSkillsPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/CombinationLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/SummonResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Summon.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/FungibleAssetTooltip.cs
Labels: Extra Large

#3768 add key about rune summon
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/notification.csv
  nekoyume/Assets/StreamingAssets/Localization/summon_name.csv
Labels: Extra Small

#3762 Feature/rune sorting
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/RuneStoneEnhancementInventoryCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/RuneStoneEnhancementInventoryCell.prefab.meta
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_RuneListview.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Item/RuneListItem.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Item/RuneListItem.prefab.meta
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView_Inventory.prefab
  nekoyume/Assets/Resources/ScriptableObject/UI_RuneData.asset
  nekoyume/Assets/Resources/SpriteAtlases/Background/MainMenu.spriteatlas
  nekoyume/Assets/Resources/UI/Animations/Item_RuneListView.controller
  nekoyume/Assets/Resources/UI/Animations/Item_RuneListView.controller.meta
  nekoyume/Assets/Resources/UI/Animations/Item_RuneListview@Idle.anim
  nekoyume/Assets/Resources/UI/Animations/Item_RuneListview@Idle.anim.meta
  nekoyume/Assets/Resources/UI/Animations/Item_RuneListview@Show.anim
  nekoyume/Assets/Resources/UI/Animations/Item_RuneListview@Show.anim.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_Rune.prefab
  nekoyume/Assets/_Scripts/Game/ScriptableObject/RuneScriptableObject.cs
  nekoyume/Assets/_Scripts/Helper/RuneFrontHelper.cs
  nekoyume/Assets/_Scripts/UI/Model/RuneItem.cs
  nekoyume/Assets/_Scripts/UI/Model/RuneListItem.cs
  nekoyume/Assets/_Scripts/UI/Model/RuneListItem.cs.meta
  nekoyume/Assets/_Scripts/UI/Model/RuneListItemView.cs
  nekoyume/Assets/_Scripts/UI/Model/RuneListItemView.cs.meta
  nekoyume/Assets/_Scripts/UI/Model/RuneStoneEnhancementInventoryItem.cs
  nekoyume/Assets/_Scripts/UI/Model/RuneStoneEnhancementInventoryItem.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/Item/BaseItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/RuneListView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/RuneListView.cs.meta
  nekoyume/Assets/_Scripts/UI/Scroller/RuneListCell.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RuneListCell.cs.meta
  nekoyume/Assets/_Scripts/UI/Scroller/RuneListScroll.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RuneListScroll.cs.meta
  nekoyume/Assets/_Scripts/UI/Scroller/RuneStoneEnhancementInventoryCell.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RuneStoneEnhancementInventoryCell.cs.meta
  nekoyume/Assets/_Scripts/UI/Scroller/RuneStoneEnhancementInventoryScroll.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RuneStoneEnhancementInventoryScroll.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
Labels: Extra Large

#3765 edit key about key import
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Extra Small

#3771 ncg voucher > special skills
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#3769 [Design]UI_Summon_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_Summon.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SummonResultPopup.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Summon.cs
Labels: Medium

#3775 change bgm christmas event date
  nekoyume/Assets/Resources/Audio/Music/clips/Ikson-Christmas.ogg
  nekoyume/Assets/Resources/Audio/Music/clips/Ikson-Christmas.ogg.meta
  nekoyume/Assets/Resources/ScriptableObject/EventData.asset
Labels: Extra Small

#3778 Update Rune Skill L10n Change
  nekoyume/Assets/StreamingAssets/Localization/skill_description.csv
Labels: Extra Small

#3774 Update Rune Sorting Order Change
  nekoyume/Assets/Resources/ScriptableObject/UI_RuneData.asset
Labels: Extra Small

#3777 [Summon, Rune] Fix rune summon
  nekoyume/Assets/Resources/ScriptableObject/UI_RuneData.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_Summon.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/Widget/Summon.cs
Labels: Small

#3773 clear upgrade description branch
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
Labels: Extra Small

#3779 fix mail find condition
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
Labels: Extra Small

#3781 merge prepare/100.0.x into release/100.0
  nekoyume/Assets/Resources/Audio/Music/Prefabs/bgm_christmas.prefab
  nekoyume/Assets/Resources/Audio/Music/Prefabs/bgm_christmas.prefab.meta
  nekoyume/Assets/Resources/Audio/Music/clips/bgm_christmas.ogg
  nekoyume/Assets/Resources/Audio/Music/clips/bgm_christmas.ogg.meta
  nekoyume/Assets/Resources/ScriptableObject/EventData.asset
  nekoyume/Assets/Resources/ScriptableObject/UI_RuneData.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_Summon.prefab
  nekoyume/Assets/Sprites/Background/MainMenu/Event/Promotion/bg_promotion_bg_02_EN.png
  nekoyume/Assets/Sprites/Background/MainMenu/Event/Promotion/bg_promotion_bg_02_JP.png
  nekoyume/Assets/Sprites/Background/MainMenu/Event/Promotion/bg_promotion_bg_02_KR.png
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/skill_description.csv
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
  nekoyume/Assets/_Scripts/UI/Widget/Summon.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Large

#3784 BackMerge Release/90.3.3 to Prepare/100.0.x
  nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SettingPopup.cs
Labels: Large

#3788 fix IStage.CoCustomEvent implementation about Tick skill info
  nekoyume/Assets/_Scripts/Game/Arena.cs
  nekoyume/Assets/_Scripts/Game/RaidStage.cs
  nekoyume/Assets/_Scripts/Game/Stage.cs
Labels: Small

#3790 Bugfix/summon loading popup
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationLoadingScreen.prefab
  nekoyume/Assets/_Scripts/UI/Module/Button/SummonCostButton.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/ItemView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
  nekoyume/Assets/_Scripts/UI/Widget/Hud/SpeechBubbleWithItem.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/CombinationLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/GrindingLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Summon.cs
Labels: Small

#3791 refresh rune enhancement value
  nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
Labels: Extra Small

#3792 merge prepare/100.0.x into release/100.0
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationLoadingScreen.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Game/Arena.cs
  nekoyume/Assets/_Scripts/Game/RaidStage.cs
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/UI/Module/Button/SummonCostButton.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/ItemView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
  nekoyume/Assets/_Scripts/UI/Widget/Hud/SpeechBubbleWithItem.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SuperCraftPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/CombinationLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/GrindingLoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Summon.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Medium

#3793 [Design]SummonSkillsCell_Prefabs_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/SummonSkillsCell.prefab
Labels: Extra Small

#3795 Feature/edit qa l10n
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/help_popup.csv
Labels: Small

#3796 Fix stat value string at recipe view
  nekoyume/Assets/_Scripts/UI/Module/Recipe/RecipeView.cs
Labels: Extra Small

#3797 fix delete account button hide in window
  nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab
Labels: Extra Small

#3800 Update Skill Description L10n Chnage
  nekoyume/Assets/StreamingAssets/Localization/skill_description.csv
Labels: Extra Small

#3801 change rune skill description about vampiric and stun
  nekoyume/Assets/_Scripts/Extensions/SkillExtensions.cs
  nekoyume/Assets/_Scripts/Helper/RuneFrontHelper.cs
  nekoyume/Assets/_Scripts/UI/Model/RuneOptionView.cs
Labels: Extra Small

#3803 Update Portuguese L10n Change
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/help_popup.csv
Labels: Extra Small

#3811 fix rune enhancement rendering about update states
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
Labels: Extra Small

#3810 Fix rune summon result order
  nekoyume/Assets/_Scripts/UI/Widget/Summon.cs
Labels: Extra Small

#3812 change dynamic grid sort order
  nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopDynamicGridLayoutView.cs
  nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs
Labels: Extra Small

#3813 merge prepare/100.0.x into release/100.0 for 100.0.4 internal
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopDynamicGridLayoutView.cs
  nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
  nekoyume/Assets/_Scripts/UI/Widget/Summon.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#3808 [Design]UI_ShopBuy_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
Labels: Small

#3809 [Design]RaidBtn_Prefabs_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
Labels: Extra Small

#3799 fix position tooltip do not inactivated
  nekoyume/Assets/_Scripts/UI/Module/Common/PositionTooltip.cs
Labels: Extra Small

#3818 refresh dim fist check product buyable state
  nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs
Labels: Extra Small

#3794 [Design]UI_SeasonPass_Prefabs_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/SeasonPass/SeasonPassCell.prefab
  nekoyume/Assets/Resources/UI/Animations/SeasonPassLastReward@Close.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPass.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_SeasonPass/LevelStep_1.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_SeasonPass/LevelStep_2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_SeasonPass/LevelStep_3.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_SeasonPass/Seasonpass_BonusReward_Bg.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_SeasonPass/Seasonpass_BonusReward_Bg.png.meta
  nekoyume/Assets/_Scripts/UI/Module/Lobby/SeasonPassMenu.cs
  nekoyume/Assets/_Scripts/UI/Module/SeasonPass/SeasonPassRewardCell.cs
  nekoyume/Assets/_Scripts/UI/Widget/SeasonPass.cs
Labels: Large

#3807 [Design]UI_QuestPopup_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_MailPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPopup.prefab
Labels: Extra Small

#3822 change live asset image root url
  nekoyume/Assets/Resources/ScriptableObject/LiveAssetEndpoint.asset
Labels: Extra Small

#3820 Fix to UpdateItemSlotState with evaluation.OutputState
  nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Blockchain/StateGetter.cs
  nekoyume/Assets/_Scripts/State/States.cs
Labels: Medium

#3825 Edit HasUnread condition at EventReleaseNotePopup
  nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.cs
Labels: Extra Small

#3824 Edit Promotion UI
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CombinationBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
  nekoyume/Assets/_Scripts/L10n/L10nImage.cs
  nekoyume/Assets/_Scripts/UI/Module/PromotionContainer.cs
  nekoyume/Assets/_Scripts/UI/Module/PromotionContainer.cs.meta
Labels: Medium

#3758 [Design]loading_worldopen_Resource_Add
  nekoyume/Assets/Resources/SpriteAtlases/Background/Loading.spriteatlas
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Textures/00_Loading/loading_worldopen.png
  nekoyume/Assets/Resources/UI/Textures/00_Loading/loading_worldopen.png.meta
  nekoyume/Assets/_Scripts/UI/Widget/Screen/LoadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/WorldMap.cs
Labels: Medium

#3782 [Design]UI_LoginSystem_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoginSystem.prefab
Labels: Extra Large

#3833 flip webcam texture when verticallyMirroed
  nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs
Labels: Extra Small

#3823 add avatar so data
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/40100004.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/40100004.atlas.txt.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/40100004.json
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/40100004.json.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/40100004.png
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/40100004.png.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/40100004_Atlas.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/40100004_Atlas.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/40100004_Material-Screen.mat
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/40100004_Material-Screen.mat.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/40100004_Material.mat
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/40100004_Material.mat.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/40100004_SkeletonData.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/40100004_SkeletonData.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/Attack.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/Attack.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/Casting.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/Casting.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/CriticalAttack.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/CriticalAttack.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/Die.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/Die.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/Hit.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/Hit.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/Idle.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/Idle.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/Run.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/Run.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/Touch.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/Touch.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/TurnOver_01.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/TurnOver_01.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/TurnOver_02.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/TurnOver_02.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/Win.asset
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100004/ReferenceAssets/Win.asset.meta
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100015/40100015.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100015/40100015.json
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100015/40100015.png
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100025/40100025.json
  nekoyume/Assets/Resources/ScriptableObject/Avatar.asset
  nekoyume/Assets/StreamingAssets/Localization/event_dungeon_name.csv
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
Labels: Extra Large

#3832 Feature/next season pass refresh
  nekoyume/Assets/_Scripts/GeneratedApi/SeasonPassServiceClient.cs
  nekoyume/Assets/_Scripts/SeasonPassService/SeasonPassServiceManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/SeasonPass.cs
Labels: Medium

#3828 Update Event Dungeon Add
  nekoyume/Assets/Resources/ScriptableObject/EventData.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab
Labels: Extra Small

#3829 Update Great Adventurer 2 Title Icon Add
  nekoyume/Assets/Resources/UI/Icons/Item/49900013.png
  nekoyume/Assets/Resources/UI/Icons/Item/49900013.png.meta
Labels: Medium

#3831 Fix disable unlock shop popup in stage 17, mobile
  nekoyume/Assets/_Scripts/Game/Stage.cs
Labels: Extra Small

#3827 add max value to required block index text at SubRecipeView
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
Labels: Extra Small

#3830 Update DCC UI
  nekoyume/Assets/AddressableAssets/UI/Module/PFP/PetSlotCell.prefab
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_PFP.spriteatlas
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccCollection.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetEnhancementPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetLevelUpResultScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetSummonResultScreen.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/DCC_BG.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/DCC_BG.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/Gradiant_bg.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/Gradiant_bg.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/PetInfo_Bg.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/PetInfo_Bg.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/PetInfo_Bg_Arrow.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/PetInfo_Bg_Arrow.png.meta
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Widget/DccCollection.cs
  nekoyume/Assets/_Scripts/UI/Widget/DccMain.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/PetEnhancementPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/PetLevelUpResultScreen.cs
Labels: Extra Large

#3838 Event Dungeon Name L10n ID Change
  nekoyume/Assets/StreamingAssets/Localization/event_dungeon_name.csv
Labels: Extra Small

#3837 Fix action point render
  nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs
  nekoyume/Assets/_Scripts/UI/Module/Currency/ActionPoint.cs
Labels: Extra Small

#3839 EventData, WorldMap Change
  nekoyume/Assets/Resources/ScriptableObject/EventData.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab
Labels: Extra Small

#3846 Fix crystal cost at rune slot unlock
  nekoyume/Assets/_Scripts/UI/Module/Item/RuneSlotView.cs
Labels: Extra Small

#3845 Fix pet summon button at dcc collection
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccCollection.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetEnhancementPopup.prefab
  nekoyume/Assets/_Scripts/UI/Widget/DccCollection.cs
Labels: Extra Small

#3844 add key about seasonpass bonus reward
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#3847 fix iteminfo eventdungeon
  nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
Labels: Extra Small

#3843 apply fav tooltip for iap reward soulstone and crystal
  nekoyume/Assets/_Scripts/Extensions/LocalizationExtensions.cs
  nekoyume/Assets/_Scripts/UI/Module/IAP/IAPRewardView.cs
  nekoyume/Assets/_Scripts/UI/Module/SeasonPass/SeasonPassRewardCell.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ShopListPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/FungibleAssetTooltip.cs
Labels: Small

#3840 [Design]40100006_Prefabs_Edit
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100006/40100006.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100006/40100006.json
  nekoyume/Assets/AddressableAssets/Character/FullCostume/40100006/40100006.png
Labels: Large

#3660 update jp l10n
  nekoyume/Assets/StreamingAssets/Localization/buff_description.csv
  nekoyume/Assets/StreamingAssets/Localization/buff_name.csv
  nekoyume/Assets/StreamingAssets/Localization/character_name.csv
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/elemental_type.csv
  nekoyume/Assets/StreamingAssets/Localization/enum_type.csv
  nekoyume/Assets/StreamingAssets/Localization/error.csv
  nekoyume/Assets/StreamingAssets/Localization/help_popup.csv
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
  nekoyume/Assets/StreamingAssets/Localization/notification.csv
  nekoyume/Assets/StreamingAssets/Localization/pet_option_description.csv
  nekoyume/Assets/StreamingAssets/Localization/quest.csv
  nekoyume/Assets/StreamingAssets/Localization/sentence.csv
  nekoyume/Assets/StreamingAssets/Localization/skill_description.csv
  nekoyume/Assets/StreamingAssets/Localization/skill_name.csv
  nekoyume/Assets/StreamingAssets/Localization/speech_bubble.csv
  nekoyume/Assets/StreamingAssets/Localization/tutorial.csv
  nekoyume/Assets/StreamingAssets/Localization/worldboss_info.csv
Labels: Extra Large

#3854 [Design]UI_CombinationMain_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
Labels: Extra Small

#3855 [Design]UI_RankPopup_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
Labels: Small

#3856 [Design]ItemView_Prefabs_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView.prefab
Labels: Extra Small

#3857 [Design]UI_ArenaBattlePreparation_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattlePreparation.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Button_Plus.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Button_Plus.png.meta
Labels: Large

#3860 [Design]UI_BattleResultPopup_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattleResultPopup.prefab
Labels: Medium

#3853 apply EventDungeonCourageAmount
  nekoyume/Assets/_Scripts/GeneratedApi/SeasonPassServiceClient.cs
  nekoyume/Assets/_Scripts/SeasonPassService/SeasonPassServiceManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/StageInformation.cs
Labels: Extra Small
