Repository planetarium/NineChronicles, pull requests merged in 2023-02, with the labels that each got.

#2326 Update Rune Skill l10n Change
  nekoyume/Assets/StreamingAssets/Localization/skill_description.csv
Labels: Extra Small

#2291 Consider QA build for `macOS`
  nekoyume/Assets/Editor/Builder.cs
Labels: Extra Small

#2331 [bugfix] RuneResult CP fix
  nekoyume/Assets/Resources/UI/Animations/UIRuneEnhancementResult@Close.anim
  nekoyume/Assets/Resources/UI/Animations/UIRuneEnhancementResult@Loop_Fail.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_RuneEnhancementResultScreen.prefab
Labels: Medium

#2330 [Design] ArenaBattle Fix
  nekoyume/Assets/Resources/UI/Animations/UIArenaBattleContoller.controller
  nekoyume/Assets/Resources/UI/Animations/UIArenaBattleContoller.controller.meta
  nekoyume/Assets/Resources/UI/Animations/UIArenaBattleController@Close.anim
  nekoyume/Assets/Resources/UI/Animations/UIArenaBattleController@Close.anim.meta
  nekoyume/Assets/Resources/UI/Animations/UIArenaBattleController@Show.anim
  nekoyume/Assets/Resources/UI/Animations/UIArenaBattleController@Show.anim.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattle.prefab
Labels: Extra Large

#2337 Fix if statement about skipSynopsys
  nekoyume/Assets/_Scripts/UI/Widget/Screen/PreloadingScreen.cs
Labels: Extra Small

#2340 Update Item l10n
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
Labels: Extra Small

#2333 [bugfix] Loading Screen fix
  nekoyume/Assets/Resources/Tutorial/Effect/Fx_TutorialArrow.mat
  nekoyume/Assets/Resources/UI/Animations/LoadingImageContainerController@Idle.anim
  nekoyume/Assets/Resources/UI/Animations/LoadingImageContainerController@Start.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_DataLoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_LoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PreLoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_UnlockWorldLoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMapLoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Textures/00_Loading/UI_loading_bg.png
  nekoyume/Assets/Resources/UI/Textures/00_Loading/UI_loading_bg.png.meta
  nekoyume/Assets/Resources/UI/Textures/00_Loading/UI_loading_lens flare.png.meta
  nekoyume/Assets/UIResources/Font/NATZSB__ SDF Material - DiceCountLine.mat
Labels: Extra Large

#2332 [bugfix] Chapter4 Background fix
  nekoyume/Assets/Resources/Prefab/Background/Chapter_04_03.prefab
Labels: Extra Small

#2313 Features/extend profile setting
  nekoyume/Assets/AddressableAssets/UI/Module/CharacterView/DetailedCharacterView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CharacterView/FramedCharacterView.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarSelectPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarSelectPopup.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_EnemyPlayerStatus.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Status.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Rank.prefab
Labels: Extra Large

#2334 Features/pet equip workshop
  nekoyume/Assets/AddressableAssets/UI/Module/Inventory.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/Pet_Slot.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/Pet_Slot.prefab.meta
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_PFP.spriteatlas
  nekoyume/Assets/Resources/UI/Icons/Item/1001.png
  nekoyume/Assets/Resources/UI/Icons/Item/1002.png
  nekoyume/Assets/Resources/UI/Icons/Item/1003.png
  nekoyume/Assets/Resources/UI/Icons/Item/1004.png
  nekoyume/Assets/Resources/UI/Prefabs/CombinationSlot.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotsPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SelectCraftSlotPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SelectCraftSlotPopup.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_WhatPetPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WhatPetPopup.prefab.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/EquipPet_Mask.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/EquipPet_bg_1.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/EquipPet_bg_Empty.png
Labels: Extra Large

#2343 [Design]PetPFP_Resource_Add
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_PFP.spriteatlas
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/DccCollection_Character_floor.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/DccCollection_Character_floor.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/DccCollection_Popup_Title_Bg.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/DccCollection_Popup_Title_Bg.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/DccCollection_Result_Obj.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/DccCollection_Result_Obj.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/DccCollection_Type_Bg.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/DccCollection_Type_Bg.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/PetCard_1001.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/PetCard_1001.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/PetCard_1002.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/PetCard_1002.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/PetCard_1003.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/PetCard_1003.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/PetCard_1004.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/PetCard_1004.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/PetCard_Empty.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/PetCard_Empty.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/PetCard_Light.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/PetCard_Light.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/PetCard_Name_Bg.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/PetCard_Name_Bg.png.meta
Labels: Extra Large

#2346 Merge extend-avatar-information into 2023q1-pfp
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccSettingPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccSettingPopup.prefab.meta
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Popup/UI_Popup_bg_09.png.meta
Labels: Small

#2352 [Design] Medal fix
  nekoyume/Assets/Resources/UI/Icons/Item/700108.png
  nekoyume/Assets/Resources/UI/Icons/Item/700206.png
  nekoyume/Assets/Resources/UI/Icons/Item/700306.png
Labels: No Changes

#2356 [bugfix] Raycast Target fix
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CombinationBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/ShopBtn.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
Labels: Medium

#2357 Introduce dcc api
  nekoyume/Assets/StreamingAssets/url.json
  nekoyume/Assets/StreamingAssets/url.json.meta
  nekoyume/Assets/_Scripts/Game/Dcc.cs
  nekoyume/Assets/_Scripts/Game/Dcc.cs.meta
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs
  nekoyume/Assets/_Scripts/Helper/Url.cs
  nekoyume/Assets/_Scripts/Helper/Url.cs.meta
  nekoyume/Assets/_Scripts/UI/Model/DccAvatars.cs
  nekoyume/Assets/_Scripts/UI/Model/DccAvatars.cs.meta
  nekoyume/Assets/_Scripts/UI/RequestManager.cs
Labels: Small

#2354 Fix/rpc-reconnection
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
Labels: Extra Small

#2345 UI/rank popup edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattle.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
Labels: Extra Large

#2362 Delete title when GameObject is deactivated
  nekoyume/Assets/_Scripts/Game/Character/CharacterAppearance.cs
Labels: bug, Extra Small

#2367 Fix initialization of `RPCAgent`
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
Labels: bug, Extra Small

#2366 fix bug about rpc agent logging
  nekoyume/Assets/_Scripts/BlockChain/RPCAgent.cs
Labels: Extra Small

#2369 Introduce D:CC collection UI
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/BoxCatBtnContainers.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/PFP/PetCardSlot.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/PFP/PetSlotCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/PFP/PetSlotCell.prefab.meta
  nekoyume/Assets/Resources/ScriptableObject/PetRenderingData.asset
  nekoyume/Assets/Resources/ScriptableObject/PetRenderingData.asset.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccCollection.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccMain.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetEnhancementPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetEnhancementPopup.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetLevelupResultScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetSummonPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetSummonResultScreen.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/PetRenderingScriptableObject.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/PetRenderingScriptableObject.cs.meta
  nekoyume/Assets/_Scripts/Helper/LoadingHelper.cs
  nekoyume/Assets/_Scripts/Helper/PetRenderingHelper.cs
  nekoyume/Assets/_Scripts/Helper/PetRenderingHelper.cs.meta
  nekoyume/Assets/_Scripts/State/PetStates.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/DccMenu.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/DccMenu.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/Lobby/MainMenu.cs
  nekoyume/Assets/_Scripts/UI/Module/Pet.meta
  nekoyume/Assets/_Scripts/UI/Module/Pet/PetSlotView.cs
  nekoyume/Assets/_Scripts/UI/Module/Pet/PetSlotView.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/Pet/PetSlotViewModel.cs
  nekoyume/Assets/_Scripts/UI/Module/Pet/PetSlotViewModel.cs.meta
  nekoyume/Assets/_Scripts/UI/Scroller/PetSlotCell.cs
  nekoyume/Assets/_Scripts/UI/Scroller/PetSlotCell.cs.meta
  nekoyume/Assets/_Scripts/UI/Scroller/PetSlotScroll.cs
  nekoyume/Assets/_Scripts/UI/Scroller/PetSlotScroll.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/DccCollection.cs
  nekoyume/Assets/_Scripts/UI/Widget/DccCollection.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/DccMain.cs
  nekoyume/Assets/_Scripts/UI/Widget/DccMain.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/PetEnhancementPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/PetEnhancementPopup.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Screen/PetLevelUpResultScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/PetLevelUpResultScreen.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Screen/PetSummonResultScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/PetSummonResultScreen.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Screen/PreloadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
Labels: Extra Large

#2372 UI/popup title
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_PFP.spriteatlas
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetEnhancementPopup.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/DccCollection_Popup_Title_Bg.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/DccCollection_Popup_Title_Bg.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/DccCollection_Result_Obj.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/DccCollection_Result_Obj.png.meta
Labels: Medium

#2374 fix bug about IconAndButtonSystem
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/IconAndButtonSystem.cs
Labels: Extra Small

#2377 UI/pfp resorce change
  nekoyume/Assets/Resources/UI/Animations/UIPfpSummonResultController@Loop.anim
  nekoyume/Assets/Resources/UI/Animations/UIPfpSummonResultController@Show.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccCollection.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetLevelUpResultScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetSummonResultScreen.prefab
  nekoyume/Assets/Sprites/Background/PFP/Bg_PFP_Levelup_7.png
  nekoyume/Assets/Sprites/Background/PFP/Bg_PFP_Levelup_7.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Inventory/UI_icon_item_bg_16.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/DccCollection_Character_floor.png
Labels: Large

#2379 UI/pfp character speed down
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/BoxCatBtnContainers.prefab
Labels: Extra Small

#2373 bugfix synopsis
  nekoyume/Assets/Resources/Character/UI_Avatar.prefab
  nekoyume/Assets/Resources/Character/UI_Avatar.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_Synopsis.prefab
  nekoyume/Assets/_Scripts/Game/Avatar/AvatarSpineController.cs
  nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
Labels: bug, Extra Large

#2378 Improve dcc collection UI
  nekoyume/Assets/AddressableAssets/UI/Module/PFP/PetInfoView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/PFP/PetInfoView.prefab.meta
  nekoyume/Assets/Resources/ScriptableObject/PetRenderingData.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccCollection.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccMain.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetEnhancementPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetLevelUpResultScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetSummonResultScreen.prefab
  nekoyume/Assets/StreamingAssets/Localization/pet_option_description.csv
  nekoyume/Assets/_Scripts/Helper/PetRenderingHelper.cs
  nekoyume/Assets/_Scripts/UI/Module/Pet/PetInfoView.cs
  nekoyume/Assets/_Scripts/UI/Module/Pet/PetInfoView.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/Pet/PetSlotView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/PetEnhancementPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/PetLevelUpResultScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/PetSummonResultScreen.cs
Labels: Extra Large

#2384 [bugfix] image add
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
  nekoyume/Assets/Sprites/Background/MainMenu/worldboss_03_Base.png
  nekoyume/Assets/Sprites/Background/MainMenu/worldboss_03_Base.png.meta
  nekoyume/Assets/Sprites/Background/MainMenu/worldboss_03_Support_Back.png
  nekoyume/Assets/Sprites/Background/MainMenu/worldboss_03_Support_Back.png.meta
Labels: Large

#2386 [Feature] Introduce new build CI (Only for android)
  .github/workflows/build.yml
  .github/workflows/new-build.yml
  nekoyume/Assets/Editor/Builder.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Large

#2382 Update `RuneState` and `RuneStoneBalance` on updating avatar
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
  nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/PreloadingScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/Synopsis.cs
Labels: Extra Small

#2388 fix mailbox serialize bug about local mail
  .github/workflows/build.yml
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Helper/LocalMailHelper.cs
Labels: Extra Small

#2389 merge rc-v100361-3 into development
  .github/workflows/build.yml
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Helper/LocalMailHelper.cs
Labels: Extra Small

#2387 UI/pfp collection edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccCollection.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/DccCollection_Character_floor.png
Labels: Extra Large

#2391 Bug fix on pet selection
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/PetDescriptionView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/PetDescriptionView.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetSelectionPopup.prefab
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/State/PetStates.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Module/PetDescriptionView.cs
  nekoyume/Assets/_Scripts/UI/Module/PetInventory.cs
  nekoyume/Assets/_Scripts/UI/Module/TextButton.cs
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
  nekoyume/Assets/_Scripts/UI/Widget/PetSelectionPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotsPopup.cs
Labels: Medium

#2393 Improve D:CC collection UI
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccCollection.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetEnhancementPopup.prefab
  nekoyume/Assets/_Scripts/Helper/PetRenderingHelper.cs
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/DccMenu.cs
  nekoyume/Assets/_Scripts/UI/Module/Pet/PetSlotView.cs
  nekoyume/Assets/_Scripts/UI/Module/Pet/PetSlotViewModel.cs
  nekoyume/Assets/_Scripts/UI/Widget/DccCollection.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/PetEnhancementPopup.cs
Labels: Large

#2395 merge 2023q1-pfp into prepare-v100380
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/PetDescriptionView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/PetDescriptionView.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccCollection.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetEnhancementPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetSelectionPopup.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_PFP/DccCollection_Character_floor.png
  nekoyume/Assets/_Scripts/BlockChain/ActionManager.cs
  nekoyume/Assets/_Scripts/Helper/PetRenderingHelper.cs
  nekoyume/Assets/_Scripts/State/PetStates.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/DccMenu.cs
  nekoyume/Assets/_Scripts/UI/Module/Pet/PetSlotView.cs
  nekoyume/Assets/_Scripts/UI/Module/Pet/PetSlotViewModel.cs
  nekoyume/Assets/_Scripts/UI/Module/PetDescriptionView.cs
  nekoyume/Assets/_Scripts/UI/Module/PetInventory.cs
  nekoyume/Assets/_Scripts/UI/Module/TextButton.cs
  nekoyume/Assets/_Scripts/UI/Widget/DccCollection.cs
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
  nekoyume/Assets/_Scripts/UI/Widget/PetSelectionPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotsPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/PetEnhancementPopup.cs
Labels: Extra Large

#2399 UpdateCurrentAvatarState to async-await
  nekoyume/Assets/_Scripts/BlockChain/ActionRenderHandler.cs
Labels: Extra Small

#2400 link missing object in Alert popup
  nekoyume/Assets/Resources/UI/Prefabs/UI_Alert.prefab
Labels: Extra Small

#2397 [Design]RankCell_Prefabs_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/RankCell.prefab
Labels: Extra Small

#2396 [Design]UI_Menu_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
Labels: Extra Small

#2401 add Status and EventBanner closing to battle ui
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBattle.cs
  nekoyume/Assets/_Scripts/UI/Widget/Battle.cs
Labels: Extra Small

#2403 Bugfix/UI 370 fix 2
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/MailCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CombinationItemInformation.prefab
  nekoyume/Assets/Resources/UI/Animations/UICombinationController_Craft@Consumable.anim
  nekoyume/Assets/Resources/UI/Animations/UICombinationController_Craft@Equipment.anim
  nekoyume/Assets/Resources/UI/Animations/UICombinationController_Craft@Show.anim
  nekoyume/Assets/Resources/UI/Animations/UICombinationController_Grind@AnySlotState.anim
  nekoyume/Assets/Resources/UI/Animations/UICombinationController_Grind@FirstRegister.anim
  nekoyume/Assets/Resources/UI/Animations/UICombinationController_Grind@NormalState.anim
  nekoyume/Assets/Resources/UI/Animations/UICombinationController_Grind@Show.anim
  nekoyume/Assets/Resources/UI/Animations/UICombinationController_Upgrade@PostRegisterBase.anim
  nekoyume/Assets/Resources/UI/Animations/UICombinationController_Upgrade@Show.anim
  nekoyume/Assets/Resources/UI/Prefabs/UI_BuyItemInformationPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Grind.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_HeaderMenuStatic.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MailPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPopup.prefab
Labels: Extra Large

#2407 handle not updated ncg at GetBalance()
  nekoyume/Assets/_Scripts/BlockChain/ActionHandler.cs
Labels: Extra Small

#2402 Update common & description L10n Change
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
Labels: Extra Small

#2404 Bugfix/UI 370 tutorial fix
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CombinationBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/TutorialDummys.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/WaveSkill/A.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/WaveSkill/S.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/WaveSkill/SS.prefab
  nekoyume/Assets/Resources/Tutorial/Prefab/Item_DialogBox.prefab
  nekoyume/Assets/Resources/UI/Prefabs/BonusBuffView.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattle.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MailPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MaterialTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/UIResources/Content/Effect/BG/Buff_Grade_3_eff.png
  nekoyume/Assets/UIResources/Content/Effect/BG/Buff_Grade_3_eff.png.meta
  nekoyume/Assets/UIResources/Content/Effect/BG/Buff_Grade_4_eff.png
  nekoyume/Assets/UIResources/Content/Effect/BG/Buff_Grade_4_eff.png.meta
  nekoyume/Assets/UIResources/Content/Effect/BG/Buff_Grade_eff.png
  nekoyume/Assets/UIResources/Content/Effect/BG/Buff_Grade_eff.png.meta
Labels: Extra Large

#2408 Add PetButton in menu
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
Labels: Medium

#2409 feat: Contain readme and oss in build result
  nekoyume/Assets/Editor/Builder.cs
Labels: Extra Small

#2410 fix l10n csv
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
Labels: Extra Small
