Repository planetarium/NineChronicles, pull requests merged in 2024-03, with the labels that each got.

#4317 UI/menu character scaffolding edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Sprites/Background/MainMenu/Object_Midday/bg_character_main_03.png
  nekoyume/Assets/Sprites/Background/MainMenu/Object_Midday/bg_character_main_10.png
Labels: Large

#4307 fix ui avatar prefab
  nekoyume/Assets/Resources/Character/UI_Avatar.prefab
Labels: Extra Large

#4322 UI/staking polishing2
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/StakingBtn.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Common_Bg_Gradiant.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Common_Bg_Gradiant.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/Light.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/Light.png.meta
Labels: Extra Large

#4286 fix: GitHub actions
  .github/workflows/android-build-and-release.yml
  nekoyume/.gitignore
  nekoyume/Assets/NineChronicles/GoogleServices/google-services.json
  nekoyume/Assets/NineChronicles/GoogleServices/google-services.json.meta
  nekoyume/Assets/Plugins/Android/FirebaseApp.androidlib.meta
  nekoyume/Assets/Plugins/Android/FirebaseApp.androidlib/AndroidManifest.xml
  nekoyume/Assets/Plugins/Android/FirebaseApp.androidlib/AndroidManifest.xml.meta
  nekoyume/Assets/Plugins/Android/FirebaseApp.androidlib/project.properties
  nekoyume/Assets/Plugins/Android/FirebaseApp.androidlib/project.properties.meta
  nekoyume/Assets/Plugins/Android/FirebaseApp.androidlib/res.meta
  nekoyume/Assets/Plugins/Android/FirebaseApp.androidlib/res/values.meta
  nekoyume/Assets/Plugins/Android/FirebaseApp.androidlib/res/values/google-services.xml
  nekoyume/Assets/Plugins/Android/FirebaseApp.androidlib/res/values/google-services.xml.meta
  nekoyume/Assets/StreamingAssets/google-services-desktop.json
  nekoyume/Assets/StreamingAssets/google-services-desktop.json.meta
Labels: Medium

#4328 fix required level bugs
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/BoxCatBtnContainers.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CollectionBtn.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/_Scripts/Game/LiveAsset/GameConfig.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/MainMenu.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/SeasonPassMenu.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/StakingMenu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CollectionEffectPopup.cs
Labels: Extra Large

#4327 fix UIPopupController animations
  nekoyume/Assets/Resources/UI/Animations/UIPopupController@Close.anim
  nekoyume/Assets/Resources/UI/Animations/UIPopupController@Show.anim
Labels: Extra Small

#4285 Caching enemy cp value
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs
Labels: Extra Small

#4348 [Design]UI_SweepResultPopup_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_SweepResultPopup.prefab
Labels: Medium

#4346 [Design]UI_ArenaJoin_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaJoin.prefab
Labels: Small

#4342 [Design]UI_StageInformation_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_StageInformation.prefab
Labels: Extra Small

#4304 add on force toggle on event tap method
  nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.cs
Labels: Extra Small

#4372 resolve #4349, polish Ingame monster collection UI(in lobby)
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/StakingBtn.prefab
  nekoyume/Assets/_Scripts/UI/Module/Lobby/StakingMenu.cs
Labels: Medium

#4400 use RewardScreen when render `ClaimStakeReward`
  nekoyume/Assets/Resources/UI/Prefabs/UI_RewardScreen.prefab
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Tutorial/TutorialController.cs
Labels: Small

#4399 [Design]ArmorIcon_Resource_Edit
  nekoyume/Assets/Resources/UI/Icons/Item/10230000.png
  nekoyume/Assets/Resources/UI/Icons/Item/10231000.png
  nekoyume/Assets/Resources/UI/Icons/Item/10232000.png
  nekoyume/Assets/Resources/UI/Icons/Item/10233000.png
  nekoyume/Assets/Resources/UI/Icons/Item/10234000.png
Labels: No Changes

#4344 [Design]ItemView_2_Prefabs_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/CostItemView.prefab
Labels: Extra Small

#4321 remove invoking OneLineSystem.Push()
  nekoyume/Assets/_Scripts/UI/Widget/Screen/RuneCombineResultScreen.cs
Labels: Extra Small

#4371 fix aura effect flip issue
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_blue_01.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_blue_02.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_blue_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_green_01.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_green_02.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_green_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_violet_01.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_violet_02.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_violet_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_yellow_01.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_yellow_02.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_adventure_yellow_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_blue_01.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_blue_02.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_blue_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_green_01.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_green_02.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_green_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_violet_01.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_violet_02.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_violet_03.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_yellow_01.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_yellow_02.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/Aura/aura_arena_yellow_03.prefab
Labels: Extra Large

#4369 Feature/collection list sorting
  nekoyume/Assets/Resources/UI/Prefabs/UI_Collection.prefab
  nekoyume/Assets/_Scripts/UI/Model/CollectionMaterial.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/CollectionItemView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Collection.cs
Labels: Medium

#4364 Feature/collection sorting group
  nekoyume/Assets/Resources/UI/Prefabs/UI_Collection.prefab
  nekoyume/Assets/_Scripts/UI/Model/CollectionMaterial.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/CollectionItemView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Collection.cs
Labels: Medium

#4401 bugfix about `StakingMenu`
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/StakingBtn.prefab
  nekoyume/Assets/_Scripts/Blockchain/StateGetter.TryGet.cs
  nekoyume/Assets/_Scripts/UI/Module/Lobby/StakingMenu.cs
Labels: Extra Small

#4177 iap error popup l10n fix
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
Labels: Extra Small

#4246 effect test scene setting
  nekoyume/Assets/_Scenes/uiTest_Grade.unity
Labels: No Changes

#4356 8World Skill Desc L10n Change
  nekoyume/Assets/StreamingAssets/Localization/skill_description.csv
Labels: Extra Small

#4415 UI/filter add
  nekoyume/Assets/AddressableAssets/UI/Module/Button/FilterButtonCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Button/FilterButtonCell.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_FilterPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_FilterPopup.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Common_TabBtn_Select2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Common_TabBtn_Select2.png.meta
Labels: Extra Large

#4416 apply shatter strike effect
  nekoyume/Assets/Editor/Testbed/TestbedCreateAvatar.asset
  nekoyume/Assets/Resources/VFX/Prefabs/ShatterStrike_casting.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/ShatterStrike_magical.prefab
  nekoyume/Assets/_Scenes/Game.unity
  nekoyume/Assets/_Scripts/Game/Arena.cs
  nekoyume/Assets/_Scripts/Game/Character/ArenaCharacter.cs
  nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs
  nekoyume/Assets/_Scripts/Game/Character/RaidCharacter.cs
  nekoyume/Assets/_Scripts/Game/RaidStage.cs
  nekoyume/Assets/_Scripts/Game/Stage.cs
Labels: Extra Large

#4418 [Design]NewGradeItem_Resource_Add
  nekoyume/Assets/Resources/UI/Icons/Item/303005.png
  nekoyume/Assets/Resources/UI/Icons/Item/303005.png.meta
  nekoyume/Assets/Resources/UI/Icons/Item/303105.png
  nekoyume/Assets/Resources/UI/Icons/Item/303105.png.meta
  nekoyume/Assets/Resources/UI/Icons/Item/303205.png
  nekoyume/Assets/Resources/UI/Icons/Item/303205.png.meta
  nekoyume/Assets/Resources/UI/Icons/Item/303305.png
  nekoyume/Assets/Resources/UI/Icons/Item/303305.png.meta
  nekoyume/Assets/Resources/UI/Icons/Item/303405.png
  nekoyume/Assets/Resources/UI/Icons/Item/303405.png.meta
Labels: Extra Large

#4426 [Design]UI_MobileShop_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
Labels: Extra Small

#4420 add Migration button to StakingPopup and introduce something...
  nekoyume/Assets/Packages/Libplanet.Action.dll
  nekoyume/Assets/Packages/Libplanet.Common.dll
  nekoyume/Assets/Packages/Libplanet.Crypto.dll
  nekoyume/Assets/Packages/Libplanet.RocksDBStore.dll
  nekoyume/Assets/Packages/Libplanet.Store.dll
  nekoyume/Assets/Packages/Libplanet.Types.dll
  nekoyume/Assets/Packages/Libplanet.dll
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Extensions/TextMeshProExtensions.cs
  nekoyume/Assets/_Scripts/Extensions/TextMeshProExtensions.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/IconAndButtonSystem.cs
Labels: Large

#4363 Feature/collection filter search
  nekoyume/Assets/Resources/UI/Prefabs/UI_Collection.prefab
  nekoyume/Assets/_Scripts/UI/Model/CollectionMaterial.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/CollectionItemView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Collection.cs
Labels: Medium

#4441 [Design]UI_MobileShop_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
Labels: Small

#4454 Upgrade Libplanet assemblies to 4.0.6
  nekoyume/Assets/Packages/Libplanet.Action.dll
  nekoyume/Assets/Packages/Libplanet.Common.dll
  nekoyume/Assets/Packages/Libplanet.Crypto.dll
  nekoyume/Assets/Packages/Libplanet.RocksDBStore.dll
  nekoyume/Assets/Packages/Libplanet.Store.dll
  nekoyume/Assets/Packages/Libplanet.Types.dll
  nekoyume/Assets/Packages/Libplanet.dll
Labels: No Changes

#4425 [Design]UI_Craft_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
Labels: Extra Large

#4457 UI/mobile shop bg edit2
  nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
Labels: Small

#4448 adjust l10n to StakingPopup
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Large

#4462 Issue/4403
  nekoyume/Assets/Resources/ScriptableObject/EventData.asset
Labels: Large

#4431 [Design]UI_MaterialNavigationPopup_Prefab_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_MaterialNavigationPopup.prefab
Labels: Medium

#4422 Update Skill L10n Change
  nekoyume/Assets/StreamingAssets/Localization/skill_description.csv
  nekoyume/Assets/StreamingAssets/Localization/skill_name.csv
Labels: Extra Small

#4444 UI/quick quest edit240314
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/GuidedQuestCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/GuidedQuest.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Battle.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
Labels: Extra Large

#4445 [Design]PopupTitle_Prefabs_Text_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_Alert.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BlockFailTitleOneButtonSystem.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ConfirmConnectPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ConfirmPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccSettingPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_InputBoxPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetSelectionPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ProfileSelectPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RedeemCode.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPassPremiumPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_TitleOneButtonSystem.prefab
Labels: Extra Large

#4453 [Design]MailCell_Prefabs_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/MailCell.prefab
Labels: Extra Small

#4460 UI/tooltip button text edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_ConsumableTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_FungibleAssetTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemCountableAndPricePopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RuneTooltip.prefab
Labels: Extra Large

#4459 fix new skill text info
  nekoyume/Assets/_Scripts/Extensions/SkillExtensions.cs
  nekoyume/Assets/_Scripts/UI/Module/Common/SkillPositionTooltip.cs
Labels: Extra Small

#4461 add message log
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
Labels: Extra Small

#4465 Update L10n & Sub Recipe Change
  nekoyume/Assets/Resources/Recipe/EquipmentSubRecipeTab.json
  nekoyume/Assets/StreamingAssets/Localization/character_name.csv
  nekoyume/Assets/StreamingAssets/Localization/collection.csv
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
  nekoyume/Assets/StreamingAssets/Localization/skill_description.csv
  nekoyume/Assets/StreamingAssets/Localization/skill_name.csv
Labels: Large

#4468 Enable guest login button check options
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Helper/CommandLineOptions.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Extra Small

#4449 UI/monster spine edit240314
  nekoyume/Assets/AddressableAssets/Character/Monster/201003/201003.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Monster/201003/201003.png
  nekoyume/Assets/AddressableAssets/Character/Monster/201003/201003.skel.bytes
  nekoyume/Assets/AddressableAssets/Character/Monster/201005/201005.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Monster/201005/201005.png
  nekoyume/Assets/AddressableAssets/Character/Monster/201005/201005.skel.bytes
  nekoyume/Assets/AddressableAssets/Character/Monster/203004/203004.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Monster/203004/203004.png
  nekoyume/Assets/AddressableAssets/Character/Monster/203004/203004.skel.bytes
  nekoyume/Assets/AddressableAssets/Character/Monster/203006/203006.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Monster/203006/203006.png
  nekoyume/Assets/AddressableAssets/Character/Monster/203006/203006.skel.bytes
  nekoyume/Assets/AddressableAssets/Character/Monster/205005/205005.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Monster/205005/205005.png
  nekoyume/Assets/AddressableAssets/Character/Monster/205005/205005.skel.bytes
  nekoyume/Assets/AddressableAssets/Character/Monster/206004/206004.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Monster/206004/206004.png
  nekoyume/Assets/AddressableAssets/Character/Monster/206004/206004.skel.bytes
  nekoyume/Assets/AddressableAssets/Character/Monster/206006/206006.skel.bytes
  nekoyume/Assets/AddressableAssets/Character/Monster/207004/207004.skel.bytes
  nekoyume/Assets/AddressableAssets/Character/Monster/207006/207006.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Monster/207006/207006.png
  nekoyume/Assets/AddressableAssets/Character/Monster/207006/207006.skel.bytes
  nekoyume/Assets/AddressableAssets/Character/Monster/208003/208003.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Monster/208003/208003.png
  nekoyume/Assets/AddressableAssets/Character/Monster/208003/208003.skel.bytes
  nekoyume/Assets/AddressableAssets/Character/Monster/208004/208004.skel.bytes
  nekoyume/Assets/AddressableAssets/Character/Monster/208005/208005.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Monster/208005/208005.png
  nekoyume/Assets/AddressableAssets/Character/Monster/208005/208005.skel.bytes
  nekoyume/Assets/AddressableAssets/Character/Monster/208006/208006.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Monster/208006/208006.png
  nekoyume/Assets/AddressableAssets/Character/Monster/208006/208006.skel.bytes
Labels: Extra Large

#4464 double check when purchase product
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ShopListPopup.cs
Labels: Extra Small

#4413 Feature/collection filter option
  nekoyume/Assets/AddressableAssets/UI/Module/Button/FilterButtonCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Button/FilterButtonCell.prefab.meta
  nekoyume/Assets/Packages/Libplanet.Action.dll
  nekoyume/Assets/Packages/Libplanet.Common.dll
  nekoyume/Assets/Packages/Libplanet.Crypto.dll
  nekoyume/Assets/Packages/Libplanet.RocksDBStore.dll
  nekoyume/Assets/Packages/Libplanet.Store.dll
  nekoyume/Assets/Packages/Libplanet.Types.dll
  nekoyume/Assets/Packages/Libplanet.dll
  nekoyume/Assets/Resources/UI/Prefabs/UI_Collection.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CollectionItemFilterPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CollectionItemFilterPopup.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Icon_Filter.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/Icon_Filter.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Common_TabBtn_Normal2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Common_TabBtn_Normal2.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Common_TabBtn_Select2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Shop/Common_TabBtn_Select2.png.meta
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Model/CollectionMaterial.cs
  nekoyume/Assets/_Scripts/UI/Widget/Collection.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CollectionItemFilterPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CollectionItemFilterPopup.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ItemFilterPopupBase.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ItemFilterPopupBase.cs.meta
Labels: Extra Large

#4467 product local value refresh
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
Labels: Extra Small

#4428 add collection material AcquisitionPlace button
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CollectionBtn.prefab
  nekoyume/Assets/Resources/UI/Animations/UICombinationController_Craft.controller
  nekoyume/Assets/Resources/UI/Prefabs/UI_Collection.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
  nekoyume/Assets/_Scripts/UI/Module/Button/AcquisitionPlaceButton.cs
  nekoyume/Assets/_Scripts/UI/Module/CollectionMaterialInfo.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
  nekoyume/Assets/_Scripts/UI/Shop/ShopView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Collection.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
  nekoyume/Assets/_Scripts/UI/Widget/Tooltip/MaterialTooltip.cs
Labels: Extra Large

#4472 Collection UI polishing
  nekoyume/Assets/AddressableAssets/UI/Module/Collection/CollectionCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView_Collection.prefab
  nekoyume/Assets/Resources/UI/Animations/Collecting_ItemSlot@Register.anim
  nekoyume/Assets/Resources/UI/Animations/ItemView_Collection.controller
  nekoyume/Assets/Resources/UI/Animations/ItemView_Collection.controller.meta
  nekoyume/Assets/Resources/UI/Animations/UI_CollectionResultPopup.controller
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_BattlePreparation.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CollectionRegistrationPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RaidPreparation.prefab
  nekoyume/Assets/_Scripts/UI/Module/AvatarInformation.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/CollectionItemView.cs
  nekoyume/Assets/_Scripts/UI/Scroller/CollectionCell.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/AvatarInfoPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CollectionResultPopup.cs
Labels: Extra Large

#4473 Upgrade Libplanet assemblies to 4.0.6
  nekoyume/Assets/Packages/Libplanet.Action.dll
  nekoyume/Assets/Packages/Libplanet.Common.dll
  nekoyume/Assets/Packages/Libplanet.Crypto.dll
  nekoyume/Assets/Packages/Libplanet.RocksDBStore.dll
  nekoyume/Assets/Packages/Libplanet.Store.dll
  nekoyume/Assets/Packages/Libplanet.Types.dll
  nekoyume/Assets/Packages/Libplanet.dll
Labels: No Changes

#4478 fix google-services.json path at android build ci
  .github/workflows/android-build-and-release.yml
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#4484 Release/160.0.2 to prepare/160.0.x
  .github/workflows/android-build-and-release.yml
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#4522 resolve #4395, fix UI Particle prefabs
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CollectionBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/PatrolBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/SeasonPassBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/StakingBtn.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Battle.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_StageProgressBar.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/PraiseVFX.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/StageProgressBarVFX.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/UI_patrolreward_000102.prefab
Labels: Extra Large

#4483 add go to collection in craft ui
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
Labels: Extra Small

#4486 Feature/collection required text
  nekoyume/Assets/Resources/UI/Prefabs/UI_Collection.prefab
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/Model/CollectionMaterial.cs
  nekoyume/Assets/_Scripts/UI/Module/CollectionMaterialInfo.cs
  nekoyume/Assets/_Scripts/UI/Widget/Collection.cs
Labels: Extra Large

#4492 [Design]UI_ShopBuy_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
Labels: Medium

#4539 condition setting to claim reward button of StakingPopup
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Extra Small

#4542 remove CoWorkshopItemMove at RuneCombineResultScreen
  nekoyume/Assets/_Scripts/UI/Widget/Screen/RuneCombineResultScreen.cs
Labels: Extra Small

#4537 save last stage clear before response and check
  nekoyume/Assets/_Scripts/Game/Stage.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
Labels: Extra Small

#4540 change tutorial target object to real button from dummy
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
Labels: Extra Small

#4536 Issue/4501
  nekoyume/Assets/AddressableAssets/UI/Module/Button/FilterButtonCell.prefab
  nekoyume/Assets/Editor/ToggleEditor.cs
  nekoyume/Assets/_Scripts/UI/Module/ToggleDropdown/Toggle.cs
  nekoyume/Assets/_Scripts/UI/Widget/Collection.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ItemFilterPopupBase.cs
Labels: Small

#4511 Add Id Sort in collection
  nekoyume/Assets/_Scripts/UI/Widget/Collection.cs
Labels: Extra Small

#4517 fix event dungeon shortcut condition
  nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
Labels: Extra Small

#4516 fix acquisition place icon name
  nekoyume/Assets/_Scripts/UI/Module/Button/AcquisitionPlaceButton.cs
Labels: Extra Small

#4521 change level tap l10n key
  nekoyume/Assets/_Scripts/UI/Widget/Collection.cs
Labels: Extra Small

#4544 UI/qa quick quest edit
  nekoyume/Assets/AddressableAssets/UI/Module/GuidedQuest.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
Labels: Medium

#4545 [Design]Tutorial_Grind_2_Resource_Edit
  nekoyume/Assets/Resources/Tutorial/Image/GuideImage/Tutorial_Grind_2.png
Labels: No Changes

#4538 change upgrade start level(0 -> 1), apply l10n key (4500 & 4502)
  nekoyume/Assets/Resources/UI/Prefabs/UI_CollectionItemFilterPopup.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Collection.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ItemFilterPopupBase.cs
Labels: Medium

#4548 [Design]UI_CombinationSlotPopup_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotPopup.prefab
Labels: Large

#4546 [Design]Tabs_Rank_Prefabs_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/CharacterView/DetailedCharacterView.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Rank.prefab
Labels: Extra Small

#4543 fix ui_Shopbuy prefab for item search
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
Labels: No Changes

#4551 update dialog
  nekoyume/Assets/StreamingAssets/Localization/dialog.csv
Labels: Large

#4547 fix mobile shop item search condition
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
Labels: Extra Small

#4541 Add log when fail product available check
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
Labels: Extra Small

#4554 [Design]UI_ItemTooltip_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_ItemTooltip.prefab
Labels: Large

#4553 add statdebuffLimitDiscription
  nekoyume/Assets/_Scripts/UI/Module/Common/SkillPositionTooltip.cs
Labels: Extra Small

#4552 Bugfix/apply l10n to upgrade
  nekoyume/Assets/Resources/UI/Prefabs/UI_CollectionItemFilterPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
Labels: Extra Small

#4571 fix patrolreward_03 vfx for UI Particle
  nekoyume/Assets/Resources/VFX/Prefabs/UI_patrolreward_03.prefab
Labels: Extra Small

#4574 resolve #4560
  nekoyume/Assets/Resources/ScriptableObject/UI_BonusBuffViewData.asset
  nekoyume/Assets/_Scripts/Editor/EnumToStringAttribute.cs
  nekoyume/Assets/_Scripts/Editor/EnumToStringAttribute.cs.meta
  nekoyume/Assets/_Scripts/Editor/EnumToStringDrawer.cs
  nekoyume/Assets/_Scripts/Editor/EnumToStringDrawer.cs.meta
  nekoyume/Assets/_Scripts/Game/ScriptableObject/BonusBuffIconData.cs
Labels: Small

#4578 UI/monstercollection icon edit
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/StakingBtn.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
Labels: Extra Large

#4577 add staking level 8 icon and object
  nekoyume/Assets/AddressableAssets/UI/Module/StakingBonus.prefab
Labels: Extra Small

#4572 change collection materialinfo active condition
  nekoyume/Assets/_Scripts/UI/Module/CollectionMaterialInfo.cs
Labels: Extra Small

#4570 fix seasonpass info list
  nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPassPremiumPopup.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs
Labels: Extra Small

#4561 fix SeasonPassPremium purchase fail bug
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs
Labels: Extra Small

#4564 fix event dungeon last stage again button
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
Labels: Extra Small

#4566 change descending icon
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/_Scripts/UI/Scroller/RecipeScroll.cs
Labels: Extra Small

#4585 add color changing to staking input field
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Extra Small

#4589 disable dll auto referencing and validating
  nekoyume/Assets/ExternalDependencyManager/Editor/1.2.177/Google.IOSResolver.dll.meta
  nekoyume/Assets/Firebase/Editor/Firebase.Editor.dll.meta
Labels: Small

#4598 change default sort option
  nekoyume/Assets/_Scripts/UI/Widget/Collection.cs
Labels: Extra Small

#4595 remove StageSimulatorV2
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Widget/Development/BattleSimulator.cs
  nekoyume/Assets/_Scripts/UI/Widget/Development/Cheat.cs
Labels: Extra Small

#4603 fix guestButton enable error
  nekoyume/Assets/Resources/UI/Prefabs/UI_IntroScreen.prefab
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Medium

#4607 fix broken VFX(s)
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CombinationBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
  nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_Electric_01_sprite_UI.mat
  nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_Electric_01_sprite_UI.mat.meta
  nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_ob_water_02_UI.mat
  nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_ob_water_02_UI.mat.meta
  nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_smoke_02_UI.mat
  nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_smoke_02_UI.mat.meta
  nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_smoke_fire_sprite_UI.mat
  nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_smoke_fire_sprite_UI.mat.meta
  nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_star_04_UI.mat
  nekoyume/Assets/Resources/VFX/MaterialsTextures/NY_star_04_UI.mat.meta
  nekoyume/Assets/Resources/VFX/Prefabs/UI_Lobby_bg_main_WorldBossVFX.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/UI_Lobby_bg_main_fireVFX.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/UI_main_light.prefab
Labels: Extra Large

#4606 show food spd button in market
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
  nekoyume/Assets/_Scripts/EnumType/ItemSubTypeFilter.cs
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
Labels: Extra Large

#4619 Update Item_description L10n Change
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
Labels: Extra Small

#4621 fix market page index unreset
  nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
Labels: Extra Small

#4625 change dummy position
  nekoyume/Assets/AddressableAssets/UI/Module/TutorialDummys.prefab
Labels: Extra Small

#4627 fix worldbutton input bug
  nekoyume/Assets/AddressableAssets/UI/Module/WorldMap/WorldButton.prefab
Labels: Small

#4628 Update Dispel Skill L10n Change
  nekoyume/Assets/StreamingAssets/Localization/skill_description.csv
Labels: Extra Small

#4629 fix new skill description allow rage
  nekoyume/Assets/_Scripts/UI/Module/Common/SkillPositionTooltip.cs
Labels: Extra Small

#4631 init avatar state after avatar created
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
Labels: Extra Small

#4632 fix not initialize toggle flag
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs
Labels: Extra Small

#4660 Update common L10n Change - UI_SUMMON_GOLDEN_AURA_PHRASE_2
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#4661 fix aura skill description error
  nekoyume/Assets/_Scripts/UI/Module/Common/SkillPositionTooltip.cs
Labels: Small

#4670 Release/160.1.0 to Main
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
  nekoyume/Assets/_Scripts/UI/Module/Common/SkillPositionTooltip.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Small

#4673 backmerge Release/160.1.0 to develop
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
  nekoyume/Assets/_Scripts/UI/Module/Common/SkillPositionTooltip.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Small

#4667 fix broken VFX(s)
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView_Collection.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/RequiredItemView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/PatrolBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/StakingBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/RecipeView/RequiredItemRecipeView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/UpgradeEquipmentSlot.prefab
  nekoyume/Assets/Resources/UI/Prefabs/EquipDesc.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CollectionResultPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/UI_GrindPressVFX.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/UI_patrolreward_000102.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/UI_patrolreward_03.prefab
  nekoyume/Assets/UIResources/Content/Effect/Grade/Distortion_Result_Success.mat
  nekoyume/Assets/UIResources/Content/Effect/Grade/Distortion_WorldBossGrade.mat
  nekoyume/Assets/UIResources/Content/WorldBoss/Effect/WorldBossGrade_01VFX.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Effect/WorldBossGrade_02VFX.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Effect/WorldBossGrade_03VFX.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Effect/WorldBossGrade_04VFX.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Effect/WorldBossGrade_05VFX.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Reward.prefab
Labels: Extra Large

#4668 fix staking menu UI update logic and vfx
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/StakingBtn.prefab
  nekoyume/Assets/_Scripts/UI/Module/Lobby/StakingMenu.cs
Labels: Extra Small

#4674 change ios cicd runner to macos-13
  .github/workflows/ios-build-and-release.yml
Labels: Extra Small

#4676 update iap pakage 4.9.3 -> 4.11.0
  nekoyume/Packages/manifest.json
  nekoyume/Packages/packages-lock.json
Labels: Extra Small

#4677 chore 160.1.1
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#4675 fix combination slot null exception
  nekoyume/Assets/_Scripts/UI/Module/CombinationSlot.cs
Labels: Extra Small
