Repository planetarium/NineChronicles, pull requests merged in 2024-04, with the labels that each got.

#4477 add ios memory optimization debug symbol
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Widget/Base/Widget.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Extra Small

#4659 [Design]UI_CombinationSlotPopup_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotPopup.prefab
Labels: Extra Small

#4663 Add Naver cloud api key for CDN Invalidation
  .github/workflows/build.yml
Labels: Extra Small

#4635 remove redundant avatar init logic
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
Labels: Extra Small

#4586 add delay on RegisterMaterials
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CollectionRegistrationPopup.cs
Labels: Extra Small

#4689 L10n issue
  nekoyume/Assets/StreamingAssets/Localization/collection.csv
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/dialog.csv
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
  nekoyume/Assets/StreamingAssets/Localization/skill_description.csv
Labels: Large

#4662 add collection scroll view animation
  nekoyume/Assets/AddressableAssets/UI/Module/Collection/CollectionCell.prefab
  nekoyume/Assets/Resources/UI/Animations/CollectionCell.controller
  nekoyume/Assets/Resources/UI/Animations/CollectionCell.controller.meta
  nekoyume/Assets/Resources/UI/Animations/CollectionCell@Show.anim
  nekoyume/Assets/Resources/UI/Animations/CollectionCell@Show.anim.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_Collection.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/_Scripts/UI/Scroller/CollectionCell.cs
  nekoyume/Assets/_Scripts/UI/Scroller/CollectionScroll.cs
Labels: Extra Large

#4657 [Design]UI_Craft_Prefabs_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/RecipeView/EquipDesc.prefab
  nekoyume/Assets/Resources/UI/Prefabs/EquipDesc.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Popup/UI_bg_frame_EventPeriod.png.meta
  nekoyume/Assets/_Scripts/UI/Combination/SubRecipeView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
Labels: Extra Large

#4680 Edit Rune UI for Rune Multi Revelup
  nekoyume/Assets/Resources/UI/Prefabs/UI_Rune.prefab
  nekoyume/Assets/_Scripts/Extensions/RuneCostSheetExtension.cs
  nekoyume/Assets/_Scripts/Extensions/RuneCostSheetExtension.cs.meta
  nekoyume/Assets/_Scripts/UI/Model/RuneCostItem.cs
  nekoyume/Assets/_Scripts/UI/Model/RuneEachCostItem.cs
  nekoyume/Assets/_Scripts/UI/Model/RuneEachCostItem.cs.meta
  nekoyume/Assets/_Scripts/UI/Model/RuneItem.cs
  nekoyume/Assets/_Scripts/UI/Model/RuneOptionView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/RuneEnhancementResultScreen.cs
Labels: Extra Large

#4651 Feature/crossfade background
  nekoyume/Assets/Resources/Prefab/Background/Chapter_01_01.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_01_02.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_01_03.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_02_01.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_02_02.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_02_03.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_03_01.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_03_02.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_03_03.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_04_01.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_04_02.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_04_03.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_05_01.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_05_02.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_05_03.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_06_01.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_06_02.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_06_03.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_07_01.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_07_02.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_07_03.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_08_01.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_08_02.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_08_03.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_99_01.prefab
  nekoyume/Assets/Resources/Prefab/Background/Chapter_Prologue.prefab
  nekoyume/Assets/Resources/Prefab/Background/EventDungeon_01_01.prefab
  nekoyume/Assets/Resources/Prefab/Background/EventDungeon_01_02.prefab
  nekoyume/Assets/Resources/Prefab/Background/EventDungeon_01_03.prefab
  nekoyume/Assets/Resources/Prefab/Background/EventDungeon_03_01.prefab
  nekoyume/Assets/Resources/Prefab/Background/EventDungeon_03_02.prefab
  nekoyume/Assets/Resources/Prefab/Background/EventDungeon_03_03.prefab
  nekoyume/Assets/Resources/Prefab/Background/EventDungeon_04_01.prefab
  nekoyume/Assets/Resources/Prefab/Background/EventDungeon_04_02.prefab
  nekoyume/Assets/Resources/Prefab/Background/EventDungeon_04_03.prefab
  nekoyume/Assets/Resources/Prefab/Background/PVP.prefab
  nekoyume/Assets/Resources/Prefab/Background/WorldBoss_01_1.prefab
  nekoyume/Assets/Resources/Prefab/Background/WorldBoss_01_2.prefab
  nekoyume/Assets/Resources/Prefab/Background/WorldBoss_01_3.prefab
  nekoyume/Assets/Resources/Prefab/Background/WorldBoss_01_4.prefab
  nekoyume/Assets/Resources/Prefab/Background/WorldBoss_01_5.prefab
  nekoyume/Assets/Resources/Prefab/Background/combination.prefab
  nekoyume/Assets/Resources/Prefab/Background/dungeon_01.prefab
  nekoyume/Assets/Resources/Prefab/Background/dungeon_02.prefab
  nekoyume/Assets/Resources/Prefab/Background/nest.prefab
  nekoyume/Assets/Resources/Prefab/Background/ranking.prefab
  nekoyume/Assets/_Scripts/Game/Background.cs
  nekoyume/Assets/_Scripts/Game/BackgroundGroup.cs
  nekoyume/Assets/_Scripts/Game/BackgroundGroup.cs.meta
  nekoyume/Assets/_Scripts/Game/Stage.cs
Labels: Extra Large

#4709 remove unused scenes
  nekoyume/Assets/_Scenes/00_Character_draft.unity
  nekoyume/Assets/_Scenes/00_Character_draft.unity.meta
  nekoyume/Assets/_Scenes/201000.unity
  nekoyume/Assets/_Scenes/201000.unity.meta
  nekoyume/Assets/_Scenes/201001.unity
  nekoyume/Assets/_Scenes/201001.unity.meta
  nekoyume/Assets/_Scenes/201002.unity
  nekoyume/Assets/_Scenes/201002.unity.meta
  nekoyume/Assets/_Scenes/201004.unity
  nekoyume/Assets/_Scenes/201004.unity.meta
  nekoyume/Assets/_Scenes/202001.unity
  nekoyume/Assets/_Scenes/202001.unity.meta
  nekoyume/Assets/_Scenes/202002.unity
  nekoyume/Assets/_Scenes/202002.unity.meta
  nekoyume/Assets/_Scenes/AudioTest.unity
  nekoyume/Assets/_Scenes/AudioTest.unity.meta
  nekoyume/Assets/_Scenes/Character_0003_test.unity
  nekoyume/Assets/_Scenes/Character_0003_test.unity.meta
  nekoyume/Assets/_Scenes/Data.unity
  nekoyume/Assets/_Scenes/Data.unity.meta
  nekoyume/Assets/_Scenes/Font.unity
  nekoyume/Assets/_Scenes/Font.unity.meta
  nekoyume/Assets/_Scenes/Game 1.unity
  nekoyume/Assets/_Scenes/Game 1.unity.meta
  nekoyume/Assets/_Scenes/Game Copy.unity
  nekoyume/Assets/_Scenes/Game Copy.unity.meta
  nekoyume/Assets/_Scenes/RaidCutsceneTest_New.meta
  nekoyume/Assets/_Scenes/Set_101000.unity
  nekoyume/Assets/_Scenes/Set_101000.unity.meta
  nekoyume/Assets/_Scenes/Set_101001.unity
  nekoyume/Assets/_Scenes/Set_101001.unity.meta
  nekoyume/Assets/_Scenes/Set_101002.unity
  nekoyume/Assets/_Scenes/Set_101002.unity.meta
  nekoyume/Assets/_Scenes/SkillEffectTest.unity
  nekoyume/Assets/_Scenes/SkillEffectTest.unity.meta
  nekoyume/Assets/_Scenes/TweenerTestScene.unity
  nekoyume/Assets/_Scenes/TweenerTestScene.unity.meta
  nekoyume/Assets/_Scenes/test.unity
  nekoyume/Assets/_Scenes/test.unity.meta
Labels: Extra Large

#4728 change live asset url
  nekoyume/Assets/Resources/ScriptableObject/LiveAssetEndpoint.asset
Labels: Extra Small

#4729 change const string url
  nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
Labels: Extra Small

#4735 fix bug about HAS simulate and CrystalRandomSkill
  nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Module/Button/BonusBuffButton.cs
Labels: Extra Small

#4742 fix: shatter strike max damage of rendering `HackAndSlash` action
  nekoyume/Assets/_Scripts/Extensions/ActionEvalToViewModelExtensions.cs
Labels: bug, Extra Small

#4741 add updating player arena score and rank when render BattleArena
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
Labels: Extra Small

#4725 Add Resource manager
  nekoyume/Assets/_Scripts/Game/AssetManagement.meta
  nekoyume/Assets/_Scripts/Game/AssetManagement/ResourceManager.cs
  nekoyume/Assets/_Scripts/Game/AssetManagement/ResourceManager.cs.meta
  nekoyume/Assets/_Scripts/Game/Game.cs
Labels: Small

#4743 add gameconfig value when simulator init
  nekoyume/Assets/Plugins/BalanceTool/Runtime/HackAndSlashCalculator.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Widget/Development/BattleSimulator.cs
  nekoyume/Assets/_Scripts/UI/Widget/Development/Cheat.cs
Labels: Extra Small

#4746 fix condition checking about crystal random skill state
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
Labels: Extra Small

#4755 upgrade unity version to 2021.3.37f1
  README.ko.md
  README.md
  nekoyume/Packages/manifest.json
  nekoyume/Packages/packages-lock.json
  nekoyume/ProjectSettings/ProjectSettings.asset
  nekoyume/ProjectSettings/ProjectVersion.txt
Labels: Extra Small

#4730 add remote l10n file
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/L10n/L10nManager.cs
Labels: Small

#4748 UI/pet summon result bg edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetLevelUpResultScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PetSummonResultScreen.prefab
Labels: Extra Large

#4747 UI/avatar info grind edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
Labels: Extra Large

#4666 UI/summon i button edit
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/SummonDetailCell.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Summon.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SummonDetailPopup.prefab
Labels: Large

#4665 [Design]UI_PatrolRewardPopup_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_PatrolRewardPopup.prefab
Labels: Medium
