Repository planetarium/NineChronicles, pull requests merged in 2024-02, with the labels that each got.

#4086 fix: Agent to create new agent state if not exits
  nekoyume/Assets/_Scripts/Blockchain/Agent.cs
Labels: bug

#3958 Introduce ingame Stake feature
  nekoyume/Assets/Resources/AddressableAssetsContainer.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
  nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Blockchain/Agent.cs
  nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
  nekoyume/Assets/_Scripts/Blockchain/StateGetter.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Game/TableSheets.cs
  nekoyume/Assets/_Scripts/Helper/LoadingHelper.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Large

#4097 remove unused code and UI at StakigPopup(wip)
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_BenefitsListView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_BenefitsListView.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/NcgStaking.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/NcgStaking.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/StakingInfo.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/StakingInfo.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/StakingReward.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/StakingReward.png.meta
  nekoyume/Assets/_Scripts/UI/Module/Item/StakingBenefitsListView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/StakingBenefitsListView.cs.meta
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Extra Large

#4099 UI/collection UI edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_CelebratesPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CollectionRegistrationPopup.prefab
  nekoyume/Assets/Resources/VFX/Prefabs/PraiseVFX.prefab
Labels: Extra Large

#4116 explicit cocoapod version 1.12.0
  Gemfile
  Gemfile.lock
Labels: Small

#4117 Gemfile.lock update with "bundle update fastlane"
  Gemfile.lock
Labels: Small

#4122 Modify StakingPopup UI and widget code
  nekoyume/Assets/Resources/HelpPopupData/HelpPopupData.json
  nekoyume/Assets/Resources/HelpPopupData/Sprites/StakingInfo.png
  nekoyume/Assets/Resources/HelpPopupData/Sprites/StakingInfo.png.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/StakingReward.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/StakingReward.png.meta
  nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
  nekoyume/Assets/_Scripts/Helper/ShortcutHelper.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Extra Large

#4129 Feature/spd unit change
  nekoyume/Assets/_Scripts/Extensions/StatExtensions.cs
Labels: Extra Small

#4127 Feature/loading polishing
  nekoyume/Assets/Plugins/BalanceTool/Runtime/Util/InitializeUtil.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Game/TableSheets.cs
  nekoyume/Assets/_Scripts/Helper/TableSheetsHelper.cs
Labels: Small

#4077 Update L10n Change
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#3960 exception handle for overflow
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/Extensions/MathematicsExtensions.cs
  nekoyume/Assets/_Scripts/UI/Model/InventoryItem.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/RuneStoneInventoryItemView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Development/BattleSimulator.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/WorldBossResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/RaidPreparation.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/WorldBossRewardScreen.cs
Labels: Extra Small

#4156 fix build compile error
  nekoyume/Assets/_Scripts/UI/Widget/Development/BattleSimulator.cs
Labels: Extra Small

#4103 [Design]600202_Resource_Add
  nekoyume/Assets/Resources/UI/Icons/Item/600202.png
  nekoyume/Assets/Resources/UI/Icons/Item/600202.png.meta
Labels: Small

#4104 [Design]UI_SeasonPass_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPass.prefab
Labels: Extra Small

#4106 [Design]UI_Battle_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_Battle.prefab
Labels: Extra Small

#4109 [Design]UI_SuperCraftPopup_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_SuperCraftPopup.prefab
Labels: Large

#4110 [Design]Popup_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationSlotsPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MailPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_QuestPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SettingPopup_2.prefab
Labels: Extra Large

#4112 [Design]UI_ConfirmConnectPopup_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_ConfirmConnectPopup.prefab
Labels: Extra Small

#4146 move letterbox pos
  nekoyume/Assets/_Scenes/Game.unity
Labels: Extra Small

#4159 change worldmap icon priority
  nekoyume/Assets/_Scripts/Helper/WorldMapDataHelper.cs
Labels: Extra Small

#4158 [Design]UI_Menu_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
Labels: Extra Large

#4166 fix collection entering
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_box_15.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Common/UI_box_15.png.meta
  nekoyume/Assets/_Scripts/UI/Widget/Collection.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Small

#4179 disable area attack cutscene
  nekoyume/Assets/_Scripts/Game/Character/Player.cs
  nekoyume/Assets/_Scripts/UI/Widget/Hud/AreaAttackCutscene.cs
Labels: Extra Small

#4185 resolve #4163 & #4169 & #4186
  nekoyume/Assets/AddressableAssets/UI/Module/StakingInfoPopup.prefab
  nekoyume/Assets/Resources/HelpPopupData/Sprites/StakingInfo.png
  nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Extra Small

#4190 Bugfix/fix spine assets
  nekoyume/Assets/AddressableAssets/Character/Cutscene/CutScene.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Cutscene/CutScene.png
  nekoyume/Assets/AddressableAssets/Character/Cutscene/CutScene.png.meta
  nekoyume/Assets/AddressableAssets/Character/Cutscene/CutScene.skel.bytes
  nekoyume/Assets/AddressableAssets/Character/Cutscene/CutScene_Atlas.asset
  nekoyume/Assets/AddressableAssets/Character/Cutscene/CutScene_SkeletonData.asset
  nekoyume/Assets/AddressableAssets/Character/Cutscene/CutScene_cutScene.mat
  nekoyume/Assets/AddressableAssets/Character/Cutscene/cutScene_Material.mat
  nekoyume/Assets/AddressableAssets/Character/Cutscene/cutScene_Material.mat.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/205003/205003.png.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/205003/205003.skel.bytes
  nekoyume/Assets/AddressableAssets/Character/Monster/205003/205003_Material-Multiply.mat
  nekoyume/Assets/AddressableAssets/Character/Monster/205003/205003_SkeletonData.asset
  nekoyume/Assets/AddressableAssets/Character/Monster/205007/205007.png.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/205007/205007.skel.bytes
  nekoyume/Assets/AddressableAssets/Character/Monster/205007/205007_Material.mat
  nekoyume/Assets/AddressableAssets/Character/Monster/205007/205007_Material_URP.mat.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/208007/208007.png.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/208007/208007.skel.bytes
  nekoyume/Assets/AddressableAssets/Character/Monster/208007/2080072.png
  nekoyume/Assets/AddressableAssets/Character/Monster/208007/2080072.png.meta
  nekoyume/Assets/AddressableAssets/Character/Monster/208007/208007_SkeletonData.asset
  nekoyume/Assets/Resources/Timeline/Sweep.playable
  nekoyume/Assets/Resources/UI/Prefabs/UI_AreaAttackCutScene.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SweepResultPopup.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SweepResultPopup.cs
Labels: Extra Large

#4193 resolve #4183 - reset consumableClick trigger on set equipment trigger
  nekoyume/Assets/_Scripts/UI/Widget/Craft.cs
Labels: Extra Small

#4216 [Design]UI_Craft_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
Labels: Extra Large

#4217 [Design]UI_ShopSell_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopSell.prefab
Labels: Medium

#4221 UI/shop buy tabbutton text edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_ShopBuy.prefab
Labels: Extra Large

#4219 Forced SetMaterialAssets when result closed
  nekoyume/Assets/_Scripts/UI/Widget/Screen/SummonResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Summon.cs
Labels: bug, Extra Small

#4215 add spine shader to always included shader
  nekoyume/ProjectSettings/GraphicsSettings.asset
Labels: Extra Small

#4220 enable price text obj at ItemView_Shop
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView_Shop.prefab
Labels: Extra Small

#4222 enable area attack Cutscene
  nekoyume/Assets/AddressableAssets/Character/Cutscene/CutScene.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Cutscene/CutScene_Atlas.asset
  nekoyume/Assets/AddressableAssets/Character/Cutscene/cutScene_Material.mat
  nekoyume/Assets/_Scripts/Game/Character/Player.cs
Labels: Extra Small

#4226 enable countText at ItemView_Sweep
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView_Sweep.prefab
Labels: Extra Small

#4213 Update L10n Change
  nekoyume/Assets/StreamingAssets/Localization/collection.csv
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/help_popup.csv
Labels: Large

#4225 boader image change
  nekoyume/Assets/Resources/UI/Textures/worldmap_bg_cover_480.png
  nekoyume/Assets/_Scenes/Game.unity
Labels: Extra Small

#4224 fix DetailedCharacterView level text
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/RankCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CharacterView/DetailedCharacterView.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattle.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBattleLoadingScreen.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossRankCell.prefab
Labels: Extra Large

#4218 fix mobile shop recommend icon
  nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
Labels: Extra Small

#4223 fix collection bugs
  nekoyume/Assets/AddressableAssets/UI/Module/Collection/CollectionCell.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CelebratesPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CollectionRegistrationPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CollectionResultPopup.prefab
  nekoyume/Assets/_Scripts/UI/Model/CollectionMaterial.cs
  nekoyume/Assets/_Scripts/UI/Widget/Collection.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CollectionResultPopup.cs
Labels: Small

#4233 enable optionTag obj at ItemView_EnhancementInventory
  nekoyume/Assets/AddressableAssets/UI/Module/ItemView/ItemView_EnhancementInventory.prefab
Labels: Extra Small

#4234 use RuneEnhancementResultScreen anyway
  nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
Labels: Extra Small

#4232 fix cat eyes in dcc main prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_DccMain.prefab
  nekoyume/ProjectSettings/GraphicsSettings.asset
Labels: Extra Small

#4231 fix collection material validation
  nekoyume/Assets/_Scripts/UI/Model/CollectionMaterial.cs
  nekoyume/Assets/_Scripts/UI/Module/CollectionInventory.cs
Labels: Extra Small

#4239 Issue/4235 - fix cut scene texture
  nekoyume/Assets/AddressableAssets/Character/Cutscene/cutScene_Material.mat
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10200000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10210000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10211000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10212000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10213000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10214000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10220000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10221000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10222000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10223000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10224000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10230000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10230001.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10231000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10231001.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10232000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10232001.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10233000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10233001.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10234000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10234001.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10240000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10240001.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10241000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10241001.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10242000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10242001.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10243000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10243001.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10244000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10244001.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10250000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10250001.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10251000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10251001.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10252000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10252001.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10253000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10253001.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10254000.png.meta
  nekoyume/Assets/Resources/Character/PlayerSpineTexture/AreaAttackCutscene/10254001.png.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_AreaAttackCutScene.prefab
  nekoyume/Assets/_Scripts/UI/Widget/Hud/AreaAttackCutscene.cs
Labels: Extra Large

#4241 add isInWorld check to GoToCollection button
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CollectionEffectPopup.cs
Labels: Extra Small

#4165 모바일 워크샵 팝업에서 펫 버튼 활성화
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotsPopup.cs
Labels: bug, Extra Small

#4228 add slot update timing
  nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentSlot.cs
Labels: Extra Small

#4240 insert PlayerArenaInfo to first index of between last Rank
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
Labels: Extra Small

#4249 Update collection L10n Add
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/UI/Module/CollectionMaterialInfo.cs
Labels: Extra Small

#4247 fix arena mission button text
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Join/ArenaJoinBottomButtons.prefab
  nekoyume/Assets/_Scripts/UI/Module/Arena/Join/ArenaJoinMissionButton.cs
Labels: Small

#4245 wait update state when render Summon***
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
Labels: Extra Small

#4244 edit equipped item warning popup icon, label
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CollectionRegistrationPopup.cs
Labels: Extra Small

#4253 remove weapon image in 10220000 atlas
  nekoyume/Assets/AddressableAssets/Character/Player/10220000/body_skin_10220000.atlas.txt
  nekoyume/Assets/AddressableAssets/Character/Player/10220000/body_skin_10220000.png
  nekoyume/Assets/AddressableAssets/Character/Player/10220000/body_skin_10220000.png.meta
  nekoyume/Assets/AddressableAssets/Character/Player/10220000/body_skin_10220000.skel.bytes
  nekoyume/Assets/AddressableAssets/Character/Player/10220000/body_skin_10220000_Material-Screen.mat
Labels: Medium

#4266 add isInWorld check to item of petInventory
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CombinationSlotsPopup.cs
Labels: Extra Small

#4268 remove LocaloLayerModifier at summon action
  nekoyume/Assets/_Scripts/Blockchain/ActionManager.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
Labels: Extra Small

#4262 Fix collection inventory filtering
  nekoyume/Assets/_Scripts/UI/Module/CollectionInventory.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/CollectionRegistrationPopup.cs
Labels: Extra Small

#4260 Fix worldboss promotion container not working
  nekoyume/Assets/Resources/UI/Prefabs/UI_Menu.prefab
Labels: Medium

#4270 Fix Stat View in FriendInfoPopup
  nekoyume/Assets/_Scripts/UI/Widget/Popup/FriendInfoPopup.cs
Labels: Extra Small

#4271 Fix to close CollectionMaterialInfo
  nekoyume/Assets/_Scripts/UI/Module/CollectionMaterialInfo.cs
  nekoyume/Assets/_Scripts/UI/Widget/Collection.cs
Labels: Extra Small

#4264 Update Collection L10n JP Change
  nekoyume/Assets/StreamingAssets/Localization/collection.csv
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#4281 fix guest login flow
  nekoyume/Assets/_Scripts/Blockchain/BlockManager.cs
  nekoyume/Assets/_Scripts/Blockchain/RPCAgent.cs
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
Labels: Small

#4294 Update collection L10n Change
  nekoyume/Assets/StreamingAssets/Localization/collection.csv
Labels: Medium

#4302 Update Event Item, World Name L10n Change
  nekoyume/Assets/StreamingAssets/Localization/event_dungeon_name.csv
  nekoyume/Assets/StreamingAssets/Localization/item_description.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
Labels: Extra Small

#4309 fix arena simulator
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
Labels: Extra Small
