Repository planetarium/NineChronicles, pull requests merged in 2024-01, with the labels that each got.

#3862 Feature/l10n english japan
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/StreamingAssets/Localization/help_popup.csv
  nekoyume/Assets/StreamingAssets/Localization/item_name.csv
  nekoyume/Assets/StreamingAssets/Localization/pet_name.csv
Labels: Small

#3867 remove directly setting mailbox
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
Labels: Extra Small

#3868 merge #3849 into development
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
Labels: Extra Small

#3866 UI/help popup edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_HelpTooltip.prefab
Labels: Extra Small

#3869 [Design]UI_Craft_Prefab_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
Labels: Small

#3870 [Design]ShopListCell_Prefab_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/ShopListCell.prefab
Labels: Medium

#3871 [Design]UI_IconAndButtonSystem_Prefab_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_IconAndButtonSystem.prefab
Labels: Small

#3872 Update tutorial target about WorldBossButton
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
  nekoyume/Assets/PostProcessing/OutlineGrow.mat
  nekoyume/Assets/Resources/UI/Shaders/CustomSpriteOutline.shader
  nekoyume/Assets/Resources/UI/Shaders/CustomSpriteOutline.shader.meta
  nekoyume/Assets/Sprites/Background/MainMenu/Object_Midday/worldboss_02.png
  nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs
Labels: Medium

#3874 UI/worldmap edit
  nekoyume/Assets/Resources/Font/Materials/ChineseSimplified SDF Material - WorldmapClose.mat
  nekoyume/Assets/Resources/Font/Materials/ChineseSimplified SDF Material - WorldmapUnlock.mat
  nekoyume/Assets/Resources/Font/Materials/ChineseTraditional SDF Material - WorldmapClose.mat
  nekoyume/Assets/Resources/Font/Materials/ChineseTraditional SDF Material - WorldmapUnlock.mat
  nekoyume/Assets/Resources/Font/Materials/English SDF Material - WorldmapClose.mat
  nekoyume/Assets/Resources/Font/Materials/English SDF Material - WorldmapUnlock.mat
  nekoyume/Assets/Resources/Font/Materials/Japanese SDF Material - WorldmapClose.mat
  nekoyume/Assets/Resources/Font/Materials/Japanese SDF Material - WorldmapUnlock.mat
  nekoyume/Assets/Resources/Font/Materials/Korean SDF Material - WorldmapClose.mat
  nekoyume/Assets/Resources/Font/Materials/Korean SDF Material - WorldmapUnlock.mat
  nekoyume/Assets/Resources/Font/Materials/PortugueseBrazil SDF Material - WorldmapClose.mat
  nekoyume/Assets/Resources/Font/Materials/PortugueseBrazil SDF Material - WorldmapUnlock.mat
  nekoyume/Assets/Resources/Font/Materials/Russia SDF Material - WorldmapClose.mat
  nekoyume/Assets/Resources/Font/Materials/Russia SDF Material - WorldmapUnlock.mat
  nekoyume/Assets/Resources/Font/Materials/Spanish SDF Material - WorldmapClose.mat
  nekoyume/Assets/Resources/Font/Materials/Spanish SDF Material - WorldmapUnlock.mat
  nekoyume/Assets/Resources/Font/Materials/Thai SDF Material - WorldmapClose.mat
  nekoyume/Assets/Resources/Font/Materials/Thai SDF Material - WorldmapUnlock.mat
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/bg_worldmap_Jotunheim_icon_01.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/bg_worldmap_muspelheim_icon_01.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/bg_worldmap_muspelheim_icon_02.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/bg_worldmap_muspelheim_icon_03.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/bg_worldmap_niflheim_icon_01.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/bg_worldmap_niflheim_icon_01.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/bg_worldmap_niflheim_icon_02.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/bg_worldmap_niflheim_icon_02.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/bg_worldmap_niflheim_icon_03.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/bg_worldmap_niflheim_icon_03.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/bg_worldmap_outline_01.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/bg_worldmap_yggdrasil_icon_01.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/bg_worldmap_yggdrasil_icon_02.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/bg_worldmap_yggdrasil_icon_03.png
Labels: Extra Small

#3865 Feature/additional log iap service
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceClient.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceEndpoints.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
Labels: Small

#3875 UI/buffbonus popup edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_BuffBonusPopup.prefab
Labels: Large

#3876 [Design]UI_MobileShop_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
  nekoyume/Assets/UIResources/Content/Shop/Prefab/TabButton_Category.prefab
Labels: Extra Large

#3878 [Design]UI_Summon_Prefabs_Edit
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Summon.spriteatlas
  nekoyume/Assets/Resources/UI/Prefabs/UI_Summon.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Summon/Summon_Character_1_2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Summon/Summon_Character_1_2.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Summon/Summon_Character_2_2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Summon/Summon_Character_2_2.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Summon/Summon_Character_3_2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Summon/Summon_Character_3_2.png.meta
Labels: Extra Large

#3877 improve animation about healing tick from vampiric
  nekoyume/Assets/_Scripts/Game/Character/CharacterBase.cs
  nekoyume/Assets/_Scripts/Game/Stage.cs
Labels: Extra Small

#3873 add planet id argument to raid reward caching key
  nekoyume/Assets/_Scripts/UI/Module/Lobby/WorldBossMenu.cs
Labels: Extra Small

#3895 Add devforum badge to README
  README.ko.md
  README.md
Labels: Extra Small

#3894 UI/character frame edit
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/RankCell.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CharacterView/DetailedCharacterView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/CharacterView/FramedCharacterView.prefab
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Item.spriteatlas
  nekoyume/Assets/Resources/UI/Icons/Item/character_frame.png
  nekoyume/Assets/Resources/UI/Icons/Item/character_frame_dcc.png
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBoard.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_RankPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldBossDetail.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/Tabs_Rank.prefab
  nekoyume/Assets/UIResources/Content/WorldBoss/Prefab/WorldBossRankCell.prefab
Labels: Large

#3882 Delegate `LoginSystem.KeyStore` and its functions to `KeyManager`
  nekoyume/Assets/Editor/KeyStoreEditor.cs
  nekoyume/Assets/_Scripts/Blockchain/KeyManager.cs
  nekoyume/Assets/_Scripts/Blockchain/KeyManager.cs.meta
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/Helper/KeyStoreHelper.cs
  nekoyume/Assets/_Scripts/Helper/KeyStoreHelper.cs.meta
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
  nekoyume/Assets/_Scripts/UI/Login/CodeReaderView.cs
  nekoyume/Assets/_Scripts/UI/Login/PortalConnect.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SettingPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/IntroScreen.cs
  nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
Labels: Extra Large

#3897 apply fav ticker l10n in mail box exception
  nekoyume/Assets/_Scripts/Extensions/MailExtensions.cs
Labels: Extra Small

#3864 Feature/change workflows
  .github/workflows/android-googleplay-release.yml
  .github/workflows/ios-build-and-release.yml
Labels: Large

#3900 add iOS CI/CD scripts
  Gemfile
  Gemfile.lock
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Matchfile
  nekoyume/Assets/Editor/Builder.cs
Labels: Medium

#3881 [Design]WorldMapWorld_Prefabs_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/WorldMap/WorldMapStage.prefab
  nekoyume/Assets/Resources/ScriptableObject/EventData.asset
  nekoyume/Assets/Resources/ScriptableObject/WorldMapStageData.asset
  nekoyume/Assets/Resources/ScriptableObject/WorldMapStageData.asset.meta
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Worldmap.spriteatlas
  nekoyume/Assets/Resources/UI/Prefabs/WorldMapWorld.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/battle_UI_icon_02.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/battle_UI_icon_02.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/battle_UI_icon_03.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/battle_UI_icon_03.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/battle_UI_icon_boss.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/battle_UI_icon_boss_02.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Worldmap/battle_UI_icon_boss_02.png.meta
  nekoyume/Assets/_Scripts/EnumType/BossType.cs
  nekoyume/Assets/_Scripts/EnumType/BossType.cs.meta
  nekoyume/Assets/_Scripts/Game/ScriptableObject/EventScriptableObject.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/WorldMapData.cs
  nekoyume/Assets/_Scripts/Game/ScriptableObject/WorldMapData.cs.meta
  nekoyume/Assets/_Scripts/Helper/WorldMapDataHelper.cs
  nekoyume/Assets/_Scripts/Helper/WorldMapDataHelper.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/WorldMap/WorldMapStage.cs
  nekoyume/Assets/_Scripts/UI/Module/WorldMap/WorldMapWorld.cs
Labels: Extra Large

#3898 [Design]UI_Rune_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_Rune.prefab
  nekoyume/Assets/_Scripts/UI/Model/RuneOptionView.cs
Labels: Extra Large

#3905 improve rendering actions about avatar state updating
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
Labels: Small

#3906 set first touch handler obj
  nekoyume/Assets/_Scripts/Game/Character/TouchHandler.cs
Labels: Extra Small

#3910 remove signer checking at update agent state
  nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
Labels: Extra Small

#3904 [Design]UI_MobileShop_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
Labels: Large

#3914 show newseasonpass popup by seasonpass id
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassNewPopup.cs
Labels: Extra Small

#3918 remove event trigger component
  nekoyume/Assets/Resources/UI/Prefabs/UI_FungibleAssetTooltip.prefab
Labels: Medium

#3916 ♻ Refactor States.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionHandler.cs
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/State/RxProps.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Widget/Rune.cs
  nekoyume/Assets/_Scripts/UI/Widget/ShopSell.cs
Labels: Large

#3919 fix: error message
  nekoyume/Assets/_Scripts/Multiplanetary/PlanetContext.cs
Labels: bug, Extra Small

#3915 UI/stading ncg list add
  nekoyume/Assets/AddressableAssets/UI/Module/Item/Item_BenefitsListView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/StakingBonus.prefab
  nekoyume/Assets/Resources/ScriptableObject/UI_StakeIconData.asset
  nekoyume/Assets/Resources/UI/Prefabs/UI_StakingPopup.prefab
  nekoyume/Assets/Sprites/Background/MainMenu/Object/Staking_03.png
  nekoyume/Assets/Sprites/Background/MainMenu/Object/Staking_04.png
  nekoyume/Assets/Sprites/Background/MainMenu/Object/Staking_05.png
  nekoyume/Assets/Sprites/Background/MainMenu/Object/Staking_06.png
  nekoyume/Assets/Sprites/Background/MainMenu/Object/Staking_07.png
  nekoyume/Assets/Sprites/Background/MainMenu/Object/Staking_08.png
  nekoyume/Assets/Sprites/Background/MainMenu/Object/Staking_08.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/Icon_Staking_Buff_04.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/icon_Staking_Buff_03.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/icon_Staking_Buff_05.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/icon_Staking_Buff_06.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/icon_Staking_Buff_07.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/icon_Staking_Buff_08.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Staking/icon_Staking_Buff_08.png.meta
  nekoyume/Assets/_Scripts/UI/Module/Item/StakingBenefitsListView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/StakingBuffBenefitsView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/StakingInterestBenefitsView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/StakingPopup.cs
Labels: Extra Large

#3923 remove github action cache resotre key
  .github/workflows/ios-build-and-release.yml
Labels: Extra Small

#3924 Introduce guild service client
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerCell.prefab
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/GeneratedApi/GuildServiceClient.cs
  nekoyume/Assets/_Scripts/GeneratedApi/GuildServiceClient.cs.meta
  nekoyume/Assets/_Scripts/Helper/CommandLineOptions.cs
  nekoyume/Assets/_Scripts/Helper/Util.cs
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
  nekoyume/Assets/_Scripts/UI/Model/ArenaParticipantModel.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardPlayerCell.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
Labels: Medium

#3921 update promotion container
  nekoyume/Assets/AddressableAssets/UI/Module/Button/BackButton.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/CombinationBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/PatrolBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/QuestBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RaidBtn.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/Lobby/RankingBtn.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_CombinationMain.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_EventPopup.prefab.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_MobileShop.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_PatrolRewardPopup.prefab
  nekoyume/Assets/Resources/UI/Textures/00_Event/400%Event.png
  nekoyume/Assets/Resources/UI/Textures/00_Event/Event.png
  nekoyume/Assets/Resources/UI/Textures/00_Event/Event.png.meta
  nekoyume/Assets/_Scripts/Game/LiveAsset/LiveAssetManager.cs
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Model/EventBannerData.cs
  nekoyume/Assets/_Scripts/UI/Model/EventNoticeData.cs
  nekoyume/Assets/_Scripts/UI/Module/EventNotice/AutoBannerItem.cs
  nekoyume/Assets/_Scripts/UI/Module/EventNotice/AutoBannerItem.cs.meta
  nekoyume/Assets/_Scripts/UI/Module/PromotionContainer.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/EventPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/EventPopup.cs.meta
Labels: Extra Large

#3917 [Design]UI_PatrolRewardPopup_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_PatrolRewardPopup.prefab
  nekoyume/Assets/Resources/UI/Textures/00_Event/400%Event.png
  nekoyume/Assets/Resources/UI/Textures/00_Event/Event.png
  nekoyume/Assets/Resources/UI/Textures/00_Event/Event.png.meta
Labels: Large

#3911 [Design]UI_ArenaTicketPopup_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaTicketPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SweepPopup.prefab
Labels: Medium

#3909 [Design]UI_Craft_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
Labels: Large

#3908 [Design]UI_WorldMap_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldMap.prefab
Labels: Extra Small

#3912 [Design]UI_AvatarInfoPopup_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_AvatarInfoPopup.prefab
Labels: Large

#3925 Update Aura Summon Phrase L10n
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: No Changes

#3896 Feature/android savefile path change
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/PlatformUtility/Platform.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#3927 Add guild arguments in planetRegistry
  nekoyume/Assets/_Scripts/Multiplanetary/PlanetInfo.cs
  nekoyume/Assets/_Scripts/Multiplanetary/PlanetSelector.cs
Labels: Extra Small

#3926 initalize rune notification state
  nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentInventoryItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/InventoryItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/MailRewardItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/ShopCartItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/ShopItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/SweepItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/SeasonPass/SeasonPassRewardCell.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RuneStoneEnhancementInventoryCell.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs
Labels: Extra Small

#3920 fix log endpoint and add log status
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceClient.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
Labels: Extra Small

#3922 [Design]ArenaBoardPlayerCell_Prefabs_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/Arena/Board/ArenaBoardPlayerCell.prefab
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Guild.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_Guild.spriteatlas.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_ArenaBoard.prefab
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Guild.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Guild/GuildEmpty.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Guild/GuildEmpty.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Guild/GuildMark_0.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Guild/GuildMark_0.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Guild/GuildMark_1.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Guild/GuildMark_1.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Guild/GuildMark_2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_Guild/GuildMark_2.png.meta
  nekoyume/Assets/_Scripts/Game/Game.cs
  nekoyume/Assets/_Scripts/GeneratedApi/GuildServiceClient.cs
  nekoyume/Assets/_Scripts/GeneratedApi/GuildServiceClient.cs.meta
  nekoyume/Assets/_Scripts/Helper/CommandLineOptions.cs
  nekoyume/Assets/_Scripts/Helper/Util.cs
  nekoyume/Assets/_Scripts/Multiplanetary/PlanetInfo.cs
  nekoyume/Assets/_Scripts/Multiplanetary/PlanetSelector.cs
  nekoyume/Assets/_Scripts/State/RxProps.Arena.cs
  nekoyume/Assets/_Scripts/UI/Model/ArenaParticipantModel.cs
  nekoyume/Assets/_Scripts/UI/Module/Arena/Board/ArenaBoardPlayerCell.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBoard.cs
Labels: Extra Large

#3901 add UI_WorldClearPopup
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldClear2.spriteatlas
  nekoyume/Assets/Resources/SpriteAtlases/UI/Atlas_WorldClear2.spriteatlas.meta
  nekoyume/Assets/Resources/UI/Animations/UI_WorldClear.controller
  nekoyume/Assets/Resources/UI/Animations/UI_WorldClear.controller.meta
  nekoyume/Assets/Resources/UI/Animations/WorldClear@Loop.anim
  nekoyume/Assets/Resources/UI/Animations/WorldClear@Loop.anim.meta
  nekoyume/Assets/Resources/UI/Animations/WorldClear@Show.anim
  nekoyume/Assets/Resources/UI/Animations/WorldClear@Show.anim.meta
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldClearPopup.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_WorldClearPopup.prefab.meta
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldClear.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldClear/back.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldClear/back.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldClear/body.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldClear/body.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldClear/bottom_1.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldClear/bottom_1.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldClear/bottom_2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldClear/bottom_2.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldClear/bottom_3.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldClear/bottom_3.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldClear/head.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldClear/head.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldClear/left_1.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldClear/left_1.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldClear/left_2.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldClear/left_2.png.meta
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldClear/leg.png
  nekoyume/Assets/UIResources/Atlas_image/Common/UI_WorldClear/leg.png.meta
  nekoyume/Assets/UIResources/Font/Black Drama SDF Material - Wave.mat
  nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs
  nekoyume/Assets/_Scripts/UI/MainCanvas.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/WorldClearPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/WorldClearPopup.cs.meta
Labels: Extra Large

#3968 delete useless log
  nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs
Labels: Extra Small

#3961 update l10n csv about clear world ui
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#3975 remove OnRoomEnter.Invoke(true) at Raid action render
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
Labels: Extra Small

#3980 resolve issue#3977, stuck at create avatar
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/State/RxProps.cs
  nekoyume/Assets/_Scripts/State/States.cs
  nekoyume/Assets/_Scripts/UI/Widget/LoginDetail.cs
Labels: Extra Small

#3988 change Url.Load logic about ios for native file reading
  nekoyume/Assets/_Scripts/Helper/Url.cs
Labels: bug

#3985 Fix grind limit notification
  nekoyume/Assets/StreamingAssets/Localization/error.csv
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
Labels: Extra Small

#3986 Fix patrol reward popup date text
  nekoyume/Assets/Resources/UI/Prefabs/UI_PatrolRewardPopup.prefab
  nekoyume/Assets/_Scripts/UI/Module/PromotionContainer.cs
Labels: Extra Small

#3979 hide mobile shop list popup by platform
  nekoyume/Assets/_Scripts/Game/Entrance/RoomEntering.cs
Labels: Extra Small

#3984 fix RuneOptionView
  nekoyume/Assets/_Scripts/UI/Model/RuneOptionView.cs
Labels: Extra Small

#3982 V130 shop empty category l10n
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: No Changes

#3992 Fix full costume wasnt displayed at character view
  nekoyume/Assets/_Scripts/UI/Module/Character/VanillaCharacterView.cs
  nekoyume/Assets/_Scripts/UI/Widget/ArenaBattle.cs
Labels: Extra Small

#3998 Update Builder.cs to remove UNITY_IOS defines
  nekoyume/Assets/Editor/Builder.cs
Labels: Extra Small

#3997 Merge/120.0.2 into main
  .github/workflows/android-googleplay-release.yml
  .github/workflows/ios-build-and-release.yml
  Gemfile
  Gemfile.lock
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Matchfile
  nekoyume/Assets/Editor/Builder.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceClient.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceEndpoints.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Large

#3999 Hotfix/120.0.3
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#4009 change type of CurrentAvatarBalances to ConcurrentDictionary
  nekoyume/Assets/_Scripts/State/States.cs
Labels: bug

#3970 fix seasonpass iap item refresh failed
  nekoyume/Assets/_Scripts/Helper/Util.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/EquipmentInventoryItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/InventoryItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/MailRewardItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/ShopCartItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/ShopItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/SweepItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/Item/TooltipItemView.cs
  nekoyume/Assets/_Scripts/UI/Module/SeasonPass/SeasonPassRewardCell.cs
  nekoyume/Assets/_Scripts/UI/Scroller/RuneStoneEnhancementInventoryCell.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/SeasonPassPremiumPopup.cs
Labels: Extra Small

#4003 fix google sign crash error
  fastlane/Fastfile
Labels: Extra Small

#4007 Feature/free iap product
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceClient.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceEndpoints.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/IAPServiceManager.cs
  nekoyume/Assets/NineChronicles/ExternalServices/IAPService/Runtime/Models/ProductSchema.cs
  nekoyume/Assets/StreamingAssets/Localization/common.csv
  nekoyume/Assets/_Scripts/IAPStore/IAPStoreManager.cs
  nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs
  nekoyume/Assets/_Scripts/UI/Widget/Menu.cs
  nekoyume/Assets/_Scripts/UI/Widget/Popup/ShopListPopup.cs
Labels: Medium

#4005 Update Arun Summon Phrase Name Change
  nekoyume/Assets/StreamingAssets/Localization/common.csv
Labels: Extra Small

#4022 Fix failed build
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
Labels: Extra Small

#4021 [Design]UI_Craft_Prefabs_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_Craft.prefab
Labels: Large

#4019 [Design]RankCell_Prefabs_Edit
  nekoyume/Assets/AddressableAssets/UI/Module/CellView/RankCell.prefab
Labels: Small

#4020 Fix ui prefab text size
  nekoyume/Assets/AddressableAssets/UI/Module/CharacterView/DetailedCharacterView.prefab
  nekoyume/Assets/AddressableAssets/UI/Module/PFP/PetCardSlot.prefab
  nekoyume/Assets/Resources/UI/Prefabs/UI_SuperCraftPopup.prefab
Labels: Extra Small

#4032 fix build failed
  nekoyume/Assets/_Scripts/UI/Widget/Enhancement.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#4031 NRE exception handle
  nekoyume/Assets/_Scripts/UI/Widget/Popup/EventReleaseNotePopup.cs
Labels: Small

#4030 change Find to TryFind
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
  nekoyume/Assets/_Scripts/UI/Widget/Screen/SummonResultPopup.cs
  nekoyume/Assets/_Scripts/UI/Widget/Summon.cs
Labels: Extra Small

#4034 Bugfix/blackout ios
  nekoyume/Assets/_Scripts/Game/Dcc.cs
  nekoyume/Assets/_Scripts/Helper/Url.cs
Labels: Small

#4036 fix costume item icon meta file
  nekoyume/Assets/Resources/UI/Icons/Item/40100026.png.meta
  nekoyume/Assets/Resources/UI/Icons/Item/40100027.png.meta
  nekoyume/Assets/Resources/UI/Icons/Item/40100028.png.meta
  nekoyume/Assets/Resources/UI/Icons/Item/40100029.png.meta
Labels: Large

#4038 fix rune enhancement stat
  nekoyume/Assets/_Scripts/UI/Widget/Screen/RuneEnhancementResultScreen.cs
Labels: Extra Small

#4037 Feature/free product category notification
  nekoyume/Assets/UIResources/Content/Shop/Prefab/TabButton_Category.prefab
  nekoyume/Assets/_Scripts/UI/Module/IAP/IAPCategoryTab.cs
  nekoyume/Assets/_Scripts/UI/Module/IAP/IAPShopProductCellView.cs
  nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
Labels: Medium

#4039 Update D:CC Help popup L10n Change
  nekoyume/Assets/StreamingAssets/Localization/help_popup.csv
Labels: No Changes

#4041 Fix crystal text animation in grind
  nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs
Labels: Extra Small

#4044 Update Title meta Change
  nekoyume/Assets/Resources/UI/Icons/Item/49900014.png.meta
Labels: Small

#4047 add invoking UpdateCurrentAvatarStateAsync when render Unload...
  nekoyume/Assets/_Scripts/Blockchain/ActionRenderHandler.cs
Labels: Extra Small

#4058 [Design]UI_Enhancement_Prefab_Edit
  nekoyume/Assets/Resources/UI/Prefabs/UI_Enhancement.prefab
Labels: Medium

#4049 add generate keystore by raw pk feature to KeystoreEditor
  nekoyume/Assets/Editor/KeyStoreEditor.cs
Labels: Extra Small

#4062 feat: revive `BalanceTool`
  nekoyume/Assets/Plugins/BalanceTool/Editor/BalanceToolWindow.cs
  nekoyume/Assets/Plugins/BalanceTool/Runtime/HackAndSlashCalculator.PlayData.cs
  nekoyume/Assets/Plugins/BalanceTool/Runtime/HackAndSlashCalculator.PlayResult.cs
  nekoyume/Assets/Plugins/BalanceTool/Runtime/HackAndSlashCalculator.cs
  nekoyume/Assets/Plugins/BalanceTool/Runtime/Util/ActionContext.cs
  nekoyume/Assets/Plugins/BalanceTool/Runtime/Util/InitializeUtil.cs
  nekoyume/Assets/Plugins/BalanceTool/Runtime/Util/MockState.cs
  nekoyume/Assets/Plugins/BalanceTool/Runtime/Util/MockState.cs.meta
  nekoyume/Assets/Plugins/BalanceTool/Runtime/Util/State.cs
  nekoyume/Assets/Plugins/BalanceTool/Runtime/Util/State.cs.meta
  nekoyume/Assets/Plugins/BalanceTool/Runtime/Util/TableSheetsImporter.cs
  nekoyume/Assets/Plugins/BalanceTool/Runtime/Util/TableSheetsImporter.cs.meta
  nekoyume/Assets/Plugins/BalanceTool/Runtime/Util/TestRandom.cs
  nekoyume/Assets/Plugins/BalanceTool/Runtime/Util/TestRandom.cs.meta
Labels: Extra Large

#4066 filter raw pk string at debug logging
  nekoyume/Assets/_Scripts/Helper/CommandLineParser.cs
  nekoyume/ProjectSettings/ProjectSettings.asset
Labels: Extra Small

#4059 change season pass producdt render limit 5 -> 6
  nekoyume/Assets/Resources/UI/Prefabs/UI_SeasonPassPremiumPopup.prefab
Labels: Large
